### ISSUE TITLE
LroHappyPathTestsRest test in AutoRest/Generators/CSharp/Azure.CSharp.Tests/AcceptanceTests.cs is failing on Travis Ubuntu 14.04 with CoreCLR RTM version

### ISSUE THREAD

**Issue by hovsepm** [Azure/autorest#1208]
Need to add more logging/debug Unix execution to understand the reason, fix it and include in CI runs. 
Here is the StackTrace from Travis:

```

    Microsoft.Rest.Generator.CSharp.Azure.Tests.AcceptanceTests.LroHappyPathTestsRest [FAIL]
      System.ObjectDisposedException : Cannot access a closed Stream.
      Stack Trace:
           at System.IO.__Error.StreamIsClosed()
           at System.IO.MemoryStream.Read(Byte[] buffer, Int32 offset, Int32 count)
           at System.IO.MemoryStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
           at System.Net.Http.CurlHandler.MultiAgent.TransferDataFromRequestStream(IntPtr buffer, Int32 length, EasyRequest easy)
           at System.Net.Http.CurlHandler.MultiAgent.CurlSendCallback(IntPtr buffer, UInt64 size, UInt64 nitems, IntPtr context)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
        /home/travis/build/Azure/autorest/ClientRuntimes/CSharp/Microsoft.Rest.ClientRuntime/RetryDelegatingHandler.cs(98,0): at Microsoft.Rest.RetryDelegatingHandler.<>c__DisplayClass11_0.<<SendAsync>b__1>d.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
        /home/travis/build/Azure/autorest/ClientRuntimes/CSharp/Microsoft.Rest.ClientRuntime/RetryDelegatingHandler.cs(132,0): at Microsoft.Rest.RetryDelegatingHandler.<SendAsync>d__11.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
           at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
        /home/travis/build/Azure/autorest/AutoRest/Generators/CSharp/Azure.CSharp.Tests/Expected/AcceptanceTests/Lro/LRORetrysOperations.cs(175,0): at Fixtures.Azure.AcceptanceTestsLro.LRORetrysOperations.<BeginPut201CreatingSucceeded200WithHttpMessagesAsync>d__6.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
        /home/travis/build/Azure/autorest/AutoRest/Generators/CSharp/Azure.CSharp.Tests/Expected/AcceptanceTests/Lro/LRORetrysOperations.cs(73,0): at Fixtures.Azure.AcceptanceTestsLro.LRORetrysOperations.<Put201CreatingSucceeded200WithHttpMessagesAsync>d__5.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
        /home/travis/build/Azure/autorest/AutoRest/Generators/CSharp/Azure.CSharp.Tests/Expected/AcceptanceTests/Lro/LRORetrysOperationsExtensions.cs(59,0): at Fixtures.Azure.AcceptanceTestsLro.LRORetrysOperationsExtensions.<Put201CreatingSucceeded200Async>d__1.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
        /home/travis/build/Azure/autorest/AutoRest/Generators/CSharp/Azure.CSharp.Tests/Expected/AcceptanceTests/Lro/LRORetrysOperationsExtensions.cs(39,0): at Fixtures.Azure.AcceptanceTestsLro.LRORetrysOperationsExtensions.Put201CreatingSucceeded200(ILRORetrysOperations operations, Product product)
        /home/travis/build/Azure/autorest/AutoRest/Generators/CSharp/Azure.CSharp.Tests/AcceptanceTests.cs(267,0): at Microsoft.Rest.Generator.CSharp.Azure.Tests.AcceptanceTests.LroHappyPathTestsRest()
```

Side effect of PR #1210. Note: This test does not fail on Windows/Jenkins builds.

**Comment by fearthecowboy** [comment]
I believe this is a known bug in the CoreCLR implementation on non-windows. 

Hey @devigned - do you have a link to the bug in CoreCLR/CoreFX/... ?
