### ISSUE TITLE
Python AOP result() call with short timeout throws exception

### ISSUE THREAD

**Issue by thenewwazoo** [Azure/autorest#1410]
If a `send_cmd` operation takes longer than the timeout passed to `AzureOperationPoller.result()`, an AttributeError exception will be thrown.

The following code:

``` python
#!/usr/bin/env python

import json
from time import sleep
from azure.common.credentials import ServicePrincipalCredentials
from azure.mgmt.resource.resources import ResourceManagementClient
from azure.mgmt.resource.resources.models import ResourceGroup

with open("credentials.json") as f:
    cred_dict = json.load(f)

location = "westus"
resource_group_name = 'stall-test2'
subscription_id = "..."

credentials = ServicePrincipalCredentials(
    client_id=cred_dict['clientId'],
    secret=cred_dict['clientSecret'],
    tenant=cred_dict['tenant']
)

resource_client = ResourceManagementClient(
    credentials,
    subscription_id
)


def stall_response(*args, **kwargs):
    response = kwargs["result"]
    print "stalling response by 5s"
    sleep(5)
    return response


def main():
    print "creating rg"
    resource_group = resource_client.resource_groups.create_or_update(
        resource_group_name=resource_group_name,
        parameters=ResourceGroup(location=location)
    )

    resource_client._client.add_hook("request", stall_response, precall=False)

    print "calling delete"
    poller = resource_client.resource_groups.delete(resource_group_name=resource_group_name)
    print "getting delete result with timeout of 2s"
    poller.result(2)


if __name__=="__main__":
    main()
```

Results in the following output:

``` shell
$ ./stall.py
creating rg
calling delete
getting delete result with timeout of 2s
stalling response by 5s
Traceback (most recent call last):
  File "./stall.py", line 52, in <module>
    main()
  File "./stall.py", line 48, in main
    poller.result(2)
  File ".../venv/lib/python2.7/site-packages/msrestazure/azure_operation.py", line 516, in result
    return self._operation.resource
AttributeError: 'NoneType' object has no attribute 'resource'
stalling response by 5s
stalling response by 5s
$
```

This is due to `result()` attempting to return a member of the `_operation` object:

``` python
        self.wait(timeout)
        return self._operation.resource
```

 but `_operation` is initialized as `None`. It is then not set until after the `send_cmd` call:

``` python
        try:
            self._response = send_cmd()
            self._operation = LongRunningOperation(self._response, output_cmd)
```

If `timeout` expires before `send_cmd` returns, `_operation` is `None`, and the exception is thrown.

**Comment by olydis** [comment]
@lmazuel @thenewwazoo This issue is pretty old. If this is still a concern, please reopen it.

**Comment by lmazuel** [comment]
@olydis Fixed by https://github.com/Azure/msrestazure-for-python/pull/24
