### ISSUE TITLE
Error generating client model: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by kbrimble** [Azure/autorest#1636]
I have a swagger.json file that looks like this:
```json
{
  "apiVersion": "2.0.0.0",
  "apis": [
    {
      "description": "Login a user and return an Auth-Token",
      "operations": [
        {
          "items": null,
          "method": "POST",
          "nickname": "CreateLoginToken",
          "notes": "Uri template /logins",
          "parameters": [
            {
              "description": "uk",
              "format": null,
              "maximum": 1,
              "minimum": 1,
              "name": "Accept-Tenant",
              "paramType": "header",
              "required": true,
              "type": "string"
            },
            {
              "description": "",
              "format": null,
              "maximum": 1,
              "minimum": 1,
              "name": "Authorization",
              "paramType": "header",
              "required": true,
              "type": "string"
            },
            {
              "description": null,
              "format": null,
              "maximum": 0,
              "minimum": 0,
              "name": "credentialsRequest",
              "paramType": "body",
              "required": false,
              "type": "KB.Api.Consumer.DTOs.CredentialsRequest"
            }
          ],
          "responseMessages": [
            {
              "code": 401,
              "message": "reCaptcha challenge must be completed before proceeding. Add x-recaptcha-answer header to request after user solves it and then re-run.",
              "responseModel": null
            },
            {
              "code": 403,
              "message": "A user with the given username and password does not exist",
              "responseModel": null
            },
            {
              "code": 429,
              "message": "Too many login attempts for username. Temporarily throttled (see ThrottleTimeoutSeconds header / response body)",
              "responseModel": null
            }
          ],
          "summary": "Login a user and return an Auth-Token",
          "type": "KB.Api.Consumer.DTOs.LoginResponse",
          "uri": "/logins"
        }
      ],
      "path": "/logins"
    }
  ],
  "basePath": "/",
  "models": {
    "KB.Api.Consumer.DTOs.LoginResponse": {
      "__type": "ModelSpec:#OpenRastaSwagger.Model.ResourceDetails",
      "id": "KB.Api.Consumer.DTOs.LoginResponse",
      "properties": {
        "Token": {
          "__type": "PropertyType:#OpenRastaSwagger.Model.ResourceDetails",
          "description": "String",
          "enum": null,
          "format": "",
          "items": null,
          "type": "string"
        }
      },
      "required": [
        "Token"
      ]
    },
    "KB.Api.Consumer.DTOs.CredentialsRequest": {
      "__type": "ModelSpec:#OpenRastaSwagger.Model.ResourceDetails",
      "id": "KB.Api.Consumer.DTOs.CredentialsRequest",
      "properties": {
        "Username": {
          "__type": "PropertyType:#OpenRastaSwagger.Model.ResourceDetails",
          "description": "String",
          "enum": null,
          "format": "",
          "items": null,
          "type": "string"
        },
        "Password": {
          "__type": "PropertyType:#OpenRastaSwagger.Model.ResourceDetails",
          "description": "String",
          "enum": null,
          "format": "",
          "items": null,
          "type": "string"
        },
        "DeviceId": {
          "__type": "PropertyType:#OpenRastaSwagger.Model.ResourceDetails",
          "description": "String",
          "enum": null,
          "format": "",
          "items": null,
          "type": "string"
        },
        "DeviceName": {
          "__type": "PropertyType:#OpenRastaSwagger.Model.ResourceDetails",
          "description": "String",
          "enum": null,
          "format": "",
          "items": null,
          "type": "string"
        },
        "DeviceType": {
          "__type": "PropertyType:#OpenRastaSwagger.Model.ResourceDetails",
          "description": "String",
          "enum": null,
          "format": "",
          "items": null,
          "type": "string"
        },
        "DeviceToken": {
          "__type": "PropertyType:#OpenRastaSwagger.Model.ResourceDetails",
          "description": "String",
          "enum": null,
          "format": "",
          "items": null,
          "type": "string"
        }
      },
      "required": [
        "Username",
        "Password",
        "DeviceId",
        "DeviceName",
        "DeviceType"
      ]
    }
  },
  "resourcePath": "/",
  "swaggerVersion": "1.2"
}
```

But when I run AutoRest with like this: 
`AutoRest.exe -Input swagger.json -verbose`
I get the following error:

> Code generation failed.
> AutoRest.exe -Input logins.json -verbose
> error: [FATAL] Error generating client model: Object reference not set to an instance of an object.
> System.NullReferenceException: Object reference not set to an instance of an object.
>    at Microsoft.Rest.Modeler.Swagger.SwaggerModeler.UpdateSettings()
>    at Microsoft.Rest.Modeler.Swagger.SwaggerModeler.Build()
>    at Microsoft.Rest.Generator.AutoRest.Generate(Settings settings)
> INFO: AutoRest Core 0.16.0.0
> INFO: Initializing modeler.
> INFO: Initializing modeler.
> INFO: Parsing swagger json file.
> INFO: Generating client model from swagger model.

I tried removing the `models` object from the json to no avail.

**Comment by amarzavery** [comment]
We do not support 1.2 version of the swagger spec. Please convert this to a 2.0 version swagger spec and then provide it as an input to Autorest
________________________________
