### ISSUE TITLE
Unable to find AutoRest.dll with version 1.0.1-20170310-2300-nightly

### ISSUE THREAD

**Issue by jaredmoo** [Azure/autorest#1992]
This error is happening on both my machine and in build labs.

Repro: 

```autorest --version 1.0.1-20170310-2300-nightly --help```

https://travis-ci.org/Azure/azure-rest-api-specs/jobs/210142400

```
Error: Unable to find AutoRest.dll.

    at AutoRestDllPath (/home/travis/.autorest/plugins/autorest/1.0.1-20170310-2300-nightly/node_modules/autorest-core/interop/autorest-dotnet.js:27:11)

    at Object.SpawnLegacyAutoRest (/home/travis/.autorest/plugins/autorest/1.0.1-20170310-2300-nightly/node_modules/autorest-core/interop/autorest-dotnet.js:39:49)

    at /home/travis/.autorest/plugins/autorest/1.0.1-20170310-2300-nightly/node_modules/autorest-core/app.js:29:47

    at next (native)

    at /home/travis/.autorest/plugins/autorest/1.0.1-20170310-2300-nightly/node_modules/autorest-core/app.js:8:71

    at __awaiter (/home/travis/.autorest/plugins/autorest/1.0.1-20170310-2300-nightly/node_modules/autorest-core/app.js:4:12)

    at legacyMain (/home/travis/.autorest/plugins/autorest/1.0.1-20170310-2300-nightly/node_modules/autorest-core/app.js:28:12)

    at /home/travis/.autorest/plugins/autorest/1.0.1-20170310-2300-nightly/node_modules/autorest-core/app.js:87:23

    at next (native)

    at /home/travis/.autorest/plugins/autorest/1.0.1-20170310-2300-nightly/node_modules/autorest-core/app.js:8:71

    at __awaiter (/home/travis/.autorest/plugins/autorest/1.0.1-20170310-2300-nightly/node_modules/autorest-core/app.js:4:12)

    at main (/home/travis/.autorest/plugins/autorest/1.0.1-20170310-2300-nightly/node_modules/autorest-core/app.js:82:12)

    at Object.<anonymous> (/home/travis/.autorest/plugins/autorest/1.0.1-20170310-2300-nightly/node_modules/autorest-core/app.js:103:1)

    at Module._compile (module.js:570:32)

    at Object.Module._extensions..js (module.js:579:10)

    at Module.load (module.js:487:32)

    at tryModuleLoad (module.js:446:12)

    at Function.Module._load (module.js:438:3)

    at Module.require (module.js:497:17)

    at require (internal/module.js:20:19)

    at Function.<anonymous> (/home/travis/.nvm/versions/node/v6.10.0/lib/node_modules/autorest/app.js:228:25)

    at next (native)
```

**Comment by jaredmoo** [comment]
Probably related to this change: https://github.com/Azure/autorest/commit/5d824d19b6f861daccf110042c6bc026fc402e57#diff-9ce211beba298ac1e4578ff0dcac4563R13

**Comment by rodrigobrito** [comment]
I'm gettting this error:

PS C:\Users\rodrigo.brito\rest-test> autorest -Input manager.json -CodeGenerator CSharp -OutputDirectory CSharp_Manager -Namespace Manager
AutoRest Code Generator
(c) 2017 Microsoft Corporation. https://aka.ms/autorest
Error: Unable to find AutoRest.dll.
    at AutoRestDllPath (C:\Users\rodrigo.brito\.autorest\plugins\autorest\1.0.1-20170312-2300-nightly\node_modules\autorest-core\interop\autorest-dotnet.js:27:11)
    at Object.SpawnLegacyAutoRest (C:\Users\rodrigo.brito\.autorest\plugins\autorest\1.0.1-20170312-2300-nightly\node_modules\autorest-core\interop\autorest-dotnet.js:39:49)
    at C:\Users\rodrigo.brito\.autorest\plugins\autorest\1.0.1-20170312-2300-nightly\node_modules\autorest-core\app.js:29:47
    at Generator.next (<anonymous>)
    at C:\Users\rodrigo.brito\.autorest\plugins\autorest\1.0.1-20170312-2300-nightly\node_modules\autorest-core\app.js:8:71
    at __awaiter (C:\Users\rodrigo.brito\.autorest\plugins\autorest\1.0.1-20170312-2300-nightly\node_modules\autorest-core\app.js:4:12)
    at legacyMain (C:\Users\rodrigo.brito\.autorest\plugins\autorest\1.0.1-20170312-2300-nightly\node_modules\autorest-core\app.js:28:12)
    at C:\Users\rodrigo.brito\.autorest\plugins\autorest\1.0.1-20170312-2300-nightly\node_modules\autorest-core\app.js:91:23
    at Generator.next (<anonymous>)
    at C:\Users\rodrigo.brito\.autorest\plugins\autorest\1.0.1-20170312-2300-nightly\node_modules\autorest-core\app.js:8:71
    at __awaiter (C:\Users\rodrigo.brito\.autorest\plugins\autorest\1.0.1-20170312-2300-nightly\node_modules\autorest-core\app.js:4:12)
    at main (C:\Users\rodrigo.brito\.autorest\plugins\autorest\1.0.1-20170312-2300-nightly\node_modules\autorest-core\app.js:82:12)
    at Object.<anonymous> (C:\Users\rodrigo.brito\.autorest\plugins\autorest\1.0.1-20170312-2300-nightly\node_modules\autorest-core\app.js:103:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Function.<anonymous> (C:\Users\rodrigo.brito\AppData\Roaming\npm\node_modules\autorest\app.js:228:25)
    at Generator.next (<anonymous>)
PS C:\Users\rodrigo.brito\rest-test>

**Comment by fearthecowboy** [comment]
DAMMIT. 

Regression in one of the files. Fixing...

**Comment by fearthecowboy** [comment]
Sorry about that folks, I went home sick on Friday, and never looked at my email all weekend. 

I'm making the path calculation a bit smarter and shouldn't have this problem again.

I'm also adding some tests in the nightly build script to make sure that it works correctly before posting the build.

**Comment by fearthecowboy** [comment]
I've posted build `1.0.1-20170313-0919-preview` (use `autorest --latest` to grab it)

**Comment by jaredmoo** [comment]
Thanks for the quick fix :)

**Comment by olydis** [comment]
This should be fixed with more recent versions, will close. Please reopen if I'm mistaken or there are further issues.

**Comment by jaredmoo** [comment]
Yes it’s fixed now. Thanks

**Comment by prinupmathew** [comment]
I am getting below error


C:\Windows\system32>AutoRest -CodeGenerator CSharp -Modeler Swagger -Input http://xxxrest.user.service/swagger/docs/v1 -Namespace Services.UserServiceClient -OutputDirectory E:\test -AddCrendentials true
AutoRest Code Generator
(c) 2017 Microsoft Corporation. https://aka.ms/autorest
**Unable to find start path for AutoRest Core Module.**

C:\Windows\system32>

**Comment by fearthecowboy** [comment]
Update to the latest npm package, and reset:
 
``` powershell
npm install -g autorest 
autorest --reset 

```

**Comment by huangpf** [comment]
Node version needs to be updated as well & quote: 
```
What version of nodejs is being used?

node -v

You need 7.10 or higher.
```

```
6.10 is ok for autorest 1.2.2 … 7.10 will be needed for autorest 2.0  
```
