### ISSUE TITLE
Useless error messages

### ISSUE THREAD

**Issue by christav** [Azure/autorest#2008]
I am attempting to generated a node.js client from a swagger file. This file is over 4000 lines long and changed by multiple people.

When I run:

```
autorest -Modeler Swagger -i .\swagger\bifrost.swagger.json -AddCredentials true -ClientName MobileCenterClient -CodeGenerator NodeJS -OutputDirectory .\src\util\apis\generated --verbose
```

I get:

```
(node:14688) DeprecationWarning: Using Buffer without `new` will soon stop working. Use `new Buffer()`, or preferably `Buffer.from()`, `Buffer.allocUnsafe()` or `Buffer.alloc()` instead.
AutoRest Code Generator
(c) 2017 Microsoft Corporation. https://aka.ms/autorest
[17:17:21] Requested '1.0.1-20170313-0919-preview' version
FATAL: Error generating client model: System.Collections.Generic.KeyNotFoundException: Please specify a field with type of System.Byte[] to deserialize the file contents to
   at AutoRest.Swagger.OperationBuilder.VerifyFirstPropertyIsByteArray(CompositeType serviceType)
   at AutoRest.Swagger.OperationBuilder.TryBuildStreamResponse(HttpStatusCode responseStatusCode, OperationResponse response, Method method, List`1 types, IModelType headerType)
   at AutoRest.Swagger.OperationBuilder.BuildResponses(Method method, CompositeType headerType)
   at AutoRest.Swagger.OperationBuilder.BuildMethod(HttpMethod httpMethod, String url, String methodName, String methodGroup)
   at AutoRest.Swagger.SwaggerModeler.Build(ServiceDefinition serviceDefinition)
   at AutoRest.Core.AutoRestController.Generate()
ERROR: Error generating client model: System.Collections.Generic.KeyNotFoundException: Please specify a field with type of System.Byte[] to deserialize the file contents to
   at AutoRest.Swagger.OperationBuilder.VerifyFirstPropertyIsByteArray(CompositeType serviceType)
   at AutoRest.Swagger.OperationBuilder.TryBuildStreamResponse(HttpStatusCode responseStatusCode, OperationResponse response, Method method, List`1 types, IModelType headerType)
   at AutoRest.Swagger.OperationBuilder.BuildResponses(Method method, CompositeType headerType)
   at AutoRest.Swagger.OperationBuilder.BuildMethod(HttpMethod httpMethod, String url, String methodName, String methodGroup)
   at AutoRest.Swagger.SwaggerModeler.Build(ServiceDefinition serviceDefinition)
   at AutoRest.Core.AutoRestController.Generate()
ERROR: Code generation failed.
ERROR: AutoRest.dll -Modeler Swagger -i .\swagger\bifrost.swagger.json -AddCredentials true -ClientName MobileCenterClient -CodeGenerator NodeJS -OutputDirectory .\src\util\apis\generated
```

This error message might as well be "something's wrong." No useful info to say WHERE in the swagger the problem is. I know you can't print line numbers, but you could easily print a node path to which operation you're trying to process at the time.

Also, the reference to "System.Byte[]" when I'm trying to generate Node.js bindings is just wrong.

**Comment by fearthecowboy** [comment]
That's definitely a strange error that is not expected -- and in a part of the code that generally doesn't do that. 

Can you post the swagger for that so I can repro it?

G

**Comment by christav** [comment]
After a bunch of binary searching, the operation that causes the error is:

```
    "/v0.1/apps/{owner_name}/{app_name}/distribution_groups/{distribution_group_name}/devices/download_csv": {
      "get": {
        "operationId": "distribute_getDeviceListForDistributionGroup",
        "description": "Returns all devices associated with the given distribution group",
        "parameters": [
          {
            "name": "distribution_group_name",
            "type": "string",
            "in": "path",
            "description": "The name of the distribution group.",
            "required": true
          },
          {
            "name": "unprovisioned_only",
            "type": "boolean",
            "in": "query",
            "description": "when true, filters out provisioned devices",
            "default": false
          },
          {
            "$ref": "#/parameters/owner_name"
          },
          {
            "$ref": "#/parameters/app_name"
          }
        ],
        "produces": [
          "text/x-csv"
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/DeviceInfo"
              }
            }
          },
          "404": {
            "description": "<b>not_found</b>: A distribution group can't be found.\n",
            "schema": {
              "$ref": "#/definitions/ErrorDetails"
            }
          },
          "500": {
            "description": "An internal error.",
            "schema": {
              "$ref": "#/definitions/ErrorDetails"
            }
          }
        },
        "security": [
          {
            "APIToken": []
          }
        ],
        "tags": [
          "distribute"
        ]
      }
    },
```

I suspect it has something to do with either the produces value or the schema for the responses, haven't found more details yet.

**Comment by amarzavery** [comment]
I havent run the swagger against Autorest yet, but as far as I know, we don't support "text/x-csv" as the content-type. As of today "application/json", "text/json" and "application/octet-stream" are supported.

**Comment by christav** [comment]
Hrm - if that's the issue, is there a way to get autorest to treat an unknown content type as if it was octet-stream instead of crashing? There are other client generators out there that could make use of the additional content-type so I'd hate to lose the information out of the swagger document just to work around this.

Or at least get an "unsupported content type <...>" error instead of a useless crash?

**Comment by christav** [comment]
So I did some more poking. I discovered the only way to get it to generate is to completely remove the "produces" block AND to remove the schema from the 200 response object. At which point the generated code is of course completely wrong, as I can't get the response body anymore.

What do I have to do to get an operation that returns a stream of bytes? Or a buffer or something?

**Comment by amarzavery** [comment]
So I was able to get the generated code. I did something different. I moved the 400 and 500 to "default" and let everything be as-is. AutoRest generated code.
In AutoRest we handle negative responses differently. To know more about how they are handled please read the default and negative responses section over [here](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/creating-swagger.md#Responses).

### This is the modified swagger:
```json5
"/v0.1/apps/{owner_name}/{app_name}/distribution_groups/{distribution_group_name}/devices/download_csv": {
      "get": {
        "operationId": "distribute_getDeviceListForDistributionGroup",
        "description": "Returns all devices associated with the given distribution group",
        "parameters": [
          {
            "name": "distribution_group_name",
            "type": "string",
            "in": "path",
            "description": "The name of the distribution group.",
            "required": true
          },
          {
            "name": "unprovisioned_only",
            "type": "boolean",
            "in": "query",
            "description": "when true, filters out provisioned devices",
            "default": false
          },
          {
            "$ref": "#/parameters/owner_name"
          },
          {
            "$ref": "#/parameters/app_name"
          }
        ],
        "produces": [
          "text/x-csv"
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/DeviceInfo"
              }
            }
          },
          "default": {
            "description": "Describes the Error received from the server.\n 400: <b>not_found</b>: A distribution group can't be found.\n500: "An internal error.",
            "schema": {
              "$ref": "#/definitions/ErrorDetails"
            }
          }
        },
        "security": [
          {
            "APIToken": []
          }
        ],
        "tags": [
          "distribute"
        ]
      }
    },
```


### This is how the generated method looks like:
```javascript
getDeviceListForDistributionGroup(distributionGroupName, ownerName, appName, options, callback) {
    let client = this.client;
    if(!callback && typeof options === 'function') {
      callback = options;
      options = null;
    }
    if (!callback) {
      throw new Error('callback cannot be null.');
    }
    let unprovisionedOnly = (options && options.unprovisionedOnly !== undefined) ? options.unprovisionedOnly : false;
    // Validate
    try {
      if (distributionGroupName === null || distributionGroupName === undefined || typeof distributionGroupName.valueOf() !== 'string') {
        throw new Error('distributionGroupName cannot be null or undefined and it must be of type string.');
      }
      if (unprovisionedOnly !== null && unprovisionedOnly !== undefined && typeof unprovisionedOnly !== 'boolean') {
        throw new Error('unprovisionedOnly must be of type boolean.');
      }
      if (ownerName === null || ownerName === undefined || typeof ownerName.valueOf() !== 'string') {
        throw new Error('ownerName cannot be null or undefined and it must be of type string.');
      }
      if (appName === null || appName === undefined || typeof appName.valueOf() !== 'string') {
        throw new Error('appName cannot be null or undefined and it must be of type string.');
      }
    } catch (error) {
      return callback(error);
    }

    // Construct URL
    let baseUrl = this.client.baseUri;
    let requestUrl = baseUrl + (baseUrl.endsWith('/') ? '' : '/') + 'v0.1/apps/{owner_name}/{app_name}/distribution_groups/{distribution_group_name}/devices/download_csv';
    requestUrl = requestUrl.replace('{distribution_group_name}', encodeURIComponent(distributionGroupName));
    requestUrl = requestUrl.replace('{owner_name}', encodeURIComponent(ownerName));
    requestUrl = requestUrl.replace('{app_name}', encodeURIComponent(appName));
    let queryParameters = [];
    if (unprovisionedOnly !== null && unprovisionedOnly !== undefined) {
      queryParameters.push('unprovisioned_only=' + encodeURIComponent(unprovisionedOnly.toString()));
    }
    if (queryParameters.length > 0) {
      requestUrl += '?' + queryParameters.join('&');
    }

    // Create HTTP transport objects
    let httpRequest = new WebResource();
    httpRequest.method = 'GET';
    httpRequest.headers = {};
    httpRequest.url = requestUrl;
    // Set Headers
    if(options) {
      for(let headerName in options['customHeaders']) {
        if (options['customHeaders'].hasOwnProperty(headerName)) {
          httpRequest.headers[headerName] = options['customHeaders'][headerName];
        }
      }
    }
    httpRequest.headers['Content-Type'] = 'application/json; charset=utf-8';
    httpRequest.body = null;
    // Send Request
    return client.pipeline(httpRequest, (err, response, responseBody) => {
      if (err) {
        return callback(err);
      }
      let statusCode = response.statusCode;
      if (statusCode !== 200) {
        let error = new Error(responseBody);
        error.statusCode = response.statusCode;
        error.request = msRest.stripRequest(httpRequest);
        error.response = msRest.stripResponse(response);
        if (responseBody === '') responseBody = null;
        let parsedErrorResponse;
        try {
          parsedErrorResponse = JSON.parse(responseBody);
          if (parsedErrorResponse) {
            let internalError = null;
            if (parsedErrorResponse.error) internalError = parsedErrorResponse.error;
            error.code = internalError ? internalError.code : parsedErrorResponse.code;
            error.message = internalError ? internalError.message : parsedErrorResponse.message;
          }
        } catch (defaultError) {
          error.message = `Error "${defaultError.message}" occurred in deserializing the responseBody ` +
                           `- "${responseBody}" for the default response.`;
          return callback(error);
        }
        return callback(error);
      }
      // Create Result
      let result = null;
      if (responseBody === '') responseBody = null;
      // Deserialize Response
      if (statusCode === 200) {
        let parsedResponse = null;
        try {
          parsedResponse = JSON.parse(responseBody);
          result = JSON.parse(responseBody);
          if (parsedResponse !== null && parsedResponse !== undefined) {
            let resultMapper = {
              required: false,
              serializedName: 'parsedResponse',
              type: {
                name: 'Sequence',
                element: {
                    required: false,
                    serializedName: 'DeviceInfoElementType',
                    type: {
                      name: 'Composite',
                      className: 'DeviceInfo'
                    }
                }
              }
            };
            result = client.deserialize(resultMapper, parsedResponse, 'result');
          }
        } catch (error) {
          let deserializationError = new Error(util.format('Error "%s" occurred in deserializing the responseBody - "%s"', error, responseBody));
          deserializationError.request = msRest.stripRequest(httpRequest);
          deserializationError.response = msRest.stripResponse(response);
          return callback(deserializationError);
        }
      }

      return callback(null, result, httpRequest, response);
    });
  }
```

**Comment by christav** [comment]
@amarzavery But that generated code is still wrong - it's trying to JSON.parse a body that's not json. It's a csv file.

Is there a way to describe an operation that just returns a blob?

**Comment by amarzavery** [comment]
I just made up that swagger by taking this spec: https://github.com/Microsoft/mobile-center-cli/blob/master/swagger/bifrost.swagger.json, adding the operation you provided up and took the DeviceInfo object from here https://github.com/Azure/azure-rest-api-specs/blob/master/arm-mobileengagement/2014-12-01/swagger/mobile-engagement.json. 
It would be nice if you can provide a link to your swagger, so that we use the same spec as input.

I think there is a way. You can add the schema "type" as a "file"
```
"200": {
            "description": "Foo Bar",
            "schema": {
              "type": "file"
            }
```

We have 

- a **test swagger** over here https://github.com/Azure/autorest/blob/master/src/dev/TestServer/swagger/body-file.json 
- and the corresponding **node.js client that returns the stream** over here https://github.com/Azure/autorest/blob/master/src/generator/AutoRest.NodeJS.Tests/Expected/AcceptanceTests/BodyFile/operations/files.js#L51

Would that help ?

**Comment by christav** [comment]
@amarzavery That helps immensely, thanks! The full swagger is at https://bifrost-int.trafficmanager.net/preview/swagger.json, but as it's our internal test environment and the contents change fairly quickly I didn't want to feed you the whole thing.

There are two different operations that case the same problem, hopefully we have the same fix for them.

**Comment by christav** [comment]
@amarzavery Ok, I just tried it. If I put `"type": "file"` and remove the `"produces"` property then the operation compiles. I think this should do the trick. Thanks!

The error message still sucks though. :smile:

**Comment by amarzavery** [comment]
Glad to know that you are unblocked. We will fix up the error message.
Btw, if you are trying out a different pattern for example file upload/download or multipart-formdata then taking a look at test swaggers (https://github.com/Azure/autorest/blob/master/src/dev/TestServer/swagger) is helpful.

A separate thing: We are revamping the node.js codegen to support:
- ES6 classes
- callbacks and promises (if callback not provided then instead of throwing an error we assume that the caller is expecting a promise and return a Promise)
- Adding a convenience method to iterate through all the pages in a pageable operation using `iterables`.
- Fixing the d.ts files as per the latest version of TS

Will be tagging you in some PRs in the node sdk to get your valuable feedback on the new prototype.

**Comment by masaeedu** [comment]
@amarzavery Have the error messages been fixed? I'm still seeing this in autorest installed with `npm install -g autorest`, not sure if I need to build from master. 

The swagger file I'm working is way too large, and has way too many `produces` sections, to be able to feasibly bisect it for culprits. If the error messages are still useless, the issue should be reopened.

**Comment by miqid** [comment]
Also saw a similar error while working with a modestly-sized Swagger file today.

```
FATAL: System.Collections.Generic.KeyNotFoundException: Please specify a field with type of System.Byte[] to deserialize the file contents to
   at AutoRest.Modeler.OperationBuilder.VerifyFirstPropertyIsByteArray(CompositeType serviceType) in C:\Users\ci\AppData\Local\Temp\PUBLISHu1dw1\43_20171213T192246\autorest.modeler\src\OperationBuilder.cs:line 441
   at AutoRest.Modeler.OperationBuilder.TryBuildStreamResponse(HttpStatusCode responseStatusCode, OperationResponse response, Method method, List`1 types, IModelType headerType) in C:\Users\ci\AppData\Local\Temp\PUBLISHu1dw1\43_20171213T192246\autorest.modeler\src\OperationBuilder.cs:line 422
   at AutoRest.Modeler.OperationBuilder.BuildResponses(Method method, CompositeType headerType) in C:\Users\ci\AppData\Local\Temp\PUBLISHu1dw1\43_20171213T192246\autorest.modeler\src\OperationBuilder.cs:line 336
   at AutoRest.Modeler.OperationBuilder.BuildMethod(HttpMethod httpMethod, String url, String methodName, String methodGroup) in C:\Users\ci\AppData\Local\Temp\PUBLISHu1dw1\43_20171213T192246\autorest.modeler\src\OperationBuilder.cs:line 195
   at AutoRest.Modeler.SwaggerModeler.BuildMethod(HttpMethod httpMethod, String url, String name, Operation operation) in C:\Users\ci\AppData\Local\Temp\PUBLISHu1dw1\43_20171213T192246\autorest.modeler\src\SwaggerModeler.cs:line 366
   at AutoRest.Modeler.SwaggerModeler.Build(ServiceDefinition serviceDefinition) in C:\Users\ci\AppData\Local\Temp\PUBLISHu1dw1\43_20171213T192246\autorest.modeler\src\SwaggerModeler.cs:line 105
   at AutoRest.Modeler.Program.<ProcessInternal>d__2.MoveNext() in C:\Users\ci\AppData\Local\Temp\PUBLISHu1dw1\43_20171213T192246\autorest.modeler\src\Program.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NewPlugin.<Process>d__15.MoveNext()
FATAL: csharp/imodeler1 - FAILED
FATAL: Error: Plugin imodeler1 reported failure.
Process() Cancelled due to exception : Plugin imodeler1 reported failure.
```

In my case, I had operations that had `produces` sections with `text/plain` and a `type` of `string` in the response schema. Removing the `produces` sections was enough to get AutoRest to run through to completion without errors.

**Comment by fearthecowboy** [comment]
@miqid you're showing a different problem -- could you file a new bug, and if you can, attach the swagger file that was failing you?
