### ISSUE TITLE
dotnet sdk is not automatically installed

### ISSUE THREAD

**Issue by jaredmoo** [Azure/autorest#2088]
Without dotnet sdk installed I get this error:

```
(c) 2017 Microsoft Corporation. https://aka.ms/autorest
  Build Information
  Autorest Bootstrapper :  0.9.21
  NetCore framework :      1.0.3
  Latest Core Installed :  1.0.1-20170327-2300-nightly
  Requested Core Version : <none>

Output Verbosity

  --verbose            show verbose output information
  --debug              show internal debug information
  --quiet              suppress output

Versions

  --list-installed     show all installed versions of AutoRest tools
  --list-available=nn  lists the last nn releases available from github
                        (defaults to 10)

Installation

  --version=version    uses version of AutoRest, installing if necessary.
                        for version you can
                        use a version label (see --list-available) or
                          latest         - get latest nightly build
                          latest-release - get latest release version
  --reset              remove all installed versions of AutoRest tools
                        and install the latest (override with --version)

Using AutoRest
{ Error: spawn dotnet ENOENT
    at exports._errnoException (util.js:1018:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn dotnet',
  path: 'dotnet',
  spawnargs:
   [ 'C:\\Users\\jaredmoo\\.autorest\\plugins\\autorest\\1.0.1-20170327-2300-nightly\\AutoRest.dll',
     '-Help' ] }
```

**Comment by RamiSh** [comment]
Yep, had the same issue this morning. Had to install .net core sdk manually

**Comment by fearthecowboy** [comment]
ah. ok.. I'll stop everything right now and put this on a new machine and test it from scratch. Something must have changed somewhere that we're not seeing

**Comment by fearthecowboy** [comment]
Egads! 
Fixed it.


Run :
``` batch 
> autorest --reset 
```

And it'll pick up the latest build.
