### ISSUE TITLE
AutoRest throws error for "body" parameter that is of type string

### ISSUE THREAD

**Issue by vivlingaiah** [Azure/autorest#2095]
AutoRest throws below error for "body" parameter that is of type string. Pls refer related swagger spec file attached. Line 454

[runbookjson.txt](https://github.com/Azure/autorest/files/886736/runbookjson.txt)

```
C:\Users\vivekl\Documents\GitHub\azure-rest-api-specs\arm-automation>autorest -input compositeAutomation.json -CodeGenerator Azure.CSharp -Modeler CompositeSwagger -disableSimpli
fier -Namespace Microsoft.Azure.Management.Automation
AutoRest

There is a new version of AutoRest available (0.9.22).
Install with 'npm install autorest -g '.

FATAL: Error generating client model: System.NullReferenceException: Object reference not set to an instance of an object.
   at AutoRest.Swagger.ParameterBuilder.BuildServiceType(String serviceTypeName)
   at AutoRest.Swagger.ParameterBuilder.Build()
   at AutoRest.Swagger.OperationBuilder.BuildMethodParameters(Method method)
   at AutoRest.Swagger.OperationBuilder.BuildMethod(HttpMethod httpMethod, String url, String methodName, String methodGroup)
   at AutoRest.Swagger.SwaggerModeler.Build(ServiceDefinition serviceDefinition)
   at AutoRest.CompositeSwagger.CompositeSwaggerModeler.Build()
   at AutoRest.Core.AutoRestController.Generate()
ERROR: Error generating client model: System.NullReferenceException: Object reference not set to an instance of an object.
   at AutoRest.Swagger.ParameterBuilder.BuildServiceType(String serviceTypeName)
   at AutoRest.Swagger.ParameterBuilder.Build()
   at AutoRest.Swagger.OperationBuilder.BuildMethodParameters(Method method)
   at AutoRest.Swagger.OperationBuilder.BuildMethod(HttpMethod httpMethod, String url, String methodName, String methodGroup)
   at AutoRest.Swagger.SwaggerModeler.Build(ServiceDefinition serviceDefinition)
   at AutoRest.CompositeSwagger.CompositeSwaggerModeler.Build()
   at AutoRest.Core.AutoRestController.Generate()
ERROR: Code generation failed.
ERROR: AutoRest.dll -input compositeAutomation.json -CodeGenerator Azure.CSharp -Modeler CompositeSwagger -disableSimplifier -Namespace Microsoft.Azure.Management.Automation

C:\Users\vivekl\Documents\GitHub\azure-rest-api-specs\arm-automation>
```

**Comment by sergey-shandar** [comment]
@vivlingaiah could you also provide a swagger file?

**Comment by vivlingaiah** [comment]
it is attached. Please refer above. <runbookjson.txt>

**Comment by fearthecowboy** [comment]
According to : http://swagger.io/specification/#parameterIn

You have to specify `schema: { ... } ` (inwhich you can say `"type":"string"` ) for body parameters.

**Comment by vivlingaiah** [comment]
thanks. Like this correct ?
          {
            "name": "runbookContent",
            "in": "body",
            "required": true,
            "schema": {
              "type": "string"
            },
            "description": "The runbook draft content."
          },

**Comment by fearthecowboy** [comment]
I believe so. I was going to test that, but I didn't have the `definitions.json` that the spec attached uses.

**Comment by vivlingaiah** [comment]
Hi, I used above. requests are all working fine when seen in fiddler. However, SDK throws Rest.CloudException
{"The response from long running operation does not contain a body."}
Also, refer, the fiddler traces attached

[RunbookDraft.txt](https://github.com/Azure/autorest/files/894728/RunbookDraft.txt)

1. Creates runbook draft
2. operations results call operationResults. This is where it throws exception as it does not return a request body
3. Get draft content. this works

Stack trace:
   at Microsoft.Rest.Azure.AzureClientExtensions.<UpdateStateFromGetResourceOperation>d__12`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Rest.Azure.AzureClientExtensions.<GetLongRunningOperationResultAsync>d__1`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Rest.Azure.AzureClientExtensions.<GetLongRunningOperationResultAsync>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Rest.Azure.AzureClientExtensions.<GetLongRunningOperationResultAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Rest.Azure.AzureClientExtensions.<GetPutOrPatchOperationResultAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.Management.Automation.RunbookDraftOperations.<CreateOrUpdateWithHttpMessagesAsync>d__6.MoveNext() in C:\Users\vivekl\Documents\GitHub\azure-sdk-for-net\src\ResourceManagement\Automation\Microsoft.Azure.Management.Automation\Generated\RunbookDraftOperations.cs:line 259
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.Management.Automation.RunbookDraftOperationsExtensions.<CreateOrUpdateAsync>d__3.MoveNext() in C:\Users\vivekl\Documents\GitHub\azure-sdk-for-net\src\ResourceManagement\Automation\Microsoft.Azure.Management.Automation\Generated\RunbookDraftOperationsExtensions.cs:line 110
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Azure.Management.Automation.RunbookDraftOperationsExtensions.CreateOrUpdate(IRunbookDraftOperations operations, String resourceGroupName, String automationAccountName, String runbookName, String runbookContent) in C:\Users\vivekl\Documents\GitHub\azure-sdk-for-net\src\ResourceManagement\Automation\Microsoft.Azure.Management.Automation\Generated\RunbookDraftOperationsExtensions.cs:line 83
   at ConsoleApplication1.Program.sampleOperation() in C:\ChangeTrackingUX\AutomationSDKSample\ConsoleApplication1\Program.cs:line 130
   at ConsoleApplication1.Program.Main(String[] args) in C:\ChangeTrackingUX\AutomationSDKSample\ConsoleApplication1\Program.cs:line 66
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by vivlingaiah** [comment]
Also, I see one more issue PUT request 202.  The request body seems to be using wrong escape characters, due to which it is ending up with unwanted behavior. The content is kind of unusable

**Comment by vivlingaiah** [comment]
"<#\r\n    .DESCRIPTION\r\n        An example runbook which prints out the first 10 Azure VMs in your subscription (ordered alphabetically).\r\n        For more information about how this runbook authenticates to your Azure subscription, see our documentation here: http://aka.ms/fxu3mn\r\n\r\n    ....

**Comment by vivlingaiah** [comment]
I'll have to use "application/text" in produces and consumes here ?

**Comment by vivlingaiah** [comment]
- here's a screenshot of end result. Runbook that is unusable
-also attached spec. OPeration is RunbookDraft_CreateOrUpdate
![runbookdraftunusable](https://cloud.githubusercontent.com/assets/25780318/24712068/a99f5b96-19d6-11e7-86cf-41184401cfa3.JPG)
[runbook_json.txt](https://github.com/Azure/autorest/files/899817/runbook_json.txt)

**Comment by vivlingaiah** [comment]
definitions file
[definitions_json.txt](https://github.com/Azure/autorest/files/899853/definitions_json.txt)

**Comment by dsgouda** [comment]
@vivlingaiah is this still relevant? Let us know if you still have any issues with the sdk and we can help out.
Will close this PR in the meantime
