### ISSUE TITLE
AutoRest bootstrapper fails to retrieve NetCore & AutoRest Core.

### ISSUE THREAD

**Issue by JoshuaWhatley** [Azure/autorest#2280]
When running the following command: `autorest --list-installed`

```
AutoRest Code Generator
(c) 2017 Microsoft Corporation. https://aka.ms/autorest
Build Information
  Autorest Bootstrapper :  0.13.2
  NetCore framework :      <none>
  Latest Core Installed :  <none>
  Requested Core Version : <none>
```
and if I try to generate a client library with the following command:  `autorest -Input "petstore.json" -Namespace "petstore" -CodeGenerator "CSharp" --debug`

There are no failures indicated and the logs are filled with a bunch of github metadata (below). It doesn't appear to retrieve the frameworks. Any insight into why this would be happening? Is there any more in depth logging that could help me discover why this would be happening. Is there a way to include a particular version of AutoRest core and bypass the bootstrapper?

```
[6:35:7] Network Enabled: true
AutoRest Code Generator
(c) 2017 Microsoft Corporation. https://aka.ms/autorest
[6:35:8] [ { url: 'https://api.github.com/repos/Azure/autorest/releases/6424998',
    assets_url: 'https://api.github.com/repos/Azure/autorest/releases/6424998/assets',
    upload_url: 'https://uploads.github.com/repos/Azure/autorest/releases/6424998/assets{?name,label}',
    html_url: 'https://github.com/Azure/autorest/releases/tag/v1.0.1-20170517-2300-nightly',
    id: 6424998,
    tag_name: 'v1.0.1-20170517-2300-nightly',
    target_commitish: 'master',
    name: '1.0.1-20170517-2300-nightly',
    draft: false,
    author: 
     { login: 'azuresdkci',
       id: 1087595,
       avatar_url: 'https://avatars2.githubusercontent.com/u/1087595?v=3',
       gravatar_id: '',
       url: 'https://api.github.com/users/azuresdkci',
       html_url: 'https://github.com/azuresdkci',
       followers_url: 'https://api.github.com/users/azuresdkci/followers',
       following_url: 'https://api.github.com/users/azuresdkci/following{/other_user}',
       gists_url: 'https://api.github.com/users/azuresdkci/gists{/gist_id}',
       starred_url: 'https://api.github.com/users/azuresdkci/starred{/owner}{/repo}',
       subscriptions_url: 'https://api.github.com/users/azuresdkci/subscriptions',
       organizations_url: 'https://api.github.com/users/azuresdkci/orgs',
       repos_url: 'https://api.github.com/users/azuresdkci/repos',
       events_url: 'https://api.github.com/users/azuresdkci/events{/privacy}',
       received_events_url: 'https://api.github.com/users/azuresdkci/received_events',
       type: 'User',
       site_admin: false },
    prerelease: true,
    created_at: '2017-05-17T16:54: 50Z',
    published_at: '2017-05-18T06:06: 39Z',
    assets: [ [Object] ],
    tarball_url: 'https://api.github.com/repos/Azure/autorest/tarball/v1.0.1-20170517-2300-nightly',
    zipball_url: 'https://api.github.com/repos/Azure/autorest/zipball/v1.0.1-20170517-2300-nightly',
    body: 'This release just contains the binary runtimes for the 1.0.1-20170517-2300-nightly release of AutoRest.\n\nTo Install AutoRest, install nodej.js 6.9.5 or later, and run\n\n&gt; npm install -g autorest\n\n(You don\'t want to download these files directly, there\'s no point.)' },
  { url: 'https://api.github.com/repos/Azure/autorest/releases/6410853',
    assets_url: 'https://api.github.com/repos/Azure/autorest/releases/6410853/assets',
    upload_url: 'https://uploads.github.com/repos/Azure/autorest/releases/6410853/assets{?name,label}',
    html_url: 'https://github.com/Azure/autorest/releases/tag/v1.0.1-20170516-2300-nightly',
    id: 6410853,
    tag_name: 'v1.0.1-20170516-2300-nightly',
    target_commitish: 'master',
    name: '1.0.1-20170516-2300-nightly',
    draft: false,
    author: 
     { login: 'azuresdkci',
       id: 1087595,
       avatar_url: 'https://avatars2.githubusercontent.com/u/1087595?v=3',
       gravatar_id: '',
       url: 'https://api.github.com/users/azuresdkci',
       html_url: 'https://github.com/azuresdkci',
       followers_url: 'https://api.github.com/users/azuresdkci/followers',
       following_url: 'https://api.github.com/users/azuresdkci/following{/other_user}',
       gists_url: 'https://api.github.com/users/azuresdkci/gists{/gist_id}',
       starred_url: 'https://api.github.com/users/azuresdkci/starred{/owner}{/repo}',
       subscriptions_url: 'https://api.github.com/users/azuresdkci/subscriptions',
       organizations_url: 'https://api.github.com/users/azuresdkci/orgs',
       repos_url: 'https://api.github.com/users/azuresdkci/repos',
       events_url: 'https://api.github.com/users/azuresdkci/events{/privacy}',
       received_events_url: 'https://api.github.com/users/azuresdkci/received_events',
       type: 'User',
       site_admin: false },
    prerelease: true,
    created_at: '2017-05-16T23:33: 04Z',
    published_at: '2017-05-17T06:08: 06Z',
    assets: [ [Object] ],
    tarball_url: 'https://api.github.com/repos/Azure/autorest/tarball/v1.0.1-20170516-2300-nightly',
    zipball_url: 'https://api.github.com/repos/Azure/autorest/zipball/v1.0.1-20170516-2300-nightly',
    body: 'This release just contains the binary runtimes for the 1.0.1-20170516-2300-nightly release of AutoRest.\n\nTo Install AutoRest, install nodej.js 6.9.5 or later, and run\n\n&gt; npm install -g autorest\n\n(You don\'t want to download these files directly, there\'s no point.)' },
  { ... (and so on)
```

**Comment by fearthecowboy** [comment]
That doesn't quite look good.

What happens if you try `autorest --reset` 

that should ensure that you have the right bits installed.

**Comment by fearthecowboy** [comment]
Hmm. You're running a slightly old build -- try `npm install -g autorest ` to get the latest

**Comment by JoshuaWhatley** [comment]
A little more context, I am trying to get AutoRest running in an Azure WebJob. I used Kudu to run the commands you mentioned above. It looks like the the latter made some progress as I am seeing the following now. 

```
(c) 2017 Microsoft Corporation. https://aka.ms/autorest
Build Information
  Autorest Bootstrapper :  0.13.3
  NetCore framework :      <none>
  Latest Core Installed :  1.0.1-20170518-2300-nightly
  Requested Core Version : <none>
Installed versions of AutoRest :

  1.0.1-20170518-2300-nightly
```

It still looks like it is having issues retrieving the NetCore framework. When I run `autorest --reset` it points to the likely issue here.

```
AutoRest Code Generator
(c) 2017 Microsoft Corporation. https://aka.ms/autorest
Error: Unsupported Windows architecture: unknown
    at Function.getRuntimeId (D:\home\site\wwwroot\app_data\jobs\continuous\ClientCodeGeneration\node_modules\autorest\utility\platform.js:180:23)
    at new PlatformInformation (D:\home\site\wwwroot\app_data\jobs\continuous\ClientCodeGeneration\node_modules\autorest\utility\platform.js:85:50)
    at GetCurrent.Promise.all.then (D:\home\site\wwwroot\app_data\jobs\continuous\ClientCodeGeneration\node_modules\autorest\utility\platform.js:139:20)
Unable to find framework for null
Downloading https://github.com/Azure/autorest/releases/download/v1.0.1-20170518-2300-nightly/autorest-1.0.1-20170518-2300-nightly.zip 
        to  D:\local\UserProfile.autorest\plugins\autorest\1.0.1-20170518-2300-nightly
```

Any guidance here?

**Comment by fearthecowboy** [comment]
O_o .. hmm. Detection needs work. 

Try adding  ` --runtime-id=win-x64`  to the command line.

**Comment by JoshuaWhatley** [comment]
I am assuming I add this to the reset command? `autorest --reset --runtime-id=win-x64`

```
AutoRest Code Generator
(c) 2017 Microsoft Corporation. https://aka.ms/autorest
Unable to find framework for win-x64
Downloading https://github.com/Azure/autorest/releases/download/v1.0.1-20170518-2300-nightly/autorest-1.0.1-20170518-2300-nightly.zip 
        to  D:\local\UserProfile.autorest\plugins\autorest\1.0.1-20170518-2300-nightly
```

Appreciate the help.

**Comment by fearthecowboy** [comment]
Dammit. Sorry about that-- it should be `--runtime-id-win7-x64`

**Comment by JoshuaWhatley** [comment]
That did the trick! Thanks.
