### ISSUE TITLE
[AzureArm][CSharp] Cannot convert Newtonsoft.Json.Linq.JObject to System.String

### ISSUE THREAD

**Issue by deathly809** [Azure/autorest#2464]
I have some swagger specs generated from Swashbuckler.  I have cleaned them up but when I try to generate C# using  the command

`autorest --input-file=smallest.json --payload-flattening-threshold=2 --verbose --debug  --csharp --azure-arm`

I get the error

```
FATAL: System.InvalidCastException: Unable to cast object of type 'Newtonsoft.Json.Linq.JObject' to type 'System.String'.
   at AutoRest.Extensions.Azure.AzureExtensions.ParseODataExtension(CodeModel codeModel)
   at AutoRest.Extensions.Azure.AzureExtensions.NormalizeAzureClientModel(CodeModel codeModel)
   at AutoRest.CSharp.Azure.TransformerCsa.AutoRest.Core.ITransformer<AutoRest.CSharp.Azure.Model.CodeModelCsa>.TransformCodeModel(CodeModel cs)
   at Generator.<ProcessInternal>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NewPlugin.<Process>d__11.MoveNext()
FATAL: csharp/generate - FAILED
FATAL: Error: Plugin csharp reported failure.
Process() Cancelled due to exception : Plugin csharp reported failure.
Error: Plugin csharp reported failure.
    at C:\Users\jerobins.REDMOND\.autorest\plugins\autorest\1.2.2\node_modules\autorest-core\lib\pipeline\pipeline.js:90:19
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\jerobins.REDMOND\AppData\Roaming\npm\node_modules\autorest\lib\polyfill.min.js:14:62)
    at <anonymous>
```

Using the command 

`autorest --input-file=StorageSystemResource.json --payload-flattening-threshold=2 --verbose --debug  --csharp`

No error and C# code is generated.

In addition, if I delete a portion of the swagger spec containing:

```
"x-ms-odata": {
      "type": "object"
}
```

Then both commands succeed.  Should the type be something else?

I have attached a small example which exhibits the error.  

[smallest.txt](https://github.com/Azure/autorest/files/1163775/smallest.txt)

**Comment by olydis** [comment]
As I understand our [documentation](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/swagger-extensions.md#x-ms-odata), this should be a reference to a type definition

**Comment by deathly809** [comment]
If object is not allowed why does it work using one code generator but not the other? Especially if they both generate C# code (but I am assuming doing something different).  Is the azure-arm generated code using a specific library which disallows object as the odata type?

**Comment by fearthecowboy** [comment]
IIRC `x-ms-odata ` is only supported for `azure-arm` it's ignored without it...

**Comment by olydis** [comment]
@deathly809 Oh I only noted the missing `--azure-arm` in the second command now - my attention was consumed by `StorageSystemResource.json` so I thought it's simply different Swaggers...

**Comment by deathly809** [comment]
No they are the same swagger spec.  I fixed the original report to make sure the files are the same.  I just copied them and changed the names since this is internal to Microsoft.

**Comment by deathly809** [comment]
I figured out how to to make it work, you just need to add a new parameter:

```
"FilterParameter" : {
    "name": "$filter",
    "in": "query,
    "type": "string"
}
```
and then add it to the list of parameters.

Not sure if still bug.

**Comment by olydis** [comment]
Awesome, thanks for investigating! Bug or not, at least the message could be better. We'll leave the issue open for that purpose 🙂
