### ISSUE TITLE
ISO 8601 timespan serialization failing in C#

### ISSUE THREAD

**Issue by DheerendraRathor** [Azure/autorest#2466]
Got error: 
Inner Exception 1:
SerializationException: Unable to deserialize the response.

Inner Exception 2:

> JsonSerializationException: Error converting value "PT6.662698S" to type 'System.Nullable`1[System.TimeSpan]'. Path 'duration', line 1, position 354.

Inner Exception 3:
ArgumentException: Could not cast or convert from System.String to System.TimeSpan.

### Another:

InnerException	{Microsoft.Rest.SerializationException: Unable to deserialize the response. ---> Newtonsoft.Json.JsonSerializationException: Error converting value "PT15.3071628S" to type 'System.Nullable`1[System.TimeSpan]'. Path 'duration', line 1, position 356. ---> System.ArgumentException: Could not cast or convert from System.String to System.TimeSpan.
   at Newtonsoft.Json.Utilities.ConvertUtils.EnsureTypeAssignable(Object value, Type initialType, Type targetType)
   at Newtonsoft.Json.Utilities.ConvertUtils.ConvertOrCast(Object initialValue, CultureInfo culture, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Microsoft.Rest.Serialization.SafeJsonConvert.DeserializeObject[T](String json, JsonSerializerSettings settings)
   at Microsoft.Azure.Management.RecoveryServices.Backup.JobDetailsOperations.<GetWithHttpMessagesAsync>d__5.MoveNext() in C:\Code\DheerendraRathor\azure-sdk-for-net\src\SDKs\RecoveryServices.Backup\Management.RecoveryServices.Backup\Generated\JobDetailsOperations.cs:line 239
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Management.RecoveryServices.Backup.JobDetailsOperations.<GetWithHttpMessagesAsync>d__5.MoveNext() in C:\Code\DheerendraRathor\azure-sdk-for-net\src\SDKs\RecoveryServices.Backup\Management.RecoveryServices.Backup\Generated\JobDetailsOperations.cs:line 248}	System.Exception {Microsoft.Rest.SerializationException}

**Comment by MaheshB0ngani** [comment]
I'm also facing the same issue.
Why is this closed? Any solution for this?

Help me.
