### ISSUE TITLE
Cannot regen schemas using profiles\ResourceSchemas.md: iterator error

### ISSUE THREAD

**Issue by jaredmoo** [Azure/autorest#2470]
```
C:\git\azure-rest-api-specs\profiles [current ≡]> autorest --help
AutoRest Code Generator
(c) 2017 Microsoft Corporation. https://aka.ms/autorest
  Build Information
  Autorest Bootstrapper :  1.2.2
  NetCore framework :      1.0.5
  Latest Core Installed :  1.2.2
  Requested Core Version : <none>

Output Verbosity

  --verbose            show verbose output information
  --debug              show internal debug information
  --quiet              suppress output

Versions

  --list-installed     show all installed versions of AutoRest tools
  --list-available=nn  lists the last nn releases available from github
                        (defaults to 10)

Installation

  --version=version    uses version of AutoRest, installing if necessary.
                        for version you can
                        use a version label (see --list-available) or
                          latest         - get latest nightly build
                          latest-release - get latest release version
  --reset              remove all installed versions of AutoRest tools
                        and install the latest (override with --version)
  --runtime-id=id      overrides the platform detection for the dotnet runtime.

  SEE ALSO : https://aka.ms/autorest/cli for additional documentation
C:\git\azure-rest-api-specs\profiles [current ≡]> autorest --output-folder=c:\git\azure-resource-manager-schemas\schemas

AutoRest Code Generator
(c) 2017 Microsoft Corporation. https://aka.ms/autorest
TypeError: config.GetEntry(...)[Symbol.iterator] is not a function
    at C:\Users\jaredmoo\.autorest\plugins\autorest\1.2.2\node_modules\autorest-core\app.js:354:44
    at next (native)
    at fulfilled (C:\Users\jaredmoo\AppData\Roaming\npm\node_modules\autorest\lib\polyfill.min.js:14:62)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

**Comment by olydis** [comment]
@fearthecowboy uhm didn't expect anyone to actually run that, it's probably the new `batch` mode that broke this. Changing it to `resource-schema-batch` should do the trick.

**Comment by jaredmoo** [comment]
FWIW I'm also interested in having a configuration that lets me run --azure-validator on all swagger files.

**Comment by fearthecowboy** [comment]
I'm working on a new bit right now to generate all the whole resource schema set by iterating over all the RP configurations and `tag`s .

I might be able to make it do a full-repo `--azure-validator` as well. Lemme see what I can do.

**Comment by olydis** [comment]
@fearthecowboy Note that for `--azure-validator` (i.e. where no post processing is necessary), a completely generic `batch` file listing all swaggers will do. Then users can go `autorest all.md --azure-validator` or `autorest all.md --csharp --csharp-sdks-folder=...` to see magic happening. 🙂

**Comment by jaredmoo** [comment]
Let me clarify: I would like a way to run --azure-validator just on my RP so that I don't have to sift through all the other RP's issues. :)

**Comment by olydis** [comment]
you mean on all (including past) Swaggers if your RP? essentially iterating over tags? That would work with the same logic but would indeed require maintaining a list of tags... which is something we are planning on automating right now 👍
