### ISSUE TITLE
[Request] Better and more useful output for errors.

### ISSUE THREAD

**Issue by deathly809** [Azure/autorest#2486]
The errors printed are not very helpful.

```
FATAL: System.NullReferenceException: Object reference not set to an instance of an object.
   at AutoRest.Swagger.ParameterBuilder.BuildServiceType(String serviceTypeName)
   at AutoRest.Swagger.ParameterBuilder.Build()
   at AutoRest.Swagger.SwaggerModeler.Build(ServiceDefinition serviceDefinition)
   at Modeler.<ProcessInternal>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NewPlugin.<Process>d__11.MoveNext()
FATAL: csharp/modeler - FAILED
FATAL: Error: Plugin modeler reported failure.
Process() Cancelled due to exception : Plugin modeler reported failure.
Error: Plugin modeler reported failure.
    at C:\Users\jerobins.REDMOND\.autorest\plugins\autorest\1.2.2\node_modules\autorest-core\lib\pipeline\pipeline.js:90:19
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\jerobins.REDMOND\AppData\Roaming\npm\node_modules\autorest\lib\polyfill.min.js:14:62)
    at <anonymous>
```

It would be nice if it referenced something in my swagger spec.  I can at least tell it has something to do with parameters (maybe?). 

Maybe have something like

```
When referencing <#/Whatever/Sure> could not find <thing>

<Giant Stack Trace which is no use to me>
```

**Comment by olydis** [comment]
Hi @deathly809, could you please provide a repro? I have the affected method in front of me but could think of a number of ways it could throw an NRE. I hopefully fixed all of them but wanna make sure I covered your case 😉 Thanks!

**Comment by deathly809** [comment]
I already fixed my issue.  I referenced a parameter that did not exist I think.

**Comment by olydis** [comment]
Slick, that should be resolved as of our next release.
