### ISSUE TITLE
Errors not useful - System.ArgumentNullException: Value cannot be null

### ISSUE THREAD

**Issue by ankushbindlish** [Azure/autorest#2500]
```
AutoRest Code Generator
(c) 2017 Microsoft Corporation. https://aka.ms/autorest
{
  "Channel": "fatal",
  "Details": null,
  "Text": "System.ArgumentNullException: Value cannot be null.\r\nParameter name: input\r\n   at System.Text.RegularExpressions.Regex.IsMatch(String input)\r\n   at AutoRest.Swagger.Validation.ListInOperationName.<GetValidationMessages>d__11.MoveNext()\r\n   at System.Linq.Enumerable.<SelectManyIterator>d__159`2.MoveNext()\r\n   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()\r\n   at System.Linq.Enumerable.<SelectManyIterator>d__159`2.MoveNext()\r\n   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()\r\n   at AzureValidator.<ProcessInternal>d__3.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at NewPlugin.<Process>d__11.MoveNext()",
  "Key": null,
  "Source": null,
  "Plugin": "azure-validator"
}
{
  "Channel": "fatal",
  "Details": null,
  "Text": "System.ArgumentNullException: Value cannot be null.\r\nParameter name: input\r\n   at System.Text.RegularExpressions.Regex.IsMatch(String input)\r\n   at AutoRest.Swagger.Validation.CollectionObjectPropertiesNaming.<GetValidationMessages>d__11.MoveNext()\r\n   at System.Linq.Enumerable.<SelectManyIterator>d__159`2.MoveNext()\r\n   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()\r\n   at System.Linq.Enumerable.<SelectManyIterator>d__159`2.MoveNext()\r\n   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()\r\n   at AzureValidator.<ProcessInternal>d__3.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at NewPlugin.<Process>d__11.MoveNext()",
  "Key": null,
  "Source": null,
  "Plugin": "azure-validator"
}
{
  "Channel": "fatal",
  "Text": "swagger-document/individual/azure-validator - FAILED"
}
{
  "Channel": "fatal",
  "Text": "Error: Plugin azure-validator reported failure."
}
(node:30220) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Plugin azure-validator reported failure.
(node:30220) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:30220) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Plugin azure-validator reported failure.
{
  "Channel": "fatal",
  "Text": "swagger-document/azure-validator - FAILED"
}
{
  "Channel": "fatal",
  "Text": "Error: Plugin azure-validator reported failure."
}
Process() Cancelled due to exception : Plugin azure-validator reported failure.
Error: Plugin azure-validator reported failure.
    at C:\Users\ankushb\.autorest\plugins\autorest\1.2.2\node_modules\autorest-core\lib\pipeline\pipeline.js:90:19
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\ankushb\AppData\Roaming\npm\node_modules\autorest\lib\polyfill.min.js:14:62)

```

**Comment by fearthecowboy** [comment]
@ankushbindlish -  that's obviously a quite unexpected error.

Can you show me your swagger file?

**Comment by ankushbindlish** [comment]
Have sent out file internally

**Comment by olydis** [comment]
@ankushbindlish Trying to generate C# code from your Swagger, I got a different, more meaningful error message:
> FATAL: OperationId is required for all operations. Please add it for 'put' operation of '/subscriptions/{subscriptionId}' path.

Whoops, indeed *all* your operations are missing an `operationId` 😉 The validator seems to blindly assume its existence so it fails - I'll open an issue there.

Let me know if you encounter any further issues!
