### ISSUE TITLE
Cannot generate a formatted sequence from a non-string array parameter AutoRest.NodeJS.Model.ParameterJs

### ISSUE THREAD

**Issue by theLichDev** [Azure/autorest#2568]
I'm trying to execute this in PowerShell:

**autorest --input-file=swaggerKoa.json --nodejs --output-folder=Node_SwaggerKOA --namespace=SwaggerKoa**

I have tested generate with other languages like C# or Java and It is alright. But when i try with **--nodejs** option I'm getting this error:

```
AutoRest Code Generator
(c) 2017 Microsoft Corporation. https://aka.ms/autorest
FATAL: System.InvalidOperationException: Cannot generate a formatted sequence from a non-string array parameter AutoRest.NodeJS.Model.ParameterJs
   at AutoRest.NodeJS.ClientModelExtensions.GetFormattedReferenceValue(Parameter parameter)
   at AutoRest.NodeJS.Model.MethodJs.BuildQueryParameterArray(IndentedStringBuilder builder)
   at AutoRest.NodeJS.Model.MethodJs.BuildUrl(String variableName)
   at AutoRest.NodeJS.Templates.MethodTemplate.<ExecuteAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AutoRest.Core.Template`1.ToString()
   at AutoRest.NodeJS.Templates.ServiceClientTemplate.<ExecuteAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AutoRest.Core.CodeGenerator.<Write>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AutoRest.NodeJS.CodeGeneratorJs.<Generate>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Generator.<ProcessInternal>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NewPlugin.<Process>d__11.MoveNext()
FATAL: nodejs/generate - FAILED
FATAL: Error: Plugin nodejs reported failure.
Process() Cancelled due to exception : Plugin nodejs reported failure.
Error: Plugin nodejs reported failure.
    at C:\Users\itorrero\.autorest\plugins\autorest\1.2.2\node_modules\autorest-core\lib\pipeline\pipeline.js:90:19
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\itorrero\AppData\Roaming\npm\node_modules\autorest\lib\polyfill.min.js:14:62)
```

The problem disappear if I delete this in the json:
```
"parameters": [
   {
	"name": "Sorts",
	"in": "query",
        "required": false,
	"type": "array",
	"items": {},
	"collectionFormat": "multi"
   }
```

My system information: 

Windows 10 64 bits.
-node: 7.10.1
-npm: 5.0.4
-autorest: 1.2.2

**Comment by amarzavery** [comment]
Thanks for pointing this. Looks like we missed implementing this in the NodeJS codegenerator. Will add support for this quickly.

**Comment by theLichDev** [comment]
You're welcome, that's what the community is for. :)

**Comment by amarzavery** [comment]
@theLichDev - 1.9.3 version of the nodejs codegenerator contains this fix. However, you will have to use the prerelease version of autorest bootstrapper to get the latest changes.
`npm install -g autorest@prerelease` and then execute the autorest command and you should be good to go. If for some reason that does not work then you can force the bootstrapper to use the new version of autorest by adding this switch `autorest <other parameters as usual> --use=azure/autorest.nodejs`.

**Comment by theLichDev** [comment]
@amarzavery Thank you very much for the solution.

**Comment by amarzavery** [comment]
closing this issue. please reopen if the problem persists.
