### ISSUE TITLE
Error when trying to update autorest

### ISSUE THREAD

**Issue by thdotnet** [Azure/autorest#2573]
I'm trying to run "autorest --latest" and I'm getting the following error:

λ autorest --latest
C:\Users\usuario\AppData\Roaming\npm\node_modules\autorest\github.js:47
function Rest(url, feed, i = 0) {
                           ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\usuario\AppData\Roaming\npm\node_modules\autorest\app.js:5:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

**Comment by olydis** [comment]
you're running a too old version of NodeJS (next AutoRest release will actually check that and emit a warning), please install Node 7.10.0 or higher :)

I'm 99% sure this is the issue, so I'll close, but please reopen the issue or post further questions in here if you encounter any issues!
