### ISSUE TITLE
Unable to model timeseriesinsights swagger

### ISSUE THREAD

**Issue by mcardosos** [Azure/autorest#2579]
It fails like this...
```
exit status 4: FATAL: System.InvalidOperationException: Found incompatible property types ,  for property 'properties' in schema inheritance chain
   at AutoRest.Modeler.SchemaResolver.ExpandAllOf(Schema schema) in C:\work\oneautorest\autorest.modeler\src\SchemaResolver.cs:line 157
   at AutoRest.Modeler.SchemaResolver.Unwrap(Schema schema) in C:\work\oneautorest\autorest.modeler\src\SchemaResolver.cs:line 75
   at AutoRest.Modeler.SchemaBuilder.BuildServiceType(String serviceTypeName) in C:\work\oneautorest\autorest.modeler\src\SchemaBuilder.cs:line 35
   at AutoRest.Modeler.SwaggerModeler.BuildCompositeTypes() in C:\work\oneautorest\autorest.modeler\src\SwaggerModeler.cs:line 297
   at AutoRest.Modeler.SwaggerModeler.Build(ServiceDefinition serviceDefinition) in C:\work\oneautorest\autorest.modeler\src\SwaggerModeler.cs:line 66
   at AutoRest.Modeler.Program.<ProcessInternal>d__2.MoveNext() in C:\work\oneautorest\autorest.modeler\src\Program.cs:line 53
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NewPlugin.<Process>d__15.MoveNext()
FATAL: go/modeler - FAILED
FATAL: Error: Plugin modeler reported failure.
Error: Plugin modeler reported failure.
    at CreatePluginExternal (C:\Users\mcardoso\.autorest\@microsoft.azure_autorest-core@1.9.6\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\pipeline.js:91:19)
    at <anonymous>
```

**Comment by olydis** [comment]
moved to https://github.com/Azure/azure-rest-api-specs/issues/1683 - no should have been able to generate any code from that so far.
@mcardosos Where you guys specifically asked for this i.e. do you need a workaround?

**Comment by mcardosos** [comment]
Well, it is one of the few swaggers from which we cannot gen stuff. But it is not urgent.

**Comment by olydis** [comment]
closing since issue is problem with Swagger and an issue was opened against the Swagger repo

**Comment by Sjhandai** [comment]
I am getting similar error while running following command:

autorest --v3 --version=3.0.6274 --input-file=api.json --csharp --output-folder=APIALL --namespace=PetStore

Error

FATAL: System.InvalidOperationException: Found incompatible property types , for property 'error' in schema Invalid Auth Request
at AutoRest.Modeler.SchemaResolver.ExpandAllOf(Schema schema) in /opt/vsts/work/1/s/src/SchemaResolver.cs:line 142
at AutoRest.Modeler.SchemaResolver.Unwrap(Schema schema) in /opt/vsts/work/1/s/src/SchemaResolver.cs:line 75
at AutoRest.Modeler.SchemaBuilder.BuildServiceType(String serviceTypeName, Boolean required) in /opt/vsts/work/1/s/src/SchemaBuilder.cs:line 35
at AutoRest.Modeler.SwaggerModeler.BuildCompositeTypes() in /opt/vsts/work/1/s/src/SwaggerModeler.cs:line 348
at AutoRest.Modeler.SwaggerModeler.Build(ServiceDefinition serviceDefinition) in /opt/vsts/work/1/s/src/SwaggerModeler.cs:line 66
at AutoRest.Modeler.Program.d__2.MoveNext() in /opt/vsts/work/1/s/src/Program.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at NewPlugin.d__15.MoveNext()
Error: Plugin imodeler1 reported failure.

Any suggestions how to fix this?
