### ISSUE TITLE
Failed to initialize CoreCLR, HRESULT: 0x80131500 running autorest inside a container

### ISSUE THREAD

**Issue by peterj** [Azure/autorest#2613]
I am trying to run ```autorest``` and generate C# code inside a Docker container. The base image I am using is ```microsoft/dotnet:sdk```. 

Here's a minimal dockerfile:

```
FROM microsoft/dotnet:sdk
RUN curl -sL https://deb.nodesource.com/setup_7.x | bash -

RUN apt-get update && \ 
    apt-get nodejs -y

RUN npm install autorest -g && autorest --version=latest
```
dotnet --version:
```
root@moby:/# dotnet --version
2.0.0
```

Autorest --help output from the inside of the container:
```
root@moby:/# autorest --help
AutoRest Code Generator
(c) 2017 Microsoft Corporation. https://aka.ms/autorest
  Build Information
  Autorest Bootstrapper :  1.2.2
  NetCore framework :      1.0.5
  Latest Core Installed :  1.2.2
  Requested Core Version : <none>
```

The issue is when I try to generate the C# code, I get this error (autorest with --debug and --verbose):
```
22:36:57] Network Enabled: true
AutoRest Code Generator
(c) 2017 Microsoft Corporation. https://aka.ms/autorest
[22:36:57] Requested '1.2.2' version
DEBUG: Creating ConfigurationView : 7 sections.
DEBUG: Creating ConfigurationView : 24 sections.
DEBUG: Creating ConfigurationView : 2 sections.
DEBUG: Creating ConfigurationView : 2 sections.
DEBUG: Creating ConfigurationView : 2 sections.
DEBUG: Creating ConfigurationView : 2 sections.
DEBUG: Creating ConfigurationView : 2 sections.
DEBUG: pipeline-emitter - START
DEBUG: swagger-document-override/md-override-loader - START
DEBUG: swagger-document/loader - START
DEBUG: Emitting 'pipeline' at file:///generated_code/pipeline
DEBUG: pipeline-emitter - END
DEBUG: swagger-document-override/md-override-loader - END
DEBUG: swagger-document/loader - END
DEBUG: swagger-document/individual/transform - START
DEBUG: swagger-document/individual/transform - END
DEBUG: swagger-document/compose - START
DEBUG: swagger-document/compose - END
DEBUG: swagger-document/transform-immediate - START
DEBUG: Creating ConfigurationView : 2 sections.
DEBUG: swagger-document/transform-immediate - END
DEBUG: swagger-document/transform - START
DEBUG: swagger-document/transform - END
DEBUG: swagger-document/emitter - START
DEBUG: csharp/modeler - START
DEBUG: Emitting 'swagger-document' at file:///generated_code/Microsoft.Azure.Namespace.blah
DEBUG: swagger-document/emitter - END
Failed to initialize CoreCLR, HRESULT: 0x80131500
FATAL: csharp/modeler - FAILED
FATAL: Error: AutoRest plugin terminated.
Process() Cancelled due to exception : AutoRest plugin terminated.
AutoRest plugin terminated.
{ Error: AutoRest plugin terminated.
    at channel.onClose (/root/.autorest/plugins/autorest/1.2.2/node_modules/autorest-core/lib/pipeline/plugin-endpoint.js:44:88)
    at CallbackList.invoke (/root/.autorest/plugins/autorest/1.2.2/node_modules/autorest-core/node_modules/vscode-jsonrpc/lib/events.js:114:39)
    at Emitter.fire (/root/.autorest/plugins/autorest/1.2.2/node_modules/autorest-core/node_modules/vscode-jsonrpc/lib/events.js:178:36)
    at closeHandler (/root/.autorest/plugins/autorest/1.2.2/node_modules/autorest-core/node_modules/vscode-jsonrpc/lib/main.js:212:26)
    at CallbackList.invoke (/root/.autorest/plugins/autorest/1.2.2/node_modules/autorest-core/node_modules/vscode-jsonrpc/lib/events.js:114:39)
    at Emitter.fire (/root/.autorest/plugins/autorest/1.2.2/node_modules/autorest-core/node_modules/vscode-jsonrpc/lib/events.js:178:36)
    at StreamMessageWriter.AbstractMessageWriter.fireClose (/root/.autorest/plugins/autorest/1.2.2/node_modules/autorest-core/node_modules/vscode-jsonrpc/lib/messageWriter.js:48:27)
    at Socket.<anonymous> (/root/.autorest/plugins/autorest/1.2.2/node_modules/autorest-core/node_modules/vscode-jsonrpc/lib/messageWriter.js:70:63)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:511:12) exitCode: 1 }
```

Running the exact same thing on a MacOS works fine (no errors).

**Comment by fearthecowboy** [comment]
Try `npm install -g autorest@preview`

That uses the 2.0 build that has a lot of fixes. We should be promoting that to stable today.

**Comment by peterj** [comment]
Thanks! I tried the preview version, and using the ```microsoft/dotnet:sdk``` image, I get a different error:
```
usr/lib/node_modules/autorest/dist/app.js:88
const checkBootstrapper = new polyfill_1.LazyPromise(async () => {
                                                           ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (/usr/lib/node_modules/autorest/dist/fs-monkey/patchRequire.js:136:16)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/autorest/dist/static-app.js:6:1)
```

This is the same error I get if I install autorest@preview on a MacOS. 

Luckily, I tried using ```ubuntu:17.04``` and that combination with autorest@preview works fine.

**Comment by fearthecowboy** [comment]
Update your node.js to at least 7.10

**Comment by peterj** [comment]
I have node v7.3.0 installed.

**Comment by fearthecowboy** [comment]
7.3 is less than 7.10

**Comment by peterj** [comment]
Duh, my bad :) I tried with the latest Node (v8.6.0) and that doesn't work either (error below). I'll try installing 7.10 then.

```
module.js:473
      throw err;
      ^

Error: Cannot find module '/node_modules/npm/node_modules/worker-farm/lib/child/index.js'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:453:25)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:607:3
module.js:473
      throw err;
      ^

Error: Cannot find module '/node_modules/npm/node_modules/worker-farm/lib/child/index.js'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:453:25)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:607:3
Failure:
{ Error: Package '@microsoft.azure/autorest-core' - '2.0.4143' failed to install:
  cancel after 1 retries!
    at npm_1.commands.install (/node_modules/@microsoft.azure/extension/dist/main.js:228: 32)
    at cb (/node_modules/npm/lib/install.js:232: 16)
    at /node_modules/npm/lib/install.js:319: 7
    at LOOP (/node_modules/npm/node_modules/slide/lib/chain.js:7: 26)
    at /node_modules/npm/node_modules/slide/lib/chain.js:18: 7
    at Installer.printInstalled (/node_modules/npm/lib/install.js:722: 28)
    at Array.<anonymous> (/node_modules/npm/node_modules/slide/lib/bind-actor.js:15: 8)
    at LOOP (/node_modules/npm/node_modules/slide/lib/chain.js:15: 14)
    at /node_modules/npm/node_modules/slide/lib/chain.js:18: 7
    at Installer.printWarnings (/node_modules/npm/lib/install.js:717: 3)
    at Array.<anonymous> (/node_modules/npm/node_modules/slide/lib/bind-actor.js:15: 8)
    at LOOP (/node_modules/npm/node_modules/slide/lib/chain.js:15: 14)
    at /node_modules/npm/node_modules/slide/lib/chain.js:18: 7
    at Installer.saveToDependencies (/node_modules/npm/lib/install.js:610: 28)
    at Array.<anonymous> (/node_modules/npm/node_modules/slide/lib/bind-actor.js:15: 8)
    at LOOP (/node_modules/npm/node_modules/slide/lib/chain.js:15: 14) exitCode: 1 }
Error: Package '@microsoft.azure/autorest-core' - '2.0.4143' failed to install:
  cancel after 1 retries!
    at npm_1.commands.install (/node_modules/@microsoft.azure/extension/dist/main.js:228: 32)
    at cb (/node_modules/npm/lib/install.js:232: 16)
    at /node_modules/npm/lib/install.js:319: 7
    at LOOP (/node_modules/npm/node_modules/slide/lib/chain.js:7: 26)
    at /node_modules/npm/node_modules/slide/lib/chain.js:18: 7
    at Installer.printInstalled (/node_modules/npm/lib/install.js:722: 28)
    at Array.<anonymous> (/node_modules/npm/node_modules/slide/lib/bind-actor.js:15: 8)
    at LOOP (/node_modules/npm/node_modules/slide/lib/chain.js:15: 14)
    at /node_modules/npm/node_modules/slide/lib/chain.js:18: 7
    at Installer.printWarnings (/node_modules/npm/lib/install.js:717: 3)
    at Array.<anonymous> (/node_modules/npm/node_modules/slide/lib/bind-actor.js:15: 8)
    at LOOP (/node_modules/npm/node_modules/slide/lib/chain.js:15: 14)
    at /node_modules/npm/node_modules/slide/lib/chain.js:18: 7
    at Installer.saveToDependencies (/node_modules/npm/lib/install.js:610: 28)
    at Array.<anonymous> (/node_modules/npm/node_modules/slide/lib/bind-actor.js:15: 8)
    at LOOP (/node_modules/npm/node_modules/slide/lib/chain.js:15: 14)
```

**Comment by fearthecowboy** [comment]
Oh, now what did the purveyors of node do? It worked on the last 8.x build...

I'll see what's going on with 8.x..

**Comment by olydis** [comment]
@fearthecowboy that's the error @amarzavery got on MacOS (@peterj I assume this last run was on MacOS?), I'll try to repro on my machine

**Comment by peterj** [comment]
Yep, the error above is from a MacOS. I also installed 7.10.0 and I get the same error.

**Comment by fearthecowboy** [comment]
FYI, I'm adding a pre-install check to notify about the node version at install time. 

And, we're going to try and repro the macos bug.

**Comment by fearthecowboy** [comment]
@peterj 

We've tracked it down and republished to fix the macos bug.

use `npm install -g autorest` to get the latest.

**Comment by peterj** [comment]
Awesome! Reinstalled on MacOS and didn't get any errors.
