### ISSUE TITLE
AutoRest fails when run in Azure

### ISSUE THREAD

**Issue by JoshuaWhatley** [Azure/autorest#2636]
I am receiving an 'unsupported platform exception' when trying to run autorest in an azure webjob. The following code is raising the exception (_note that I added the architecture output to help debug_). It would appear that the architecture for azure webjobs is **ia32**

Would support be as trivial as adding a mapping for ia32 in that switch statement?

```
function detectArchitecture() {
    switch (os_1.platform()) {
        case 'darwin': return 'osx';
        case 'linux': return `linux`;
        case 'win32':
            switch (os_1.arch()) {
                case 'x64': return 'win';
                case 'x86': return 'win-x86';
            }
            break;
    }
    throw new Error(`Unsupported Platform: ${os_1.platform()} - ${os_1.arch()}`);
}
```

**Exception details**:

exit code: 1
Error Output: D:\local\UserProfile\.autorest\@microsoft.azure_autorest.csharp@2.0.21\node_modules\@microsoft.azure\autorest.csharp\node_modules\dotnet-2.0.0\dist\common.js:29
    throw new Error(`Unsupported Platform: ${os_1.platform()} &amp; ${os_1.arch()}`);
    ^
Error: Unsupported Platform: win32 - **ia32**
    at detectArchitecture (D:\local\UserProfile\.autorest\@microsoft.azure_autorest.csharp@2.0.21\node_modules\@microsoft.azure\autorest.csharp\node_modules\dotnet-2.0.0\dist\common.js:29:11)
    at Object.&lt;anonymous&gt; (D:\local\UserProfile\.autorest\@microsoft.azure_autorest.csharp@2.0.21\node_modules\@microsoft.azure\autorest.csharp\node_modules\dotnet-2.0.0\dist\common.js:8:56)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.&lt;anonymous&gt; (D:\local\UserProfile\.autorest\@microsoft.azure_autorest.csharp@2.0.21\node_modules\@microsoft.azure\autorest.csharp\node_modules\dotnet-2.0.0\dist\call.js:4:18)

**Comment by fearthecowboy** [comment]
Ah... that's .... interesting.

Yeah, I can fix that. 

G

**Comment by olydis** [comment]
@fearthecowboy I assume this is fixed, will close
