### ISSUE TITLE
Java ClientRuntime model flattening broken?

### ISSUE THREAD

**Issue by olydis** [Azure/autorest#2653]
I think your client runtime is broken with regards to flattening. Raw error:

```
Tests run: 9, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.235 sec <<< FAILURE! - in fixtures.modelflattening.ModelFlatteningTests
putArray(fixtures.modelflattening.ModelFlatteningTests)  Time elapsed: 0.019 sec  <<< ERROR!
fixtures.modelflattening.models.ErrorException: Status code 400, {"message":"The received body '[{\"properties\":{},\"tags\":{\"tag1\":\"value1\",\"tag2\":\"value3\"},\"location\":\"West US\"},{\"properties\":{},\"location\":\"Building 44\"}]' did not match the expected body '\"[{\\\"location\\\":\\\"West US\\\",\\\"tags\\\":{\\\"tag1\\\":\\\"value1\\\",\\\"tag2\\\":\\\"value3\\\"}},{\\\"location\\\":\\\"Building 44\\\"}]\"'.","status":400}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.microsoft.rest.ServiceResponseBuilder.build(ServiceResponseBuilder.java:122)
	at fixtures.modelflattening.implementation.AutoRestResourceFlatteningTestServiceImpl.putArrayDelegate(AutoRestResourceFlatteningTestServiceImpl.java:289)
	at fixtures.modelflattening.implementation.AutoRestResourceFlatteningTestServiceImpl.access$000(AutoRestResourceFlatteningTestServiceImpl.java:48)
	at fixtures.modelflattening.implementation.AutoRestResourceFlatteningTestServiceImpl$4.call(AutoRestResourceFlatteningTestServiceImpl.java:276)
	at fixtures.modelflattening.implementation.AutoRestResourceFlatteningTestServiceImpl$4.call(AutoRestResourceFlatteningTestServiceImpl.java:272)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$RequestArbiter.request(RxJavaCallAdapterFactory.java:173)
	at rx.Subscriber.setProducer(Subscriber.java:211)
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102)
	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:152)
	at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:138)
	at rx.Observable.unsafeSubscribe(Observable.java:10142)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.subscribe(Observable.java:10238)
	at rx.Observable.subscribe(Observable.java:10205)
	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:444)
	at rx.observables.BlockingObservable.single(BlockingObservable.java:341)
	at fixtures.modelflattening.implementation.AutoRestResourceFlatteningTestServiceImpl.putArray(AutoRestResourceFlatteningTestServiceImpl.java:231)
	at fixtures.modelflattening.ModelFlatteningTests.putArray(ModelFlatteningTests.java:63)
```

Essence:
**expected**
```
[ { location: 'West US',
    tags: { tag1: 'value1', tag2: 'value3' } },
  { location: 'Building 44' } 
]
```

**actual**
```
[ { properties: {},
    tags: { tag1: 'value1', tag2: 'value3' },
    location: 'West US' },
  { properties: {}, 
    location: 'Building 44' } 
]
```

So somehow there's a `properties` property on the wire...

See https://github.com/Azure/autorest.java/pull/19 for CI logs.

**Comment by RikkiGibson** [comment]
Is this PR related? https://github.com/Azure/autorest-clientruntime-for-java/pull/259 @jianghaolu

**Comment by jianghaolu** [comment]
Yes
