### ISSUE TITLE
FATAL: System.NotSupportedException: long does not have default value!

### ISSUE THREAD

**Issue by olydis** [Azure/autorest#2675]
The following happens when you get a `query` parameter of type `int64` that is marked as `x-nullable: false`
```
FATAL: System.NotSupportedException: long does not have default value!
   at AutoRest.Java.Model.PrimaryTypeJv.get_DefaultValue() in C:\Users\ci\AppData\Local\Temp\PUBLISHswsf6\16_20170923T001947\autorest.java\src\vanilla\Model\PrimaryTypeJv.cs:line 68
   at AutoRest.Java.Model.IModelTypeExtensions.GetDefaultValue(IModelType type, Method parent) in C:\Users\ci\AppData\Local\Temp\PUBLISHswsf6\16_20170923T001947\autorest.java\src\vanilla\Model\IModelTypeJv.cs:line 29
   at AutoRest.Java.vanilla.Templates.MethodTemplate.<ExecuteAsync>d1.MoveNext() in C:\Users\ci\AppData\Local\Temp\PUBLISHswsf6\16_20170923T001947\autorest.java\src\obj\Razor\vanilla\Templates\MethodTemplate.cshtml:line 137
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AutoRest.Core.Template`1.ToString()
   at AutoRest.Java.vanilla.Templates.MethodGroupTemplate.<ExecuteAsync>d1.MoveNext() in C:\Users\ci\AppData\Local\Temp\PUBLISHswsf6\16_20170923T001947\autorest.java\src\obj\Razor\vanilla\Templates\MethodGroupTemplate.cshtml:line 48
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AutoRest.Core.CodeGenerator.<Write>d12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AutoRest.Java.CodeGeneratorJv.<Generate>d10.MoveNext() in C:\Users\ci\AppData\Local\Temp\PUBLISHswsf6\16_20170923T001947\autorest.java\src\vanilla\CodeGeneratorJv.cs:line 56 --- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AutoRest.Java.Program.<ProcessInternal>d3.MoveNext() in C:\Users\ci\AppData\Local\Temp\PUBLISHswsf6\16_20170923T001947\autorest.java\src\Program.cs:line 115
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NewPlugin.<Process>d15.MoveNext()
```

Not sure about Java, but wouldn't the default value just be 0? 😉 

For an example, take https://github.com/Picturepark/Picturepark.SDK.Playground/blob/master/swagger/PictureparkSwaggerAutoRest.json and modify, say `chunkNumber`, to be `x-nullable: false`

This issue is a fork of https://github.com/Azure/autorest/issues/2652

**Comment by RikkiGibson** [comment]
I can't repro this in the "v1" generator currently used for azure-libraries-for-java but I do get a different and exciting new error which I'll track at Azure/autorest.java#272
