### ISSUE TITLE
autorest failed finally and reported error "at AutoRest.Modeler.SwaggerParser.Parse(String swaggerDocument) in"

### ISSUE THREAD

**Issue by smartmaster** [Azure/autorest#2756]
autorest failed finally and reported error

   at AutoRest.Modeler.SwaggerParser.Parse(String swaggerDocument) in C:\Users\ci\AppData\Local\Temp\PUBLISH8kiit\38_20171116T010915\autorest.modeler\src\SwaggerParser.cs:line 52
   at AutoRest.Modeler.Program.<ProcessInternal>d__2.MoveNext() in C:\Users\ci\AppData\Local\Temp\PUBLISH8kiit\38_20171116T010915\autorest.modeler\src\Program.cs:line 58
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NewPlugin.<Process>d__15.MoveNext()
FATAL: java/imodeler1 - FAILED
FATAL: Error: Plugin imodeler1 reported failure.
  Error: Plugin imodeler1 reported failure.

the sample json file and logs are attached
[autorest-error.txt](https://github.com/Azure/autorest/files/1529655/autorest-error.txt)
[autorest-output.txt](https://github.com/Azure/autorest/files/1529656/autorest-output.txt)

[ntx.json.txt](https://github.com/Azure/autorest/files/1529658/ntx.json.txt)

**Comment by fearthecowboy** [comment]
Hey @smartmaster -- Swagger doesn't technically support `"additionalProperties": true` or `"additionalProperties": false` -- and AutoRest is blowing up on those. (see https://github.com/OAI/OpenAPI-Specification/issues/668 )

I removed those, and it seems a lot happier.

That being said OAI 3 does support that, and I think we either have something in progress to add it, or will very soon.

**Comment by MiYanni** [comment]
AutoRest 3 supports this. Closing.

**Comment by joaopi** [comment]
Hi @MiYanni , 

I just installed autorest@beta in order to use with an OpenApi V3 spec, and it's still generating an exception with the same issue with additionalProperties :

`autorest autorest.yml
AutoRest code generation utility [version: 3.0.5231; node: v10.16.3, max-memory: 8192 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      'C:\Users\jep\.autorest\@microsoft.azure_autorest-core@3.0.5537\node_modules\@microsoft.azure\autorest-core\dist' (3.0.5537)
   Installing AutoRest extension '@microsoft.azure/autorest.csharp' (~2.3.79)
   Installed AutoRest extension '@microsoft.azure/autorest.csharp' (~2.3.79->2.3.82)
   Installing AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.55)
   Installed AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.55->2.3.55)
FATAL: Error parsing swagger file. Error converting value False to type 'AutoRest.Modeler.Model.Schema'. Path 'components.schemas.UserCreateParameters.additionalProperties', line 1, position 104395.
FATAL: AutoRest.Core.Logging.CodeGenerationException: Error parsing swagger file. Error converting value False to type 'AutoRest.Modeler.Model.Schema'. Path 'components.schemas.UserCreateParameters.additionalProperties', line 1, position 104395.
   at AutoRest.Modeler.SwaggerParser.Parse(String swaggerDocument) in /opt/vsts/work/1/s/src/SwaggerParser.cs:line 52
   at AutoRest.Modeler.Program.<ProcessInternal>d__2.MoveNext() in /opt/vsts/work/1/s/src/Program.cs:line 58
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NewPlugin.<Process>d__15.MoveNext()
C:\Users\jep\.autorest\@microsoft.azure_autorest-core@3.0.5537\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\pipeline.js - FAILURE {}
Process() cancelled due to exception : Plugin imodeler1 reported failure. / Error: Plugin imodeler1 reported failure.
    at C:\Users\jep\.autorest\@microsoft.azure_autorest-core@3.0.5537\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\plugins\external.js:26:19
  Error: Plugin imodeler1 reported failure.
`

**Comment by MiYanni** [comment]
@joaopi Have you tried using the value `false` instead of `False`?

**Comment by fearthecowboy** [comment]
It's the V2 modeler that doesn't like it. 

I have a configuration hack that can fix that. I just gotta find it.

... found it.

ok, if you're just calling autorest on the command line:

>` autorest --input-file:swagger.json <yada yada yada> ` 

create a file called config.yaml:

``` yaml
directive:
- from: swagger-document
  where: $..*[?(@.additionalProperties == false)]
  transform: $.additionalProperties = undefined;
```
and run 
>` autorest --input-file:swagger.json <yada yada yada> config.yaml`

**Comment by joaopi** [comment]
@MiYanni the value for additionalProperties in the spec is  false (lowercase).

**Comment by joaopi** [comment]
@fearthecowboy you say it's using V2 modeller? But I installed autorest@beta in order to handle OpenApi V3, and my spec document is in V3.
Is there a way to change the modeller to a V3 version?

**Comment by MiYanni** [comment]
@joaopi The modeler is a plugin for the AutoRest pipeline. Looking at your original information, it looks like you were trying to generate Java(?) code. So, the Java pipeline would be using that modeler plugin. It doesn't have to do with the version of AutoRest directly. Updated pipelines for AutoRest v3 wouldn't be released until sometime after AutoRest v3 is release.

Please try the workaround @fearthecowboy provided and see if that does the job.

**Comment by HawkPK** [comment]
I have the same problem with generating code for C#. The solution provided by @fearthecowboy works in my case.

**Comment by thedwillis** [comment]
> 
> 
> It's the V2 modeler that doesn't like it.
> 
> I have a configuration hack that can fix that. I just gotta find it.
> 
> ... found it.
> 
> ok, if you're just calling autorest on the command line:
> 
> > `autorest --input-file:swagger.json <yada yada yada>`
> 
> create a file called config.yaml:
> 
> ```yaml
> directive:
> - from: swagger-document
>   where: $..*[?(@.additionalProperties == false)]
>   transform: $.additionalProperties = undefined;
> ```
> 
> and run
> 
> > ` autorest --input-file:swagger.json <yada yada yada> config.yaml`

Sadly this fix no longer works, the latest autorest beta now returns 'FATAL: System.ArgumentNullException: Value cannot be null.' when using this directive.

**Comment by fearthecowboy** [comment]
@thedwillis You're going to have be more clear about what's going wrong. 

- command line
- version
- input files
?

**Comment by thedwillis** [comment]
Sorry should have provided more detail, I'm using the following config file:

```
## AutoRest configuration ...
``` yaml
input-file:
  - http://localhost:5003/swagger/v1/swagger.json
add-credentials: true
override-client-name: Client
csharp:
  namespace: Api.Client #override the namespace
  output-folder : . # relative to the global value
directive:
- from: swagger-document
  where: $..*[?(@.additionalProperties == false)]
  transform: $.additionalProperties = undefined;
```

I am using version: 3.0.5231, and my swagger is generated by Swashbuckle 5.0.0 and is as follows:

```
{
  "openapi": "3.0.1",
  "info": {
    "title": "API",
    "description": "API for exposing document endpoints.",
    "termsOfService": "http://tempuri.org/terms",
    "contact": {
      "name": "Bleh",
      "email": "bleh@bleh.net"
    },
    "version": "1.0.0"
  },
  "paths": {
    "/api/v1/{authId}/documents": {
      "get": {
        "tags": [
          "Documents"
        ],
        "summary": "Retrieves user's uploaded documents meta-data.",
        "operationId": "Documents_GetAll",
        "parameters": [
          {
            "name": "authId",
            "in": "path",
            "description": "User's unique auth identifier.",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/DocumentMetaData"
                  }
                }
              },
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/DocumentMetaData"
                  }
                }
              },
              "text/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/DocumentMetaData"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          }
        },
        "security": [
          {
            "OAuth2": [
              ""
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Documents"
        ],
        "summary": "Uploads a new document to user's storage.",
        "operationId": "Documents_Upload",
        "parameters": [
          {
            "name": "authId",
            "in": "path",
            "description": "User's unique auth identifier.",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "description": "Document meta data.",
          "content": {
            "multipart/form-data": {
              "schema": {
                "$ref": "#/components/schemas/DocumentMetaDataCreate"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Success",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "string"
                }
              },
              "application/json": {
                "schema": {
                  "type": "string"
                }
              },
              "text/json": {
                "schema": {
                  "type": "string"
                }
              }
            }
          },
          "415": {
            "description": "Client Error",
            "content": {
              "text/plain": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                }
              },
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                }
              },
              "text/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          }
        },
        "security": [
          {
            "OAuth2": [
              ""
            ]
          }
        ]
      }
    },
    "/api/v1/{authId}/documents/{fileName}": {
      "get": {
        "tags": [
          "Documents"
        ],
        "summary": "Retrieves a URI to the document.",
        "operationId": "Documents_GetUri",
        "parameters": [
          {
            "name": "authId",
            "in": "path",
            "description": "User's unique auth identifier.",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "fileName",
            "in": "path",
            "description": "Name of the file to retrieve.",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "string",
                  "format": "uri"
                }
              },
              "application/json": {
                "schema": {
                  "type": "string",
                  "format": "uri"
                }
              },
              "text/json": {
                "schema": {
                  "type": "string",
                  "format": "uri"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "text/plain": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                }
              },
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                }
              },
              "text/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          }
        },
        "security": [
          {
            "OAuth2": [
              ""
            ]
          }
        ]
      }
    },
    "/api/v1/{authId}/documents/{id}": {
      "put": {
        "tags": [
          "Documents"
        ],
        "summary": "Updates an existing document's meta-data.",
        "operationId": "Documents_Update",
        "parameters": [
          {
            "name": "authId",
            "in": "path",
            "description": "User's unique auth identifier.",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "id",
            "in": "path",
            "description": "Unique document identifier.",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "description": "Update data for the document's meta-data.",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/DocumentMetaDataUpdate"
              }
            },
            "text/json": {
              "schema": {
                "$ref": "#/components/schemas/DocumentMetaDataUpdate"
              }
            },
            "application/*+json": {
              "schema": {
                "$ref": "#/components/schemas/DocumentMetaDataUpdate"
              }
            }
          }
        },
        "responses": {
          "204": {
            "description": "Success"
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "text/plain": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                }
              },
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                }
              },
              "text/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "text/plain": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                }
              },
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                }
              },
              "text/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          }
        },
        "security": [
          {
            "OAuth2": [
              ""
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Documents"
        ],
        "summary": "Deletes a document and associated meta-data.",
        "operationId": "Documents_Delete",
        "parameters": [
          {
            "name": "authId",
            "in": "path",
            "description": "User's unique auth identifier.",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "id",
            "in": "path",
            "description": "Unique document identifier.",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "Success"
          },
          "404": {
            "description": "Not Found",
            "content": {
              "text/plain": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                }
              },
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                }
              },
              "text/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          }
        },
        "security": [
          {
            "OAuth2": [
              ""
            ]
          }
        ]
      }
    }
  },
  "components": {
    "schemas": {
      "DocumentMetaData": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "description": "Document meta data unique identifier.",
            "nullable": true
          },
          "documentType": {
            "type": "string",
            "description": "Type of document.",
            "nullable": true
          },
          "identifier": {
            "type": "string",
            "description": "Document identifier (not unique).",
            "nullable": true
          },
          "startDate": {
            "type": "string",
            "description": "Date the document started.",
            "format": "date-time"
          },
          "endDate": {
            "type": "string",
            "description": "Date the document ended.",
            "format": "date-time"
          },
          "placeOfIssue": {
            "type": "string",
            "description": "Place the document was issued.",
            "nullable": true
          },
          "notes": {
            "type": "string",
            "description": "Notes/description of the document.",
            "nullable": true
          },
          "filePath": {
            "type": "string",
            "description": "Path of where the document is stored.",
            "nullable": true
          },
          "uploaded": {
            "type": "string",
            "description": "Date and time when the document was uploaded.",
            "format": "date-time"
          },
          "modified": {
            "type": "string",
            "description": "Date and time the meta data was last modified.",
            "format": "date-time",
            "nullable": true
          }
        },
        "additionalProperties": false,
        "description": "Document meta data model."
      },
      "DocumentMetaDataCreate": {
        "type": "object",
        "properties": {
          "documentType": {
            "type": "string",
            "description": "Type of document.",
            "nullable": true
          },
          "identifier": {
            "type": "string",
            "description": "Document identifier (not unique).",
            "nullable": true
          },
          "startDate": {
            "type": "string",
            "description": "Date the document started.",
            "format": "date-time"
          },
          "endDate": {
            "type": "string",
            "description": "Date the document ended.",
            "format": "date-time"
          },
          "placeOfIssue": {
            "type": "string",
            "description": "Place the document was issued.",
            "nullable": true
          },
          "notes": {
            "type": "string",
            "description": "Notes/description of the document.",
            "nullable": true
          }
        },
        "additionalProperties": false,
        "description": "Document meta data create model."
      },
      "ProblemDetails": {
        "type": "object",
        "properties": {
          "type": {
            "type": "string",
            "nullable": true
          },
          "title": {
            "type": "string",
            "nullable": true
          },
          "status": {
            "type": "integer",
            "format": "int32",
            "nullable": true
          },
          "detail": {
            "type": "string",
            "nullable": true
          },
          "instance": {
            "type": "string",
            "nullable": true
          },
          "extensions": {
            "type": "object",
            "additionalProperties": {
              "type": "object",
              "additionalProperties": false
            },
            "nullable": true,
            "readOnly": true
          }
        },
        "additionalProperties": false
      },
      "DocumentMetaDataUpdate": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "description": "Document meta data unique identifier.",
            "nullable": true
          },
          "documentType": {
            "type": "string",
            "description": "Type of document.",
            "nullable": true
          },
          "identifier": {
            "type": "string",
            "description": "Document identifier (not unique).",
            "nullable": true
          },
          "startDate": {
            "type": "string",
            "description": "Date the document started.",
            "format": "date-time"
          },
          "endDate": {
            "type": "string",
            "description": "Date the document ended.",
            "format": "date-time"
          },
          "placeOfIssue": {
            "type": "string",
            "description": "Place the document was issued.",
            "nullable": true
          },
          "notes": {
            "type": "string",
            "description": "Notes/description of the document.",
            "nullable": true
          }
        },
        "additionalProperties": false,
        "description": "Document meta-data update model."
      }
    },
    "securitySchemes": {
      "OAuth2": {
        "type": "oauth2",
        "description": "Login with your bearer authentication token, e.g. Bearer <auth-token>",
        "flows": {
          "clientCredentials": {
            "tokenUrl": "http://localhost:5555/connect/token",
            "scopes": {
              "documents": ""
            }
          }
        }
      }
    }
  }
}
```

Without the directive I get:

![alt text](https://i.imgur.com/4sp5jBT.png "Without directive")

With the directive:

![alt text](https://i.imgur.com/bjJ5dgL.png "With directive")

**Comment by fearthecowboy** [comment]
It doesn't look like it has anything to do with the `additionalProperties` workaround.

It's dying trying to build a request body.

it probably doesn't like the multiple request types. that's unnecessary.

**Comment by thedwillis** [comment]
The swagger is auto generated by Swashbuckle 5.0.0 so I'm not sure how much control I have over it...

**Comment by Mezzenine** [comment]
I'm currently working with autorest and for me, it seems this bug still exists. In my opinion, the parser didn't consider the "additionalProperties" value can be a boolean or object. See the spec of a schema object. https://swagger.io/specification/

![image](https://user-images.githubusercontent.com/28353171/81395046-3e1a1100-9123-11ea-949f-6d8ef0276500.png)

If I change the value from true or false, to an object this error disappear.

I'm using the versions of autorest:
![image](https://user-images.githubusercontent.com/28353171/81395277-9f41e480-9123-11ea-90f0-9a346c4851a6.png)

**Comment by fearthecowboy** [comment]
Yes, OpenAPI3 changed the definition from before when it was `true` or an object. 

Unfortunately the old modeler only knew of OpenAPI2 standards. The new v3 generators won't have that problem, but I don't have the time to go back and fix the old one.

**Comment by Mezzenine** [comment]
> Yes, OpenAPI3 changed the definition from before when it was `true` or an object.
> 
> Unfortunately the old modeler only knew of OpenAPI2 standards. The new v3 generators won't have that problem, but I don't have the time to go back and fix the old one.

I assume that I used the V3 generator. 
This is the executed command line: 
`autorest --input-file=$outFile --v3 --csharp --verbose --namespace="OpenApiEval.$specType.autorest" --override-client-name="$specType" --sync-methods=all --output-folder="$outputRoot\autorest\$specType"`

I explicitly specified the --v3 parameter.

**Comment by MiYanni** [comment]
@Mezzenine The v3 generator for csharp is not released yet. So, you'd be using the v2 csharp generator which does not use the new modeler. Thus, you will still have the issue.
