### ISSUE TITLE
Ruby: FATAL: System.NotSupportedException: Collection format Multi is not supported.

### ISSUE THREAD

**Issue by epet** [Azure/autorest#2806]
We are getting autorest exceptions when processing json with '"collectionFormat": "multi"' (see below
                "parameters": [
                    {
                        "name": "customer_id",
                        "in": "path",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "name": "user_id",
                        "in": "path",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "name": "licenseGroupIds",
                        "in": "query",
                        "description": "license group ids (ex: \"Group1\" which means AAD products, \"Group2\" which means MDollar products).",
                        "required": false,
                        "type": "array",
                        "items": {
                            "type": "string",
                            "enum": [
                                "none",
                                "group1",
                                "group2",
                                "group3"
                            ]
                        },
                        "collectionFormat": "multi"
                    },

Exception being thrown:
FATAL: System.NotSupportedException: Collection format Multi is not supported.
   at AutoRest.Ruby.ClientModelExtensions.GetSeparator(CollectionFormat format) in C:\Users\ci\AppData\Local\Temp\PUBLISHh75ma\20_20171128T221448\autorest.ruby\src\vanilla\ClientModelExtensions.cs:line 178
   at AutoRest.Ruby.ClientModelExtensions.GetFormattedReferenceValue(Parameter parameter) in C:\Users\ci\AppData\Local\Temp\PUBLISHh75ma\20_20171128T221448\autorest.ruby\src\vanilla\ClientModelExtensions.cs:line 195
   at AutoRest.Ruby.Model.MethodRb.ParamsToRubyDict(IEnumerable`1 parameters) in C:\Users\ci\AppData\Local\Temp\PUBLISHh75ma\20_20171128T221448\autorest.ruby\src\vanilla\Model\MethodRb.cs:line 552
   at AutoRest.Ruby.Model.MethodRb.get_QueryParamsRbDict() in C:\Users\ci\AppData\Local\Temp\PUBLISHh75ma\20_20171128T221448\autorest.ruby\src\vanilla\Model\MethodRb.cs:line 94
   at AutoRest.Ruby.vanilla.Templates.MethodTemplate.&lt;ExecuteAsync&gt;d__1.MoveNext() in C:\Users\ci\AppData\Local\Temp\PUBLISHh75ma\20_20171128T221448\autorest.ruby\src\obj\Razor\vanilla\Templates\MethodTemplate.cshtml:line 138
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AutoRest.Core.Template`1.ToString()
   at AutoRest.Core.Template`1.Include[TU,TV](TU template, TV templateModel)
   at AutoRest.Ruby.vanilla.Templates.MethodGroupTemplate.&lt;ExecuteAsync&gt;d__1.MoveNext() in C:\Users\ci\AppData\Local\Temp\PUBLISHh75ma\20_20171128T221448\autorest.ruby\src\obj\Razor\vanilla\Templates\MethodGroupTemplate.cshtml:line 33
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AutoRest.Core.CodeGenerator.&lt;Write&gt;d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at AutoRest.Ruby.CodeGeneratorRb.&lt;Generate&gt;d__10.MoveNext() in C:\Users\ci\AppData\Local\Temp\PUBLISHh75ma\20_20171128T221448\autorest.ruby\src\vanilla\CodeGeneratorRb.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at AutoRest.Ruby.Program.&lt;ProcessInternal&gt;d__3.MoveNext() in C:\Users\ci\AppData\Local\Temp\PUBLISHh75ma\20_20171128T221448\autorest.ruby\src\Program.cs:line 112
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NewPlugin.&lt;Process&gt;d__15.MoveNext()
FATAL: ruby/generate - FAILED
FATAL: Error: Plugin ruby reported failure.
(node:15700) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 15): Error: Plugin ruby reported failure.
(node:15700) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:15700) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 16): Error: Plugin ruby reported failure.
(node:15700) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 17): Error: Plugin ruby reported failure.
FATAL: System.NotSupportedException: Collection format Multi is not supported.
   at AutoRest.Go.Extensions.GetSeparator(CollectionFormat format) in C:\Users\autorest-ci\AppData\Local\Temp\2\PUBLISHj0rdu\75_20180106T163239\autorest.go\src\Extensions.cs:line 252
   at AutoRest.Go.Model.ParameterGo.ValueForMap() in C:\Users\autorest-ci\AppData\Local\Temp\2\PUBLISHj0rdu\75_20180106T163239\autorest.go\src\Model\ParameterGo.cs:line 104
   at AutoRest.Go.Model.ParameterGo.AddToMap(String mapVariable) in C:\Users\autorest-ci\AppData\Local\Temp\2\PUBLISHj0rdu\75_20180106T163239\autorest.go\src\Model\ParameterGo.cs:line 41
   at AutoRest.Go.Templates.MethodTemplate.&lt;ExecuteAsync&gt;d__1.MoveNext() in C:\Users\autorest-ci\AppData\Local\Temp\2\PUBLISHj0rdu\75_20180106T163239\autorest.go\src\obj\Razor\Templates\MethodTemplate.cshtml:line 118
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AutoRest.Core.Template`1.ToString()
   at AutoRest.Core.Template`1.Include[TU,TV](TU template, TV templateModel)
   at AutoRest.Go.Templates.MethodGroupTemplate.&lt;ExecuteAsync&gt;d__1.MoveNext() in C:\Users\autorest-ci\AppData\Local\Temp\2\PUBLISHj0rdu\75_20180106T163239\autorest.go\src\obj\Razor\Templates\MethodGroupTemplate.cshtml:line 66
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AutoRest.Core.CodeGenerator.&lt;Write&gt;d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at AutoRest.Go.CodeGeneratorGo.&lt;Generate&gt;d__6.MoveNext() in C:\Users\autorest-ci\AppData\Local\Temp\2\PUBLISHj0rdu\75_20180106T163239\autorest.go\src\CodeGeneratorGo.cs:line 86
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at AutoRest.Go.Program.&lt;ProcessInternal&gt;d__3.MoveNext() in C:\Users\autorest-ci\AppData\Local\Temp\2\PUBLISHj0rdu\75_20180106T163239\autorest.go\src\Program.cs:line 107
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NewPlugin.&lt;Process&gt;d__15.MoveNext()
FATAL: go/generate - FAILED
FATAL: Error: Plugin go reported failure.
(node:15700) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 18): Error: Plugin go reported failure.
(node:15700) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 19): Error: Plugin go reported failure.
(node:15700) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 20): Error: Plugin go reported failure.
  Error: Plugin ruby reported failure.

Standard Output: AutoRest code generation utility [version: 2.0.4238; node: v7.10.1]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      'D:\local\UserProfile\.autorest\@microsoft.azure_autorest-core@2.0.4238\node_modules\@microsoft.azure\autorest-core\dist' (2.0.4238)
No configuration found at 'file:///D:/local/Temp/jobs/continuous/ClientCodeGeneration/cwbogjpg.yxo/'.
   Loading AutoRest extension '@microsoft.azure/autorest.csharp' (~2.2.51)
   Loading AutoRest extension '@microsoft.azure/autorest.go' (~2.1.47)
   Loading AutoRest extension '@microsoft.azure/autorest.java' (~2.1.32)
   Loading AutoRest extension '@microsoft.azure/autorest.nodejs' (~2.1.25)
   Loading AutoRest extension '@microsoft.azure/autorest.python' (~2.1.26)
   Loading AutoRest extension '@microsoft.azure/autorest.ruby' (~3.1.26)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.1.22)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.38)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.44)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.43)
Process() Cancelled due to exception : Plugin ruby reported failure.

Parameters: --input-file="D:\local\Temp\jobs\continuous\ClientCodeGeneration\cwbogjpg.yxo\6957bfdc-cfcd-4104-8fd1-df8753d31ee9\partnercenterfdswagger.json" --namespace="Microsoft.Swagger.Codegen.PartnerCenterFD" --csharp --csharp.output-folder="D:\local\Temp\jobs\continuous\ClientCodeGeneration\cwbogjpg.yxo\6957bfdc-cfcd-4104-8fd1-df8753d31ee9\csharpcodegen\csharp" --java --java.output-folder="D:\local\Temp\jobs\continuous\ClientCodeGeneration\cwbogjpg.yxo\6957bfdc-cfcd-4104-8fd1-df8753d31ee9\javacodegen\java" --nodejs --nodejs.output-folder="D:\local\Temp\jobs\continuous\ClientCodeGeneration\cwbogjpg.yxo\6957bfdc-cfcd-4104-8fd1-df8753d31ee9\nodejscodegen\nodejs" --python --python.output-folder="D:\local\Temp\jobs\continuous\ClientCodeGeneration\cwbogjpg.yxo\6957bfdc-cfcd-4104-8fd1-df8753d31ee9\pythoncodegen\python" --go --go.output-folder="D:\local\Temp\jobs\continuous\ClientCodeGeneration\cwbogjpg.yxo\6957bfdc-cfcd-4104-8fd1-df8753d31ee9\gocodegen\go" --ruby --ruby.output-folder="D:\local\Temp\jobs\continuous\ClientCodeGeneration\cwbogjpg.yxo\6957bfdc-cfcd-4104-8fd1-df8753d31ee9\rubycodegen\ruby"

**Comment by wendyleach** [comment]
@fearthecowboy has this issue been addressed? I tried the latest beta but no luck.
