### ISSUE TITLE
AutoRest doesn't support HTTP status codes outside HttpStatusCode such as 424 Failed Dependency across the board

### ISSUE THREAD

**Issue by abatishchev** [Azure/autorest#2821]
I'm using Microsoft //Swagger and it generates an AutoRest-based client from my XML docs.

If I'm using the following declaration:

    /// <response code="424">Specified program was not found</response>

Then getting the following exception:

```
<Logs>
  <Log>
    <Path>UPP Calc Rules</Path>
    <Message>Client code generation failed
 exit code: 1
Error Output: FATAL: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at AutoRest.Go.Model.MethodGo.get_ResponseCodes() in C:\Users\ci\AppData\Local\Temp\PUBLISHs0k5t\77_20180119T203345\autorest.go\src\Model\MethodGo.cs:line 335
   at AutoRest.Go.Model.MethodGo.get_RespondDecorators() in C:\Users\ci\AppData\Local\Temp\PUBLISHs0k5t\77_20180119T203345\autorest.go\src\Model\MethodGo.cs:line 448
   at AutoRest.Go.Templates.MethodTemplate.&lt;ExecuteAsync&gt;d__1.MoveNext() in C:\Users\ci\AppData\Local\Temp\PUBLISHs0k5t\77_20180119T203345\autorest.go\src\obj\Razor\Templates\MethodTemplate.cshtml:line 224
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AutoRest.Core.Template`1.ToString()
   at AutoRest.Core.Template`1.Include[TU,TV](TU template, TV templateModel)
   at AutoRest.Go.Templates.ServiceClientTemplate.&lt;ExecuteAsync&gt;d__1.MoveNext() in C:\Users\ci\AppData\Local\Temp\PUBLISHs0k5t\77_20180119T203345\autorest.go\src\obj\Razor\Templates\ServiceClientTemplate.cshtml:line 117
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AutoRest.Core.CodeGenerator.&lt;Write&gt;d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at AutoRest.Go.CodeGeneratorGo.&lt;Generate&gt;d__6.MoveNext() in C:\Users\ci\AppData\Local\Temp\PUBLISHs0k5t\77_20180119T203345\autorest.go\src\CodeGeneratorGo.cs:line 64
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at AutoRest.Go.Program.&lt;ProcessInternal&gt;d__3.MoveNext() in C:\Users\ci\AppData\Local\Temp\PUBLISHs0k5t\77_20180119T203345\autorest.go\src\Program.cs:line 107
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NewPlugin.&lt;Process&gt;d__15.MoveNext()
FATAL: go/generate - FAILED
FATAL: Error: Plugin go reported failure.
(node:15196) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 15): Error: Plugin go reported failure.
(node:15196) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:15196) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 16): Error: Plugin go reported failure.
(node:15196) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 17): Error: Plugin go reported failure.
  Error: Plugin go reported failure.

Standard Output: AutoRest code generation utility [version: 2.0.4238; node: v7.10.1]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      'D:\local\UserProfile\.autorest\@microsoft.azure_autorest-core@2.0.4238\node_modules\@microsoft.azure\autorest-core\dist' (2.0.4238)
No configuration found at 'file:///D:/local/Temp/jobs/continuous/ClientCodeGeneration/yjgcr4yu.wwi/'.
   Loading AutoRest extension '@microsoft.azure/autorest.csharp' (~2.2.51)
   Loading AutoRest extension '@microsoft.azure/autorest.go' (~2.1.47)
   Loading AutoRest extension '@microsoft.azure/autorest.java' (~2.1.32)
   Loading AutoRest extension '@microsoft.azure/autorest.nodejs' (~2.1.25)
   Loading AutoRest extension '@microsoft.azure/autorest.python' (~2.1.26)
   Loading AutoRest extension '@microsoft.azure/autorest.ruby' (~3.1.26)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.1.22)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.38)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.44)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.43)
Process() Cancelled due to exception : Plugin go reported failure.

Parameters: --input-file="D:\local\Temp\jobs\continuous\ClientCodeGeneration\yjgcr4yu.wwi\ea133db9-7cbf-4ef1-8ca4-001cecc7667f\microsoft-upp-calc-rules-api.json" --namespace="Microsoft.Swagger.Codegen.UPPCalcRules" --csharp --csharp.output-folder="D:\local\Temp\jobs\continuous\ClientCodeGeneration\yjgcr4yu.wwi\ea133db9-7cbf-4ef1-8ca4-001cecc7667f\csharpcodegen\csharp" --java --java.output-folder="D:\local\Temp\jobs\continuous\ClientCodeGeneration\yjgcr4yu.wwi\ea133db9-7cbf-4ef1-8ca4-001cecc7667f\javacodegen\java" --nodejs --nodejs.output-folder="D:\local\Temp\jobs\continuous\ClientCodeGeneration\yjgcr4yu.wwi\ea133db9-7cbf-4ef1-8ca4-001cecc7667f\nodejscodegen\nodejs" --python --python.output-folder="D:\local\Temp\jobs\continuous\ClientCodeGeneration\yjgcr4yu.wwi\ea133db9-7cbf-4ef1-8ca4-001cecc7667f\pythoncodegen\python" --go --go.output-folder="D:\local\Temp\jobs\continuous\ClientCodeGeneration\yjgcr4yu.wwi\ea133db9-7cbf-4ef1-8ca4-001cecc7667f\gocodegen\go" --ruby --ruby.output-folder="D:\local\Temp\jobs\continuous\ClientCodeGeneration\yjgcr4yu.wwi\ea133db9-7cbf-4ef1-8ca4-001cecc7667f\rubycodegen\ruby" 
</Message>
    <TimeStamp>2018-01-24 12:40:25</TimeStamp>
  </Log>
</Logs>
```

which I could track down to [MethodGo.cs#L335](https://github.com/Azure/autorest.go/blob/master/src/Model/MethodGo.cs#L335) and [CodeNamerGo.cs#L100](https://github.com/Azure/autorest.go/blob/master/src/CodeNamerGo.cs#L100).

How can this be resolved as I'm blocked? I'm willing to submit pull requests if that would help.

P.S. An effort in .NET Core is ongoing to bring HttpStatusCode enum up to date with RFC, see https://github.com/dotnet/corefx/issues/4382.

**Comment by abatishchev** [comment]
Can you please take a look?

**Comment by fearthecowboy** [comment]
@mcardosos @jhendrixMSFT  -- any ideas?

**Comment by mcardosos** [comment]
I think we need to add the status code to a list in the code namer.

**Comment by abatishchev** [comment]
Do you plan to take any action on this any time soon? Would love to see this fixed so Swagger could pick it up and unblock us!

**Comment by abatishchev** [comment]
And this is not an issue for other platforms/languages? They all already can handle 424 or other enums outside HttpStatusCode?
