### ISSUE TITLE
AutoRest exited unexpectedly after launching

### ISSUE THREAD

**Issue by JanEggers** [Azure/autorest#2854]
FATAL: AutoRest exited unexpectedly after launching autorest-core module @microsoft.azure/autorest-core from [USer]AppData\Local\Temp\.autorest\@microsoft.azure_autorest-core@2.0.4251

how to diagnose this?

im really mad. i used 1.9.0 and it just worked. i spend more than an hour to upgratde to 2.0.4251

because i get a load of useless error messages like:

> missing magic string

> line ending expected

> no mapping found

and now it tries to do something but fails with internal error thats just frustrating.

**Comment by JanEggers** [comment]
I switched to swagger-codegen, that just worked with:

java -jar ./node_modules/swagger-codegen-cli/vendor/swagger-codegen-cli.jar generate -i ./client/swagger.json -l csharp -o ./client/generated

**Comment by fearthecowboy** [comment]
Hey @JanEggers -- can you post the swagger file and command-line you were trying to generate for?

**Comment by JanEggers** [comment]
hers the swagger file:

https://gist.github.com/JanEggers/edeca2fddfcd83c16cd6e62e483f189d

autorest --input-file=swagger.json --output-folder=./generated/ --csharp

**Comment by fearthecowboy** [comment]
I suspect you had a space between `--input-file=` and `file.swagger` with the error that you got.

I tried the file and I got two kinds of problems:


The first one, you have duplicate `application/json` in a couple of arrays. The JSON Validator didn't like that.

``` bash
C:\tmp\janeggers> autorest --input-file=file.json --output-folder=./generated/ --csharp
AutoRest code generation utility [version: 2.0.4248; node: v8.9.3]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      'C:\Users\garretts\AppData\Local\Temp\.autorest\@microsoft.azure_autorest-core@2.0.4251\node_modules\@microsoft.azure\autorest-core\dist' (2.0.4251)
   Loading AutoRest extension '@microsoft.azure/autorest.csharp' (~2.2.51->2.2.57)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.43->2.3.43)
ERROR: Schema violation: Array items are not unique (indexes 0 and 2)
    - file:///C:/tmp/janeggers/file.json:157:16 ($.paths["/api/Mqtt/Pif/ParamChange"].post.consumes)
ERROR: Schema violation: Array items are not unique (indexes 0 and 2)
    - file:///C:/tmp/janeggers/file.json:13:16 ($.paths["/api/Mqtt/Publish"].post.consumes)
FATAL: swagger-document/individual/schema-validator - FAILED
FATAL: Error: [OperationAbortedException] Error occurred. Exiting.
Process() cancelled due to exception : [OperationAbortedException] Error occurred. Exiting.
```

Once I corrected that, I tried again: 

``` bash
C:\tmp\janeggers> autorest --input-file=file.json --output-folder=./generated/ --csharp
AutoRest code generation utility [version: 2.0.4248; node: v8.9.3]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      'C:\Users\garretts\AppData\Local\Temp\.autorest\@microsoft.azure_autorest-core@2.0.4251\node_modules\@microsoft.azure\autorest-core\dist' (2.0.4251)
   Loading AutoRest extension '@microsoft.azure/autorest.csharp' (~2.2.51->2.2.57)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.43->2.3.43)
FATAL: System.InvalidOperationException: Found incompatible property types Object, Object for property 'value' in schema
   at AutoRest.Modeler.SchemaResolver.ExpandAllOf(Schema schema) in C:\Users\ci\AppData\Local\Temp\PUBLISHu1dw1\43_20171213T192246\autorest.modeler\src\SchemaResolver.cs:line 142
   at AutoRest.Modeler.SchemaResolver.Unwrap(Schema schema) in C:\Users\ci\AppData\Local\Temp\PUBLISHu1dw1\43_20171213T192246\autorest.modeler\src\SchemaResolver.cs:line 75
   at AutoRest.Modeler.SchemaBuilder.BuildServiceType(String serviceTypeName, Boolean required) in C:\Users\ci\AppData\Local\Temp\PUBLISHu1dw1\43_20171213T192246\autorest.modeler\src\SchemaBuilder.cs:line 35
   at AutoRest.Modeler.SwaggerModeler.BuildCompositeTypes() in C:\Users\ci\AppData\Local\Temp\PUBLISHu1dw1\43_20171213T192246\autorest.modeler\src\SwaggerModeler.cs:line 310
   at AutoRest.Modeler.SwaggerModeler.Build(ServiceDefinition serviceDefinition) in C:\Users\ci\AppData\Local\Temp\PUBLISHu1dw1\43_20171213T192246\autorest.modeler\src\SwaggerModeler.cs:line 66
   at AutoRest.Modeler.Program.<ProcessInternal>d__2.MoveNext() in C:\Users\ci\AppData\Local\Temp\PUBLISHu1dw1\43_20171213T192246\autorest.modeler\src\Program.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NewPlugin.<Process>d__15.MoveNext()
FATAL: csharp/imodeler1 - FAILED
FATAL: Error: Plugin imodeler1 reported failure.
Process() cancelled due to exception : Plugin imodeler1 reported failure.
  Error: Plugin imodeler1 reported failure.
```

Ouch! It apparently didn't like the duplicated fields between the `allOf` and declared properties. (Worse it's throwing an exception!).

Looking into it, you have models where you have duplicate properties in `allOf` and the model definition itself:

``` json
 "ParameterDataBitSet": {
            "type": "object",
            "allOf": [
                { "$ref": "#/definitions/ParameterDataBase" },
                {
                    "type": "object",
                    "properties": {
                        "default": {
                            "format": "int64",
                            "type": "integer"
                        },
                        "locked": {
                            "format": "int64",
                            "type": "integer"
                        },
                        "used": {
                            "format": "int64",
                            "type": "integer"
                        },
                        "value": {
                            "format": "int64",
                            "type": "integer"
                        }
                    }
                }
            ],
            "properties": {
                "default": {
                    "format": "int64",
                    "type": "integer"
                },
                "locked": {
                    "format": "int64",
                    "type": "integer"
                },
                "used": {
                    "format": "int64",
                    "type": "integer"
                },
                "value": {
                    "format": "int64",
                    "type": "integer"
                }
            }
        },
``` 

The inlined model in the `allOf`s aren't necessary (as you are declaring the same properties in the model anyway), and case, seems to be confusing it when it tries to merge the definitions.

I removed the inlined models from the `allOf`s and ran it again:

``` bash
C:\tmp\janeggers> autorest --input-file=file.json --output-folder=./generated/ --csharp
AutoRest code generation utility [version: 2.0.4248; node: v8.9.3]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      'C:\Users\garretts\AppData\Local\Temp\.autorest\@microsoft.azure_autorest-core@2.0.4251\node_modules\@microsoft.azure\autorest-core\dist' (2.0.4251)
   Loading AutoRest extension '@microsoft.azure/autorest.csharp' (~2.2.51->2.2.57)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.43->2.3.43)
C:\tmp\janeggers> dir .\generated\


    Directory: C:\tmp\janeggers\generated


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        2/21/2018   8:34 AM                Models
-a----        2/21/2018   8:34 AM         166297 DeviceApi.cs
-a----        2/21/2018   8:34 AM          35291 DeviceApiExtensions.cs
-a----        2/21/2018   8:34 AM          16028 IDeviceApi.cs
```

**Comment by JanEggers** [comment]
@fearthecowboy thx for analysing the issues.

Im a little confused why you get that detailed info and im just getting AutoRest exited unexpectedly after launching autorest-core module @microsoft.azure/autorest-core from [USer]AppData\Local\Temp.autorest@microsoft.azure_autorest-core@2.0.4251

and for the issues in the swagger im using swashbuckle.aspnetcore. maybe i should raise an issue there.

**Comment by fearthecowboy** [comment]
maybe try `autorest --reset` to see if a plugin got broken.
