### ISSUE TITLE
Add swagger version to validation schema

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/autorest#2883]
Ported from https://github.com/Azure/azure-sdk-for-go/issues/1199

Using autorest to generate go client fails with below error if version in the specification json file is empty

Error:
FATAL: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: startIndex
at System.String.LastIndexOf(Char value, Int32 startIndex, Int32 count)
at AutoRest.Go.Model.CodeModelGo.PackageVerDir() in C:\Users\ci\AppData\Local\Temp\PUBLISHwf52p\100_20180220T231516\autorest.go\src\Model\CodeModelGo.cs:line 64
at AutoRest.Go.Model.CodeModelGo.get_DefaultUserAgent() in C:\Users\ci\AppData\Local\Temp\PUBLISHwf52p\100_20180220T231516\autorest.go\src\Model\CodeModelGo.cs:line 83
at AutoRest.Go.Model.CodeModelGo.get_UserAgent() in C:\Users\ci\AppData\Local\Temp\PUBLISHwf52p\100_20180220T231516\autorest.go\src\Model\CodeModelGo.cs:line 31
at AutoRest.Go.Templates.VersionTemplate.d__1.MoveNext() in C:\Users\ci\AppData\Local\Temp\PUBLISHwf52p\100_20180220T231516\autorest.go\src\obj\Razor\Templates\VersionTemplate.cshtml:line 28
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at AutoRest.Core.CodeGenerator.d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at AutoRest.Go.CodeGeneratorGo.d__6.MoveNext() in C:\Users\ci\AppData\Local\Temp\PUBLISHwf52p\100_20180220T231516\autorest.go\src\CodeGeneratorGo.cs:line 91
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at AutoRest.Go.Program.d__3.MoveNext() in C:\Users\ci\AppData\Local\Temp\PUBLISHwf52p\100_20180220T231516\autorest.go\src\Program.cs:line 107
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at NewPlugin.d__15.MoveNext()
FATAL: go/generate - FAILED
FATAL: Error: Plugin go reported failure.
Process() cancelled due to exception : Plugin go reported failure.
Error: Plugin go reported failure.
-------------------------------------------------------------------------------------------------------------------
Sample Json file, with empty version field that causes exception:
```json
{
  "basePath": "/",
  "definitions": {},
  "host": "testhost",
  "info": {
    "title": "testAPI",
    "version": ""
  },
  "paths": {
    "/users/get": {
      "post": {
        "description": "",
        "operationId": "postUsersGet",
        "parameters": [],
        "responses": {
          "default": {
            "description": "Unexpected Error!"
          }
        },
        "summary": "Get user",
        "tags": [
          "Users"
        ]
      }
    }
  },
  "produces": [
    "application/json",
    "text/json",
    "application/xml",
    "text/xml"
  ],
  "schemes": [
    "https"
  ],
  "swagger": "2.0"
}
```

**Comment by fearthecowboy** [comment]
I've created a PR to force it to at least one character: @see #2884
