### ISSUE TITLE
c# JsonReaderException when deserializing a string

### ISSUE THREAD

**Issue by RohrerF** [Azure/autorest#2913]
I have a Method which returns a string. The generated code part that throws the Error looks like this:

```
_responseContent = await _httpResponse.Content.ReadAsStringAsync().ConfigureAwait(false);
try
{
      _result.Body = Microsoft.Rest.Serialization.SafeJsonConvert.DeserializeObject<string>(_responseContent, Client.DeserializationSettings);
}
catch (JsonException ex)
```

The `_responseContent`has a valid string value("Hello"). While deserializing the following error is thrown:

```
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: H. Path '', line 1, position 1.
   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsString()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Microsoft.Rest.Serialization.SafeJsonConvert.DeserializeObject[T](String json, JsonSerializerSettings settings)
```

**Comment by fearthecowboy** [comment]
You need to switch to using `type:object` and `format: file`  which will treat the response as a stream instead of a JSON string. Make sure that you change your `produces` to an appropriate mime-type.

**Comment by RohrerF** [comment]
Can you please provide an example for this? I can't get it running
