### ISSUE TITLE
Using autorest when API's return a list of objects

### ISSUE THREAD

**Issue by dpmartin990** [Azure/autorest#2929]
I have some API operations which return a List of objects.  In the swagger v 2.0 document (which I generated using Swashbuckle) in the definitions section the Json looks like this:

    "PartnerAPIPagingList[Customer]": {
 ... },

and in the paths/(operation path)/get/responses/200/schema/$ref it says "#/definitions/PartnerAPIPagingList[Customer]"

But in order to get validation to pass using the Swagger-Editor online I had to change it to "#/definitions/PartnerAPIPagingList%5BCustomer%5D" because percent encoding is apparently mandatory for brackets in ref.  But I am getting this error:

AutoRest code generation utility [version: 2.0.4262; node: v10.1.0]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
(node:30640) ExperimentalWarning: The fs.promises API is experimental
   Loading AutoRest core      'C:\Users\dmartin3\.autorest\@microsoft.azure_autorest-core@2.0.4277\node_modules\@microso
ft.azure\autorest-core\dist' (2.0.4277)
   Loading AutoRest extension '@microsoft.azure/autorest.csharp' (~2.2.51->2.2.57)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.43->2.3.43)
FATAL: openapi-document/openapi-document-converter - FAILED
FATAL: Error: Could not resolve reference #/definitions/PartnerAPIPagingList%5BCustomer%5D
Process() cancelled due to exception : Could not resolve reference #/definitions/PartnerAPIPagingList%5BCustomer%5D
  Error: Could not resolve reference #/definitions/PartnerAPIPagingList%5BCustomer%5D
(node:30640) UnhandledPromiseRejectionWarning: Error: Could not resolve reference #/definitions/PartnerAPIPagingList%5BC
ustomer%5D
    at throwError (/node_modules/swagger2openapi/index.js:25:15)
    at throwOrWarn (/node_modules/swagger2openapi/index.js:35:9)
    at fixupRefs (/node_modules/swagger2openapi/index.js:149:17)
    at recurse (/node_modules/reftools/lib/recurse.js:36:9)
    at recurse (/node_modules/reftools/lib/recurse.js:52:13)
    at recurse (/node_modules/reftools/lib/recurse.js:52:13)
    at recurse (/node_modules/reftools/lib/recurse.js:52:13)
    at recurse (/node_modules/reftools/lib/recurse.js:52:13)
    at recurse (/node_modules/reftools/lib/recurse.js:52:13)
    at Object.recurse (/node_modules/reftools/lib/recurse.js:52:13)
    at main (/node_modules/swagger2openapi/index.js:830:12)
    at /node_modules/swagger2openapi/index.js:1222:13
    at Generator.next (<anonymous>)
    at onFulfilled (/node_modules/co/index.js:65:19)
    at /node_modules/co/index.js:54:5
    at new Promise (<anonymous>)
(node:30640) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing ins
ide of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejectio
n id: 9)
(node:30640) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejection
s that are not handled will terminate the Node.js process with a non-zero exit code.
(node:30640) UnhandledPromiseRejectionWarning: Error: Could not resolve reference #/definitions/PartnerAPIPagingList%5BC
ustomer%5D
    at throwError (/node_modules/swagger2openapi/index.js:25:15)
    at throwOrWarn (/node_modules/swagger2openapi/index.js:35:9)
    at fixupRefs (/node_modules/swagger2openapi/index.js:149:17)
    at recurse (/node_modules/reftools/lib/recurse.js:36:9)
    at recurse (/node_modules/reftools/lib/recurse.js:52:13)
    at recurse (/node_modules/reftools/lib/recurse.js:52:13)
    at recurse (/node_modules/reftools/lib/recurse.js:52:13)
    at recurse (/node_modules/reftools/lib/recurse.js:52:13)
    at recurse (/node_modules/reftools/lib/recurse.js:52:13)
    at Object.recurse (/node_modules/reftools/lib/recurse.js:52:13)
    at main (/node_modules/swagger2openapi/index.js:830:12)
    at /node_modules/swagger2openapi/index.js:1222:13
    at Generator.next (<anonymous>)
    at onFulfilled (/node_modules/co/index.js:65:19)
    at /node_modules/co/index.js:54:5
    at new Promise (<anonymous>)
....
  
So then I tried changing them both to "PartnerAPIPagingList%5BCustomer%5D" but I'm now getting this error

AutoRest code generation utility [version: 2.0.4262; node: v10.1.0]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
(node:27316) ExperimentalWarning: The fs.promises API is experimental
   Loading AutoRest core      'C:\Users\dmartin3\.autorest\@microsoft.azure_autorest-core@2.0.4277\node_modules\@microso
ft.azure\autorest-core\dist' (2.0.4277)
   Loading AutoRest extension '@microsoft.azure/autorest.csharp' (~2.2.51->2.2.57)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.43->2.3.43)
(node:27316) UnhandledPromiseRejectionWarning: TypeError: volume[member].bind is not a function
    at patchFilesystem (C:\Users\dmartin3\AppData\Roaming\npm\node_modules\autorest\dist\static-loader.js:277:43)
    at C:\Users\dmartin3\AppData\Roaming\npm\node_modules\autorest\dist\static-loader.js:281:18
    at Object.global.staticloader.undo (C:\Users\dmartin3\AppData\Roaming\npm\node_modules\autorest\dist\static-loader.j
s:163:7)
    at process.exit.n [as exit] (C:\Users\dmartin3\AppData\Roaming\npm\node_modules\autorest\dist\static-loader.js:170:2
7)
    at main (C:\Users\dmartin3\.autorest\@microsoft.azure_autorest-core@2.0.4277\node_modules\@microsoft.azure\autorest-
core\dist\app.js:514:21)
(node:27316) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing ins
ide of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejectio
n id: 7)
(node:27316) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejection
s that are not handled will terminate the Node.js process with a non-zero exit code.
Shutting Down

I also changed them both to real brackets but still got the same error as above.

How can I get my client code generated?

**Comment by fearthecowboy** [comment]
I'd have to see the whole swagger file.

In AutoRest, the brackets shouldn't make any difference, they're legal URI characters.

The other thing I'd suggest is to upgrade your node to at least 10.3 (or downgrade to 8.11.x) -- early builds of node 10 have given me some weird things. 

G

**Comment by dpmartin990** [comment]
Turns out something did get generated at least one of those times despite the errors I saw in the console.  Will try an upgrade.  Thanks.

**Comment by MiYanni** [comment]
Question resolved. Closing.
