### ISSUE TITLE
Enhancement: For CSharp generate constructor with HttpClient

### ISSUE THREAD

**Issue by lkurzyniec** [Azure/autorest#2951]
I'm making integration tests for api client package generated by autorest. 

Code snippet for test server:
```csharp
    public class TestServerClientFixture
    {
        protected const string API_BASE_URL = "http://localhost:5000";

        public HttpClient Client { get; }

        public TestServerClientFixture()
        {
            var server = new TestServer(WebHost.CreateDefaultBuilder()
                .UseEnvironment("Test")
                .UseStartup<TestStartup>().ConfigureServices(services => services.AddAutofac()))
            {
                BaseAddress = new Uri(API_BASE_URL)
            };

            Client = server.CreateClient();
        }
    }
```

Code for Api Client fixture:
```csharp
    public class ApiClientWrapperFixture : TestServerClientFixture
    {
        public MyClientApi ApiClient => new MyClientApi(Client);    //error: no such constructor

        public ApiClientWrapperFixture()
        {
            
        }
    }
```

But above code doesn't work because there is no such constructor with `HttpClient` as a parameter, so I need to create separate file with partial declaration as below.

```csharp
    public partial class MyClientApi 
    {
        public MyClientApi(HttpClient httpClient) : base(httpClient)
        {
            Initialize();
        }
    }
```

It would be great that autorest autogenerate also this constructor.

**Comment by g4d** [comment]
Add a second param to control disposing of your httpClient.

I get this when I gen for csharp on [version: 2.0.4283; node: v8.11.3]
```
public MyClientApi(HttpClient httpClient, bool disposeHttpClient) : base(httpClient, disposeHttpClient)
{
    Initialize();
}
```

**Comment by lkurzyniec** [comment]
Perfect! Thanks.

**Comment by ryanelian** [comment]
Excuse me, I'm trying this exact constructor, with [`IHttpClientFactory`](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-2.2)

```cs
            var client = HttpClientFac.CreateClient();
            client.BaseAddress = new Uri(Settings.OIDC.AdministrationBaseUri);
            var hydra = new ORYHydra(client, false);
```

I ran into this error:

```
System.Net.Http.HttpRequestException: No connection could be made because the target machine actively refused it ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Accelist.HydraSDK.ORYHydra.UpdateOAuth2ClientWithHttpMessagesAsync(String id, OAuth2Client body, Dictionary`2 customHeaders, CancellationToken cancellationToken) in F:\VS\Accelist.KingCerberus\Accelist.HydraSDK\ORYHydra.cs:line 1112
   at Accelist.HydraSDK.ORYHydraExtensions.UpdateOAuth2ClientAsync(IORYHydra operations, String id, OAuth2Client body, CancellationToken cancellationToken) in F:\VS\Accelist.KingCerberus\Accelist.HydraSDK\ORYHydraExtensions.cs:line 322
   at Accelist.KingCerberus.API.BootstrapApiController.Post() in F:\VS\Accelist.KingCerberus\Accelist.KingCerberus\API\BootstrapApiController.cs:line 36
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

If I instead use this, it'll work...

```
var hydra = new ORYHydra(new Uri(Settings.OIDC.AdministrationBaseUri));
```

[I need the HTTP Client Factory to avoid HTTP Client stale DNS problem.](http://www.nimaara.com/2016/11/01/beware-of-the-net-httpclient/)

How to solve this problem?
