### ISSUE TITLE
--namespace $config.namespace.replace is not a function

### ISSUE THREAD

**Issue by thedwillis** [Azure/autorest#2961]
When using the following autorest statement to generate a client lib I am receiving the titled error:
`autorest --input-file=<path_to_swagger> --namespace API.ClientLib --csharp --clear-output-folder --override-client-name=DataApiClient --add-credentials`
If I omit the --namespace argument the error doesn't occur and the lib generates successfully, but obviously the namespace is set to Swagger, which isn't ideal.

The full stack trace is:
```
AutoRest code generation utility [version: 2.0.4280; node: v8.11.3]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      'C:\Users\willis\.autorest\@microsoft.azure_autorest-core@2.0.4280\node_modules\@microsoft.azure\autorest-core\dist
' (2.0.4280)
   Loading AutoRest extension '@microsoft.azure/autorest.csharp' (~2.2.51->2.2.67)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.50->2.3.50)
FATAL: swagger-document/emitter - FAILED
FATAL: TypeError: $config.namespace.replace is not a function
FATAL: openapi-document/emitter - FAILED
FATAL: TypeError: $config.namespace.replace is not a function
(node:31324) UnhandledPromiseRejectionWarning: TypeError: $config.namespace.replace is not a function
(node:31324) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function witho
ut a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 13)
(node:31324) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will te
rminate the Node.js process with a non-zero exit code.
(node:31324) UnhandledPromiseRejectionWarning: TypeError: $config.namespace.replace is not a function
(node:31324) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function witho
ut a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 14)
System.ArgumentException: Can not convert Object to String.
   at Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject[T]()
   at Microsoft.Perks.JsonRPC.CallerResponse`1.SetCompleted(JToken result)
   at Microsoft.Perks.JsonRPC.Connection.<>c__DisplayClass27_0.<<Process>b__0>d.MoveNext()
```

I haven't attached my swagger JSON as it is rather long, but if you need it to investigate further let me know, and I'll link it via pastebin or something...

**Comment by thedwillis** [comment]
Another thing to note, this appears to only happen with the 'new' CLI, using the -namespace argument works perfectly.

**Comment by fearthecowboy** [comment]
Double dash parameters use equals signs ` --namespace=my.namespace`
