### ISSUE TITLE
 Duplicate File Generation

### ISSUE THREAD

**Issue by Ellaiyaraja** [Azure/autorest#2975]
i tried to generate C# code for An Microsoft OPEN API for face detection 
https://apis.guru/browse-apis/,
And i got the follwing error, Please help me in validating OPEN API specification.

<<

System.Exception: Duplicate File Generation: Face.cs
   at AutoRest.Core.CodeGenerator.<Write>d__13.MoveNext() in /opt/vsts/work/1/s/autorest.common/src/CodeGenerator.cs:line 151
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AutoRest.Core.CodeGenerator.<Write>d__12.MoveNext() in /opt/vsts/work/1/s/autorest.common/src/CodeGenerator.cs:line 121
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AutoRest.CSharp.CodeGeneratorCs.<GenerateOperations>d__14`1.MoveNext() in /opt/vsts/work/1/s/src/vanilla/CodeGeneratorCs.cs:line 86
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AutoRest.CSharp.CodeGeneratorCs.<GenerateClientSideCode>d__12.MoveNext() in /opt/vsts/work/1/s/src/vanilla/CodeGeneratorCs.cs:line 63
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AutoRest.CSharp.CodeGeneratorCs.<GenerateRestCode>d__19.MoveNext() in /opt/vsts/work/1/s/src/vanilla/CodeGeneratorCs.cs:line 155
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AutoRest.CSharp.CodeGeneratorCs.<Generate>d__20.MoveNext() in /opt/vsts/work/1/s/src/vanilla/CodeGeneratorCs.cs:line 188
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AutoRest.CSharp.Program.<ProcessInternal>d__4.MoveNext() in /opt/vsts/work/1/s/src/Program.cs:line 147
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NewPlugin.<Process>d__20.MoveNext() in /opt/vsts/work/1/s/autorest.common/src/Plugins/NewPlugin.cs:line 163
FATAL: csharp/generate - FAILED
FATAL: Error: Plugin csharp reported failure.
Process() cancelled due to exception : Plugin csharp reported failure.
  Error: Plugin csharp reported failure.

**Comment by deathly809** [comment]
@Ellaiyaraja Do you mean this spec?  https://api.apis.guru/v2/specs/azure.com/cognitiveservices-Face/1.0/swagger.json

**Comment by Ellaiyaraja** [comment]
Yes. The same spec. you have pointed.
autorest --input-file=FaceDetectionMicrosoft.json --csharp --output-folder=CSharp_FaceStore --namespace=faceTest

And Another help,

How can i use "configuration-file.md" file, can you provide me reference to help content.

**Comment by deathly809** [comment]
Here is an example of the md file,

https://github.com/Azure/azure-rest-api-specs/blob/master/specification/azurestack/resource-manager/readme.md

You should file this issue over with the csharp extension team, they would have better insight.

https://github.com/Azure/autorest.csharp

**Comment by fearthecowboy** [comment]
Or you could use the swagger file from the original source: https://github.com/Azure/azure-rest-api-specs/tree/master/specification/cognitiveservices/data-plane/Face 

Or just use the autorest-generated SDK : https://www.nuget.org/packages/Microsoft.Azure.CognitiveServices.Vision.Face/2.2.0-preview

**Comment by deathly809** [comment]
@fearthecowboy  That is no fun!

**Comment by Ellaiyaraja** [comment]
@microsoftopensource , @olydis

i tried to generate C# code for An Microsoft OPEN API for face detection
https://apis.guru/browse-apis/,
And i got the Duplicate File Generation error file name called "Face". How to resolve this issue.

**Comment by deathly809** [comment]
@Ellaiyaraja  Like I said above, you should file an issue with the csharp autorest extension team.

**Comment by Ellaiyaraja** [comment]
@deathly809 ,

Iam Sorry . 
Actually i could not find an option to report Issue over C# home, https://github.com/Azure/autorest.csharp.

i don't know exactly how to report, so i just added two C# contributors. @microsoftopensource , @olydis
