### ISSUE TITLE
Plugin 'modeler' not found

### ISSUE THREAD

**Issue by scott-lin** [Azure/autorest#2981]
I'm using AutoRest as a library instead of from the command line. See https://github.com/Azure/autorest/issues/2896

When I call AutoRest to generate clients in languages PHP, Ruby & Typescript, I encounter an error stating `Plugin 'modeler' not found`. I'm successfully able to generate clients in other languages such as C#, Java & Python, however.

I'm calling AutoRest with the Petstore OpenAPI document: http://petstore.swagger.io/v2/swagger.json

**Node version**: 8.9.4

**package.json**
```
"dependencies": {
    "@microsoft.azure/autorest-core": "^2.0.4275",
    "@microsoft.azure/autorest.csharp": "^2.3.79",
    "@microsoft.azure/autorest.go": "^2.1.47",
    "@microsoft.azure/autorest.java": "^2.1.32",
    "@microsoft.azure/autorest.modeler": "^2.3.55",
    "@microsoft.azure/autorest.nodejs": "^2.1.25",
    "@microsoft.azure/autorest.php": "^2.0.12",
    "@microsoft.azure/autorest.python": "^2.1.26",
    "@microsoft.azure/autorest.ruby": "^3.1.26",
    "@microsoft.azure/autorest.typescript": "^2.0.12",
    "autorest": "^2.0.4275",
    "uuid": "^3.2.1"
}
```

**Stack**
```
Error: Plugin 'modeler' not found.
  at ScheduleNode (.\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\pipeline.js:318:19)
  at <anonymous> 
  at runMicrotasksCallback (internal/process/next_tick.js:121:5) 
  at _combinedTickCallback (internal/process/next_tick.js:131:7) 
  at process._tickCallback (internal/process/next_tick.js:180:9)
```

Is this a bug in AutoRest? Or do I need to use a specific version of modeler for the languages that are failing? Other?

**Comment by scott-lin** [comment]
Did some more debugging, and I came across an interesting finding. When I lower the version of `modeler` dependency to `2.1.22`, the client is generated successfully for PHP. However, other languages have similar issue still.

I suspect the various language extensions have a requirement around which version of `modeler` is supported. Would love if someone more intimate with AutoRest could confirm.

Is there a recommendation for how to generate clients in any language using AutoRest as a library? Let's say I did package up each required version of modeler for the languages I'm targeting, is there a way to tell AutoRest core which one to use via a folder path? I suspect there should be since AutoRest from the command line seems to be doing something similar (downloads multiple versions of modeler for the various language extensions requirements and runs them).

**Comment by scott-lin** [comment]
I came across some code in AutoRest that seems to specify the dependencies to use: https://github.com/Azure/autorest/blob/aafd072e035a5a3aad01cfa9803a3663f675a2d3/src/autorest-core/test/modifiers.ts#L27

So I've been trying to mimic this, but without success.

```
autoRest.AddConfiguration({ "use": "d:\\my\\path\\autorest.modeler@2.1.22" });
```

**Error**
```
Package 'd:\\my\\path\\autorest.modeler' - '2.1.22' is not a valid package reference:
Invalid package name \"d:\\my\\path\\autorest.modeler\": name can only contain URL-friendly characters
  at resolveName (/node_modules/@microsoft.azure/extension/dist/main.js:307:19)
  at ExtensionManager.findPackage (/node_modules/@microsoft.azure/extension/dist/main.js:361:26)
  at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by scott-lin** [comment]
Changed the @ symbol to a hyphen and got past the error. I'm using `npm-install-version` via gulp to install all of the modeler version I need.
