### ISSUE TITLE
Autorest fails when it shouldn't: The schema's 'Operation' ancestors should have at lease one property

### ISSUE THREAD

**Issue by epet** [Azure/autorest#2988]
seems similar to if not exact type of failure. [https://github.com/Azure/autorest/issues/2671#issuecomment-416706057](url)
sample json is a private service, sent direct to @fearthecowboy 

individual commands all fail:
`autorest --generate-empty-classes --use=@microsoft.azure/autorest.modeler@preview --input-file="F:\some_service\some_service.json" --namespace="some.service.namespace" --python --python.output-folder="F:\some_service\pythoncodegen\python" > autorest-python-output.txt 2>&1`
```
AutoRest code generation utility [version: 2.0.4283; node: v8.11.2]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      'C:\Users\epet.REDMOND\.autorest\@microsoft.azure_autorest-core@2.0.4283\node_modules\@microsoft.azure\autorest-core\dist' (2.0.4283)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (preview->2.3.55)
   Loading AutoRest extension '@microsoft.azure/autorest.python' (~2.1.26->2.1.26)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.38->2.3.38)
FATAL: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at AutoRest.Modeler.OperationBuilder.<>cDisplayClass13_0.<BuildMethodReturnType>b0(Stack`1 typeStack) in /opt/vsts/work/1/s/src/OperationBuilder.cs:line 376
   at System.Collections.Generic.List1.ForEach(Action1 action)
   at AutoRest.Modeler.OperationBuilder.BuildMethodReturnType(List`1 types, IModelType headerType) in /opt/vsts/work/1/s/src/OperationBuilder.cs:line 369
   at AutoRest.Modeler.OperationBuilder.BuildMethod(HttpMethod httpMethod, String url, String methodName, String methodGroup) in /opt/vsts/work/1/s/src/OperationBuilder.cs:line 197
   at AutoRest.Modeler.SwaggerModeler.BuildMethod(HttpMethod httpMethod, String url, String name, Operation operation) in /opt/vsts/work/1/s/src/SwaggerModeler.cs:line 404
   at AutoRest.Modeler.SwaggerModeler.Build(ServiceDefinition serviceDefinition) in /opt/vsts/work/1/s/src/SwaggerModeler.cs:line 106
   at AutoRest.Modeler.Program.<ProcessInternal>d__2.MoveNext() in /opt/vsts/work/1/s/src/Program.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NewPlugin.<Process>d__15.MoveNext()
FATAL: python/imodeler1 - FAILED
FATAL: Error: Plugin imodeler1 reported failure.
Process() cancelled due to exception : Plugin imodeler1 reported failure.
  Error: Plugin imodeler1 reported failure.

```

`autorest --generate-empty-classes --use=@microsoft.azure/autorest.modeler@preview --input-file="F:\some_service\some_service.json" --namespace="some.service.namespace" --nodejs --nodejs.output-folder="F:\some_service\nodejscodegen\nodejs" > autorest-nodejs-output.txt 2>&1`
```
AutoRest code generation utility [version: 2.0.4283; node: v8.11.2]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      'C:\Users\epet.REDMOND\.autorest\@microsoft.azure_autorest-core@2.0.4283\node_modules\@microsoft.azure\autorest-core\dist' (2.0.4283)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (preview->2.3.55)
   Loading AutoRest extension '@microsoft.azure/autorest.nodejs' (~2.1.25->2.1.25)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.38->2.3.38)
FATAL: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at AutoRest.Modeler.OperationBuilder.<>cDisplayClass13_0.<BuildMethodReturnType>b0(Stack`1 typeStack) in /opt/vsts/work/1/s/src/OperationBuilder.cs:line 376
   at System.Collections.Generic.List1.ForEach(Action1 action)
   at AutoRest.Modeler.OperationBuilder.BuildMethodReturnType(List`1 types, IModelType headerType) in /opt/vsts/work/1/s/src/OperationBuilder.cs:line 369
   at AutoRest.Modeler.OperationBuilder.BuildMethod(HttpMethod httpMethod, String url, String methodName, String methodGroup) in /opt/vsts/work/1/s/src/OperationBuilder.cs:line 197
   at AutoRest.Modeler.SwaggerModeler.BuildMethod(HttpMethod httpMethod, String url, String name, Operation operation) in /opt/vsts/work/1/s/src/SwaggerModeler.cs:line 404
   at AutoRest.Modeler.SwaggerModeler.Build(ServiceDefinition serviceDefinition) in /opt/vsts/work/1/s/src/SwaggerModeler.cs:line 106
   at AutoRest.Modeler.Program.<ProcessInternal>d__2.MoveNext() in /opt/vsts/work/1/s/src/Program.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NewPlugin.<Process>d__15.MoveNext()
FATAL: nodejs/imodeler1 - FAILED
FATAL: Error: Plugin imodeler1 reported failure.
Process() cancelled due to exception : Plugin imodeler1 reported failure.
  Error: Plugin imodeler1 reported failure.

```

`autorest --generate-empty-classes --use=@microsoft.azure/autorest.modeler@preview --input-file="F:\some_service\some_service.json" --namespace="some.service.namespace" --ruby --ruby.output-folder="F:\some_service\rubycodegen\ruby" > autorest-ruby-output.txt 2>&1`
```
AutoRest code generation utility [version: 2.0.4283; node: v8.11.2]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      'C:\Users\epet.REDMOND\.autorest\@microsoft.azure_autorest-core@2.0.4283\node_modules\@microsoft.azure\autorest-core\dist' (2.0.4283)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (preview->2.3.55)
   Loading AutoRest extension '@microsoft.azure/autorest.ruby' (~3.1.26->3.1.26)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.1.22->2.1.22)
FATAL: The schema's 'Operation' ancestors should have at lease one property
FATAL: AutoRest.Core.Logging.CodeGenerationException: The schema's 'Operation' ancestors should have at lease one property
   at AutoRest.Modeler.SwaggerModeler.BuildCompositeTypes() in C:\Users\ci\AppData\Local\Temp\PUBLISHv6236\20_20171009T223650\autorest.modeler\src\SwaggerModeler.cs:line 312
   at AutoRest.Modeler.SwaggerModeler.Build(ServiceDefinition serviceDefinition) in C:\Users\ci\AppData\Local\Temp\PUBLISHv6236\20_20171009T223650\autorest.modeler\src\SwaggerModeler.cs:line 69
   at AutoRest.Modeler.Program.<ProcessInternal>d__2.MoveNext() in C:\Users\ci\AppData\Local\Temp\PUBLISHv6236\20_20171009T223650\autorest.modeler\src\Program.cs:line 53
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NewPlugin.<Process>d__15.MoveNext()
FATAL: ruby/modeler - FAILED
FATAL: Error: Plugin modeler reported failure.
Process() cancelled due to exception : Plugin modeler reported failure.
  Error: Plugin modeler reported failure.

```

`autorest --generate-empty-classes --use=@microsoft.azure/autorest.modeler@preview --input-file="F:\some_service\some_service.json" --namespace="some.service.namespace" --java --java.output-folder="F:\some_service\javacodegen\java" > autorest-java-output.txt 2>&1`
```
AutoRest code generation utility [version: 2.0.4283; node: v8.11.2]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      'C:\Users\epet.REDMOND\.autorest\@microsoft.azure_autorest-core@2.0.4283\node_modules\@microsoft.azure\autorest-core\dist' (2.0.4283)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (preview->2.3.55)
   Loading AutoRest extension '@microsoft.azure/autorest.java' (~2.1.32->2.1.32)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.38->2.3.38)
FATAL: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at AutoRest.Modeler.OperationBuilder.<>cDisplayClass13_0.<BuildMethodReturnType>b0(Stack`1 typeStack) in /opt/vsts/work/1/s/src/OperationBuilder.cs:line 376
   at System.Collections.Generic.List1.ForEach(Action1 action)
   at AutoRest.Modeler.OperationBuilder.BuildMethodReturnType(List`1 types, IModelType headerType) in /opt/vsts/work/1/s/src/OperationBuilder.cs:line 369
   at AutoRest.Modeler.OperationBuilder.BuildMethod(HttpMethod httpMethod, String url, String methodName, String methodGroup) in /opt/vsts/work/1/s/src/OperationBuilder.cs:line 197
   at AutoRest.Modeler.SwaggerModeler.BuildMethod(HttpMethod httpMethod, String url, String name, Operation operation) in /opt/vsts/work/1/s/src/SwaggerModeler.cs:line 404
   at AutoRest.Modeler.SwaggerModeler.Build(ServiceDefinition serviceDefinition) in /opt/vsts/work/1/s/src/SwaggerModeler.cs:line 106
   at AutoRest.Modeler.Program.<ProcessInternal>d__2.MoveNext() in /opt/vsts/work/1/s/src/Program.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NewPlugin.<Process>d__15.MoveNext()
FATAL: java/imodeler1 - FAILED
FATAL: Error: Plugin imodeler1 reported failure.
Process() cancelled due to exception : Plugin imodeler1 reported failure.
  Error: Plugin imodeler1 reported failure.

```

`autorest --generate-empty-classes --use=@microsoft.azure/autorest.modeler@preview --input-file="F:\some_service\some_service.json" --namespace="some.service.namespace" --csharp --csharp.output-folder="F:\some_service\csharpcodegen\csharp" > autorest-csharp-output.txt 2>&1`
```
AutoRest code generation utility [version: 2.0.4283; node: v8.11.2]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      'C:\Users\epet.REDMOND\.autorest\@microsoft.azure_autorest-core@2.0.4283\node_modules\@microsoft.azure\autorest-core\dist' (2.0.4283)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (preview->2.3.55)
   Loading AutoRest extension '@microsoft.azure/autorest.csharp' (~2.3.79->2.3.80)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.55->2.3.55)
FATAL: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at AutoRest.Modeler.OperationBuilder.<>cDisplayClass13_0.<BuildMethodReturnType>b0(Stack`1 typeStack) in /opt/vsts/work/1/s/src/OperationBuilder.cs:line 376
   at System.Collections.Generic.List1.ForEach(Action1 action)
   at AutoRest.Modeler.OperationBuilder.BuildMethodReturnType(List`1 types, IModelType headerType) in /opt/vsts/work/1/s/src/OperationBuilder.cs:line 369
   at AutoRest.Modeler.OperationBuilder.BuildMethod(HttpMethod httpMethod, String url, String methodName, String methodGroup) in /opt/vsts/work/1/s/src/OperationBuilder.cs:line 197
   at AutoRest.Modeler.SwaggerModeler.BuildMethod(HttpMethod httpMethod, String url, String name, Operation operation) in /opt/vsts/work/1/s/src/SwaggerModeler.cs:line 404
   at AutoRest.Modeler.SwaggerModeler.Build(ServiceDefinition serviceDefinition) in /opt/vsts/work/1/s/src/SwaggerModeler.cs:line 106
   at AutoRest.Modeler.Program.<ProcessInternal>d__2.MoveNext() in /opt/vsts/work/1/s/src/Program.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NewPlugin.<Process>d__15.MoveNext()
FATAL: csharp/imodeler1 - FAILED
FATAL: Error: Plugin imodeler1 reported failure.
Process() cancelled due to exception : Plugin imodeler1 reported failure.
  Error: Plugin imodeler1 reported failure.

```

**Comment by epet** [comment]
@fearthecowboy, is the above enough information for you to go on?

**Comment by fearthecowboy** [comment]
We;re building a new set of generators; bugs in the existing modeler aren't going to get fixed at this point, sorry.
