### ISSUE TITLE
FormatException when initialising HttpClient on MacOs Mojave

### ISSUE THREAD

**Issue by caitchison** [Azure/autorest#3041]
Hello,

I am getting an exception when my application starts up using a KeyVault to retrieve some configuration values. The exception is inside the ServiceClient InitializeHttpClient function. It is attempting to create a UserAgent value and so interrogating the underlying OS to try and get the OsVersion. On my Mac Mojave that is returning the below string as a headerValue.

`Darwin18.2.0DarwinKernelVersion18.2.0FriOct5194149PDT2018rootxnu-4903.221.22/RELEASE_X86_64`

The Exception detail is below:

`System.FormatException: The format of value 'Darwin18.2.0DarwinKernelVersion18.2.0FriOct5194149PDT2018rootxnu-4903.221.22/RELEASE_X86_64' is invalid.
  at at System.Net.Http.Headers.HeaderUtilities.CheckValidToken(String value, String parameterName)
  at at System.Net.Http.Headers.ProductHeaderValue..ctor(String name, String version)
  at at System.Net.Http.Headers.ProductInfoHeaderValue..ctor(String productName, String productVersion)
  at at Microsoft.Rest.ServiceClient``1.UpdateDefaultUserAgentList(String headerName, String headerValue)
  at at Microsoft.Rest.ServiceClient``1.get_DefaultUserAgentInfoList()
  at at Microsoft.Rest.ServiceClient``1.InitializeHttpClient(HttpClient httpClient, HttpClientHandler httpClientHandler, DelegatingHandler[] handlers)
  at at Microsoft.Rest.ServiceClient``1..ctor(HttpClient serviceHttpClient, HttpClientHandler rootHandler, Boolean disposeHttpClient, DelegatingHandler[] delHandlers)
  at at Microsoft.Rest.ServiceClient``1..ctor(DelegatingHandler[] handlers)
  at at Microsoft.Azure.KeyVault.KeyVaultClient..ctor(DelegatingHandler[] handlers)
  at at Microsoft.Azure.KeyVault.KeyVaultClient..ctor(ServiceClientCredentials credentials, DelegatingHandler[] handlers)
  at at Microsoft.Azure.KeyVault.KeyVaultClient..ctor(AuthenticationCallback authenticationCallback, DelegatingHandler[] handlers)
  at CEADS.Admin.Web.Program.<>c__DisplayClass2_0.<CreateWebHostBuilder>b__1(IConfigurationBuilder c) in /Users/chrisaitchison/dataservices/admin/src/CEADS.Admin.Web/Program.cs:37
  at at Microsoft.AspNetCore.Hosting.WebHostBuilderExtensions.<>c__DisplayClass5_0.<ConfigureAppConfiguration>b__0(WebHostBuilderContext context, IConfigurationBuilder builder)
  at at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
  at at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
  at CEADS.Admin.Web.Program.Main(String[] args) in /Users/chrisaitchison/dataservices/admin/src/CEADS.Admin.Web/Program.cs:21
`

I am using Microsoft.Azure.KeyVault 3.0.1, which is using Microsoft.Rest.ClientRuntime 2.3.17

I have also created a duplicate of this issue in the Azure SDK for net repo as I am not sure where it should go. azure/azure-sdk-for-net#4994

Am I doing something wrong? 

Thanks,
Chris

**Comment by caitchison** [comment]
I found that if I downgrade the Microsoft.Rest.ClientRuntime Nuget package to 2.3.12 (It may work with a later version still, but not the latest) then this issue does not occur.

**Comment by nbuchert** [comment]
Thanks, I had the same problem, and downgrading to 2.3.12 worked for me as well.
I tried one of the newer versions, but that didn't work. Also, I had to uninstall Microsoft.Azure.KeyVault and downgrade this as well to 3.0.0, as it wouldn't install when I selected the 3.0.1 version.

**Comment by caitchison** [comment]
I see that 2.3.18 has been released and fixes this issue for me.
