### ISSUE TITLE
produces text/csv causes KeyNotFoundException (requires schema models a stream/binary data)

### ISSUE THREAD

**Issue by Sebbs128** [Azure/autorest#3055]
While attempting to generate a client library for the Visual Studio App Center Client, using `autorest --input-file=https://api.appcenter.ms/preview/swagger.json --csharp` I get the following error

```
FATAL: System.Collections.Generic.KeyNotFoundException: The 'produces' of 'devices_listCsvFormat' requires that schema 'ErrorDetails' models a stream/binary data (e.g. 'type: string, format: binary'), however 'ErrorDetails' is an object schema (which would require 'produces' of 'application/json' or 'application/xml'). Please adjust either the 'produces' or the response schema to match your service's behavior.
   at AutoRest.Modeler.OperationBuilder.VerifyFirstPropertyIsByteArray(Method method, CompositeType serviceType) in /opt/vsts/work/1/s/src/OperationBuilder.cs:line 440
   at AutoRest.Modeler.OperationBuilder.TryBuildStreamResponse(HttpStatusCode responseStatusCode, OperationResponse response, Method method, List`1 types, IModelType headerType) in /opt/vsts/work/1/s/src/OperationBuilder.cs:line 422
   at AutoRest.Modeler.OperationBuilder.BuildResponses(Method method, CompositeType headerType) in /opt/vsts/work/1/s/src/OperationBuilder.cs:line 336
   at AutoRest.Modeler.OperationBuilder.BuildMethod(HttpMethod httpMethod, String url, String methodName, String methodGroup) in /opt/vsts/work/1/s/src/OperationBuilder.cs:line 195
   at AutoRest.Modeler.SwaggerModeler.BuildMethod(HttpMethod httpMethod, String url, String name, Operation operation) in /opt/vsts/work/1/s/src/SwaggerModeler.cs:line 404
   at AutoRest.Modeler.SwaggerModeler.Build(ServiceDefinition serviceDefinition) in /opt/vsts/work/1/s/src/SwaggerModeler.cs:line 106
   at AutoRest.Modeler.Program.<ProcessInternal>d__2.MoveNext() in /opt/vsts/work/1/s/src/Program.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NewPlugin.<Process>d__15.MoveNext()
FATAL: csharp/imodeler1 - FAILED
FATAL: Error: Plugin imodeler1 reported failure.
Process() cancelled due to exception : Plugin imodeler1 reported failure.
  Error: Plugin imodeler1 reported failure.
```

This seems similar to #2008 as the cause appears to be same: not being able to handle `"produces": [ "text/csv" ]`. The offending section from https://api.appcenter.ms/preview/swagger.json is

```javascript
"/v0.1/apps/{owner_name}/{app_name}/distribution_groups/{distribution_group_name}/devices/download_devices_list": {
      "get": {
        "operationId": "devices_listCsvFormat",
        "description": "Returns all devices associated with the given distribution group.",
        "parameters": [
          {
            "name": "distribution_group_name",
            "type": "string",
            "in": "path",
            "description": "The name of the distribution group.",
            "required": true
          },
          {
            "name": "unprovisioned_only",
            "type": "boolean",
            "in": "query",
            "description": "when true, filters out provisioned devices",
            "default": false
          },
          {
            "name": "udids",
            "type": "array",
            "in": "query",
            "description": "multiple UDIDs which should be part of the resulting CSV.",
            "items": {
              "type": "string"
            },
            "collectionFormat": "csv"
          },
          {
            "$ref": "#/parameters/owner_name"
          },
          {
            "$ref": "#/parameters/app_name"
          }
        ],
        "produces": [
          "text/csv"
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "400": {
            "description": "<b>bad_request</b>: Devices information can only be requested for iOS apps.\n",
            "schema": {
              "$ref": "#/definitions/ErrorDetails"
            }
          },
          "404": {
            "description": "<b>not_found</b>: A distribution group can't be found.\n",
            "schema": {
              "$ref": "#/definitions/ErrorDetails"
            }
          },
          "500": {
            "description": "An internal error.",
            "schema": {
              "$ref": "#/definitions/ErrorDetails"
            }
          }
        },
        "security": [
          {
            "APIToken": []
          }
        ],
        "tags": [
          "distribute"
        ]
      }
    },
```

**Comment by fearthecowboy** [comment]
AutoRest doesn't have support for Response body models as `"text/csv"` -- there really isn't enough data to know how to generate deserialization code for that sort of thing. 

Model Schema definitions (ie `ErrorDetails` ) in swagger represent JSON or XML payloads.  Anything else is left to the consumer as a stream.  (in which case it should be modeled as a stream an not a Object)

**Comment by Sebbs128** [comment]
Ok, that's fair enough if AutoRest isn't intended to support those Response body models.

In these cases, would it be a better option for AutoRest to do one of the following, instead of throwing a fatal error?

- Skip/ignore the operation and display a relevant message
- Automatically model as a stream (and, likely with a relevant message displayed)

As it is, a user encountering this for the first time might be left wondering if there is some larger problem with the swagger schema, rather than AutoRest just lacking support for a type.

**Comment by S-Tasker** [comment]
I completely agree that it should instead fail less fatally. By all means display a warning, perhaps even generate a blank class.

**Comment by mswilson4040** [comment]
I agree with @Sebbs128, it should just auto-skip those. I don't want to have to remember all the different things I had to modify in my 20k lines of json/swagger only to go through the same headache on an updated file.
