### ISSUE TITLE
Autorest for zipkin not working

### ISSUE THREAD

**Issue by AceHack** [Azure/autorest#3182]
https://zipkin.io/zipkin-api/zipkin2-api.yaml

FATAL: OperationId is required for all operations. Please add it for 'get' operation of '/services' path.
FATAL: AutoRest.Core.Logging.CodeGenerationException: OperationId is required for all operations. Please add it for 'get' operation of '/services' path.
   at AutoRest.Modeler.SwaggerModeler.Build(ServiceDefinition serviceDefinition) in /opt/vsts/work/1/s/src/SwaggerModeler.cs:line 96
   at AutoRest.Modeler.Program.<ProcessInternal>d__2.MoveNext() in /opt/vsts/work/1/s/src/Program.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NewPlugin.<Process>d__15.MoveNext()
FATAL: csharp/imodeler1 - FAILED
FATAL: Error: Plugin imodeler1 reported failure.
Process() cancelled due to exception : Plugin imodeler1 reported failure.
  Error: Plugin imodeler1 reported failure.

**Comment by fearthecowboy** [comment]
Read the error.

An `operationId` is required for all operations; AutoRest uses that to create method names.

**Comment by AceHack** [comment]
Can you give me an example from the yaml above?  I know nothing about swagger.

**Comment by MiYanni** [comment]
Basic misuse of swagger. Closing.
