### ISSUE TITLE
JSON parsing error when default value is array of string

### ISSUE THREAD

**Issue by hendrytl** [Azure/autorest#3188]
I have a property that is an array of strings, with a default value specified: 
"HistoryConfiguration": {
      "type": "object",
      "properties": {
        "directoriesToWatch": {
          "description": "The list of directories to monitor and upload files from.",
          **"default": [
            "logs"
          ],**
          "uniqueItems": false,
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "additionalProperties": {
        "type": "object"
      }
When I try to run the azure validator `autorest --input-file=swagger.json --azure-validator=true --openapi-type=data-plane`
The following exception is thrown:
   Loading AutoRest core      'C:\Users\toddhen\.autorest\@microsoft.azure_autorest-core@2.0.4300\node_modules\@microsoft.azure\autorest-core\dist' (2.0.4300)
   Loading AutoRest extension '@microsoft.azure/classic-openapi-validator' (~1.0.9->1.0.14)
   Loading AutoRest extension '@microsoft.azure/openapi-validator' (~1.0.2->1.0.4)
FATAL: Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: [. Path 'properties.directoriesToWatch.default', line 10, position 18.
   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsString()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
...
Full swagger file is in attached zip file.
[Swagger.zip](https://github.com/Azure/autorest/files/2984301/Swagger.zip)

**Comment by KeMicrosoft** [comment]
any updates?

**Comment by hendrytl** [comment]
Hi Ke,
In order to work around this issue, I have added a schema filter that excludes the default value when it is of this type.  Still hoping this issue gets addressed and the work-around can be removed.

**Comment by KeMicrosoft** [comment]
Got it, thank you.

**Comment by fearthecowboy** [comment]
I'll add this to the list of tests to update for autorest 3.0
