### ISSUE TITLE
Go Code Generator fails with Preview subdirectory failure

### ISSUE THREAD

**Issue by joerob-msft** [Azure/autorest#3191]
I'm running autorest to generate the Go sdk. Previously this worked, but I renamed some files and now it fails with an error about preview. Can you help?

 autorest ./specification/tokenstore/resource-manager/readme.md --go --go-sdk-folder=c:/temp/azure-sdk-for-go --multiapi --preview-chk --use=@microsoft.azure/autorest.go@~2.1.127 --use-onever --verbose

PS C:\github\azure-rest-api-specs-pr> autorest ./specification/tokenstore/resource-manager/readme.md --go --go-sdk-folder=c:/temp/azure-sdk-for-go --multiapi --preview-chk --use=@microsoft.azure/autorest.go@~2.1.127 --use-onever --verbose
AutoRest code generation utility [version: 2.0.4283; node: v10.15.1]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      'C:\Users\joerob\.autorest\@microsoft.azure_autorest-core@2.0.4302\node_modules\@microsoft.azure\autorest-core\dist' (2.0.4302)
   Loading AutoRest extension '@microsoft.azure/autorest.go' (~2.1.127->2.1.127)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.38->2.3.38)
Processing batch task - {"tag":"package-2018-08-01-preview"} .
FATAL: System.InvalidOperationException: codegen for preview swagger Microsoft.Token/preview/2018-08-01-preview/TokenStore.json must be under a preview subdirectory
   at AutoRest.Go.CodeGeneratorGo.<Generate>d__6.MoveNext() in /home/vsts/work/1/s/src/CodeGeneratorGo.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AutoRest.Go.Program.<ProcessInternal>d__3.MoveNext() in /home/vsts/work/1/s/src/Program.cs:line 107
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NewPlugin.<Process>d__20.MoveNext() in /home/vsts/work/1/s/autorest.common/src/Plugins/NewPlugin.cs:line 163
FATAL: go/generate - FAILED
FATAL: Error: Plugin go reported failure.
Process() cancelled due to exception : Plugin go reported failure.
Failure during batch task - {"tag":"package-2018-08-01-preview"} -- Error: Plugin go reported failure..
  Error: Plugin go reported failure.

**Comment by joerob-msft** [comment]
I was able to fix this with help of @jhendrixMSFT 
The output-folder had to have a subdirectory of preview included in the path
