### ISSUE TITLE
[v3 Beta] No such file or directory "...\dist\static_modules.fs" 

### ISSUE THREAD

**Issue by dantheman999301** [Azure/autorest#3249]
```
AutoRest code generation utility [version: 3.0.5197; node: v10.15.3, max-memory: 8192 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
{ Error: ENOENT: no such file or directory, stat 'C:\Users\daniel.edwards\node_modules\@microsoft.azure\autorest-core\dist\static_modules.fs'
    at Object.statSync (fs.js:850:3)
    at new StaticVolumeFile (C:\Users\daniel.edwards\AppData\Roaming\npm\node_modules\autorest\dist\static-loader.js:1:6192)
    at StaticFilesystem.load (C:\Users\daniel.edwards\AppData\Roaming\npm\node_modules\autorest\dist\static-loader.js:1:8756)
    at Object.load (C:\Users\daniel.edwards\node_modules\@microsoft.azure\autorest-core\dist\static-loader.js:1:4332)
    at Object.<anonymous> (C:\Users\daniel.edwards\node_modules\@microsoft.azure\autorest-core\entrypoints\app.js:5:56)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (C:\Users\daniel.edwards\AppData\Roaming\npm\node_modules\autorest\dist\static-loader.js:1:18665)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.tryRequire (C:\Users\daniel.edwards\AppData\Roaming\npm\node_modules\autorest\dist\autorest-as-a-service.js:75:20)
  errno: -4058,
  syscall: 'stat',
  code: 'ENOENT',
  path:
   'C:\\Users\\daniel.edwards\\node_modules\\@microsoft.azure\\autorest-core\\dist\\static_modules.fs' }
```

Think I've tried a few different beta versions now but keep running into this. Uninstalled and reinstalled a few times with no luck. Any help appreciated.

**Comment by fearthecowboy** [comment]
do an `autorest -reset ` -- looks like a plugin is corrupt.

**Comment by dantheman999301** [comment]
Gave that another go, didn't work but did prompt me to try go through the start up again.

What I didn't do was install DotNetSdk through NPM (although I did have a version greater than 2.1 installed on the machine).

Installing it through NPM fixed that for whatever reason. Not sure if the documentation needs updating in this case as I had both 2.1 and 2.2 installed but unless you do the install through NPM, doesn't seem to work.

**Comment by dantheman999301** [comment]
Tried that and unfortunately did not work.

**Comment by fearthecowboy** [comment]
does the file `'C:\Users\daniel.edwards\node_modules\@microsoft.azure\autorest-core\dist\static_modules.fs'` exist?

**Comment by dantheman999301** [comment]
No.

Folder looks like this:
![image](https://user-images.githubusercontent.com/9741849/58004232-aae36800-7ada-11e9-8f17-98bb6983e303.png)

**Comment by fearthecowboy** [comment]
Wait. Why do you even have a `node_modules` in `C:\Users\daniel.edwards\` ? 

Remove the folder `C:\Users\daniel.edwards\node_modules\` completely , that shouldn't be there. 

And remove '`C:\Users\daniel.edwards\.autorest' too, just to make sure it's starting clean.

**Comment by dantheman999301** [comment]
OK so completely uninstalled everything I could find, deleted the whole `node_module` folder in the user directory, deleted autorest from `Roaming`, and deleted `.autorest` folder.

Reinstalled.

```
> autorest@3.0.5199 preinstall C:\Users\daniel.edwards\AppData\Roaming\npm\node_modules\autorest
> node ./.scripts/preinstall-check

C:\Users\daniel.edwards\AppData\Roaming\npm\autorest -> C:\Users\daniel.edwards\AppData\Roaming\npm\node_modules\autorest\entrypoints\app.js
+ autorest@3.0.5199
updated 1 package in 0.86s
```

Ran `autorest --input-file:https://myapi.com/swagger/openapi.json --csharp`

Then it just kind of sat there before finally getting the output.

```
AutoRest code generation utility [version: 3.0.5199; node: v10.15.3, max-memory: 8192 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
Failure:
Error: Unable to start AutoRest Core from C:\Users\daniel.edwards\.autorest\@microsoft.azure_autorest-core@3.0.5452\node_modules\@microsoft.azure\autorest-core
Error: Unable to start AutoRest Core from C:\Users\daniel.edwards\.autorest\@microsoft.azure_autorest-core@3.0.5452\node_modules\@microsoft.azure\autorest-core
    at main (C:\Users\daniel.edwards\AppData\Roaming\npm\node_modules\autorest\dist\app.js:230:19)
```

As soon as I run that command `node_modules` folder appears again in the user directory. In the `.autorest` directory, there is a folder but no files.

I'm a bit stumped in all honesty, I'm guessing I have something set somewhere that is causing this to happen but I can't think what. On my personal machine at home, the instructions work fine, so I know it's something specific to my work machine.

**Comment by fearthecowboy** [comment]
New AutoRest v3 beta builds -- try installing:

`npm install  -g @autorest/autorest` 

and then run 

`autorest-beta --reset `

If that's still not working, ... are you behind a corporate proxy?

**Comment by fenrix** [comment]
Hi
I don't  know if this still an issue
I happen to stumble on this problem today, I think it maybe when you run npm your permission not allow to create file on that folder so I do this

1. Run powershell as admin
2. npm install -g @autorest/autorest (reinstall)

And static_modules.fs is being create there and everything work fine now

**Comment by dantheman999301** [comment]
@fearthecowboy @fenrix 

Gave this another go.

Followed the instructions and tried with the `petstore.yaml`.

First time run you get:

```
autorest --input-file=petstore.yaml --csharp --output-folder=CSharp_PetStore --namespace=PetStore
AutoRest code generation utility [version: 3.0.5199; node: v10.16.3, max-memory: 8192 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      'C:\Users\daniel.edwards\node_modules\@microsoft.azure\autorest-core\dist' (3.0.5452)
   Installing AutoRest extension '@microsoft.azure/autorest.csharp' (~2.3.79)
Failed to install or start extension '@microsoft.azure/autorest.csharp' (~2.3.79)
  Error: Package '@microsoft.azure/autorest.csharp' - '2.3.82' failed to install:
  Failed to install package 'https://registry.npmjs.org/@microsoft.azure/autorest.csharp/-/autorest.csharp-2.3.82.tgz' -- Error: Process Failed.Error: Failed to install package 'https://registry.npmjs.org/@microsoft.azure/autorest.csharp/-/autorest.csharp-2.3.82.tgz' -- Error: Process Failed.
    at install (/node_modules/@microsoft.azure/extension/dist/main.js:303:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

And then back to this when you run again:
```
AutoRest code generation utility [version: 3.0.5199; node: v10.16.3, max-memory: 8192 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
{ Error: ENOENT: no such file or directory, stat 'C:\Users\daniel.edwards\node_modules\@microsoft.azure\autorest-core\dist\static_modules.fs'
    at Object.statSync (fs.js:855:3)
    at new StaticVolumeFile (C:\Users\daniel.edwards\AppData\Roaming\npm\node_modules\autorest\dist\static-loader.js:1:6130)
    at StaticFilesystem.load (C:\Users\daniel.edwards\AppData\Roaming\npm\node_modules\autorest\dist\static-loader.js:1:8694)
    at Object.load (C:\Users\daniel.edwards\node_modules\@microsoft.azure\autorest-core\dist\static-loader.js:1:4270)
    at Object.<anonymous> (C:\Users\daniel.edwards\node_modules\@microsoft.azure\autorest-core\entrypoints\app.js:5:56)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (C:\Users\daniel.edwards\AppData\Roaming\npm\node_modules\autorest\dist\static-loader.js:1:18603)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.tryRequire (C:\Users\daniel.edwards\AppData\Roaming\npm\node_modules\autorest\dist\autorest-as-a-service.js:75:20)
  errno: -4058,
  syscall: 'stat',
  code: 'ENOENT',
  path:
   'C:\\Users\\daniel.edwards\\node_modules\\@microsoft.azure\\autorest-core\\dist\\static_modules.fs' }
```

**Comment by fearthecowboy** [comment]
use `autorest-beta` as the command. you have a really old `autorest` beta 
``` bash 
npm uninstall -g autorest
npm install -g @autorest/autorest
```

**Comment by nickzhums** [comment]
@fearthecowboy 
I am having this exact same issue
I removed the old autorest using **npm uninstall -g autorest**
and did **npm install -g @autorest/autorest**

When i did  **autorest-beta --help**

I get the following:


Error: ENOENT: no such file or directory, stat 'C:\Users\littl\node_modules\@autorest\core\dist\static_modules.fs'
    at Object.statSync (fs.js:915:3)
    at new StaticVolumeFile (C:\Users\littl\AppData\Roaming\npm\node_modules\@autorest\autorest\dist\static-loader.js:1:7081)
    at exports.StaticFilesystem.load (C:\Users\littl\AppData\Roaming\npm\node_modules\@autorest\autorest\dist\static-loader.js:1:9730)
    at Object.load (C:\Users\littl\node_modules\@autorest\core\dist\static-loader.js:1:5187)
    at Object.<anonymous> (C:\Users\littl\node_modules\@autorest\core\entrypoints\app.js:5:56)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (C:\Users\littl\AppData\Roaming\npm\node_modules\@autorest\autorest\dist\static-loader.js:1:19423)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19) {
  errno: -4058,
  syscall: 'stat',
  code: 'ENOENT',
  path: 'C:\\Users\\littl\\node_modules\\@autorest\\core\\dist\\static_modules.fs'
