### ISSUE TITLE
[TypeScript Client Codegen] TypeError: Invalid Version: 2 

### ISSUE THREAD

**Issue by spallister** [Azure/autorest#3296]
Hi There,

I've previously used swagger-codegen together with OAS 2.0 (via Swashbuckle.AspNetCore), however, am now trying to evaluate autorest upon updating to Swashbuckle.AspNetCore v5.0.0-rc2, which supports OAS 3.0.

Upon initially installing autorest and attempting to generate a TypeScript client, I received a message saying something to the effect that only OAS 2.0 is supported.  I then noticed that I should be able to use the autorest@beta release to consume OAS 3.0.  While doing so resolved the "only OAS 2.0 is supported" error message I came across, I am now getting the following error message upon attempting to run `autorest --input-file=http://localhost:8014/swagger/v2/swagger.json --debug`:

`Process() cancelled due to exception : Invalid Version: 2 / TypeError: Invalid Version: 2`

The above error message was extracted from the following debug output:

```
DEBUG [2.51 s]: openapi-document/profile-filter - START inputs = 1
DEBUG [2.51 s]: openapi-document/profile-filter - END [0 s]
DEBUG [2.51 s]: openapi-document/model-deduplicator - START inputs = 1
DEBUG [2.51 s]: openapi-document/emitter - START inputs = 1
DEBUG [2.52 s]: openapi-document/emitter - END [0.01 s]
DEBUG [2.63 s]: openapi-document/model-deduplicator - END [0.12 s]
DEBUG [2.64 s]: openapi-document/compose - START inputs = 1
C:\Users\******\.autorest\@microsoft.azure_autorest-core@3.0.5534\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\pipeline.js - FAILURE {}
Process() cancelled due to exception : Invalid Version: 2 / TypeError: Invalid Version: 2
    at new SemVer (/node_modules/semver/semver.js:323:11)
    at compare (/node_modules/semver/semver.js:614:10)
    at Function.gt (/node_modules/semver/semver.js:643:10)
    at gt (/node_modules/@microsoft.azure/codegen/dist/apiversion.js:70:19)
    at highest (/node_modules/@microsoft.azure/codegen/dist/apiversion.js:78:12)
    at Object.maximum (/node_modules/@microsoft.azure/codegen/dist/apiversion.js:98:18)
    at codegen_2.values.linq.toArray.sort (C:\Users\******\.autorest\@microsoft.azure_autorest-core@3.0.5534\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\plugins\new-composer.js:329:74)
    at Array.sort (native)
    at NewComposer.visitSchemas (C:\Users\******\.autorest\@microsoft.azure_autorest-core@3.0.5534\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\plugins\new-composer.js:329:14)
    at NewComposer.visitComponents (C:\Users\******\.autorest\@microsoft.azure_autorest-core@3.0.5534\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\plugins\new-composer.js:376:26)
    at NewComposer.process (C:\Users\******\.autorest\@microsoft.azure_autorest-core@3.0.5534\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\plugins\new-composer.js:107:26)
    at NewComposer.runProcess (/node_modules/@microsoft.azure/datastore/dist/processor.js:76:28)
  TypeError: Invalid Version: 2
[2.67 s] Shutting Down.
[2.67 s] Exiting.
```

It's suspicious to me that when I look in the `C:\Users\******\.autorest` folder, I see the following:
- @microsoft.azure_autorest.modeler@2.3.51
- @microsoft.azure_autorest.typescript@2.0.683
- @microsoft.azure_autorest-core@3.0.5534

While it makes sense to be that I'm seeing v3.0.5534 for `autorest-core` since I installed autorest@beta, I'm surprised to see v2.0.683 for `autorest.typescript` since it looks like that package is 9 months old, and the latest version in the npm registry is v4.2.2.

Is the "Invalid Version: 2" message that I'm seeing in anyway related to the fact that a v2 autorest.typescript package is being installed alongside autorest-core@3.0.5534?  Otherwise, would you be able to point in the right direction to resolve this issue, and successfully generate a TypeScript client using autorest@beta together with OAS 3.0?

Thanks for your help!

Sean

**Comment by spallister** [comment]
Hey @alsami - Thanks for the heads-up!  That does indeed fix the issue for me.
