### ISSUE TITLE
autorest-beta doesn't set correct exit code in case of failure.

### ISSUE THREAD

**Issue by pakrym** [Azure/autorest#3337]
```
>>> autorest-beta .\samples\Xkcd\readme.md --version=3.0.6132

WARNING: AutoRest has not been tested with Node versions greater than v10.

AutoRest code generation utility [version: 3.0.6122; node: v12.13.0, max-memory: 8192 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      'C:\Users\pakrym\.autorest\@autorest_core@3.0.6132\node_modules\@autorest\core\dist' (3.0.6132)
   Installing AutoRest extension '@autorest/csharp-v3' (file:///D:/github/azure/autorest.csharp/samples/../)
Failed to install or start extension '@autorest/csharp-v3' (file:///D:/github/azure/autorest.csharp/samples/../)
  Error: Package '@autorest/csharp-v3' - '' failed to install:
  Failed to install package 'D:/github/azure/autorest.csharp/samples/../' -- Error: Process Failed.Error: Failed to install package 'D:/github/azure/autorest.csharp/samples/../' -- Error: Process Failed.
    at install (/node_modules/@azure-tools/extension/dist/main.js:307:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ExtensionManager.installPackage (/node_modules/@azure-tools/extension/dist/main.js:485:13)
    at async resolveExtensions (C:\Users\pakrym\.autorest\@autorest_core@3.0.6132\node_modules\@autorest\core\dist\lib\configuration.js:842:55)
    at async Configuration.CreateView (C:\Users\pakrym\.autorest\@autorest_core@3.0.6132\node_modules\@autorest\core\dist\lib\configuration.js:883:9)
    at async AutoRest.RegenerateView (C:\Users\pakrym\.autorest\@autorest_core@3.0.6132\node_modules\@autorest\core\dist\lib\autorest-core.js:66:29)
    at async currentMain (C:\Users\pakrym\.autorest\@autorest_core@3.0.6132\node_modules\@autorest\core\dist\app.js:305:21)
    at async mainImpl (C:\Users\pakrym\.autorest\@autorest_core@3.0.6132\node_modules\@autorest\core\dist\app.js:507:20)
    at async main (C:\Users\pakrym\.autorest\@autorest_core@3.0.6132\node_modules\@autorest\core\dist\app.js:538:20)
>>> $LASTEXITCODE
0
```

**Comment by pakrym** [comment]
cc @fearthecowboy

**Comment by fearthecowboy** [comment]
can't repro now
