### ISSUE TITLE
Autorest v3 doesn't support url anymore

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest#3353]
autorest-beta --use=D:\VSProjects\autorest.python.v3 --add-crentials --payload-flattening-threshold=2 --namespace=azure.cognitiveservices.language.textanalytics --package-name=azure-cognitiveservices-language-textanalytics --no-namespace-folders ---clear-output-folder --output-folder=TextAnalytics --input-file https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/cognitiveservices/data-plane/TextAnalytics/stable/v2.1/TextAnalytics.json --debug
AutoRest code generation utility [version: 3.0.6116; node: v10.15.3, max-memory: 8192 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
Network Enabled: true
Starting @autorest/core from C:\Users\lmazuel\.autorest\@autorest_core@3.0.6139
   Loading AutoRest core      'C:\Users\lmazuel\.autorest\@autorest_core@3.0.6139\node_modules\@autorest\core\dist' (3.0.6139)
   Loading local AutoRest extension '@autorest/python' (D:\VSProjects\autorest.python.v3)
   Loading AutoRest extension '@autorest/modelerfour' (~4.1.56->4.1.60)
Process() cancelled due to exception : path.match is not a function / TypeError: path.match is not a function
    at isAbsolute (/node_modules/@azure-tools/uri/dist/main.js:77:19)
    at Object.ResolveUri (/node_modules/@azure-tools/uri/dist/main.js:159:9)
    at ConfigurationView.ResolveAsPath (C:\Users\lmazuel\.autorest\@autorest_core@3.0.6139\node_modules\@autorest\core\dist\lib\configuration.js:246:22)
    at linq_es2015_1.From.Select.each (C:\Users\lmazuel\.autorest\@autorest_core@3.0.6139\node_modules\@autorest\core\dist\lib\configuration.js:341:34)
    at EnumerableImpl.Select [as _factory] (/node_modules/linq-es2015/lib/generators.js:29:15)
    at Select.next (<anonymous>)
    at EnumerableImpl.ToArray (/node_modules/linq-es2015/lib/linq.js:372:18)
    at ConfigurationView.get InputFileUris [as InputFileUris] (C:\Users\lmazuel\.autorest\@autorest_core@3.0.6139\node_modules\@autorest\core\dist\lib\configuration.js:342:14)
    at Object.get (C:\Users\lmazuel\.autorest\@autorest_core@3.0.6139\node_modules\@autorest\core\dist\lib\configuration.js:233:82)
    at processInternal (C:\Users\lmazuel\.autorest\@autorest_core@3.0.6139\node_modules\@autorest\core\dist\lib\autorest-core.js:103:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  TypeError: path.match is not a function
[3.98 s] Shutting Down.
[3.98 s] Exiting.

**Comment by lmazuel** [comment]
Nevermind, there was a missing = in my line after input-file :p
