### ISSUE TITLE
Error parsing swagger file in autorest v3.0

### ISSUE THREAD

**Issue by shurd** [Azure/autorest#3392]
I am attempting to generate a python SDK from the swagger file added in this pull request: https://github.com/Azure/azure-rest-api-specs/pull/8151, but I am getting an error when parsing the file. I am using autorest-beta. The full debug command and output are included below.

autorest-beta --credential-scopes=https://storage.azure.com/.default --tag=package-2018-10 --python-sdks-folder="C:\tablesGenerated" --python --use=https://github.com/Azure/autorest.python/releases/download/v5.0.0_20200123/autorest-python-5.0.0-20200123.tgz --debug

AutoRest code generation utility [cli version: 3.0.6163; node: v10.13.0, max-memory: 8192 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
Network Enabled: true
Starting @autorest/core from C:\Users\sahurd\.autorest\@autorest_core@3.0.6198
NOTE: AutoRest core version selected from configuration: 3.0.6187.
   Loading AutoRest core      'C:\Users\sahurd\.autorest\@autorest_core@3.0.6187\node_modules\@autorest\core\dist' (3.0.6187)
   Loading AutoRest extension '@autorest/python' (https://github.com/Azure/autorest.python/releases/download/v5.0.0_20200123/autorest-python-5.0.0-20200123.tgz->5.0.0)
   Loading AutoRest extension '@autorest/modelerfour' (4.3.142->4.3.142)
DEBUG [53.4 s]: swagger-document/loader-swagger - START inputs = 0
DEBUG [53.4 s]: openapi-document-override/md-override-loader-openapi - START inputs = 0
DEBUG [53.4 s]: openapi-document/loader-openapi - START inputs = 0
DEBUG [53.41 s]: swagger-document-override/md-override-loader-swagger - START inputs = 0
DEBUG [53.41 s]: pipeline-emitter - START inputs = 0
DEBUG [53.47 s]: configuration-emitter - START inputs = 0
DEBUG [53.51 s]: pipeline-emitter - END [0.11 s]
DEBUG [53.51 s]: configuration-emitter - END [0.11 s]
DEBUG [53.59 s]: openapi-document-override/md-override-loader-openapi - END [0.19 s]
DEBUG [53.59 s]: swagger-document-override/md-override-loader-swagger - END [0.19 s]
DEBUG [53.61 s]: openapi-document/loader-openapi - END [0.21 s]
DEBUG [53.61 s]: openapi-document/individual/transform - SKIPPING
DEBUG [53.62 s]: openapi-document/individual/schema-validator-openapi - SKIPPING
DEBUG [53.62 s]: openapi-document/individual/identity - SKIPPING
DEBUG [53.63 s]: openapi-document/transform-immediate - START inputs = 1
DEBUG [53.63 s]: openapi-document/transform-immediate - END [0 s]
DEBUG [53.72 s]: swagger-document/loader-swagger - END [0.32 s]
DEBUG [53.73 s]: swagger-document/individual/transform - START inputs = 1
DEBUG [53.76 s]: swagger-document/individual/transform - END [0.03 s]
DEBUG [53.76 s]: swagger-document/individual/schema-validator-swagger - START inputs = 1
DEBUG [53.82 s]: swagger-document/individual/schema-validator-swagger - END [0.06 s]
DEBUG [53.82 s]: swagger-document/identity - START inputs = 1
DEBUG [53.83 s]: swagger-document/individual/identity - START inputs = 1
DEBUG [53.83 s]: swagger-document/identity - END [0 s]
DEBUG [53.83 s]: swagger-document/individual/identity - END [0 s]
DEBUG [53.83 s]: openapi-document/openapi-document-converter - START inputs = 1
DEBUG [53.88 s]: openapi-document/openapi-document-converter - END [0.05 s]
DEBUG [53.89 s]: openapi-document/transform - START inputs = 2
DEBUG [53.9 s]: openapi-document/transform - END [0.01 s]
DEBUG [53.9 s]: openapi-document/allof-cleaner - START inputs = 1
DEBUG [53.9 s]: openapi-document/allof-cleaner - END [0 s]
DEBUG [53.91 s]: openapi-document/tree-shaker - START inputs = 1
C:\Users\sahurd\.autorest\@autorest_core@3.0.6187\node_modules\@autorest\core\dist\lib\pipeline\pipeline.js - FAILURE {"exitCode":1}
Process() cancelled due to exception : Collision detected inserting into object: description / Error: Collision detected inserting into object: description
    at Object.set (/node_modules/@azure-tools/datastore/dist/graph-builder.js:45:23)
    at OAI3Shaker.clone (/node_modules/@azure-tools/datastore/dist/processor.js:62:31)
    at OAI3Shaker.visitResponse (C:\Users\sahurd\.autorest\@autorest_core@3.0.6187\node_modules\@autorest\core\dist\lib\pipeline\plugins\tree-shaker.js:432:26)
    at OAI3Shaker.dereference (C:\Users\sahurd\.autorest\@autorest_core@3.0.6187\node_modules\@autorest\core\dist\lib\pipeline\plugins\tree-shaker.js:518:27)
    at OAI3Shaker.dereferenceItems (C:\Users\sahurd\.autorest\@autorest_core@3.0.6187\node_modules\@autorest\core\dist\lib\pipeline\plugins\tree-shaker.js:378:18)
    at OAI3Shaker.visitHttpOperation (C:\Users\sahurd\.autorest\@autorest_core@3.0.6187\node_modules\@autorest\core\dist\lib\pipeline\plugins\tree-shaker.js:176:26)
    at OAI3Shaker.visitPath (C:\Users\sahurd\.autorest\@autorest_core@3.0.6187\node_modules\@autorest\core\dist\lib\pipeline\plugins\tree-shaker.js:129:26)
    at OAI3Shaker.visitPaths (C:\Users\sahurd\.autorest\@autorest_core@3.0.6187\node_modules\@autorest\core\dist\lib\pipeline\plugins\tree-shaker.js:103:18)
    at OAI3Shaker.process (C:\Users\sahurd\.autorest\@autorest_core@3.0.6187\node_modules\@autorest\core\dist\lib\pipeline\plugins\tree-shaker.js:78:26)
    at OAI3Shaker.runProcess (/node_modules/@azure-tools/datastore/dist/processor.js:76:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  Error: Collision detected inserting into object: description
[53.97 s] Shutting Down.
[53.98 s] Exiting.

**Comment by gsaadeh** [comment]
Having the same error with V3 although I tried validating the swagger file through the editor and all looks good

**Comment by fearthecowboy** [comment]
Fixed in `3.0.6205`+
