### ISSUE TITLE
Error: Plugin imodeler1 reported failure. - KeyNotFoundException

### ISSUE THREAD

**Issue by tazdevilnl** [Azure/autorest#3394]
I get the following error:
```
AutoRest code generation utility [version: 2.0.4413; node: v12.14.1]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
Network Enabled: true
Starting @microsoft.azure/autorest-core from C:\Users\patrickb\.autorest\@microsoft.azure_autorest-core@2.0.4413
   Loading AutoRest core      'C:\Users\patrickb\.autorest\@microsoft.azure_autorest-core@2.0.4413\node_modules\@microsoft.azure\autorest-core\dist' (2.0.4413)
   Installing AutoRest extension '@microsoft.azure/autorest.csharp' (~2.3.79)
   Installing AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.55)
DEBUG: swagger-document-override/md-override-loader - START
DEBUG: swagger-document/loader - START
DEBUG: pipeline-emitter - START
DEBUG: configuration-emitter - START
DEBUG: Emitting 'pipeline' at file:///C:/Source/Villit/Development/Applications/ChipSoft.SelfCare.Communication/src/ChipSoft.SelfCare.Communication.Client/Generated/V1/pipeline
DEBUG: Emitting 'configuration' at file:///C:/Source/Villit/Development/Applications/ChipSoft.SelfCare.Communication/src/ChipSoft.SelfCare.Communication.Client/Generated/V1/configuration
DEBUG: pipeline-emitter - END
DEBUG: configuration-emitter - END
DEBUG: swagger-document-override/md-override-loader - END
DEBUG: swagger-document/loader - END
DEBUG: swagger-document/individual/transform - START
DEBUG: swagger-document/individual/transform - END
DEBUG: swagger-document/individual/schema-validator - START
DEBUG: swagger-document/individual/schema-validator - END
DEBUG: swagger-document/individual/identity - START
DEBUG: swagger-document/individual/identity - END
DEBUG: swagger-document/compose - START
DEBUG: swagger-document/compose - END
DEBUG: swagger-document/transform-immediate - START
DEBUG: swagger-document/transform-immediate - END
DEBUG: swagger-document/transform - START
DEBUG: swagger-document/transform - END
DEBUG: swagger-document/identity - START
DEBUG: swagger-document/identity - END
DEBUG: openapi-document/openapi-document-converter - START
DEBUG: swagger-document/emitter - START
DEBUG: Emitting 'swagger-document' at file:///C:/Source/Villit/Development/Applications/ChipSoft.SelfCare.Communication/src/ChipSoft.SelfCare.Communication.Client/Generated/V1/ChipSoft.SelfCare.Communication.Client.V1
DEBUG: swagger-document/emitter - END
DEBUG: openapi-document/openapi-document-converter - END
DEBUG: openapi-document/transform - START
DEBUG: openapi-document/transform - END
DEBUG: openapi-document/component-modifiers - START
DEBUG: openapi-document/component-modifiers - END
DEBUG: openapi-document/identity - START
DEBUG: openapi-document/identity - END
DEBUG: csharp/imodeler1 - START
DEBUG: openapi-document/emitter - START
DEBUG: openapi-document/emitter - END
node.exe : FATAL: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
At C:\Users\patrickb\AppData\Roaming\npm\autorest.ps1:15 char:3
+   & "node$exe"  "$basedir/node_modules/autorest/dist/app.js" $args
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (FATAL: System.C...the dictionary.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at AutoRest.Modeler.SwaggerModeler.Build(ServiceDefinition serviceDefinition) in /opt/vsts/work/1/s/src/SwaggerModeler.cs:line 142
   at AutoRest.Modeler.Program.<ProcessInternal>d__2.MoveNext() in /opt/vsts/work/1/s/src/Program.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NewPlugin.<Process>d__15.MoveNext()
FATAL: csharp/imodeler1 - FAILED
FATAL: Error: Plugin imodeler1 reported failure.
Process() cancelled due to exception : Plugin imodeler1 reported failure.
  Error: Plugin imodeler1 reported failure.
```

Running the same json file with NSwag I have no issues. I think the issue is with enums

Autorest version 
```
utoRest code generation utility [version: 2.0.4413; node: v12.14.1]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest


Showing All Installed Extensions

 Type       Extension Name                           Version      Location 
 core       @microsoft.azure/autorest-core           2.0.4413     C:\Users\patrickb\.autorest\@microsoft.azure_autorest-core@2.0.4413
 extension  @microsoft.azure/autorest.csharp         2.3.82       C:\Users\patrickb\.autorest\@microsoft.azure_autorest.csharp@2.3.82
 extension  @microsoft.azure/autorest.modeler        2.3.55       C:\Users\patrickb\.autorest\@microsoft.azure_autorest.modeler@2.3.55
```
My json file
[swagger.log](https://github.com/Azure/autorest/files/4134307/swagger.log)

**Comment by tazdevilnl** [comment]
This is my json file
[Communication_V1.log](https://github.com/Azure/autorest/files/4134167/Communication_V1.log)

**Comment by tazdevilnl** [comment]
AutoRest code generation utility [version: 2.0.4413; node: v12.14.1]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest


Showing All Installed Extensions

 Type       Extension Name                           Version      Location 
 core       @microsoft.azure/autorest-core           2.0.4413     C:\Users\patrickb\.autorest\@microsoft.azure_autorest-core@2.0.4413
 extension  @microsoft.azure/autorest.csharp         2.3.82       C:\Users\patrickb\.autorest\@microsoft.azure_autorest.csharp@2.3.82
 extension  @microsoft.azure/autorest.modeler        2.3.55       C:\Users\patrickb\.autorest\@microsoft.azure_autorest.modeler@2.3.55

**Comment by fearthecowboy** [comment]
Why have `enum` with integer values? That's a terrible way to write it.

Try using 
``` json
{
  "type": "integer",
  "format:" : "int32",
  "minimum": 1,
  "maximum": 5
}
```

While there is definitely a bug, you don't want the code that would generate anyway.

**Comment by tazdevilnl** [comment]
Oke will change it.

**Comment by tazdevilnl** [comment]
Any updates about the bug?

**Comment by fearthecowboy** [comment]
The bug is in the v2 modeler; it's not going to get looked at anytime soon; there's just too much work on the newer generation of generators right now.
