### ISSUE TITLE
autorest-v3 --info 'not a function' TypeError on node v13 and v10

### ISSUE THREAD

**Issue by OzBob** [Azure/autorest#3397]
fresh install of 
npm @autorest/autorest@preview
on
node --version v13.7.0
and
node --version v10.18.1

npm -v 6.13.7

On  Windows 10 build 1909

>autorest-v3 --info

WARNING: AutoRest has not been tested with Node versions greater than v10.

AutoRest code generation utility [version: 3.0.6110; node: v13.7.0, max-memory: 8192 gb]
...
Failure:
TypeError: volume[member].bind is not a function
TypeError: volume[member].bind is not a function
    at patchFilesystem (C:\Users\{username}\AppData\Roaming\npm\node_modules\@autorest\autorest\dist\static-loader.js:1:4885)
    at C:\Users\{username}\AppData\Roaming\npm\node_modules\@autorest\autorest\dist\static-loader.js:1:4908
    at Object.global.staticloader.undo (C:\Users\{username}\AppData\Roaming\npm\node_modules\@autorest\autorest\dist\static-loader.js:1:2495)
    at process.exit (C:\Users\{username}\AppData\Roaming\npm\node_modules\@autorest\autorest\dist\static-loader.js:1:2647)
    at main (C:\Users\{username}\AppData\Roaming\npm\node_modules\@autorest\autorest\dist\app.js:175:21)

and
AutoRest code generation utility [version: 3.0.6110; node: v10.18.1, max-memory: 8192 gb]
node.exe : TypeError: volume[member].bind is not a function
At C:\{username}\robma\AppData\Roaming\npm\autorest-v3.ps1:15 char:3

**Comment by fearthecowboy** [comment]
Don't install `@autorest/autorest@preview` just install `@autorest/autorest`

**Comment by fearthecowboy** [comment]
You can install the RC build directly now:

``` ps
npm install -g  https://github.com/Azure/autorest/releases/download/autorest-3.0.6173/autorest-3.0.6173.tgz
autorest --reset

```
and then just use the  `autorest` command (not `autorest-beta`).
