### ISSUE TITLE
Collision detected inserting into object: name

### ISSUE THREAD

**Issue by Maheshprakashrao** [Azure/autorest#3409]
D:\>autorest --powershell --input-file:v2_all.json --output-folder:testingpw --debug

WARNING: AutoRest has not been tested with Node versions greater than v10.

AutoRest code generation utility [version: 3.0.5231; node: v12.15.0, max-memory: 16384 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
Network Enabled: true
Starting @microsoft.azure/autorest-core from C:\Users\maheshp\.autorest\@microsoft.azure_autorest-core@3.0.5537
   Loading AutoRest core      'C:\Users\maheshp\.autorest\@microsoft.azure_autorest-core@3.0.5537\node_modules\@microsoft.azure\autorest-core\dist' (3.0.5537)
   Loading AutoRest extension '@microsoft.azure/autorest.powershell' (beta->2.0.678)
   Loading AutoRest extension '@microsoft.azure/autorest.remodeler' (beta->2.0.382)
   Loading AutoRest extension '@microsoft.azure/autorest.csharp-v2' (beta->2.0.433)
DEBUG [15.3 s]: swagger-document/loader-swagger - START inputs = 0
DEBUG [15.31 s]: openapi-document-override/md-override-loader-openapi - START inputs = 0
DEBUG [15.31 s]: openapi-document/loader-openapi - START inputs = 0
DEBUG [15.31 s]: swagger-document-override/md-override-loader-swagger - START inputs = 0
DEBUG [15.31 s]: pipeline-emitter - START inputs = 0
DEBUG [15.34 s]: configuration-emitter - START inputs = 0
DEBUG [15.42 s]: pipeline-emitter - END [0.11 s]
DEBUG [15.42 s]: configuration-emitter - END [0.11 s]
DEBUG [22.03 s]: openapi-document-override/md-override-loader-openapi - END [6.72 s]
DEBUG [22.03 s]: swagger-document-override/md-override-loader-swagger - END [6.72 s]
DEBUG [25.45 s]: openapi-document/loader-openapi - END [10.15 s]
DEBUG [25.46 s]: openapi-document/individual/transform - SKIPPING
DEBUG [25.46 s]: openapi-document/individual/schema-validator-openapi - SKIPPING
DEBUG [25.75 s]: openapi-document/individual/identity - SKIPPING
DEBUG [26.13 s]: openapi-document/transform-immediate - START inputs = 1
DEBUG [26.13 s]: openapi-document/transform-immediate - END [0 s]
DEBUG [31.62 s]: swagger-document/loader-swagger - END [16.31 s]
DEBUG [31.62 s]: swagger-document/individual/transform - START inputs = 1
DEBUG [33.35 s]: swagger-document/individual/transform - END [1.72 s]
DEBUG [33.35 s]: swagger-document/individual/schema-validator-swagger - START inputs = 1
DEBUG [34.17 s]: swagger-document/individual/schema-validator-swagger - END [0.81 s]
DEBUG [34.17 s]: swagger-document/identity - START inputs = 1
DEBUG [34.17 s]: swagger-document/individual/identity - START inputs = 1
DEBUG [34.17 s]: swagger-document/identity - END [0 s]
DEBUG [34.17 s]: swagger-document/individual/identity - END [0 s]
DEBUG [34.17 s]: openapi-document/openapi-document-converter - START inputs = 1
DEBUG [37.31 s]: openapi-document/openapi-document-converter - END [3.13 s]
DEBUG [37.31 s]: openapi-document/transform - START inputs = 2
DEBUG [39.34 s]: openapi-document/transform - END [2.02 s]
DEBUG [40.2 s]: openapi-document/tree-shaker - START inputs = 2
C:\Users\maheshp\.autorest\@microsoft.azure_autorest-core@3.0.5537\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\pipeline.js - FAILURE {"exitCode":1}
Process() cancelled due to exception : Collision detected inserting into object: name / Error: Collision detected inserting into object: name
    at Object.set (/node_modules/@microsoft.azure/datastore/dist/graph-builder.js:45:23)
    at OAI3Shaker.clone (/node_modules/@microsoft.azure/datastore/dist/processor.js:62:31)
    at OAI3Shaker.visitParameter (C:\Users\maheshp\.autorest\@microsoft.azure_autorest-core@3.0.5537\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\plugins\tree-shaker.js:184:26)
    at OAI3Shaker.dereference (C:\Users\maheshp\.autorest\@microsoft.azure_autorest-core@3.0.5537\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\plugins\tree-shaker.js:480:27)
    at OAI3Shaker.visitHttpOperation (C:\Users\maheshp\.autorest\@microsoft.azure_autorest-core@3.0.5537\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\plugins\tree-shaker.js:142:40)
    at OAI3Shaker.visitPath (C:\Users\maheshp\.autorest\@microsoft.azure_autorest-core@3.0.5537\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\plugins\tree-shaker.js:120:26)
    at OAI3Shaker.visitPaths (C:\Users\maheshp\.autorest\@microsoft.azure_autorest-core@3.0.5537\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\plugins\tree-shaker.js:101:18)
    at OAI3Shaker.process (C:\Users\maheshp\.autorest\@microsoft.azure_autorest-core@3.0.5537\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\plugins\tree-shaker.js:76:26)
    at OAI3Shaker.runProcess (/node_modules/@microsoft.azure/datastore/dist/processor.js:76:28)
    at async OAI3Shaker.getOutput (/node_modules/@microsoft.azure/datastore/dist/processor.js:14:9)
    at async shakeTree (C:\Users\maheshp\.autorest\@microsoft.azure_autorest-core@3.0.5537\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\plugins\tree-shaker.js:491:66)
    at async ScheduleNode (C:\Users\maheshp\.autorest\@microsoft.azure_autorest-core@3.0.5537\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\pipeline.js:276:33)
  Error: Collision detected inserting into object: name
[41.6 s] Shutting Down.
[41.6 s] Exiting.
(node:36888) UnhandledPromiseRejectionWarning: Error: Collision detected inserting into object: name
    at Object.set (/node_modules/@microsoft.azure/datastore/dist/graph-builder.js:45:23)
    at OAI3Shaker.clone (/node_modules/@microsoft.azure/datastore/dist/processor.js:62:31)
    at OAI3Shaker.visitParameter (C:\Users\maheshp\.autorest\@microsoft.azure_autorest-core@3.0.5537\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\plugins\tree-shaker.js:184:26)
    at OAI3Shaker.dereference (C:\Users\maheshp\.autorest\@microsoft.azure_autorest-core@3.0.5537\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\plugins\tree-shaker.js:480:27)
    at OAI3Shaker.visitHttpOperation (C:\Users\maheshp\.autorest\@microsoft.azure_autorest-core@3.0.5537\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\plugins\tree-shaker.js:142:40)
    at OAI3Shaker.visitPath (C:\Users\maheshp\.autorest\@microsoft.azure_autorest-core@3.0.5537\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\plugins\tree-shaker.js:120:26)
    at OAI3Shaker.visitPaths (C:\Users\maheshp\.autorest\@microsoft.azure_autorest-core@3.0.5537\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\plugins\tree-shaker.js:101:18)
    at OAI3Shaker.process (C:\Users\maheshp\.autorest\@microsoft.azure_autorest-core@3.0.5537\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\plugins\tree-shaker.js:76:26)
    at OAI3Shaker.runProcess (/node_modules/@microsoft.azure/datastore/dist/processor.js:76:28)
    at async OAI3Shaker.getOutput (/node_modules/@microsoft.azure/datastore/dist/processor.js:14:9)
    at async shakeTree (C:\Users\maheshp\.autorest\@microsoft.azure_autorest-core@3.0.5537\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\plugins\tree-shaker.js:491:66)
    at async ScheduleNode (C:\Users\maheshp\.autorest\@microsoft.azure_autorest-core@3.0.5537\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\pipeline.js:276:33)
(node:36888) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 29)

Attaching JSON as txt:
[v2_all.txt](https://github.com/Azure/autorest/files/4185260/v2_all.txt)

if the issue is fixed, could you please tell when the change would be available ?

**Comment by fearthecowboy** [comment]
You're using an outdated autorest.

``` bash
npm uninstall -g autorest
npm install -g @autorest/autorest 

# then use  autorest-beta until v3 is released.
autorest-beta --powershell ...
```

**Comment by Maheshprakashrao** [comment]
i followed the steps as you suggested, but still the error persists as shown below.

Interestingly, the python generator works in v2 but has stopped working in the beta version as well with the same error. could you check pls ? 

D:\>autorest-beta --powershell --input-file:v2_all.json --output-folder:testingpw --debug
AutoRest code generation utility [cli version: 3.0.6175; node: v12.15.0, max-memory: 8192 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
Network Enabled: true
Starting @autorest/core from C:\Users\maheshp\.autorest\@microsoft.azure_autorest-core@3.0.5537
   Loading AutoRest core      'C:\Users\maheshp\.autorest\@microsoft.azure_autorest-core@3.0.5537\node_modules\@microsoft.azure\autorest-core\dist' (3.0.5537)
DEBUG [28.04 s]: swagger-document/loader-swagger - START inputs = 0
DEBUG [28.05 s]: openapi-document-override/md-override-loader-openapi - START inputs = 0
DEBUG [28.05 s]: openapi-document/loader-openapi - START inputs = 0
DEBUG [28.05 s]: swagger-document-override/md-override-loader-swagger - START inputs = 0
DEBUG [28.05 s]: pipeline-emitter - START inputs = 0
DEBUG [28.08 s]: configuration-emitter - START inputs = 0
DEBUG [28.14 s]: pipeline-emitter - END [0.09 s]
DEBUG [28.14 s]: configuration-emitter - END [0.09 s]
DEBUG [35.13 s]: openapi-document-override/md-override-loader-openapi - END [7.09 s]
DEBUG [35.14 s]: swagger-document-override/md-override-loader-swagger - END [7.09 s]
DEBUG [38.78 s]: openapi-document/loader-openapi - END [10.73 s]
DEBUG [38.78 s]: openapi-document/individual/transform - SKIPPING
DEBUG [38.78 s]: openapi-document/individual/schema-validator-openapi - SKIPPING
DEBUG [39.18 s]: openapi-document/individual/identity - SKIPPING
DEBUG [39.73 s]: openapi-document/transform-immediate - START inputs = 1
DEBUG [39.73 s]: openapi-document/transform-immediate - END [0 s]
DEBUG [44.67 s]: swagger-document/loader-swagger - END [16.62 s]
DEBUG [44.67 s]: swagger-document/individual/transform - START inputs = 1
DEBUG [46.41 s]: swagger-document/individual/transform - END [1.74 s]
DEBUG [46.42 s]: swagger-document/individual/schema-validator-swagger - START inputs = 1
DEBUG [47.21 s]: swagger-document/individual/schema-validator-swagger - END [0.79 s]
DEBUG [47.21 s]: swagger-document/identity - START inputs = 1
DEBUG [47.21 s]: swagger-document/individual/identity - START inputs = 1
DEBUG [47.21 s]: swagger-document/identity - END [0 s]
DEBUG [47.21 s]: swagger-document/individual/identity - END [0 s]
DEBUG [47.22 s]: openapi-document/openapi-document-converter - START inputs = 1
DEBUG [50.19 s]: openapi-document/openapi-document-converter - END [2.97 s]
DEBUG [50.19 s]: openapi-document/transform - START inputs = 2
DEBUG [52.01 s]: openapi-document/transform - END [1.81 s]
DEBUG [52.01 s]: openapi-document/tree-shaker - START inputs = 2
C:\Users\maheshp\.autorest\@microsoft.azure_autorest-core@3.0.5537\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\pipeline.js - FAILURE {"exitCode":1}
Process() cancelled due to exception : Collision detected inserting into object: name / Error: Collision detected inserting into object: name
    at Object.set (/node_modules/@microsoft.azure/datastore/dist/graph-builder.js:45:23)
    at OAI3Shaker.clone (/node_modules/@microsoft.azure/datastore/dist/processor.js:62:31)
    at OAI3Shaker.visitParameter (C:\Users\maheshp\.autorest\@microsoft.azure_autorest-core@3.0.5537\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\plugins\tree-shaker.js:184:26)
    at OAI3Shaker.dereference (C:\Users\maheshp\.autorest\@microsoft.azure_autorest-core@3.0.5537\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\plugins\tree-shaker.js:480:27)
    at OAI3Shaker.visitHttpOperation (C:\Users\maheshp\.autorest\@microsoft.azure_autorest-core@3.0.5537\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\plugins\tree-shaker.js:142:40)
    at OAI3Shaker.visitPath (C:\Users\maheshp\.autorest\@microsoft.azure_autorest-core@3.0.5537\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\plugins\tree-shaker.js:120:26)
    at OAI3Shaker.visitPaths (C:\Users\maheshp\.autorest\@microsoft.azure_autorest-core@3.0.5537\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\plugins\tree-shaker.js:101:18)
    at OAI3Shaker.process (C:\Users\maheshp\.autorest\@microsoft.azure_autorest-core@3.0.5537\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\plugins\tree-shaker.js:76:26)
    at OAI3Shaker.runProcess (/node_modules/@microsoft.azure/datastore/dist/processor.js:76:28)
    at async OAI3Shaker.getOutput (/node_modules/@microsoft.azure/datastore/dist/processor.js:14:9)
    at async shakeTree (C:\Users\maheshp\.autorest\@microsoft.azure_autorest-core@3.0.5537\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\plugins\tree-shaker.js:491:66)
    at async ScheduleNode (C:\Users\maheshp\.autorest\@microsoft.azure_autorest-core@3.0.5537\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\pipeline.js:276:33)
  Error: Collision detected inserting into object: name
[53.3 s] Shutting Down.
