### ISSUE TITLE
volume[member].bind is not a function

### ISSUE THREAD

**Issue by matthchr** [Azure/autorest#3435]
Getting the following error when running AutoRest:

My command line is:
`cmd.exe /c autorest.cmd https://github.com/matthchr/azure-rest-api-specs/blob/feature/march-2020-dataplane-swagger-changes/specification/batch/data-plane/readme.md --csharp --version=2.0.4283 --reflect-api-versions --tag=package-2020-03.11.0 --csharp.output-folder=C:\work\github\azure-sdk-for-net\sdk\batch\Microsoft.Azure.Batch\src\GeneratedProtocol`

```
There is a new version of AutoRest available (3.0.6187).
 > You can install the newer version with with npm install -g autorest@latest

   Loading AutoRest core      'C:\Users\matthchr\.autorest\@microsoft.azure_autorest-core@2.0.4283\node_modules\@microsoft.azure\autorest-core\dist' (2.0.4283)
   Loading AutoRest extension '@microsoft.azure/autorest.csharp' (~2.3.79->2.3.82)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.55->2.3.55)

Write-ErrorLog : (node:57108) UnhandledPromiseRejectionWarning: TypeError: volume[member].bind is not a function
    at patchFilesystem (C:\Users\matthchr\AppData\Roaming\npm\node_modules\autorest\dist\static-loader.js:277:43)
    at C:\Users\matthchr\AppData\Roaming\npm\node_modules\autorest\dist\static-loader.js:281:18
    at Object.global.staticloader.undo (C:\Users\matthchr\AppData\Roaming\npm\node_modules\autorest\dist\static-loader.js:163:7)
    at process.exit (C:\Users\matthchr\AppData\Roaming\npm\node_modules\autorest\dist\static-loader.js:170:27)
    at main (C:\Users\matthchr\.autorest\@microsoft.azure_autorest-core@2.0.4283\node_modules\@microsoft.azure\autorest-core\dist\app.js:514:21)
(node:57108) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a
catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag
`--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 62)
(node:57108) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate
the Node.js process with a non-zero exit code.
Shutting Down
Shutting Down
At C:\Users\matthchr\Documents\WindowsPowerShell\Modules\CodeGenerationModules\AutoRestCodeGenerationModule\AutoRestCodeGenerationModule.psm1:104 char:5
+     Write-ErrorLog $stderr
+     ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Write-ErrorLog
```

Sometimes it works anyway -- sometimes it fails.
Either way, the node process consumes a ton of memory (1+GB).

I noticed https://github.com/Azure/autorest/issues/3397 which seems related, but:
1. I'm not installing autorest.preview
2. I need to use an older version of autorest (`2.0.4283`) due to issues with the latest version: #3432, #3434

**Comment by fearthecowboy** [comment]
What version of node are you running. You probably should be on node 10 or 12.

**Comment by matthchr** [comment]
I'm running
C:\work\onebranch\Batch\Service>node -v
v12.16.1


I wasn't able to reproduce this when I re-ran things though so you can probably close this.
