### ISSUE TITLE
[c#]Found incompatible property types ,  for property 'type' in schema inheritance chain

### ISSUE THREAD

**Issue by aim-for-better** [Azure/autorest#3447]
Write-ErrorLog : FATAL: System.InvalidOperationException: Found incompatible property types ,  for property 'type' in schema inheritance chain
   at AutoRest.Modeler.SchemaResolver.ExpandAllOf(Schema schema) in /opt/vsts/work/1/s/src/SchemaResolver.cs:line 157
   at AutoRest.Modeler.SchemaResolver.Unwrap(Schema schema) in /opt/vsts/work/1/s/src/SchemaResolver.cs:line 75
   at AutoRest.Modeler.SchemaBuilder.BuildServiceType(String serviceTypeName, Boolean required) in /opt/vsts/work/1/s/src/SchemaBuilder.cs:line 35
   at AutoRest.Modeler.SwaggerModeler.BuildCompositeTypes() in /opt/vsts/work/1/s/src/SwaggerModeler.cs:line 348
   at AutoRest.Modeler.SwaggerModeler.Build(ServiceDefinition serviceDefinition) in /opt/vsts/work/1/s/src/SwaggerModeler.cs:line 66
   at AutoRest.Modeler.Program.<ProcessInternal>d__2.MoveNext() in /opt/vsts/work/1/s/src/Program.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NewPlugin.<Process>d__15.MoveNext()
  Error: Plugin imodeler1 reported failure.
所在位置 C:\Users\xxx\Documents\WindowsPowerShell\Modules\CodeGenerationModules\AutoRestCodeGenerationModule\AutoRestCodeGenerationModule.psm1:104 字符: 5
+     Write-ErrorLog $stderr
+     ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Write-ErrorLog

**Comment by fearthecowboy** [comment]
Need a lot more information. Swagger, autorest version, command line.

**Comment by MatanShabtay** [comment]
I got the same error

Write-ErrorLog : FATAL: System.InvalidOperationException: Found incompatible property types ,  for property 'ruleType' in schema inheritance chain


AutoRest version: 3.0.6187
Node version: 10.0.16
AutoRest execution: https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/securitycenter/Microsoft.Azure.Management.SecurityCenter/src/generate.ps1

I suspect the problem is somehow related to the [DeviceSecurityGroup ](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/securitycenter/Microsoft.Azure.Management.SecurityCenter/src/Generated/Models/DeviceSecurityGroup.cs )model as its the only model that has a field called ruleTyped in Microsoft.Security swagger.
Any suggestions?

**Comment by vivekkwatra** [comment]
I am getting same error while running following command:

autorest --v3 --version=3.0.6274 --input-file=api.json --csharp --output-folder=APIALL --namespace=PetStore

Any suggestions how to fix this?

**Comment by vespaet3** [comment]
Hi, I get this error

 Loading AutoRest core      'C:\node_modules\@autorest\core\dist' (3.0.6262)
   Loading AutoRest extension '@microsoft.azure/autorest.csharp' (preview->2.3.84)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.55->2.3.55)
FATAL: System.InvalidOperationException: Found incompatible property types ,  for property 'description' in schema
   at AutoRest.Modeler.SchemaResolver.ExpandAllOf(Schema schema) in /opt/vsts/work/1/s/src/SchemaResolver.cs:line 142
   at AutoRest.Modeler.SchemaResolver.Unwrap(Schema schema) in /opt/vsts/work/1/s/src/SchemaResolver.cs:line 75
   at AutoRest.Modeler.SchemaBuilder.BuildServiceType(String serviceTypeName, Boolean required) in /opt/vsts/work/1/s/src/SchemaBuilder.cs:line 35
   at AutoRest.Modeler.SwaggerModeler.BuildCompositeTypes() in /opt/vsts/work/1/s/src/SwaggerModeler.cs:line 348
   at AutoRest.Modeler.SwaggerModeler.Build(ServiceDefinition serviceDefinition) in /opt/vsts/work/1/s/src/SwaggerModeler.cs:line 66
   at AutoRest.Modeler.Program.<ProcessInternal>d__2.MoveNext() in /opt/vsts/work/1/s/src/Program.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NewPlugin.<Process>d__15.MoveNext()

**Comment by dsynclabsllc** [comment]
I am also getting a similar error
autorest --v3 --input-file="C:\Users\PrimaryUser\AppData\Local\Temp\AutoRestConnectedService\2020_Aug_12_09_25_26\swagger.json" --csharp --namespace=MyProject.PaymentService --override-client-name=MyProjectPaymentServiceClient --output-folder="C:\Users\PrimaryUser\AppData\Local\Temp\AutoRestConnectedService\2020_Aug_12_09_25_26"
Opening
Opened
AutoRest code generation utility [cli version: 3.0.6187; node: v12.18.3, max-memory: 8192 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      'C:\Users\PrimaryUser\.autorest\@autorest_core@3.0.6274\node_modules\@autorest\core\dist' (3.0.6274)
   Loading AutoRest extension '@microsoft.azure/autorest.csharp' (~2.3.79->2.3.84)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.55->2.3.55)
Error:FATAL: System.InvalidOperationException: Found incompatible property types ,  for property 'ApplicationName' in schema inheritance chain 
Error:   at AutoRest.Modeler.SchemaResolver.ExpandAllOf(Schema schema) in /opt/vsts/work/1/s/src/SchemaResolver.cs:line 157
   at AutoRest.Modeler.SchemaResolver.Unwrap(Schema schema) in /opt/vsts/work/1/s/src/SchemaResolver.cs:line 75
   at AutoRest.Modeler.SchemaBuilder.BuildServiceType(String serviceTypeName, Boolean required) in /opt/vsts/work/1/s/src/SchemaBuilder.cs:line 35
   at AutoRest.Modeler.SwaggerModeler.BuildCompositeTypes() in /opt/vsts/work/1/s/src/SwaggerModeler.cs:line 348
   at AutoRest.Modeler.SwaggerModeler.Build(ServiceDefinition serviceDefinition) in /opt/vsts/work/1/s/src/SwaggerModeler.cs:line 66
   at AutoRest.Modeler.Program.<ProcessInternal>d__2.MoveNext() in /opt/vsts/work/1/s/src/Program.cs:line 60

**Comment by luizfbicalho** [comment]
I got the same error with this command and this json

autorest --input-file=openapi.json --csharp --output-folder=API --namespace=Zenvia.API --v3

https://zenvia.github.io/zenvia-openapi-spec/v2/openapi.json

**Comment by timotheeguerin** [comment]
@luizfbicalho for your spec there your operations are missing unique operation Id. Latest version should tell you that. Make sure to have unique `operationId` for each operation or that the `tags` list is unique(as in this case it defaults to the tag names for the operation name)

Please reopen a new issue with the latest information if you are still having problems.

**Comment by DmitriyKirakosyan** [comment]
Having the same issue with the AppCenter Open API json: https://github.com/microsoft/appcenter-cli/blob/master/swagger/bifrost.swagger.json

autorest version: `3.6.3`

Error:
```
fatal   | System.InvalidOperationException: Found incompatible property types ,  for property 'created_at' in schema inheritance chain 
   at AutoRest.Modeler.SchemaResolver.ExpandAllOf(Schema schema) in C:\Users\ci\AppData\Local\Temp\PUBLISHu1dw1\44_20171214T003644\autorest.modeler\src\SchemaResolver.cs:line 157
```

Autorest worked well with this json on version `2.0.4413`. I'm trying to upgrade it to `3` to get rid of `ms-rest` dependency. However it can't parse json now.
Any ideas on how to resolve it?
