### ISSUE TITLE
The schema's 'TypeName' ancestors should have at lease one property

### ISSUE THREAD

**Issue by SkinnySackboy** [Azure/autorest#3462]
Hi,

I'm just upgrading from 2.x to 3.0.6187 (node: v12.14.1) using @autorest\core\dist (3.0.6262) and the following input:

```json
{
  "openapi": "3.0.1",
  "info": {
    "title": "MyAPI",
    "description": "This API.",
    "version": "0.0.0.0"
  },
  "paths": {
    "/api/Chairs": {
      "get": {
        "tags": [
          "Chairs"
        ],
        "operationId": "GetChairs",
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/ChairDTO"
                  },
                  "x-nullable": false
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "ChairType": {
        "enum": [
          "A",
          "B",
          "C"
        ],
        "type": "string",
        "x-nullable": false,
        "x-ms-enum": {
          "name": "ChairType",
          "modelAsString": false
        }
      },
      "ChairDTO": {
        "type": "object",
        "properties": {
          "eventCode": {
            "type": "string",
            "nullable": true
          },
          "ChairType": {
            "allOf": [
              {
                "$ref": "#/components/schemas/ChairType"
              }
            ],
            "x-nullable": false,
            "x-ms-enum": {
              "name": "ChairType",
              "modelAsString": false
            }
          }
        }
      }
    }
  }
}
```

Generates the following error:

> node.exe : FATAL: The schema's 'ChairType' ancestors should have at lease one property
> At C:\Users\username\AppData\Roaming\npm\autorest.ps1:15 char:3
> +   & "node$exe"  "$basedir/node_modules/autorest/entrypoints/app.js" $ ...
> +   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (FATAL: The sche...se one property:String) [], RemoteException
>     + FullyQualifiedErrorId : NativeCommandError
>  
> FATAL: AutoRest.Core.Logging.CodeGenerationException: The schema's 'ChairType' ancestors should have at lease one property
>    at AutoRest.Modeler.SwaggerModeler.BuildCompositeTypes() in /opt/vsts/work/1/s/src/SwaggerModeler.cs:line 361
>    at AutoRest.Modeler.SwaggerModeler.Build(ServiceDefinition serviceDefinition) in /opt/vsts/work/1/s/src/SwaggerModeler.cs:line 66
>    at AutoRest.Modeler.Program.<ProcessInternal>d__2.MoveNext() in /opt/vsts/work/1/s/src/Program.cs:line 60
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at NewPlugin.<Process>d__15.MoveNext()
> 
>   Error: Plugin imodeler1 reported failure.

If I replace the ChairType definition with this it works, but I lose the ability to set the additional properties which I need.

```json
{ "ChairType": { "$ref": "#/components/schemas/ChairType" }
```

Has anyone got any thoughts? Thanks in advance. _Edited for formatting._

**Comment by SkinnySackboy** [comment]
In case it helps, I have tried switching to Node.js v10.15.3, same issue.

I tried out of curiosity using the --v3 flag and instead I see the following error:

> Error: Unable to find a valid AutoRest core package '@autorest/core' @ '~3.0.6212'.
Error: Unable to find a valid AutoRest core package '@autorest/core' @ '~3.0.6212'.

I have tried installing this version multiple times but I still keep seeing the same error when using the --v3 flag. Without the --v3 flag I see the error in my original comment above.
