### ISSUE TITLE
Multi-Level Inheritance Broken

### ISSUE THREAD

**Issue by mattrhoden** [Azure/autorest#3473]
_After initially filing this bug under the [csharp repo](https://github.com/Azure/autorest.csharp/issues/618). I realized this is broken for the python client generator as well and figure this is probably a core issue. Please feel free to direct me to the correct autorest repo to move the issue to if this is the wrong one._

Hi, I hope this is the right place to file this bug. I am trying to use autorest to generate an api client for our project. It seems to fail when there's an inheritance structure that's at least 2 levels deep. I found one ticket that shows this issue as being resolved, but I am still able to reproduce this.

https://github.com/Azure/autorest/issues/2430

The command and the result are at the bottom of this ticket. Sorry, even the shortest schema is still kind of long. 

Also, I just wanted to point out that the error message looks like it is missing additional information that is supposed to be printed out: `Found incompatible property types ,  for property 'bestFriends' in schema inheritance chain`

**Version Info**
Type | Extension Name | Version
----- | ---------------- | --------
core | @autorest/core | 3.0.6262
extension | @microsoft.azure/autorest.csharp | 2.3.84
extension | @microsoft.azure/autorest.modeler | 2.3.55

**Model Structure**

```csharp
    public abstract class Dog : Animal
    {
        [Required]
        public bool Friendly { get; set; }

        public IList<Animal> BestFriends { get; set; }
    }

    public class GreenlandDog : Dog
    {
        public bool IsBoofer { get; set; }
    }

    public class Boxer : Dog
    {
        public bool IsBarker { get; set; }
    }
```

**Generated Schema**
```json
{
  "openapi": "3.0.1",
  "info": {
    "title": "My API",
    "version": "v1"
  },
  "paths": {
    "/v4/animals-impacted": {
      "get": {
        "tags": [
          "HomeZoo"
        ],
        "operationId": "GetAnimalsImpactedV4",
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "oneOf": [
                      {
                        "oneOf": [
                          {
                            "$ref": "#/components/schemas/GreenlandDog"
                          },
                          {
                            "$ref": "#/components/schemas/Boxer"
                          }
                        ]
                      },
                      {
                        "$ref": "#/components/schemas/GreenlandDog"
                      },
                      {
                        "$ref": "#/components/schemas/Boxer"
                      }
                    ]
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Animal": {
        "required": [
          "$type",
          "name"
        ],
        "type": "object",
        "properties": {
          "$type": {
            "type": "string"
          },
          "name": {
            "type": "string"
          }
        },
        "discriminator": {
          "propertyName": "$type"
        }
      },
      "Dog": {
        "allOf": [
          {
            "$ref": "#/components/schemas/Animal"
          },
          {
            "required": [
              "$type",
              "friendly",
              "name"
            ],
            "type": "object",
            "properties": {
              "friendly": {
                "type": "boolean"
              },
              "bestFriends": {
                "type": "array",
                "items": {
                  "oneOf": [
                    {
                      "oneOf": [
                        {
                          "$ref": "#/components/schemas/GreenlandDog"
                        },
                        {
                          "$ref": "#/components/schemas/Boxer"
                        }
                      ]
                    },
                    {
                      "$ref": "#/components/schemas/GreenlandDog"
                    },
                    {
                      "$ref": "#/components/schemas/Boxer"
                    }
                  ]
                },
                "nullable": true
              }
            },
            "discriminator": {
              "propertyName": "$type"
            }
          }
        ]
      },
      "Boxer": {
        "allOf": [
          {
            "$ref": "#/components/schemas/Dog"
          },
          {
            "required": [
              "friendly",
              "name"
            ],
            "type": "object",
            "properties": {
              "isBarker": {
                "type": "boolean"
              },
              "friendly": {
                "type": "boolean"
              },
              "bestFriends": {
                "type": "array",
                "items": {
                  "oneOf": [
                    {
                      "oneOf": [
                        {
                          "$ref": "#/components/schemas/GreenlandDog"
                        },
                        {
                          "$ref": "#/components/schemas/Boxer"
                        }
                      ]
                    },
                    {
                      "$ref": "#/components/schemas/GreenlandDog"
                    },
                    {
                      "$ref": "#/components/schemas/Boxer"
                    }
                  ]
                },
                "nullable": true
              },
              "name": {
                "type": "string"
              }
            }
          }
        ]
      },
      "GreenlandDog": {
        "allOf": [
          {
            "$ref": "#/components/schemas/Dog"
          },
          {
            "required": [
              "friendly",
              "name"
            ],
            "type": "object",
            "properties": {
              "isBoofer": {
                "type": "boolean"
              },
              "friendly": {
                "type": "boolean"
              },
              "bestFriends": {
                "type": "array",
                "items": {
                  "oneOf": [
                    {
                      "oneOf": [
                        {
                          "$ref": "#/components/schemas/GreenlandDog"
                        },
                        {
                          "$ref": "#/components/schemas/Boxer"
                        }
                      ]
                    },
                    {
                      "$ref": "#/components/schemas/GreenlandDog"
                    },
                    {
                      "$ref": "#/components/schemas/Boxer"
                    }
                  ]
                },
                "nullable": true
              },
              "name": {
                "type": "string"
              }
            }
          }
        ]
      }
    }
  }
}
```

**Command & Result**

```
>autorest --v3 --csharp --input-file=./swagger.json --generate-empty-classes --sync-methods=essential --output-folder=dotnet --namespace=Test.Name.Space
AutoRest code generation utility [cli version: 3.0.6187; node: v12.16.1, max-memory: 8192 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      'C:\Users\matt.rhoden.HQ\.autorest\@autorest_core@3.0.6262\node_modules\@autorest\core\dist' (3.0.6262)
   Loading AutoRest extension '@microsoft.azure/autorest.csharp' (~2.3.79->2.3.84)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.55->2.3.55)
FATAL: System.InvalidOperationException: Found incompatible property types ,  for property 'bestFriends' in schema inheritance chain
   at AutoRest.Modeler.SchemaResolver.ExpandAllOf(Schema schema) in /opt/vsts/work/1/s/src/SchemaResolver.cs:line 157
   at AutoRest.Modeler.SchemaResolver.Unwrap(Schema schema) in /opt/vsts/work/1/s/src/SchemaResolver.cs:line 75
   at AutoRest.Modeler.SchemaBuilder.BuildServiceType(String serviceTypeName, Boolean required) in /opt/vsts/work/1/s/src/SchemaBuilder.cs:line 35
   at AutoRest.Modeler.SwaggerModeler.BuildCompositeTypes() in /opt/vsts/work/1/s/src/SwaggerModeler.cs:line 348
   at AutoRest.Modeler.SwaggerModeler.Build(ServiceDefinition serviceDefinition) in /opt/vsts/work/1/s/src/SwaggerModeler.cs:line 66
   at AutoRest.Modeler.Program.<ProcessInternal>d__2.MoveNext() in /opt/vsts/work/1/s/src/Program.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NewPlugin.<Process>d__15.MoveNext()
  Error: Plugin imodeler1 reported failure.
```

**Comment by fearthecowboy** [comment]
We currently don't have support for `oneOf` in OAI3 docs at the moment (see https://github.com/Azure/autorest#openapi3-support)

But beyond that... what are you trying to accomplish with the `oneOf ` that has nested `oneOf`s?

``` js
"oneOf": [
  {
    "oneOf": [
      {
        "$ref": "#/components/schemas/GreenlandDog"
      },
      {
        "$ref": "#/components/schemas/Boxer"
      }
    ]
  },
  {
    "$ref": "#/components/schemas/GreenlandDog"
  },
  {
    "$ref": "#/components/schemas/Boxer"
  }
]
```

Even if we supported `oneOf` the nested set does nothing that the outer set wouldn't.

If you're trying to support polymorphism, there is a better way to do that.

**Comment by mattrhoden** [comment]
To provide some background: We have a legacy project which is consuming a hand written client api. We are in the process of doing a major upgrade to dotnet core 3, which included updates to swashbuckle, swagger, etc. So we are trying to use autorest to generate a client for us. There are some results which are polymorphic. Which is why I have this test project to help me diagnose this. 

Looking at your linked documentation, I did see the `--V3` flag. I thought this meant it would be supported. Which is why I am running this command below. This is why I included the versions of the extensions because I thought maybe they weren't the right ones?
```
autorest --v3 --csharp --input-file=./swagger.json --generate-empty-classes --sync-methods=essential --output-folder=dotnet --namespace=Test.Name.Space
```

As far as the generated schema goes, this is what I am getting back from swashbuckle. If you are aware of some flags that will give us a collapsed polymorphic result I would appreciate the pointer. 

My end goal is to get a generated client from our existing API that can handle polymorphic results so that with minimal changes we can continue supporting the legacy project. Our project has the same structures referenced in this issue, so if you know a way to get it working I'm up for it.

If it helps, I can upload the demo project to a public repo?

**Comment by fearthecowboy** [comment]
*sigh* Swashbuckle. 

I can't help with that, I never use the tool -- it constantly makes weird choices for generating OAI.

Unfortunately, while it generates things that are technically correct OAI3, it's not something that makes it easy to build relevant SDKs across a number of languages. 

ie, how exactly would you declare a member that was an array of oneOf `GreenLanddog` and `Boxer` ? 
You can't just say 'find the common parent between them' (ie, `public Animal BestFriends[] ` ) -- because it's possible there are other animals that aren't in the oneOf.

Polymorphic models are usually handled with a polymorphic discriminator property and adding `x-ms-discriminator-value` to the children to identify what value means what type.

**Comment by mattrhoden** [comment]
Out of curiosity, what tool do you use for dotnet webapi projects? If there's something better than Swashbuckle, that autorest provides stronger support for the generated schema, it might be worth the hassle to switch.

**Comment by fearthecowboy** [comment]
Personally, I code the OAI spec first by hand. It's the only way to be sure :D

**Comment by timotheeguerin** [comment]
Issue seems to be resolved in latest core and v3 generators
