### ISSUE TITLE
ArgumentException: Can not convert Object to String

### ISSUE THREAD

**Issue by dpokluda** [Azure/autorest#3484]
I am new to auto-rest. I have installed the latest version:
`npm install -g autorest`

I have version 3.0.6187 installed:
```
CMD> autorest --info
AutoRest code generation utility [cli version: 3.0.6187; node: v13.13.0, max-memory: 8192 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest


Showing All Installed Extensions

 Type       Extension Name                           Version      Location
 core       @autorest/core                           3.0.6274     C:\Users\dpokluda\.autorest\@autorest_core@3.0.6274 core       @microsoft.azure/autorest-core           2.0.4417     C:\Users\dpokluda\.autorest\@microsoft.azure_autorest-core@2.0.4417
 core       @microsoft.azure/autorest-core           3.0.5537     C:\Users\dpokluda\.autorest\@microsoft.azure_autorest-core@3.0.5537
 extension  @microsoft.azure/autorest.csharp         2.3.84       C:\Users\dpokluda\.autorest\@microsoft.azure_autorest.csharp@2.3.84
 extension  @microsoft.azure/autorest.modeler        2.3.44       C:\Users\dpokluda\.autorest\@microsoft.azure_autorest.modeler@2.3.44
 extension  @microsoft.azure/autorest.modeler        2.3.55       C:\Users\dpokluda\.autorest\@microsoft.azure_autorest.modeler@2.3.55
 extension  @microsoft.azure/autorest.python         3.0.62       C:\Users\dpokluda\.autorest\@microsoft.azure_autorest.python@3.0.62
```
I have downloaded the Petstore.yaml from Examples section and ran the command to generate C# code with the following output:

```
CMD> autorest --v3 --csharp --input-file=Petstore.yaml --output-folder=Petstore --namespace Petstore --debug
AutoRest code generation utility [cli version: 3.0.6187; node: v13.13.0, max-memory: 8192 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
Network Enabled: true
Starting @autorest/core from C:\Users\dpokluda\.autorest\@autorest_core@3.0.6274
   Loading AutoRest core      'C:\Users\dpokluda\.autorest\@autorest_core@3.0.6274\node_modules\@autorest\core\dist' (3.0.6274)
   Loading AutoRest extension '@microsoft.azure/autorest.csharp' (~2.3.79->2.3.84)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.55->2.3.55)
DEBUG [1.88 s]: swagger-document/loader-swagger - START inputs = 0
DEBUG [1.88 s]: openapi-document/loader-openapi - START inputs = 0
DEBUG [1.88 s]: pipeline-emitter - START inputs = 0
DEBUG [1.89 s]: configuration-emitter - START inputs = 0
DEBUG [1.9 s]: pipeline-emitter - END [0.02 s]
DEBUG [1.9 s]: configuration-emitter - END [0.02 s]
DEBUG [1.91 s]: swagger-document/loader-swagger - END [0.03 s]
DEBUG [1.92 s]: swagger-document/individual/transform - SKIPPING
DEBUG [1.92 s]: swagger-document/individual/schema-validator-swagger - SKIPPING
DEBUG [1.92 s]: swagger-document/identity - SKIPPING
DEBUG [1.92 s]: swagger-document/individual/identity - SKIPPING
DEBUG [1.92 s]: openapi-document/openapi-document-converter - SKIPPING
DEBUG [1.93 s]: openapi-document/loader-openapi - END [0.04 s]
DEBUG [1.93 s]: openapi-document/individual/transform - START inputs = 1
DEBUG [1.93 s]: openapi-document/individual/transform - END [0 s]
DEBUG [1.93 s]: openapi-document/individual/schema-validator-openapi - START inputs = 1
DEBUG [1.95 s]: openapi-document/individual/schema-validator-openapi - END [0.01 s]
DEBUG [1.95 s]: openapi-document/individual/identity - START inputs = 1
DEBUG [1.95 s]: openapi-document/individual/identity - END [0 s]
DEBUG [1.95 s]: openapi-document/transform-immediate - START inputs = 1
DEBUG [1.95 s]: openapi-document/transform-immediate - END [0 s]
DEBUG [1.95 s]: openapi-document/transform - START inputs = 1
DEBUG [1.97 s]: openapi-document/transform - END [0.01 s]
DEBUG [1.97 s]: openapi-document/allof-cleaner - START inputs = 1
DEBUG [1.97 s]: openapi-document/allof-cleaner - END [0 s]
DEBUG [1.97 s]: openapi-document/tree-shaker - START inputs = 1
DEBUG [1.98 s]: openapi-document/tree-shaker - END [0.01 s]
DEBUG [1.98 s]: openapi-document/multi-api-merger - START inputs = 1
DEBUG [2 s]: openapi-document/multi-api-merger - END [0.01 s]
DEBUG [2 s]: openapi-document/components-cleaner - START inputs = 1
DEBUG [2.01 s]: openapi-document/components-cleaner - END [0.01 s]
DEBUG [2.02 s]: openapi-document/component-modifiers - START inputs = 1
DEBUG [2.02 s]: openapi-document/component-modifiers - END [0 s]
DEBUG [2.02 s]: openapi-document/api-version-parameter-handler - START inputs = 1
DEBUG [2.02 s]: openapi-document/api-version-parameter-handler - END [0 s]
DEBUG [2.02 s]: openapi-document/profile-filter - START inputs = 1
DEBUG [2.02 s]: openapi-document/profile-filter - END [0 s]
DEBUG [2.02 s]: openapi-document/model-deduplicator - START inputs = 1
DEBUG [2.02 s]: openapi-document/emitter - START inputs = 1
DEBUG [2.03 s]: openapi-document/emitter - END [0 s]
DEBUG [2.03 s]: openapi-document/model-deduplicator - END [0 s]
DEBUG [2.03 s]: openapi-document/compose - START inputs = 1
DEBUG [2.05 s]: openapi-document/compose - END [0.01 s]
DEBUG [2.05 s]: openapi-document/identity - START inputs = 1
DEBUG [2.05 s]: openapi-document/identity - END [0 s]
DEBUG [2.05 s]: csharp/imodeler1 - START inputs = 1
System.ArgumentException: Can not convert Object to String.
   at Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject[T]()
   at Microsoft.Perks.JsonRPC.CallerResponse`1.SetCompleted(JToken result)
   at Microsoft.Perks.JsonRPC.Connection.<>c__DisplayClass27_0.<<Process>b__0>d.MoveNext()
```
Am I doing something wrong? How do I workaround this issue? I was trying to downgrade autorest (to an older version: `npm install -g autorest@3.0.5231`) but that didn't work. Still the same issue.

**Comment by dpokluda** [comment]
My bad. Please ignore.

**Comment by dpokluda** [comment]
I have used space for "namespace" argument. When I switched from `--namespace Petstore` to `--namespace=Petstore` things started to work. Sorry.

**Comment by darraghjones** [comment]
I did the same thing, and this post showed me the problem. I guess the error message could be better....
