### ISSUE TITLE
[GO] x-ms-pageable with non collection response error during Go SDK generation

### ISSUE THREAD

**Issue by alexhcheng** [Azure/autorest#3494]
The GO SDK generation for x-ms-pageable seems to require all responses to be a collection.
In the case where we list non-200 response object which is not itself a collection, we get an error in SDK generation.

Sample Json:
```
{
  "swagger": "2.0",
  "info": {
    "version": "1.0.0",
    "title": "Simple API"
  },
  "produces": [
    "application/json"
  ],
  "paths": {
    "/getIntegers": {
      "get": {
        "operationId": "list",
        "description": "Gets those integers.",
        "x-ms-pageable": {
          "nextLinkName": "nextLink"
        },
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/PagedIntegerCollection"
            }
          },
          "400": {
            "description": "",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "PagedIntegerCollection": {
      "description": "Page of integers.",
      "type": "object",
      "properties": {
        "value": {
          "type": "array",
          "items": {
            "type": "integer"
          }
        },
        "nextLink": {
          "type": "string"
        }
      }
    },
    "Error": {
      "description": "Error",
      "type": "object",
      "properties": {
        "message": {
          "type": "string"
        }
      }
    }
  }
}
```
Error Message
```
\node_modules\.bin\autorest --use=@microsoft.azure/autorest.go@~2.1.144 --go --verbose --multiapi --use-onever --preview-chk --version=previous --go-sdk-folder=/z/work/src/github.com/Azure/azure-sdk-for-go specification/cognitiveservices/data-plane/TranslatorText/Batch/readme.md
AutoRest code generation utility [cli version: 3.0.6187; node: v12.16.1, max-memory: 8192 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      'C:\Users\alcheng\.autorest\@microsoft.azure_autorest-core@2.0.4413\node_modules\@microsoft.azure\autorest-core\dist' (2.0.4413)
   Including configuration file 'file:///C:/src/azure-rest-api-specs/specification/cognitiveservices/data-plane/TranslatorText/Batch/readme.go.md'
   Loading AutoRest extension '@microsoft.azure/autorest.go' (~2.1.144->2.1.145)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.38->2.3.38)
FATAL: System.InvalidOperationException: pageable return type SetObject for method BaseClient.List does not contain an array
   at AutoRest.Go.Model.PageTypeGo..ctor(MethodGo method) in /home/vsts/work/1/s/src/Model/PageTypeGo.cs:line 36
   at AutoRest.Go.Model.CodeModelGo.CreatePageableTypeForMethod(MethodGo method) in /home/vsts/work/1/s/src/Model/CodeModelGo.cs:line 382
   at AutoRest.Go.TransformerGo.TransformMethods(CodeModelGo cmg) in /home/vsts/work/1/s/src/TransformerGo.cs:line 313
   at AutoRest.Go.TransformerGo.TransformCodeModel(CodeModel cm) in /home/vsts/work/1/s/src/TransformerGo.cs:line 28
   at AutoRest.Go.Program.<ProcessInternal>d__3.MoveNext() in /home/vsts/work/1/s/src/Program.cs:line 100
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NewPlugin.<Process>d__20.MoveNext() in /home/vsts/work/1/s/autorest.common/src/Plugins/NewPlugin.cs:line 163
FATAL: go/generate - FAILED
FATAL: Error: Plugin go reported failure.
Process() cancelled due to exception : Plugin go reported failure.
  Error: Plugin go reported failure.
```

**Comment by jiacheng-L** [comment]
Hi Alex, I got the same error as yours. How do you fix this?

**Comment by jhendrixMSFT** [comment]
The problem here is that the track 1 Go code generator doesn't properly handle `x-ms-error-response` types (it's missing in the provided example but is implied).  @ArcturusZhang is working on the fix.

**Comment by ArcturusZhang** [comment]
@jhendrixMSFT my fix might fix this, but the swagger posted in the description does not mark `400` by `x-ms-error-response`, therefore my fix would not fix the swagger in the description.
Actually it is reasonable that autorest throws an error on the swagger in description.

**Comment by jhendrixMSFT** [comment]
I believe the swagger is in error, it should have the `x-ms-error-response` annotation for error responses.

At any rate this should now be fixed, please ping back if still an issue.
