### ISSUE TITLE
NPM Error: Package '@microsoft.azure/autorest.csharp' - '2.3.84' failed to install

### ISSUE THREAD

**Issue by jstevensgithub** [Azure/autorest#3506]
Any easy solution for this?  I got this years ago but fixed it with downloading binaries, etc.  That was an old machine.  Trying to compare this to NSwag.

**Comment by daviwil** [comment]
@jstevensgithub Are you still experiencing issues with this?  Which operating system did you try this on?

**Comment by jstevensgithub** [comment]
I have not attempted it in a while.  I will try again.  Most development work moved on with NSWag.

**Comment by jstevensgithub** [comment]
Just tried on new covid notebook.  Same problem.

PS C:\sc\gh\openapiexample> autorest --input-file=swagger.json --csharp
AutoRest code generation utility [cli version: 3.0.6247; node: v14.13.1, max-memory: 4096 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      'C:\Users\jstevens\.autorest\@autorest_core@3.0.6320\node_modules\@autorest\core\dist' (3.0.6320)
   Installing AutoRest extension '@microsoft.azure/autorest.csharp' (~2.3.79)
Failed to install or start extension '@microsoft.azure/autorest.csharp' (~2.3.79)
  Error: Package '@microsoft.azure/autorest.csharp' - '2.3.90' failed to install:
  Failed to install package 'https://registry.npmjs.org/@microsoft.azure/autorest.csharp/-/autorest.csharp-2.3.90.tgz' -- Error: Process Failed.Error: Failed to install package 'https://registry.npmjs.org/@microsoft.azure/autorest.csharp/-/autorest.csharp-2.3.90.tgz' -- Error: Process Failed.
    at install (/node_modules/@azure-tools/extension/dist/main.js:367:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ExtensionManager.installPackage (/node_modules/@azure-tools/extension/dist/main.js:571:13)
    at async resolveExtensions (C:\Users\jstevens\.autorest\@autorest_core@3.0.6320\node_modules\@autorest\core\dist\lib\configuration.js:926:55)
    at async Configuration.CreateView (C:\Users\jstevens\.autorest\@autorest_core@3.0.6320\node_modules\@autorest\core\dist\lib\configuration.js:967:9)
    at async AutoRest.RegenerateView (C:\Users\jstevens\.autorest\@autorest_core@3.0.6320\node_modules\@autorest\core\dist\lib\autorest-core.js:66:29)
    at async currentMain (C:\Users\jstevens\.autorest\@autorest_core@3.0.6320\node_modules\@autorest\core\dist\app.js:311:21)
    at async mainImpl (C:\Users\jstevens\.autorest\@autorest_core@3.0.6320\node_modules\@autorest\core\dist\app.js:510:20)
    at async main (C:\Users\jstevens\.autorest\@autorest_core@3.0.6320\node_modules\@autorest\core\dist\app.js:537:20)

**Comment by timotheeguerin** [comment]
@jstevensgithub Does the following commands fail for you as well?
```
npm install -g @microsoft.azure/autorest.csharp@2.3.90

# If it succeed can you try with yarn(Run first: npm install -g yarn)
yarn add @microsoft.azure/autorest.csharp@2.3.90

```
