### ISSUE TITLE
servers.url should honor `--input-file` location

### ISSUE THREAD

**Issue by TylerLeonhardt** [Azure/autorest#3513]
Here's an example using the [FDIC](https://banks.data.fdic.gov/docs)'s fairly complex yaml:

```
autorest-beta --input-file=https://banks.data.fdic.gov/docs/swagger.yaml --output-folder=./PSFdic --powershell --v3
```

Unfortunately, after building and running:
```pwsh
Search-StructureInstitution -Filters 'STALP:WA'
```

I get:
```
Search-StructureInstitution_Search: Only 'http' and 'https' schemes are allowed. (Parameter 'requestUri')
```

Their [OpenApi spec](https://banks.data.fdic.gov/docs/swagger.yaml) has:
```
servers:
  - description: API to serve banking industry data to the public.
    url: '/api'
```

The input file of `https://banks.data.fdic.gov/docs/swagger.yaml` should be honored when computing the url so it resolves to: `https://banks.data.fdic.gov/api`.

This also happens with the nodejs generator:

```
autorest-beta --input-file=https://banks.data.fdic.gov/docs/swagger.yaml --output-folder=./fdic.js --nodejs --v3
```

which when running some code:

```
Invalid URI "/api/institutions?filters=STALP%3ANC%20AND%20ACTIVE%3A1%20AND%20CITY%3ACharlotte&sort_by=NAME&sort_order=ASC&limit=100&offset=0"
```

I figured I would open it here since 2 generators didn't have support for this.

**Comment by TylerLeonhardt** [comment]
@daviwil I gave that typescript generator a try and had some trouble:
```
WARNING (PreCheck/CheckDuplicateSchemas): Checking for duplicate schemas, this could take a (long) while.  Run with --verbose for more detail.
An error was encountered while handling a request: NotImplementedError: Unexpected scenario where a(n) OpenBraceToken was not found.
    at getTokenEnd (/Users/tyleonha/.autorest/@autorest_typescript@6.0.0-dev.20200521.1/node_modules/ts-morph/dist/ts-morph.js:2524:23)
    at Function.getContainerBodyPos (/Users/tyleonha/.autorest/@autorest_typescript@6.0.0-dev.20200521.1/node_modules/ts-morph/dist/ts-morph.js:2516:20)
    at getNodes (/Users/tyleonha/.autorest/@autorest_typescript@6.0.0-dev.20200521.1/node_modules/ts-morph/dist/ts-morph.js:2534:48)
    at getNodes.next (<anonymous>)
    at Function.from (<anonymous>)
    at Function.getOrParseChildren (/Users/tyleonha/.autorest/@autorest_typescript@6.0.0-dev.20200521.1/node_modules/ts-morph/dist/ts-morph.js:2476:30)
    at Function.getContainerArray (/Users/tyleonha/.autorest/@autorest_typescript@6.0.0-dev.20200521.1/node_modules/ts-morph/dist/ts-morph.js:2697:34)
    at ClassDeclaration.getMembersWithComments (/Users/tyleonha/.autorest/@autorest_typescript@6.0.0-dev.20200521.1/node_modules/ts-morph/dist/ts-morph.js:13342:44)
    at ClassDeclaration.addConstructor (/Users/tyleonha/.autorest/@autorest_typescript@6.0.0-dev.20200521.1/node_modules/ts-morph/dist/ts-morph.js:13075:69)
    at writeConstructor (/Users/tyleonha/.autorest/@autorest_typescript@6.0.0-dev.20200521.1/node_modules/@autorest/typescript/dist/src/generators/clientFileGenerator.js:114:48)
FATAL: Error: Unexpected scenario where a(n) OpenBraceToken was not found.
  Error: Plugin typescript reported failure.
```
