### ISSUE TITLE
System.ArgumentNullException: Value cannot be null. with using file parameter

### ISSUE THREAD

**Issue by Terra-jin** [Azure/autorest#3520]
Hi,

Hi,

When using Swashbuckle 5.4.1, autorest 3.0.6282 and OpenApi 3.0.1, a file parameter within a multipart/form-data results in an exception. It seems that the `properties` field of `schema` is `null`, even though it isn't in the swagger.json.

The stacktrace:

```
FATAL: System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable1 source, Func2 selector)
   at AutoRest.Modeler.Model.RequestBody.AsParameters() in /opt/vsts/work/1/s/src/Model/RequestBody.cs:line 38
   at AutoRest.Modeler.SwaggerModeler.Unwrap(SwaggerParameter swaggerParameter) in /opt/vsts/work/1/s/src/SwaggerModeler.cs:line 452
   at AutoRest.Modeler.OperationBuilder.BuildMethodParameters(Method method) in /opt/vsts/work/1/s/src/OperationBuilder.cs:line 255
   at AutoRest.Modeler.OperationBuilder.BuildMethod(HttpMethod httpMethod, String url, String methodName, String methodGroup) in /opt/vsts/work/1/s/src/OperationBuilder.cs:line 100
   at AutoRest.Modeler.SwaggerModeler.BuildMethod(HttpMethod httpMethod, String url, String name, Operation operation) in /opt/vsts/work/1/s/src/SwaggerModeler.cs:line 404
   at AutoRest.Modeler.SwaggerModeler.Build(ServiceDefinition serviceDefinition) in /opt/vsts/work/1/s/src/SwaggerModeler.cs:line 106
   at AutoRest.Modeler.Program.<ProcessInternal>d__2.MoveNext() in /opt/vsts/work/1/s/src/Program.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NewPlugin.<Process>d__15.MoveNext()
  Error: Plugin imodeler1 reported failure.
```

The relevant bit of the swagger.json:

```
    "/api/print/user/file": {
      "post": {
        "tags": [
          "Print"
        ],
        "summary": "Prints documents from a WebDav server. The caller should supply the username, \r\ndocument url (webdav) and document type. Based on the document type, the configured \r\nsettings for the document will be loaded from the database. The user's default printer\r\nwill be used to print the document.",
        "operationId": "PrintUserDocument",
        "parameters": [
          {
            "name": "api-version",
            "in": "query",
            "description": "The requested API version",
            "schema": {
              "type": "string",
              "default": "1.0"
            }
          }
        ],
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "required": [
                  "Document",
                  "DocumentType",
                  "UserName"
                ],
                "type": "object",
                "properties": {
                  "UserName": {
                    "type": "string"
                  },
                  "Document": {
                    "type": "string",
                    "description": "The document as byte array.",
                    "format": "binary"
                  },
                  "DocumentType": {
                    "$ref": "#/components/schemas/DocumentType"
                  },
                  "AmountOfOriginals": {
                    "type": "integer",
                    "description": "The amount of originals that should be printed. The original setting for the document type\r\nwill be supplied to the print job.",
                    "format": "int32"
                  },
                  "AmountOfCopies": {
                    "type": "integer",
                    "description": "The amount of copies that should be printed. The copy setting for the document type will\r\nbe supplied to the print job.",
                    "format": "int32"
                  },
                  "PrintDoubleSided": {
                    "type": "boolean"
                  }
                }
              },
              "encoding": {
                "UserName": {
                  "style": "form"
                },
                "Document": {
                  "style": "form"
                },
                "DocumentType": {
                  "style": "form"
                },
                "AmountOfOriginals": {
                  "style": "form"
                },
                "AmountOfCopies": {
                  "style": "form"
                },
                "PrintDoubleSided": {
                  "style": "form"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          },
          "422": {
            "description": "The print job is not valid."
          }
        }
      }
    },
```

The endpoint definition in C#:

```
        [HttpPost]
        [Route("user/file")]
        [ProducesResponseType(200)]
        [SwaggerOperation(OperationId = "PrintUserDocument")]
        public async Task<IActionResult> PrintDocumentForUser([FromForm] PrintForClientFileJob printJob)
        {
            // implementation omitted
        }

```

Is there anything that I'm missing concerning the JSON?

**Comment by dweggemans** [comment]
This issue is similar to https://github.com/Azure/autorest/issues/3441
A workaround by using an older version of autorest is described in that issue.
