### ISSUE TITLE
Installation not working

### ISSUE THREAD

**Issue by KIC** [Azure/autorest#3527]
When I type `sudo npm install -g autorest`

```
$ sudo npm install -g autorest  
> autorest@3.0.6187 preinstall /usr/local/lib/node_modules/autorest                                                                                                                  
> node ./.scripts/preinstall-check                                                                                                                                                   

$ autorest       
Command 'autorest' not found, did you mean:     
```

Ubuntu Linux 20.04, Node 10.19.0, npm.6.14.4

**Comment by daviwil** [comment]
Hi @KIC, don't use `sudo` when you `npm install -g autorest`, I believe `autorest` will get installed into the `root` user's global `node_modules` path.  Just run it as your user and then you should have access to the command.

**Comment by priyankajayaswal1** [comment]
I am facing a similar issue while installing autorest:

```
root@82c9815da6b7:/# npm install -g autorest

> autorest@3.0.6187 preinstall /root/.nvm/versions/node/v12.3.0/lib/node_modules/autorest
> node ./.scripts/preinstall-check

internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module '/root/.nvm/versions/node/v12.3.0/lib/node_modules/autorest/.scripts/preinstall-check'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! autorest@3.0.6187 preinstall: `node ./.scripts/preinstall-check`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the autorest@3.0.6187 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.  

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-08-05T17_58_32_530Z-debug.log
```

Configuration:

root@82c9815da6b7:/# node -v
v12.3.0
root@82c9815da6b7:/# npm -v
6.9.0
root@82c9815da6b7:/# 

This is in linux docker image - mcr.microsoft.com/dotnet/core/sdk:3.1
Let me know if you may help me on this.

**Comment by timotheeguerin** [comment]
Believe this issue is due to running node as `root` See this stackoverflow for information and solution https://stackoverflow.com/questions/51811564/sh-1-node-permission-denied
