### ISSUE TITLE
AutoRest fails to install package

### ISSUE THREAD

**Issue by ThomasEg** [Azure/autorest#3545]
I'm trying to consume a service which requires me to use custom packages(CSharpV3). I've tried to use both the `--use-extension` in CLI-v2 which didn't work. So i've upgrade to latest and i'm now trying to use the `--use`-parameter, but i get the exact same error. I'm running circles on this and could use a bit of help here...

This is what i'm trying to execute:
```
autorest --verbose --debug --input-file=input.json --output-folder=somedir --csharp --use="https://github.com/Azure/autorest.csharp#feature/v3"
```

...but i'm getting some generic "Process Failed"-error:
```
AutoRest code generation utility [cli version: 3.0.6187; node: v12.18.2, max-memory: 8192 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
Network Enabled: true
Starting @autorest/core from C:\Users\user\.autorest\@autorest_core@3.0.6302
   Loading AutoRest core      'C:\Users\user\.autorest\@autorest_core@3.0.6302\node_modules\@autorest\core\dist' (3.0.6302)
No configuration found at 'file:///C:/Users/user/Documents/GitHub/project/src/Project/Services/'.
   Including configuration file 'file:///C:/Users/user/.autorest/@autorest_core@3.0.6302/node_modules/@autorest/core/resources/inspect.md'
   Including configuration file 'file:///C:/Users/user/.autorest/@autorest_core@3.0.6302/node_modules/@autorest/core/resources/directives.md'
   Including configuration file 'file:///C:/Users/user/.autorest/@autorest_core@3.0.6302/node_modules/@autorest/core/resources/pipeline.md'
   Including configuration file 'file:///C:/Users/user/.autorest/@autorest_core@3.0.6302/node_modules/@autorest/core/resources/loader-openapi.md'
   Including configuration file 'file:///C:/Users/user/.autorest/@autorest_core@3.0.6302/node_modules/@autorest/core/resources/miscellaneous.md'
   Including configuration file 'file:///C:/Users/user/.autorest/@autorest_core@3.0.6302/node_modules/@autorest/core/resources/patches.md'
   Including configuration file 'file:///C:/Users/user/.autorest/@autorest_core@3.0.6302/node_modules/@autorest/core/resources/plugin-powershell.md'
   Including configuration file 'file:///C:/Users/user/.autorest/@autorest_core@3.0.6302/node_modules/@autorest/core/resources/plugin-azureresourceschema.md'
   Including configuration file 'file:///C:/Users/user/.autorest/@autorest_core@3.0.6302/node_modules/@autorest/core/resources/plugin-csharp.md'
   Including configuration file 'file:///C:/Users/user/.autorest/@autorest_core@3.0.6302/node_modules/@autorest/core/resources/plugin-go.md'
   Including configuration file 'file:///C:/Users/user/.autorest/@autorest_core@3.0.6302/node_modules/@autorest/core/resources/plugin-java.md'
   Including configuration file 'file:///C:/Users/user/.autorest/@autorest_core@3.0.6302/node_modules/@autorest/core/resources/plugin-nodejs.md'
   Including configuration file 'file:///C:/Users/user/.autorest/@autorest_core@3.0.6302/node_modules/@autorest/core/resources/plugin-php.md'
   Including configuration file 'file:///C:/Users/user/.autorest/@autorest_core@3.0.6302/node_modules/@autorest/core/resources/plugin-python.md'
   Including configuration file 'file:///C:/Users/user/.autorest/@autorest_core@3.0.6302/node_modules/@autorest/core/resources/plugin-ruby.md'
   Including configuration file 'file:///C:/Users/user/.autorest/@autorest_core@3.0.6302/node_modules/@autorest/core/resources/plugin-typescript.md'
   Including configuration file 'file:///C:/Users/user/.autorest/@autorest_core@3.0.6302/node_modules/@autorest/core/resources/plugin-validators.md'
   Including configuration file 'file:///C:/Users/user/.autorest/@autorest_core@3.0.6302/node_modules/@autorest/core/resources/plugin-az.md'
   Including configuration file 'file:///C:/Users/user/.autorest/@autorest_core@3.0.6302/node_modules/@autorest/core/resources/plugin-trenton.md'
   Including configuration file 'file:///C:/Users/user/.autorest/@autorest_core@3.0.6302/node_modules/@autorest/core/resources/graphs.md'
   Including configuration file 'file:///C:/Users/user/.autorest/@autorest_core@3.0.6302/node_modules/@autorest/core/resources/help-configuration.md'
   Installing AutoRest extension '@autorest/csharp-v3' (https://github.com/Azure/autorest.csharp#feature/v3)
VERBOSE [2.1 s]: Installing @autorest/csharp-v3,
VERBOSE [5.34 s]: Error: Failed to install package 'git+https://github.com/Azure/autorest.csharp.git#481c0b330f97d84c99ec7046c4f59d94e228f29c' -- Error: Process Failed.
VERBOSE [5.34 s]: Error: Failed to install package 'git+https://github.com/Azure/autorest.csharp.git#481c0b330f97d84c99ec7046c4f59d94e228f29c' -- Error: Process Failed.
    at install (/node_modules/@azure-tools/extension/dist/main.js:367:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ExtensionManager.installPackage (/node_modules/@azure-tools/extension/dist/main.js:571:13)
    at async resolveExtensions (C:\Users\user\.autorest\@autorest_core@3.0.6302\node_modules\@autorest\core\dist\lib\configuration.js:926:55)
    at async Configuration.CreateView (C:\Users\user\.autorest\@autorest_core@3.0.6302\node_modules\@autorest\core\dist\lib\configuration.js:967:9)
    at async AutoRest.RegenerateView (C:\Users\user\.autorest\@autorest_core@3.0.6302\node_modules\@autorest\core\dist\lib\autorest-core.js:66:29)
    at async currentMain (C:\Users\user\.autorest\@autorest_core@3.0.6302\node_modules\@autorest\core\dist\app.js:311:21)
    at async mainImpl (C:\Users\user\.autorest\@autorest_core@3.0.6302\node_modules\@autorest\core\dist\app.js:510:20)
    at async main (C:\Users\user\.autorest\@autorest_core@3.0.6302\node_modules\@autorest\core\dist\app.js:537:20)
VERBOSE [5.34 s]: Cleaning up failed installation: C:\Users\user\.autorest\@autorest_csharp-v3@
Failed to install or start extension '@autorest/csharp-v3' (https://github.com/Azure/autorest.csharp#feature/v3)
  Error: Package '@autorest/csharp-v3' - '' failed to install:
  Failed to install package 'git+https://github.com/Azure/autorest.csharp.git#481c0b330f97d84c99ec7046c4f59d94e228f29c' -- Error: Process Failed.Error: Failed to install package 'git+https://github.com/Azure/autorest.csharp.git#481c0b330f97d84c99ec7046c4f59d94e228f29c' -- Error: Process Failed.
    at install (/node_modules/@azure-tools/extension/dist/main.js:367:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ExtensionManager.installPackage (/node_modules/@azure-tools/extension/dist/main.js:571:13)
    at async resolveExtensions (C:\Users\user\.autorest\@autorest_core@3.0.6302\node_modules\@autorest\core\dist\lib\configuration.js:926:55)
    at async Configuration.CreateView (C:\Users\user\.autorest\@autorest_core@3.0.6302\node_modules\@autorest\core\dist\lib\configuration.js:967:9)
    at async AutoRest.RegenerateView (C:\Users\user\.autorest\@autorest_core@3.0.6302\node_modules\@autorest\core\dist\lib\autorest-core.js:66:29)
    at async currentMain (C:\Users\user\.autorest\@autorest_core@3.0.6302\node_modules\@autorest\core\dist\app.js:311:21)
    at async mainImpl (C:\Users\user\.autorest\@autorest_core@3.0.6302\node_modules\@autorest\core\dist\app.js:510:20)
    at async main (C:\Users\user\.autorest\@autorest_core@3.0.6302\node_modules\@autorest\core\dist\app.js:537:20)
[5.45 s] Shutting Down.
[5.45 s] Exiting.
```
It was the exact same kind of error i got in CLI-v2 when i tried the `--use-extension`-parameter.

The error does not give me a lot of clues on what actually went wrong or how to try to fix it. Do you have any ideas or suggestions on what to try?

**Comment by timotheeguerin** [comment]
@ThomasEg Hey, I don't think you can reference an extension via the git url if the repo doesn't corespond to a valid extracted npm package(Which is not the case here as it needs some compilation steps and the package is under `src/AutoRest.CSharp`. 

See trying to run it directly:
```bash
npm install https://github.com/Azure/autorest.csharp          
npm ERR! Can't install git+https://github.com/Azure/autorest.csharp.git#fe4f66ab3f65cffb282005f93ff135c22fb31022: Missing package version
```
