### ISSUE TITLE
problems trying out latest autorest

### ISSUE THREAD

**Issue by ctaggart** [Azure/autorest#3551]
For the az-vmware-cli extension, I use @microsoft.azure/autorest.python@3.0.62 like [this](https://github.com/Azure/az-vmware-cli/blob/master/run-autorest.sh):

> autorest --input-file=$spec --python --output-folder=azext_vmware --namespace=vendored_sdks --azure-arm=true --override-client-name=AVSClient --use=@microsoft.azure/autorest.python@3.0.62

I thought I'd try out the latest autorest bits for fun and ran into some issue.

```
npm cache clean -f
npm install -g autorest@3.0.6187
autorest --use:@autorest/python@5.1.0-preview.5 --input-file=$spec --output-folder=azext_vmware --namespace=vendored_sdks --azure-arm=true --override-client-name=AVSClient
```

```
Error: Cannot find module '/Users/cameron/github/autorest/core/entrypoints/../dist/app.js'
Require stack:
- /Users/cameron/github/autorest/core/entrypoints/app.js
- /Users/cameron/tmp/[eval]
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:772:15)
    at Function.Module._load (internal/modules/cjs/loader.js:677:27)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/Users/cameron/github/autorest/core/entrypoints/app.js:7:3)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (/usr/local/lib/node_modules/autorest/dist/static-loader.js:1:19423)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/cameron/github/autorest/core/entrypoints/app.js',
    '/Users/cameron/tmp/[eval]'
  ]
}
```

After some digging, I found that I could get around that problem by installing @autorest/core as well:
```
npm install -g @autorest/core@3.0.6302
```

But then it looks like the new python generator requires a virtual environment or something. I probably missed the documentation. It fails like so:

```
Camerons-MacBook-Pro:tmp cameron$ autorest --use:@autorest/python@5.1.0-preview.5 --input-file=$spec --output-folder=azext_vmware --namespace=vendored_sdks --azure-arm=true --override-client-name=AVSClient
AutoRest code generation utility [cli version: 3.0.6187; node: v12.10.0, max-memory: 8192 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
NOTE: AutoRest core version selected from configuration: 3.0.6287.
   Loading AutoRest core      '/Users/cameron/.autorest/@autorest_core@3.0.6287/node_modules/@autorest/core/dist' (3.0.6287)
   Loading AutoRest extension '@autorest/python' (5.1.0-preview.5->5.1.0-preview.5)
   Loading AutoRest extension '@autorest/modelerfour' (4.15.378->4.15.378)
dyld: Library not loaded: @executable_path/../Python3
  Referenced from: /Users/cameron/.autorest/@autorest_python@5.1.0-preview.5/node_modules/@autorest/python/venv/bin/python3
  Reason: image not found
Executing: venv/bin/python3 -m autorest.jsonrpc.server
Command '['venv/bin/python3', '-m', 'autorest.jsonrpc.server']' died with <Signals.SIGABRT: 6>.
Process() cancelled due to failure 
```

**Comment by timotheeguerin** [comment]
Hi @ctaggart it seems to be some issue with your installed version of python
Seems like https://mattbanderson.com/so-you-hosed-your-mac-os-python-install/ might have information related to your issue

**Comment by ctaggart** [comment]
Thanks @timotheeguerin. That may be it. I do not have time to check, but will reopen if I hit the error again.
