### ISSUE TITLE
FileUpload Powershell build-module fails The parameter '{{param}}' has multiple parameter types [...] defined

### ISSUE THREAD

**Issue by SamWalkerRxSense** [Azure/autorest#3567]
Hi, I'm new to all this, so I suspect I'm doing something wrong, but I can't figure out what.

I have this swagger json.
```
{
    "swagger": "2.0",
    "info": {
        "version": "v1",
        "title": "FileUploadTest"
    },
    "host": "localhost:44317",
    "schemes": [
        "https"
    ],
    "paths": {
        "/api/upload-file": {
            "post": {
                "summary": "Upload file.",
                "operationId": "UploadFile",
                "consumes": [
                    "multipart/form-data"
                ],
                "parameters": [
                    {
                        "name": "file",
                        "in": "formData",
                        "required": true,
                        "type": "file"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        }
    }
}
```

I ran this
```
PS C:\> autorest --powershell --input-file:fileupload.json --clear-output-folder
AutoRest code generation utility [cli version: 3.0.6187; node: v12.18.2, max-memory: 8192 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      'C:\{{user}}\.autorest\@autorest_core@3.0.6306\node_modules\@autorest\core\dist' (3.0.6306)
   Loading AutoRest extension '@autorest/powershell' (~2.1.327->2.1.400)
   Loading AutoRest extension '@autorest/remodeler' (~2.1.0->2.1.27)
[4.38 s] Generation Complete

PS C:\> .\generated\build-module.ps1
Creating isolated process...
Cleaning build folders...
Compiling module...
Creating exports and docs...
$ParsingMetadataException/   at Sample.API.Runtime.PowerShell.ParameterGroup..ctor(String parameterName, Parameter[] parameters, String[] allVariantNames) in C:\generated\generated\runtime\BuildTime\Models\PsProxyTypes.cs:line 203
   at Sample.API.Runtime.PowerShell.PsProxyTypeExtensions.<>c__DisplayClass7_0.<ToParameterGroups>b__3(IGrouping`2 pg) in C:\generated\generated\runtime\BuildTime\Models\PsProxyTypes.cs:line 487
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToArray()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Sample.API.Runtime.PowerShell.VariantGroup..ctor(String moduleName, String cmdletName, Variant[] variants, String outputFolder, String profileName, Boolean isTest, Boolean isInternal) in C:\generated\generated\runtime\BuildTime\Models\PsProxyTypes.cs:line 66
   at Sample.API.Runtime.PowerShell.ExportProxyCmdlet.<>c__DisplayClass36_2.<ProcessRecord>b__10(IGrouping`2 vg) in C:\generated\generated\runtime\BuildTime\Cmdlets\ExportProxyCmdlet.cs:line 68
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.SparseArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.SparseArrayBuilder`1.ReserveOrAdd(IEnumerable`1 items)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Sample.API.Runtime.PowerShell.ExportProxyCmdlet.ProcessRecord() in C:\generated\generated\runtime\BuildTime\Cmdlets\ExportProxyCmdlet.cs:line 66
Export-ProxyCmdlet: C:\generated\build-module.ps1:134
Line |
 134 |    Export-ProxyCmdlet -ModuleName $moduleName -ModulePath $modulePaths …
     |    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The parameter 'File' has multiple parameter types
     | [IPathsBno64UApiUploadFilePostRequestbodyContentMultipartFormDataSchema, Stream]
     | defined, which is not supported.
```

Thanks for any help.

This is actually part of a much larger set of API, but I narrowed the error down to this particular path.
Now, I'm manually deleting this path from the swagger json so it will build, which works, but it's not ideal.

**Comment by timotheeguerin** [comment]
Hi @SamWalkerRxSense  you are returning a body here but you don't define a `produce` content type in your API.
The latest version of autorest has a much better error explaining that.

Add this next to `consumes`(Replace with whatever content type you are returning): 
```json
 "produces": [
    "application/json"
],
```
