### ISSUE TITLE
error "TypeError: value.indexOf is not a function" when using property with name "$ref"

### ISSUE THREAD

**Issue by marklindell** [Azure/autorest#3584]
test.yml 
```
openapi: 3.0.3
info:
  version: '1'
paths:
  /test:
    get:
      operationId: x
      responses:
        "200":
          content:
            application/json:
              schema:
                properties:
                    $ref:
                        type: string
```

Command:
`autorest --csharp --input-file=test.yml --v3 --debug`

Result:
```
Starting @autorest/core from C:\Users\linde\.autorest\@autorest_core@3.0.6282
   Loading AutoRest core      'C:\Users\linde\.autorest\@autorest_core@3.0.6282\node_modules\@autorest\core\dist' (3.0.6282)
   Loading AutoRest extension '@microsoft.azure/autorest.csharp' (~2.3.79->2.3.84)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.55->2.3.55)
DEBUG [2.12 s]: swagger-document/loader-swagger - START inputs = 0
DEBUG [2.12 s]: openapi-document/loader-openapi - START inputs = 0
DEBUG [2.12 s]: pipeline-emitter - START inputs = 0
DEBUG [2.15 s]: configuration-emitter - START inputs = 0
DEBUG [2.16 s]: pipeline-emitter - END [0.04 s]
DEBUG [2.16 s]: configuration-emitter - END [0.04 s]
DEBUG [2.17 s]: swagger-document/loader-swagger - END [0.05 s]
DEBUG [2.17 s]: swagger-document/individual/transform - SKIPPING
DEBUG [2.17 s]: swagger-document/individual/schema-validator-swagger - SKIPPING
DEBUG [2.18 s]: swagger-document/identity - SKIPPING
DEBUG [2.18 s]: swagger-document/individual/identity - SKIPPING
DEBUG [2.19 s]: openapi-document/openapi-document-converter - SKIPPING
C:\Users\linde\.autorest\@autorest_core@3.0.6282\node_modules\@autorest\core\dist\lib\pipeline\pipeline.js - FAILURE {}
Process() cancelled due to exception : value.indexOf is not a function / TypeError: value.indexOf is not a function
    at RefProcessor.process (C:\Users\linde\.autorest\@autorest_core@3.0.6282\node_modules\@autorest\core\dist\lib\pipeline\plugins\ref-crawling.js:90:44)
    at RefProcessor.process (C:\Users\linde\.autorest\@autorest_core@3.0.6282\node_modules\@autorest\core\dist\lib\pipeline\plugins\ref-crawling.js:105:28)
    at RefProcessor.process (C:\Users\linde\.autorest\@autorest_core@3.0.6282\node_modules\@autorest\core\dist\lib\pipeline\plugins\ref-crawling.js:105:28)
    at RefProcessor.process (C:\Users\linde\.autorest\@autorest_core@3.0.6282\node_modules\@autorest\core\dist\lib\pipeline\plugins\ref-crawling.js:105:28)
    at RefProcessor.process (C:\Users\linde\.autorest\@autorest_core@3.0.6282\node_modules\@autorest\core\dist\lib\pipeline\plugins\ref-crawling.js:105:28)
    at RefProcessor.process (C:\Users\linde\.autorest\@autorest_core@3.0.6282\node_modules\@autorest\core\dist\lib\pipeline\plugins\ref-crawling.js:105:28)
    at RefProcessor.process (C:\Users\linde\.autorest\@autorest_core@3.0.6282\node_modules\@autorest\core\dist\lib\pipeline\plugins\ref-crawling.js:105:28)
    at RefProcessor.process (C:\Users\linde\.autorest\@autorest_core@3.0.6282\node_modules\@autorest\core\dist\lib\pipeline\plugins\ref-crawling.js:105:28)
    at RefProcessor.process (C:\Users\linde\.autorest\@autorest_core@3.0.6282\node_modules\@autorest\core\dist\lib\pipeline\plugins\ref-crawling.js:105:28)
    at RefProcessor.process (C:\Users\linde\.autorest\@autorest_core@3.0.6282\node_modules\@autorest\core\dist\lib\pipeline\plugins\ref-crawling.js:105:28)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RefProcessor.runProcess (C:\Users\linde\.autorest\@autorest_core@3.0.6282\node_modules\@autorest\core\dist\lib\pipeline\plugins\ref-crawling.js:121:17)
    at async RefProcessor.getOutput (/node_modules/@azure-tools/datastore/dist/processor.js:14:9)
    at async crawl (C:\Users\linde\.autorest\@autorest_core@3.0.6282\node_modules\@autorest\core\dist\lib\pipeline\plugins\ref-crawling.js:19:24)
    at async C:\Users\linde\.autorest\@autorest_core@3.0.6282\node_modules\@autorest\core\dist\lib\pipeline\plugins\ref-crawling.js:45:22
    at async Promise.all (index 0)
  TypeError: value.indexOf is not a function
[2.2 s] Shutting Down.
```

**Comment by timotheeguerin** [comment]
Believe this I resolved this recently. https://github.com/Azure/autorest/pull/3922
