### ISSUE TITLE
Version specified in readme.md seems to be ignored

### ISSUE THREAD

**Issue by HakanL** [Azure/autorest#3588]
I have a readme.md file that has the yaml section. It picks up the input file and settings just fine, but the version is ignored. I have to force it from command line. Am I missing something?
``` yaml
# specify the version of Autorest to use
version: 3.0.6244
input-file: swagger.json
sync-methods: none
csharp:
  namespace: MyProject.Services.ApiClient
  output-folder: ApiClient
```
I have latest AutoRest installed (3.0.6318) and it's just using that version (which throws an error with additionalProperties, version 6244 works).

```
C:\Projects\MyProject\src\MyProject.Services.ApiClient>autorest --v3
AutoRest code generation utility [cli version: 3.0.6244; node: v14.2.0, max-memory: 8192 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      'C:\Users\hlindest\.autorest\@autorest_core@3.0.6318\node_modules\@autorest\core\dist' (3.0.6318)
   Loading AutoRest extension '@microsoft.azure/autorest.csharp' (~2.3.79->2.3.84)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.55->2.3.55)
FATAL: Error parsing swagger file. Error converting value False to type 'AutoRest.Modeler.Model.Schema'. Path 'components.schemas.Channel.additionalProperties', line 1, position 110101.
FATAL: AutoRest.Core.Logging.CodeGenerationException: Error parsing swagger file. Error converting value False to type 'AutoRest.Modeler.Model.Schema'. Path 'components.schemas.Channel.additionalProperties', line 1, position 110101.
   at AutoRest.Modeler.SwaggerParser.Parse(String swaggerDocument) in /opt/vsts/work/1/s/src/SwaggerParser.cs:line 52
   at AutoRest.Modeler.Program.<ProcessInternal>d__2.MoveNext() in /opt/vsts/work/1/s/src/Program.cs:line 58
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NewPlugin.<Process>d__15.MoveNext()
  Error: Plugin imodeler1 reported failure.
```
Note that it says **autorest_core@3.0.6318**.

**Comment by daviwil** [comment]
Hey @HakanL, I have also noticed this recently, I'll look into it soon.

**Comment by timotheeguerin** [comment]
There was some fixes around this issue in the recent releases. Please reopen if you are still having the issue.
