### ISSUE TITLE
Unable to run autorest due to error with JSON RPC

### ISSUE THREAD

**Issue by rjmholt** [Azure/autorest#3597]
With any autorest generation command I run, I hit the following:

```
> autorest https://github.com/Azure/azure-rest-api-specs/tree/master/specification/storage/resource-manager --use:. --tag=package-2019-06 --debug
AutoRest code generation utility [cli version: 3.0.6247; node: v10.13.0, max-memory: 512 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
Network Enabled: true
(node:15448) ExperimentalWarning: The fs.promises API is experimental
Starting @autorest/core from C:\Users\rjmho\.autorest\@autorest_core@3.0.6320
   Loading AutoRest core      'C:\Users\rjmho\.autorest\@autorest_core@3.0.6320\node_modules\@autorest\core\dist' (3.0.6320)
(node:19508) ExperimentalWarning: The fs.promises API is experimental
   Loading local AutoRest extension '@autorest/sputnik' (C:\Users\rjmho\Documents\Dev\Microsoft\PSArm\sputnik.generator)
   Loading AutoRest extension '@autorest/modelerfour' (4.13.312->4.13.312)
/node_modules/vscode-jsonrpc/lib/messageReader.js:68
                throw new Error('Message header must separate key and value using :');
                ^

Error: Message header must separate key and value using :
    at /node_modules/vscode-jsonrpc/lib/messageReader.js:68:23
    at Array.forEach (<anonymous>)
    at MessageBuffer.tryReadHeaders (/node_modules/vscode-jsonrpc/lib/messageReader.js:65:17)
    at StreamMessageReader.onData (/node_modules/vscode-jsonrpc/lib/messageReader.js:194:43)
    at Socket.<anonymous> (/node_modules/vscode-jsonrpc/lib/messageReader.js:185:19)
    at Socket.emit (events.js:187:15)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

Please let me know if this might be caused by something in my own code -- I have my own autorest plugin.

**Comment by rjmholt** [comment]
So based on the assumption that this is something emitting improperly to stdout, I looked through my code, but I haven't been able to find anywhere where I might be emitting to stdout. Is there a way to debug or log what's going on so I can work out what child process / plugin is causing this and what the offending output might be?

**Comment by timotheeguerin** [comment]
@rjmholt are you still having this issue? This does look like the error when using `console.log` in an extension.
A simple way to verify first if its your code would be to remove the --use parameter

**Comment by rjmholt** [comment]
Yes @fearthecowboy helped me solve it. I needed to upgrade off of node LTS to node 14, because LTS was emitting a deprecation message or something similar that was taking down the transport channel.
