### ISSUE TITLE
[new user] errors running autorest to generate powershell modules 

### ISSUE THREAD

**Issue by hiaga** [Azure/autorest#3598]
I am trying to generate PowerShell modules from scratch using AutoREST. I'm using the "azure-rest-api-specs" repository to generate the powershell cmdlets and the json file I used is - **https://github.com/Azure/azure-rest-api-specs/blob/master/specification/recoveryservicesbackup/resource-manager/Microsoft.RecoveryServices/stable/2020-07-01/bms.json**, is this json correct? I'm facing some errors - details below
 
### Steps followed:
Installed AutoREST, node.js. 

### Command ran
autorest --powershell --input-file:"C:\Source\azure-rest-api-specs\specification\recoveryservicesbackup\resource-manager\Microsoft.RecoveryServices\stable\2020-07-01\bms.json"

### Error Details
C:\Users\hiaga\.autorest\@autorest_powershell@2.1.400\node_modules\@autorest\powershell\dist\plugins\llcsharp.js - TypeError: Cannot read property 'value' of undefined
    at valueOf (C:\Users\hiaga\.autorest\@autorest_powershell@2.1.400\node_modules\@azure-tools\codegen-csharp\expression.ts:17:67)
    at Array.map (<anonymous>)
    at Array.joinWith (C:\Users\hiaga\.autorest\@autorest_powershell@2.1.400\node_modules\@autorest\powershell\node_modules\@azure-tools\codegen\text-manipulation.ts:35:27)
    at ClassType.new (C:\Users\hiaga\.autorest\@autorest_powershell@2.1.400\node_modules\@azure-tools\codegen-csharp\dotnet.ts:35:60)
    at CallMethod.finalGet (C:\Users\hiaga\.autorest\@autorest_powershell@2.1.400\node_modules\@autorest\powershell\llcsharp\operation\method.ts:548:89)
    at finalGet.next (<anonymous>)
    at IfStatement.add (C:\Users\hiaga\.autorest\@autorest_powershell@2.1.400\node_modules\@azure-tools\codegen-csharp\statements\statement.ts:110:18)
    at IfStatement.add (C:\Users\hiaga\.autorest\@autorest_powershell@2.1.400\node_modules\@azure-tools\codegen-csharp\statements\statement.ts:111:14)
    at IfStatement.add (C:\Users\hiaga\.autorest\@autorest_powershell@2.1.400\node_modules\@azure-tools\codegen-csharp\statements\statement.ts:108:21)
    at new Statements (C:\Users\hiaga\.autorest\@autorest_powershell@2.1.400\node_modules\@azure-tools\codegen-csharp\statements\statement.ts:42:12)/Cannot read property 'value' of undefined
FATAL: TypeError: Cannot read property 'value' of undefined
  Error: Plugin llcsharp reported failure.

### Snapshot of the run
![image](https://user-images.githubusercontent.com/20358332/94630519-a68ca900-02e3-11eb-957e-d254d00a6caf.png)

**Comment by daviwil** [comment]
Hi @hiaga, this seems to be an issue with the PowerShell generator, I'll transfer your issue to that repo so that the team might be able to help you.
