### ISSUE TITLE
  Error: Plugin csnamer reported failure.

### ISSUE THREAD

**Issue by icyfire0573** [Azure/autorest#3607]
https://docs.baroan.com/ManageAPI.json 

C:\Users\WDAGUtilityAccount\Documents>autorest --powershell --input-file=C:\Users\WDAGUtilityAccount\Desktop\ManageAPI.json  --namespace=Connectwise.Manage    --debug

PLUGIN FAILURE: Unknown Model. Fatal., Error: Unknown Model. Fatal.
    at SchemaDefinitionResolver.resolveTypeDeclaration (C:\Users\WDAGUtilityAccount\.autorest\@autorest_powershell@2.1.400\node_modules\@autorest\powershell\llcsharp\schema\schema-resolver.ts:145:11)
    at SchemaDefinitionResolver.resolveTypeDeclaration (C:\Users\WDAGUtilityAccount\.autorest\@autorest_powershell@2.1.400\node_modules\@autorest\powershell\llcsharp\schema\schema-resolver.ts:41:121)
    at SchemaDefinitionResolver.resolveTypeDeclaration (C:\Users\WDAGUtilityAccount\.autorest\@autorest_powershell@2.1.400\node_modules\@autorest\powershell\llcsharp\schema\schema-resolver.ts:41:121)
    at setOperationNames (C:\Users\WDAGUtilityAccount\.autorest\@autorest_powershell@2.1.400\node_modules\@autorest\powershell\plugins\cs-namer.ts:191:67)
    at nameStuffRight (C:\Users\WDAGUtilityAccount\.autorest\@autorest_powershell@2.1.400\node_modules\@autorest\powershell\plugins\cs-namer.ts:234:9)
    at Object.processCodeModel (C:\Users\WDAGUtilityAccount\.autorest\@autorest_powershell@2.1.400\node_modules\@azure-tools\codemodel-v3\process-code-model.ts:16:96)
    at C:\Users\WDAGUtilityAccount\.autorest\@autorest_powershell@2.1.400\node_modules\@azure-tools\autorest-extension-base\extension-base.ts:68:9, {}
FATAL: Error: Unknown Model. Fatal.
C:\Users\WDAGUtilityAccount\.autorest\@autorest_core@3.0.6320\node_modules\@autorest\core\dist\lib\pipeline\pipeline.js - FAILURE {}
Process() cancelled due to exception : Plugin csnamer reported failure. / Error: Plugin csnamer reported failure.
    at C:\Users\WDAGUtilityAccount\.autorest\@autorest_core@3.0.6320\node_modules\@autorest\core\dist\lib\pipeline\plugins\external.js:26:19
    at async ScheduleNode (C:\Users\WDAGUtilityAccount\.autorest\@autorest_core@3.0.6320\node_modules\@autorest\core\dist\lib\pipeline\pipeline.js:294:33)
  Error: Plugin csnamer reported failure.

**Comment by daviwil** [comment]
This seems specifically related to the PowerShell generator, moving to the Azure/autorest.powershell repo.
