### ISSUE TITLE
System.ArgumentNullException: Value cannot be null. Parameter name: key

### ISSUE THREAD

**Issue by motoko89** [Azure/autorest#3609]
I'm trying to generate typescript from this https://api.appcenter.ms/preview/swagger.json
This is my `config.yaml`:
`````
input-file: swagger.json
namespace: com.appcenter
output-folder: output
license-header: MIT
`````
This is the command: `autorest config.yaml --typescript --verbose`

Full error:
`````
AutoRest code generation utility [cli version: 3.0.6247; node: v14.13.1, max-memory: 4096 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
NOTE: AutoRest core version selected from configuration: ~2.0.4413.
   Loading AutoRest core      'C:\Users\hohung\.autorest\@microsoft.azure_autorest-core@2.0.4417\node_modules\@microsoft.azure\autorest-core\dist' (2.0.4417)
   Loading AutoRest extension '@microsoft.azure/autorest.typescript' (~4.2.0->4.2.4)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.51->2.3.51)
FATAL: System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.ContainsKey(TKey key)
   at AutoRest.Modeler.SchemaBuilder.BuildServiceType(String serviceTypeName, Boolean required) in c:\publish\autorest.modeler\src\SchemaBuilder.cs:line 194
   at AutoRest.Modeler.OperationBuilder.TryBuildStreamResponse(HttpStatusCode responseStatusCode, OperationResponse response, Method method, List`1 types, IModelType headerType) in c:\publish\autorest.modeler\src\OperationBuilder.cs:line 412
   at AutoRest.Modeler.OperationBuilder.BuildResponses(Method method, CompositeType headerType) in c:\publish\autorest.modeler\src\OperationBuilder.cs:line 336
   at AutoRest.Modeler.OperationBuilder.BuildMethod(HttpMethod httpMethod, String url, String methodName, String methodGroup) in c:\publish\autorest.modeler\src\OperationBuilder.cs:line 195
   at AutoRest.Modeler.SwaggerModeler.BuildMethod(HttpMethod httpMethod, String url, String name, Operation operation) in c:\publish\autorest.modeler\src\SwaggerModeler.cs:line 404
   at AutoRest.Modeler.SwaggerModeler.Build(ServiceDefinition serviceDefinition) in c:\publish\autorest.modeler\src\SwaggerModeler.cs:line 106
   at AutoRest.Modeler.Program.<ProcessInternal>d__2.MoveNext() in c:\publish\autorest.modeler\src\Program.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NewPlugin.<Process>d__15.MoveNext()
FATAL: typescript/imodeler1 - FAILED
FATAL: Error: Plugin imodeler1 reported failure.
Process() cancelled due to exception : Plugin imodeler1 reported failure.
  Error: Plugin imodeler1 reported failure.
`````

**Comment by timotheeguerin** [comment]
If you use the version 3.0(`--v3` flag). You'll see a little more helpful error saying there is a conflict with the name `Subscription`. It seems like there is a definition called `Subscription` and multiple api responses as well with the title `Subscription` this is causing issue.
