### ISSUE TITLE
Error resolving $ref in examples

### ISSUE THREAD

**Issue by leni-msft** [Azure/autorest#3616]
When generateing schemas for apimanagement 2019-12-01, I encountered error `$ref to original location is not found in the new refs collection`.

It seems caused by `$ref` used in examples, where the property is defined as a literally schema object:
https://github.com/Azure/azure-rest-api-specs/blob/55543f8edeb99155523c829aff9b51229ade2c51/specification/apimanagement/resource-manager/Microsoft.ApiManagement/stable/2019-12-01/examples/ApiManagementListContentTypes.json#L22
```
➜  azure-rest-api-specs git:(master) ✗ autorest --azureresourceschema --tag=schema-apimanagement-2019-12-01 specification/apimanagement/resource-manager/readme.md --debug
AutoRest code generation utility [cli version: 3.0.6247; node: v14.8.0, max-memory: 4096 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
Network Enabled: true
Starting @autorest/core from /home/leni/.autorest/@autorest_core@3.0.6320
   Loading AutoRest core      '/home/leni/.autorest/@autorest_core@3.0.6320/node_modules/@autorest/core/dist' (3.0.6320)
   Loading AutoRest extension '@autorest/azureresourceschema' (~3.0.45->3.0.92)
DEBUG [1.78 s]: swagger-document/loader-swagger - START inputs = 0
DEBUG [1.78 s]: openapi-document/loader-openapi - START inputs = 0
DEBUG [1.78 s]: pipeline-emitter - START inputs = 0
DEBUG [1.8 s]: configuration-emitter - START inputs = 0
DEBUG [1.81 s]: pipeline-emitter - END [0.02 s]
DEBUG [1.81 s]: configuration-emitter - END [0.02 s]
DEBUG [2.75 s]: openapi-document/loader-openapi - END [0.96 s]
DEBUG [2.75 s]: openapi-document/individual/transform - SKIPPING
DEBUG [2.75 s]: openapi-document/individual/schema-validator-openapi - SKIPPING
DEBUG [2.75 s]: openapi-document/individual/identity - SKIPPING
DEBUG [3.9 s]: swagger-document/loader-swagger - END [2.12 s]
DEBUG [3.9 s]: swagger-document/individual/transform - START inputs = 35
DEBUG [5.3 s]: swagger-document/individual/transform - END [1.39 s]
DEBUG [5.3 s]: swagger-document/individual/schema-validator-swagger - START inputs = 35
DEBUG [5.65 s]: swagger-document/individual/schema-validator-swagger - END [0.34 s]
DEBUG [5.65 s]: swagger-document/identity - START inputs = 35
DEBUG [5.65 s]: swagger-document/individual/identity - START inputs = 35
DEBUG [5.65 s]: swagger-document/identity - END [0 s]
DEBUG [5.65 s]: swagger-document/individual/identity - END [0 s]
DEBUG [5.65 s]: openapi-document/openapi-document-converter - START inputs = 35
DEBUG [6.29 s]: openapi-document/openapi-document-converter - END [0.63 s]
DEBUG [6.29 s]: openapi-document/transform - START inputs = 35
DEBUG [6.41 s]: openapi-document/transform - END [0.11 s]
DEBUG [6.41 s]: openapi-document/allof-cleaner - START inputs = 35
DEBUG [6.49 s]: openapi-document/allof-cleaner - END [0.08 s]
DEBUG [6.49 s]: openapi-document/tree-shaker - START inputs = 35
DEBUG [7.51 s]: openapi-document/tree-shaker - END [1.01 s]
DEBUG [7.51 s]: openapi-document/multi-api-merger - START inputs = 35
/home/leni/.autorest/@autorest_core@3.0.6320/node_modules/@autorest/core/dist/lib/pipeline/pipeline.js - FAILURE {}
Process() cancelled due to exception : $ref to original location 'file:///home/leni/workspace/azure-rest-api-specs/specification/apimanagement/resource-manager/Microsoft.ApiManagement/stable/2019-12-01/apimcontenttypes.json#/definitions/metadata' is not found in the new refs collection / Error: $ref to original location 'file:///home/leni/workspace/azure-rest-api-specs/specification/apimanagement/resource-manager/Microsoft.ApiManagement/stable/2019-12-01/apimcontenttypes.json#/definitions/metadata' is not found in the new refs collection
    at MultiAPIMerger.updateRefs (/home/leni/.autorest/@autorest_core@3.0.6320/node_modules/@autorest/core/dist/lib/pipeline/plugins/merger.js:236:31)
    at MultiAPIMerger.updateRefs (/home/leni/.autorest/@autorest_core@3.0.6320/node_modules/@autorest/core/dist/lib/pipeline/plugins/merger.js:240:22)
    at MultiAPIMerger.updateRefs (/home/leni/.autorest/@autorest_core@3.0.6320/node_modules/@autorest/core/dist/lib/pipeline/plugins/merger.js:240:22)
    at MultiAPIMerger.updateRefs (/home/leni/.autorest/@autorest_core@3.0.6320/node_modules/@autorest/core/dist/lib/pipeline/plugins/merger.js:240:22)
    at MultiAPIMerger.updateRefs (/home/leni/.autorest/@autorest_core@3.0.6320/node_modules/@autorest/core/dist/lib/pipeline/plugins/merger.js:240:22)
    at MultiAPIMerger.updateRefs (/home/leni/.autorest/@autorest_core@3.0.6320/node_modules/@autorest/core/dist/lib/pipeline/plugins/merger.js:240:22)
    at MultiAPIMerger.updateRefs (/home/leni/.autorest/@autorest_core@3.0.6320/node_modules/@autorest/core/dist/lib/pipeline/plugins/merger.js:240:22)
    at MultiAPIMerger.updateRefs (/home/leni/.autorest/@autorest_core@3.0.6320/node_modules/@autorest/core/dist/lib/pipeline/plugins/merger.js:240:22)
    at MultiAPIMerger.updateRefs (/home/leni/.autorest/@autorest_core@3.0.6320/node_modules/@autorest/core/dist/lib/pipeline/plugins/merger.js:240:22)
    at MultiAPIMerger.updateRefs (/home/leni/.autorest/@autorest_core@3.0.6320/node_modules/@autorest/core/dist/lib/pipeline/plugins/merger.js:240:22)
    at MultiAPIMerger.updateRefs (/home/leni/.autorest/@autorest_core@3.0.6320/node_modules/@autorest/core/dist/lib/pipeline/plugins/merger.js:240:22)
    at MultiAPIMerger.updateRefs (/home/leni/.autorest/@autorest_core@3.0.6320/node_modules/@autorest/core/dist/lib/pipeline/plugins/merger.js:240:22)
    at MultiAPIMerger.updateRefs (/home/leni/.autorest/@autorest_core@3.0.6320/node_modules/@autorest/core/dist/lib/pipeline/plugins/merger.js:240:22)
    at MultiAPIMerger.updateRefs (/home/leni/.autorest/@autorest_core@3.0.6320/node_modules/@autorest/core/dist/lib/pipeline/plugins/merger.js:240:22)
    at MultiAPIMerger.finish (/home/leni/.autorest/@autorest_core@3.0.6320/node_modules/@autorest/core/dist/lib/pipeline/plugins/merger.js:216:14)
    at MultiAPIMerger.runProcess (/node_modules/@azure-tools/datastore/dist/processor.js:78:24)
  Error: $ref to original location 'file:///home/leni/workspace/azure-rest-api-specs/specification/apimanagement/resource-manager/Microsoft.ApiManagement/stable/2019-12-01/apimcontenttypes.json#/definitions/metadata' is not found in the new refs collection
[12.72 s] Shutting Down.
[12.72 s] Exiting.
```

**Comment by leni-msft** [comment]
@daviwil Could you help check again? After we changed the parameters from `--api-version` to `--tag`, the issue is still there.
cc. @fearthecowboy @anthony-c-martin

**Comment by leni-msft** [comment]
Hi @timotheeguerin , the bug seems still there:
```➜  azure-rest-api-specs git:(55543f8ed) ✗ autorest --azureresourceschema --tag=schema-apimanagement-2019-12-01 specification/apimanagement/resource-manager/readme.md
AutoRest code generation utility [cli version: 3.0.6322; node: v12.18.0, max-memory: 2048 MB]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      '/home/leni/.autorest/@autorest_core@3.0.6351/node_modules/@autorest/core/dist' (3.0.6351)
   Loading AutoRest extension '@autorest/azureresourceschema' (~3.0.45->3.0.92)
  Error: $ref to original location 'file:///home/leni/workspace/azure-rest-api-specs/specification/apimanagement/resource-manager/Microsoft.ApiManagement/stable/2019-12-01/apimcontenttypes.json#/definitions/metadata' is not found in the new refs collection
```
Could you check again?

**Comment by timotheeguerin** [comment]
This is weird i tried running the same command as you in the `azure-rest-api-specs` repo and it works. From the logs it also seems like its using the latest `@autorest/core` version so I don't really know why you would have a different result.

Did you try running `autorest --reset`?

**Comment by leni-msft** [comment]
did you checkout the specific revision?
```
git checkout 55543f8edeb99155523c829aff9b51229ade2c51
```

**Comment by leni-msft** [comment]
you can also find the error in https://github.com/Azure/azure-rest-api-specs/pull/12411#issuecomment-759332862 . In the PR, I tried to revert the previous hotfix. So in current master branch, there's no $ref in examples for you to reproduce the bug.

**Comment by timotheeguerin** [comment]
@leni-msft yeah my bad, didn't check it out. I am able to reproduce with the command line you gave. What is weird is if you try to generate the code(add `--python`) then it doesn't crash
