### ISSUE TITLE
[ruby] error while building from azure-rest-api-specs

### ISSUE THREAD

**Issue by tbugfinder** [Azure/autorest#3624]
Hi,

I'd like to create a PR for ruby-sdk however I'm unable to run `autorest --ruby` on azure-rest-api-specs. autorest.ruby repo doesn't allow to open issues (or is the project dead?) so my guess is that this project might maintain or reach out to maintainers of autorest.ruby.
Ruby code is a requirement as the code should be used within inspec.

What's the "hidden" parameter I'm missing here or is it indeed a bug? 

Execution for compute module.
```
[root@localhost resource-manager]# autorest --ruby 
AutoRest code generation utility [cli version: 3.0.6247; node: v12.19.0, max-memory: 768 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
NOTE: AutoRest core version selected from configuration: ~2.0.4413.
   Loading AutoRest core      '/root/.autorest/@microsoft.azure_autorest-core@2.0.4417/node_modules/@microsoft.azure/autorest-core/dist' (2.0.4417)
   Loading AutoRest extension '@microsoft.azure/autorest.ruby' (~3.1.26->3.1.40)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.1.22->2.1.22)
FATAL: System.NullReferenceException: CodeModel doesn't have api-version set, specs in code model have mismatching api-versions.
   at AutoRest.Ruby.Azure.CodeGeneratorRba.<Generate>d__6.MoveNext() in /opt/vsts/work/1/s/src/azure/CodeGeneratorRba.cs:line 52
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AutoRest.Ruby.Program.<ProcessInternal>d__4.MoveNext() in /opt/vsts/work/1/s/src/Program.cs:line 118
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NewPlugin.<Process>d__20.MoveNext() in /opt/vsts/work/1/s/autorest.common/src/Plugins/NewPlugin.cs:line 163
FATAL: ruby/generate - FAILED
FATAL: Error: Plugin ruby reported failure.
Process() cancelled due to exception : Plugin ruby reported failure.
  Error: Plugin ruby reported failure.
[root@localhost resource-manager]# 

```

I get comparable error for execution in the containerregistry module.
```
[root@localhost resource-manager]# pwd
/root/GITHUB/azure-rest-api-specs/specification/containerregistry/resource-manager
[root@localhost resource-manager]# 
[root@localhost resource-manager]# 
[root@localhost resource-manager]# 
[root@localhost resource-manager]# autorest --ruby
AutoRest code generation utility [cli version: 3.0.6247; node: v12.19.0, max-memory: 768 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
NOTE: AutoRest core version selected from configuration: ~2.0.4413.
   Loading AutoRest core      '/root/.autorest/@microsoft.azure_autorest-core@2.0.4417/node_modules/@microsoft.azure/autorest-core/dist' (2.0.4417)
   Loading AutoRest extension '@microsoft.azure/autorest.ruby' (~3.1.26->3.1.40)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.1.22->2.1.22)
FATAL: System.ArgumentNullException: Value cannot be null.
Parameter name: input
   at System.Text.RegularExpressions.Regex.IsMatch(String input)
   at AutoRest.Ruby.Program.<ProcessInternal>d__4.MoveNext() in /opt/vsts/work/1/s/src/Program.cs:line 116
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NewPlugin.<Process>d__20.MoveNext() in /opt/vsts/work/1/s/autorest.common/src/Plugins/NewPlugin.cs:line 163
FATAL: ruby/generate - FAILED
FATAL: Error: Plugin ruby reported failure.
Process() cancelled due to exception : Plugin ruby reported failure.
  Error: Plugin ruby reported failure.
[root@localhost resource-manager]# 

```

Running `autorest --python` just builds nicely.

```
[root@localhost resource-manager]# pwd
/root/GITHUB/azure-rest-api-specs/specification/containerregistry/resource-manager
[root@localhost resource-manager]# 
[root@localhost resource-manager]# 
[root@localhost resource-manager]# 
[root@localhost resource-manager]# autorest --ruby --input-file=./Microsoft.ContainerRegistry/stable/2019-05-01/containerregistry.json 
AutoRest code generation utility [cli version: 3.0.6247; node: v12.19.0, max-memory: 768 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
NOTE: AutoRest core version selected from configuration: ~2.0.4413.
   Loading AutoRest core      '/root/.autorest/@microsoft.azure_autorest-core@2.0.4417/node_modules/@microsoft.azure/autorest-core/dist' (2.0.4417)
   Loading AutoRest extension '@microsoft.azure/autorest.ruby' (~3.1.26->3.1.40)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.1.22->2.1.22)
FATAL: swagger-document/compose - FAILED
FATAL: Error: '$.paths["/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ContainerRegistry/registries/{registryName}/importImage"].post.parameters' has incompatible values (---
- name: api-version
  in: query
  description: The client API version.
  required: true
  type: string
  enum:
    - '2019-05-01'
- $ref: '#/parameters/SubscriptionIdParameter'
- $ref: '#/parameters/ResourceGroupParameter'
- $ref: '#/parameters/RegistryNameParameter'
- name: parameters
  in: body
  description: >-
    The parameters specifying the image to copy and the source container
    registry.
  required: true
  schema:
    $ref: '#/definitions/ImportImageParameters'
, ---
- name: api-version
  in: query
  description: The client API version.
  required: true
  type: string
  enum:
    - 2019-12-01-preview
- $ref: '#/parameters/SubscriptionIdParameter'
- $ref: '#/parameters/ResourceGroupParameter'
- $ref: '#/parameters/RegistryNameParameter'
- name: parameters
  in: body
  description: >-
    The parameters specifying the image to copy and the source container
    registry.
  required: true
  schema:
    $ref: '#/definitions/ImportImageParameters'
).
Process() cancelled due to exception : '$.paths["/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ContainerRegistry/registries/{registryName}/importImage"].post.parameters' has incompatible values (---
- name: api-version
  in: query
  description: The client API version.
  required: true
  type: string
  enum:
    - '2019-05-01'
- $ref: '#/parameters/SubscriptionIdParameter'
- $ref: '#/parameters/ResourceGroupParameter'
- $ref: '#/parameters/RegistryNameParameter'
- name: parameters
  in: body
  description: >-
    The parameters specifying the image to copy and the source container
    registry.
  required: true
  schema:
    $ref: '#/definitions/ImportImageParameters'
, ---
- name: api-version
  in: query
  description: The client API version.
  required: true
  type: string
  enum:
    - 2019-12-01-preview
- $ref: '#/parameters/SubscriptionIdParameter'
- $ref: '#/parameters/ResourceGroupParameter'
- $ref: '#/parameters/RegistryNameParameter'
- name: parameters
  in: body
  description: >-
    The parameters specifying the image to copy and the source container
    registry.
  required: true
  schema:
    $ref: '#/definitions/ImportImageParameters'
).
  Error: '$.paths["/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ContainerRegistry/registries/{registryName}/importImage"].post.parameters' has incompatible values (---
- name: api-version
  in: query
  description: The client API version.
  required: true
  type: string
  enum:
    - '2019-05-01'
- $ref: '#/parameters/SubscriptionIdParameter'
- $ref: '#/parameters/ResourceGroupParameter'
- $ref: '#/parameters/RegistryNameParameter'
- name: parameters
  in: body
  description: >-
    The parameters specifying the image to copy and the source container
    registry.
  required: true
  schema:
    $ref: '#/definitions/ImportImageParameters'
, ---
- name: api-version
  in: query
  description: The client API version.
  required: true
  type: string
  enum:
    - 2019-12-01-preview
- $ref: '#/parameters/SubscriptionIdParameter'
- $ref: '#/parameters/ResourceGroupParameter'
- $ref: '#/parameters/RegistryNameParameter'
- name: parameters
  in: body
  description: >-
    The parameters specifying the image to copy and the source container
    registry.
  required: true
  schema:
    $ref: '#/definitions/ImportImageParameters'
).
[root@localhost resource-manager]# 
```

**Comment by tbugfinder** [comment]
beep

**Comment by lmazuel** [comment]
We don't support the Ruby code generator anymore, and the SDK is going deprecated this year:
https://github.com/Azure/azure-sdk-for-ruby
