### ISSUE TITLE
ModuleNotFoundError: No module named 'yaml' and more

### ISSUE THREAD

**Issue by fuomag9** [Azure/autorest#3732]
Hi, I installed autorest via npm and tried to generate a python client but it failed with `ModuleNotFoundError: No module named 'yaml'`. My local python3 install has it, but the program seems to be using python from `C:\\Users\\fuomag9\\.autorest\\@autorest_python@5.5.0\\node_modules\\@autorest\\python\\venv\\Scripts\\python.exe` instead.
I manually installed `pyaml` on that python but it complained about other dependencies, I installed `jsonrpc` as well but now it's stuck at `ImportError: cannot import name 'dispatcher' from 'jsonrpc' ` with the traceback below:

```
Traceback (most recent call last):
  File "C:\Users\fuomag9\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\fuomag9\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\fuomag9\.autorest\@autorest_python@5.5.0\node_modules\@autorest\python\autorest\jsonrpc\server.py", line 11, in <module>
    from jsonrpc import dispatcher, JSONRPCResponseManager
ImportError: cannot import name 'dispatcher' from 'jsonrpc' (C:\Users\fuomag9\.autorest\@autorest_python@5.5.0\node_modules\@autorest\python\venv\lib\site-packages\jsonrpc\__init__.py)
Command '['C:\\Users\\fuomag9\\.autorest\\@autorest_python@5.5.0\\node_modules\\@autorest\\python\\venv\\Scripts\\python.exe', '-m', 'autorest.jsonrpc.server']' returned non-zero exit status 1.
Process() cancelled due to failure
```

**Comment by iscai-msft** [comment]
hey @fuomag9, can you try running `autorest --reset`?

If that doesn't work, can you let me know your system information (what OS you're using, what kind of termianl)

**Comment by fuomag9** [comment]
> hey @fuomag9, can you try running `autorest --reset`?
> 
> If that doesn't work, can you let me know your system information (what OS you're using, what kind of termianl)

That worked! I managed to generate a python client, but with java it throws a `Error: Plugin javagen reported failure.` error

Full stacktrace ```
VERBOSE [2.15 s]: Reading OpenAPI 3.0 file file:///C:/Users/fuomag9/Downloads/petstore.json

WARNING (PreCheck/CheckDuplicateSchemas): Checking for duplicate schemas, this could take a (long) while.  Run with --verbose for more detail.
VERBOSE [2.28 s]:   ModelerFour/api-version-mode:client
VERBOSE [2.28 s]:   ModelerFour/api-version-parameter:constant
VERBOSE [2.28 s]:   ModelerFour/use-model-namespace:false
  Error: Plugin javagen reported failure.
```

**Comment by fuomag9** [comment]
This is the json I'm using:

```
{
  "openapi": "3.0.0",
  "info": {
    "version": "1.0.0",
    "title": "Swagger Petstore",
    "license": {
      "name": "MIT"
    }
  },
  "servers": [
    {
      "url": "http://petstore.swagger.io/v1"
    }
  ],
  "paths": {
    "/pets": {
      "get": {
        "summary": "List all pets",
        "operationId": "listPets",
        "tags": [
          "pets"
        ],
        "parameters": [
          {
            "name": "limit",
            "in": "query",
            "description": "How many items to return at one time (max 100)",
            "required": false,
            "schema": {
              "type": "integer",
              "format": "int32"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "A paged array of pets",
            "headers": {
              "x-next": {
                "description": "A link to the next page of responses",
                "schema": {
                  "type": "string"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Pets"
                }
              }
            }
          },
          "default": {
            "description": "unexpected error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          }
        }
      },
      "post": {
        "summary": "Create a pet",
        "operationId": "createPets",
        "tags": [
          "pets"
        ],
        "responses": {
          "201": {
            "description": "Null response"
          },
          "default": {
            "description": "unexpected error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          }
        }
      }
    },
    "/pets/{petId}": {
      "get": {
        "summary": "Info for a specific pet",
        "operationId": "showPetById",
        "tags": [
          "pets"
        ],
        "parameters": [
          {
            "name": "petId",
            "in": "path",
            "required": true,
            "description": "The id of the pet to retrieve",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Expected response to a valid request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Pet"
                }
              }
            }
          },
          "default": {
            "description": "unexpected error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Pet": {
        "type": "object",
        "required": [
          "id",
          "name"
        ],
        "properties": {
          "id": {
            "type": "integer",
            "format": "int64"
          },
          "name": {
            "type": "string"
          },
          "tag": {
            "type": "string"
          }
        }
      },
      "Pets": {
        "type": "array",
        "items": {
          "$ref": "#/components/schemas/Pet"
        }
      },
      "Error": {
        "type": "object",
        "required": [
          "code",
          "message"
        ],
        "properties": {
          "code": {
            "type": "integer",
            "format": "int32"
          },
          "message": {
            "type": "string"
          }
        }
      }
    }
  }
}

```

**Comment by iscai-msft** [comment]
Glad that `autorest --reset` worked! It's always the go to for any autorest versioning / packaging issues.

I'm going to drag in @jianghaolu / @srnagar to help with java issues.

**Comment by srnagar** [comment]
@fuomag9 - I just tried to generate Java code for the swagger provided above. I was able to successfully generate the Java client library. How are you trying to generate the Java code? 

For reference, I have provided the command I used (replace output folder name, path to json file and namespace options below).

```sh
 autorest --version=3.0.6282 --java --use=@autorest/java@4.0.4 --output-folder=<your-output-foldername> --sync-methods=all --client-side-validations --add-context-parameter --required-parameter-client-methods --input-file=<relative-path-to-json-file> --namespace=<your-java-root-package-name>
```

**Comment by fuomag9** [comment]
@srnagar the command I'm using is ```autorest --input-file=petstore.json --java --output-folder=prova2 --v3```.

I diffed your command from mine and adding ```--namespace=<anything>``` made it work

**Comment by srnagar** [comment]
@fuomag9 So, were you able to successfully generate Java code?

**Comment by fuomag9** [comment]
@srnagar I was!

**Comment by srnagar** [comment]
Thanks for confirming and closing the issue!
