### ISSUE TITLE
Client is unable to be generated when 1st operation is referenced with $ref

### ISSUE THREAD

**Issue by iorlas** [Azure/autorest#3751]
**Describe the bug**
We've been trying to get an advantage or $ref linking for the paths to split almost 10k-lines sized spec. The issue is, even on a simple spec file, we are unable to produce the client with autorest for the **TypeScript**. It produced an error. The input file was successfully validated with IBM OpenAPI Validator, so there should be 0 issues from the spec itself.

After spending a bit of time investigating it, it feels like autorest-typescript tries to get the host from the first path definition, from the original file(before resolving any refs). So, it fails to do that.

Introducement of the temporary inline route fixes the issue, but it proves that something is wrong.

**Expected behavior**
TypeScript client should be generated, it should have 1 route generated, sourcing it from the $ref, which points to the local file.

**Additional context**
Command: `autorest --azure-validator --input-file=./openapi.yaml --v3 --typescript --output-folder=typescript`

```
WARNING: AutoRest has not been tested with Node versions greater than v14.

AutoRest code generation utility [cli version: 3.0.6322; node: v15.4.0, max-memory: 4096 MB]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      '/Users/iorlas/.autorest/@autorest_core@3.0.6349/node_modules/@autorest/core/dist' (3.0.6349)
   Loading AutoRest extension '@autorest/typescript' (6.0.0-dev.20201105.2->6.0.0-dev.20201105.2)
   Loading AutoRest extension '@microsoft.azure/classic-openapi-validator' (~1.0.9->1.0.14)
   Loading AutoRest extension '@microsoft.azure/openapi-validator' (~1.0.2->1.0.4)
   Loading AutoRest extension '@autorest/modelerfour' (4.15.421->4.15.421)

WARNING (PreCheck/CheckDuplicateSchemas): Checking for duplicate schemas, this could take a (long) while.  Run with --verbose for more detail.
An error was encountered while handling a request: TypeError: Cannot read property 'operations' of undefined
    at Object.transformBaseUrl (/Users/iorlas/.autorest/@autorest_typescript@6.0.0-dev.20201105.2/node_modules/@autorest/typescript/dist/src/transforms/urlTransforms.js:13:59)
    at Object.transformCodeModel (/Users/iorlas/.autorest/@autorest_typescript@6.0.0-dev.20201105.2/node_modules/@autorest/typescript/dist/src/transforms/transforms.js:74:25)
    at async Object.generateTypeScriptLibrary (/Users/iorlas/.autorest/@autorest_typescript@6.0.0-dev.20201105.2/node_modules/@autorest/typescript/dist/src/typescriptGenerator.js:46:27)
    at async processRequest (/Users/iorlas/.autorest/@autorest_typescript@6.0.0-dev.20201105.2/node_modules/@autorest/typescript/dist/src/main.js:12:9)
    at async /Users/iorlas/.autorest/@autorest_typescript@6.0.0-dev.20201105.2/node_modules/@azure-tools/autorest-extension-base/dist/extension-base.js:42:17
FATAL: TypeError: Cannot read property 'operations' of undefined
  Error: Plugin typescript reported failure.

```

openapi.yaml:
```
openapi: 3.0.1
info:
  title: Test API
  version: 1.0.0
servers:
  - url: http://localhost:8080

tags:
  - name: Test
    description: Test my API

paths:
  /api/v1/my_path:
    $ref: "my_path.yaml"

components:
  schemas: {}
```

my_path.yaml
```
post:
  operationId: post_my_path
  tags:
    - Test
  summary: Test summary
  description: Test description
  requestBody:
    content:
      application/json:
        schema:
          type: boolean
  responses:
    200:
      description: Ok
      content:
        application/json:
          schema:
            type: boolean

```

**Comment by timotheeguerin** [comment]
understanding more, this is not something we support at all at the moment. I created a new feature request  #3759. Will close this one.
