### ISSUE TITLE
Error: Plugin typescript reported failure.

### ISSUE THREAD

**Issue by cheahengteong** [Azure/autorest#3754]
**Describe the bug**
I had try the v2/1a-code-generation-minimal and it show me **Error: Plugin typescript reported failure.**
```
cheahengsoon@DESKTOP-IQB8LK0 MINGW64 ~/Documents/GitHub/Handshakes/autorest (master)
$ autorest --typescript --output-foler=Samples\openapi-v2\1a-code-generation-minimal\output --input-file=Samples/openapi-v2/1a-code-generation-minimal/petstore.json --packagename=petstore --package-version=2.0
AutoRest code generation utility [cli version: 3.0.6322; node: v14.15.1, max-memory: 2048 MB]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
NOTE: AutoRest core version selected from configuration: ~3.0.6298.
   Loading AutoRest core      'C:\Users\cheahengsoon\.autorest\@autorest_core@3.0.6349\node_modules\@autorest\core\dist' (3.0.6349)
   Loading AutoRest extension '@autorest/typescript' (6.0.0-dev.20201105.2->6.0.0-dev.20201105.2)
   Loading AutoRest extension '@autorest/modelerfour' (4.15.421->4.15.421)

WARNING (PreCheck/SchemaMissingType): The schema 'User' with an undefined type and decalared properties is a bit ambigious. This has been 
auto-corrected to 'type:object'

WARNING (PreCheck/SchemaMissingType): The schema 'Category' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object'

WARNING (PreCheck/SchemaMissingType): The schema 'Pet' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object'

WARNING (PreCheck/SchemaMissingType): The schema 'Tag' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object'

WARNING (PreCheck/SchemaMissingType): The schema 'Order' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object'

WARNING (PreCheck/CheckDuplicateSchemas): Checking for duplicate schemas, this could take a (long) while.  Run with --verbose for more detail.
An error was encountered while handling a request: Error: Unexpected value type: Sequence
    at Object.getStringForValue (C:\Users\cheahengsoon\.autorest\@autorest_typescript@6.0.0-dev.20201105.2\node_modules\@autorest\typescript\dist\src\utils\valueHelpers.js:60:19)
    at writeDefaultValue (C:\Users\cheahengsoon\.autorest\@autorest_typescript@6.0.0-dev.20201105.2\node_modules\@autorest\typescript\dist\src\generators\mappersGenerator.js:220:61)
    at C:\Users\cheahengsoon\.autorest\@autorest_typescript@6.0.0-dev.20201105.2\node_modules\@autorest\typescript\dist\src\generators\mappersGenerator.js:107:9
    at CodeBlockWriter._indentBlockInternal (C:\Users\cheahengsoon\.autorest\@autorest_typescript@6.0.0-dev.20201105.2\node_modules\code-block-writer\dist\code-block-writer.js:164:13)
    at CodeBlockWriter.inlineBlock (C:\Users\cheahengsoon\.autorest\@autorest_typescript@6.0.0-dev.20201105.2\node_modules\code-block-writer\dist\code-block-writer.js:141:14)
    at CodeBlockWriter.block (C:\Users\cheahengsoon\.autorest\@autorest_typescript@6.0.0-dev.20201105.2\node_modules\code-block-writer\dist\code-block-writer.js:130:14)
    at Object.writeMapper (C:\Users\cheahengsoon\.autorest\@autorest_typescript@6.0.0-dev.20201105.2\node_modules\@autorest\typescript\dist\src\generators\mappersGenerator.js:104:12)
    at writeParameterMapper (C:\Users\cheahengsoon\.autorest\@autorest_typescript@6.0.0-dev.20201105.2\node_modules\@autorest\typescript\dist\src\generators\parametersGenerator.js:76:28)
    at C:\Users\cheahengsoon\.autorest\@autorest_typescript@6.0.0-dev.20201105.2\node_modules\@autorest\typescript\dist\src\generators\parametersGenerator.js:52:17
    at CodeBlockWriter._indentBlockInternal (C:\Users\cheahengsoon\.autorest\@autorest_typescript@6.0.0-dev.20201105.2\node_modules\code-block-writer\dist\code-block-writer.js:164:13)
FATAL: Error: Unexpected value type: Sequence
  Error: Plugin typescript reported failure.

cheahengsoon@DESKTOP-IQB8LK0 MINGW64 ~/Documents/GitHub/Handshakes/autorest (master)
$ npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

audited 102 packages in 1.473s

16 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities


cheahengsoon@DESKTOP-IQB8LK0 MINGW64 ~/Documents/GitHub/Handshakes/autorest (master)
$ autorest --typescript --output-foler=Samples\openapi-v2\1a-code-generation-minimal\output --input-file=Samples/openapi-v2/1a-code-generation-minimal/petstore.json --packagename=petstore --package-version=2.0
AutoRest code generation utility [cli version: 3.0.6322; node: v14.15.1, max-memory: 2048 MB]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
NOTE: AutoRest core version selected from configuration: ~3.0.6298.
   Loading AutoRest core      'C:\Users\cheahengsoon\.autorest\@autorest_core@3.0.6349\node_modules\@autorest\core\dist' (3.0.6349)
   Loading AutoRest extension '@autorest/typescript' (6.0.0-dev.20201105.2->6.0.0-dev.20201105.2)
   Loading AutoRest extension '@autorest/modelerfour' (4.15.421->4.15.421)

WARNING (PreCheck/SchemaMissingType): The schema 'User' with an undefined type and decalared properties is a bit ambigious. This has been 
auto-corrected to 'type:object'

WARNING (PreCheck/SchemaMissingType): The schema 'Category' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object'

WARNING (PreCheck/SchemaMissingType): The schema 'Pet' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object'

WARNING (PreCheck/SchemaMissingType): The schema 'Tag' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object'

WARNING (PreCheck/SchemaMissingType): The schema 'Order' with an undefined type and decalared properties is a bit ambigious. This has been auto-corrected to 'type:object'

WARNING (PreCheck/CheckDuplicateSchemas): Checking for duplicate schemas, this could take a (long) while.  Run with --verbose for more detail.
An error was encountered while handling a request: Error: Unexpected value type: Sequence
    at Object.getStringForValue (C:\Users\cheahengsoon\.autorest\@autorest_typescript@6.0.0-dev.20201105.2\node_modules\@autorest\typescript\dist\src\utils\valueHelpers.js:60:19)
    at writeDefaultValue (C:\Users\cheahengsoon\.autorest\@autorest_typescript@6.0.0-dev.20201105.2\node_modules\@autorest\typescript\dist\src\generators\mappersGenerator.js:220:61)
    at C:\Users\cheahengsoon\.autorest\@autorest_typescript@6.0.0-dev.20201105.2\node_modules\@autorest\typescript\dist\src\generators\mappersGenerator.js:107:9
    at CodeBlockWriter._indentBlockInternal (C:\Users\cheahengsoon\.autorest\@autorest_typescript@6.0.0-dev.20201105.2\node_modules\code-block-writer\dist\code-block-writer.js:164:13)
    at CodeBlockWriter.inlineBlock (C:\Users\cheahengsoon\.autorest\@autorest_typescript@6.0.0-dev.20201105.2\node_modules\code-block-writer\dist\code-block-writer.js:141:14)
    at CodeBlockWriter.block (C:\Users\cheahengsoon\.autorest\@autorest_typescript@6.0.0-dev.20201105.2\node_modules\code-block-writer\dist\code-block-writer.js:130:14)
    at Object.writeMapper (C:\Users\cheahengsoon\.autorest\@autorest_typescript@6.0.0-dev.20201105.2\node_modules\@autorest\typescript\dist\src\generators\mappersGenerator.js:104:12)
    at writeParameterMapper (C:\Users\cheahengsoon\.autorest\@autorest_typescript@6.0.0-dev.20201105.2\node_modules\@autorest\typescript\dist\src\generators\parametersGenerator.js:76:28)
    at C:\Users\cheahengsoon\.autorest\@autorest_typescript@6.0.0-dev.20201105.2\node_modules\@autorest\typescript\dist\src\generators\parametersGenerator.js:52:17
    at CodeBlockWriter._indentBlockInternal (C:\Users\cheahengsoon\.autorest\@autorest_typescript@6.0.0-dev.20201105.2\node_modules\code-block-writer\dist\code-block-writer.js:164:13)
FATAL: Error: Unexpected value type: Sequence
  Error: Plugin typescript reported failure.
```

**Comment by timotheeguerin** [comment]
Believe this might be and issue with https://github.com/Azure/autorest.typescript. I see you are using a dev version `6.0.0-dev.20201105` how are you configuring this and is this expected?
I tried running 
``` bash
autorest --typescript \
    --input-file=$input \
    --clear-output-folder \
    --packagename=petstore \
     --package-version=2.0
```

and it worked just fine but the autorest.typescript version used is `4.2.4` 
```
 Loading AutoRest extension '@microsoft.azure/autorest.typescript' (~4.2.0->4.2.4)
```

**Comment by daviwil** [comment]
Going to move this one to autorest.typescript so they can take a look
