### ISSUE TITLE
Unable to find a valid AutoRest core package '@autorest/core' @ '~3.1.0'

### ISSUE THREAD

**Issue by lima-msft** [Azure/autorest#3904]
**Describe the bug**

Install latest autorest version and hit below failure. From https://github.com/Azure/autorest/releases, could not find 3.1.0 version for autorest-core
```
Error: Unable to find a valid AutoRest core package '@autorest/core' @ '~3.1.0'.
Error: Unable to find a valid AutoRest core package '@autorest/core' @ '~3.1.0'.
    at Object.selectVersion (C:\Users\li\AppData\Roaming\npm\node_modules\autorest\dist\src_autorest-as-a-service_ts-src_coloring_ts.js:297:23)
    at async main (C:\Users\li\AppData\Roaming\npm\node_modules\autorest\dist\app.js:213:31)
```

**Comment by timotheeguerin** [comment]
duplicate of #3904

**Comment by poyyaren** [comment]
> duplicate of #3904

you mean duplicate of #3899 ? Since #3904 is a self-reference....

**Comment by timotheeguerin** [comment]
yes sorry, good catch
