### ISSUE TITLE
[Python]Error when loading AutoRest core (3.0.6373)

### ISSUE THREAD

**Issue by msyyc** [Azure/autorest#3908]
Error happened when using 'python -m packaging_tools.generate_sdk -v -m /_/azure-rest-api-specs/specification/confluent/resource-manager/readme.md'. 
I notice it is ok when loading @autorest_core@3.0.6370. What should I do to pin the version to a stable version?
```
===================detailed info========================
root@auto:/_/azure-sdk-for-python# python -m packaging_tools.generate_sdk -v -m /_/azure-rest-api-specs/specification/confluent/resource-manager/readme.md
INFO:__main__:Readme files: ['/_/azure-rest-api-specs/specification/confluent/resource-manager/readme.md']
INFO:packaging_tools.swaggertosdk.autorest_tools:Looking for swagger-to-sdk section in /_/azure-rest-api-specs/specification/confluent/resource-manager/readme.md
INFO:packaging_tools.swaggertosdk.autorest_tools:==[autorest]AutoRest code generation utility [cli version: 3.0.6339; node: v10.15.0, max-memory: 1280 MB]
INFO:packaging_tools.swaggertosdk.autorest_tools:==[autorest](C) 2018 Microsoft Corporation.
INFO:packaging_tools.swaggertosdk.autorest_tools:==[autorest]https://aka.ms/autorest
INFO:packaging_tools.swaggertosdk.autorest_tools:==[autorest](node:820) ExperimentalWarning: The fs.promises API is experimental
INFO:packaging_tools.swaggertosdk.autorest_tools:==[autorest]   Loading AutoRest core      '/root/.autorest/@autorest_core@3.0.6373/node_modules/@autorest/core/dist' (3.0.6373)
INFO:packaging_tools.swaggertosdk.autorest_tools:==[autorest](node:831) ExperimentalWarning: The fs.promises API is experimental
INFO:packaging_tools.swaggertosdk.autorest_tools:==[autorest]  TypeError: Cannot read property 'pass-thru' of undefined
[Autorest] https://aka.ms/autorest
[Autorest] (node:820) ExperimentalWarning: The fs.promises API is experimental
[Autorest]    Loading AutoRest core      '/root/.autorest/@autorest_core@3.0.6373/node_modules/@autorest/core/dist' (3.0.6373)
[Autorest] (node:831) ExperimentalWarning: The fs.promises API is experimental
[Autorest]   TypeError: Cannot read property 'pass-thru' of undefined
ERROR:packaging_tools.swaggertosdk.autorest_tools:Command '['/usr/local/bin/autorest', '/_/azure-rest-api-specs/specification/confluent/resource-manager/readme.md', '--perform-load=false', '--swagger-to-sdk', '--output-artifact=configuration.json', '--input-file=foo', '--output-folder=/tmp/tmpk_wler0m']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/_/azure-sdk-for-python/tools/azure-sdk-tools/packaging_tools/generate_sdk.py", line 137, in <module>
    generate_main()
  File "/_/azure-sdk-for-python/tools/azure-sdk-tools/packaging_tools/generate_sdk.py", line 134, in generate_main
    args.force)
  File "/_/azure-sdk-for-python/tools/azure-sdk-tools/packaging_tools/generate_sdk.py", line 42, in generate
    extract_conf_from_readmes(swagger_files_in_pr, restapi_git_folder, repotag, config, force_generation=force_generation)
  File "/_/azure-sdk-for-python/tools/azure-sdk-tools/packaging_tools/swaggertosdk/SwaggerToSdkCore.py", line 195, in extract_conf_from_readmes
    build_swaggertosdk_conf_from_json_readme(readme_file, sdk_git_id, config, base_folder=restapi_git_folder, force_generation=force_generation)
  File "/_/azure-sdk-for-python/tools/azure-sdk-tools/packaging_tools/swaggertosdk/SwaggerToSdkCore.py", line 225, in build_swaggertosdk_conf_from_json_readme
    temp_dir
  File "/_/azure-sdk-for-python/tools/azure-sdk-tools/packaging_tools/swaggertosdk/autorest_tools.py", line 27, in autorest_swagger_to_sdk_conf
    execute_simple_command(cmd_line.split())
  File "/_/azure-sdk-for-python/tools/azure-sdk-tools/packaging_tools/swaggertosdk/autorest_tools.py", line 148, in execute_simple_command
    output
subprocess.CalledProcessError: Command '['/usr/local/bin/autorest', '/_/azure-rest-api-specs/specification/confluent/resource-manager/readme.md', '--perform-load=false', '--swagger-to-sdk', '--output-artifact=configuration.json', '--input-file=foo', '--output-folder=/tmp/tmpk_wler0m']' returned non-zero exit status 1.
```

**Comment by kant2002** [comment]
I have similar problem with TypeScript/C# codegen. Location of error following.
```
.autorest\@autorest_core@3.0.6320\node_modules\@autorest\core\dist\lib\pipeline\pipeline.js:266

const passthru = config.GetEntry(node.configScope.last.toString())['pass-thru'] === true || linq_1.values(configView.GetEntry('pass-thru')).any(each => each === pluginName);
```

**Comment by kant2002** [comment]
@timotheeguerin 
and for anybody who hit this error.
I replace 
```
const passthru = config.GetEntry(node.configScope.last.toString())['pass-thru'] === true || linq_1.values(configView.GetEntry('pass-thru')).any(each => each === pluginName);
const usenull = config.GetEntry(node.configScope.last.toString())['null'] === true || linq_1.values(configView.GetEntry('null')).any(each => each === pluginName);
```
with
```
const configEntry = config.GetEntry(node.configScope.last.toString());
const passthru = (configEntry && configEntry['pass-thru'] === true) || linq_1.values(configView.GetEntry('pass-thru')).any(each => each === pluginName);
const usenull = (configEntry && configEntry['null'] === true) || linq_1.values(configView.GetEntry('null')).any(each => each === pluginName);
```
