### ISSUE TITLE
Error: Unable to find a valid AutoRest core package '@autorest/core' @ 'true'.

### ISSUE THREAD

**Issue by banibrata** [Azure/autorest#3910]
**Describe the bug**
```


AutoRest code generation utility [cli version: 3.0.6339; node: v12.20.1, max-memory: 2048 MB]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest

There is a new version of AutoRest available (3.1.1).
 > You can install the newer version with with npm install -g autorest@latest

Failure:
Error: Unable to find a valid AutoRest core package '@autorest/core' @ 'true'.
Error: Unable to find a valid AutoRest core package '@autorest/core' @ 'true'.
    at Object.selectVersion (C:\Users\banide\AppData\Roaming\npm\node_modules\autorest\dist\src\autorest-as-a-service.js:287:23)


After installing the latest, getting the same error:

(base) PS C:\Users\banide> autorest --version
AutoRest code generation utility [cli version: 3.1.1; node: v12.20.1, max-memory: 2048 MB]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
Failure:
Error: Unable to find a valid AutoRest core package '@autorest/core' @ 'true'.
Error: Unable to find a valid AutoRest core package '@autorest/core' @ 'true'.
    at Object.selectVersion (C:\Users\banide\AppData\Roaming\npm\node_modules\autorest\dist\src_autorest-as-a-service_ts-src_coloring_ts.js:303:23)
```

**Expected behavior**
It should show the version

**Additional context**
Same outcome with both Windows and Ubuntu

**Comment by timotheeguerin** [comment]
Autorest `--version` flag is to pick the version of `@autorest/core` it doesn't actually print the version itself. You can use `autorest --info` for information about all the plugins.
