### ISSUE TITLE
@autorest/python generator KeyError: 'description'

### ISSUE THREAD

**Issue by Wuliyuanulb** [Azure/autorest#3946]
Hi,

I am using autorest to generate the pythoh code:

autorest --input-file=swagger.json --output-folder=. --python --namespace=xx --override-client-name=xx

But I encountered this error:

![image](https://user-images.githubusercontent.com/37895561/109769451-2de49c80-7c35-11eb-9390-90af1e6393b3.png)

ERROR: [main.Process:54] Python generator raised an exception
Traceback (most recent call last):
  File "C:\Users\liyw\.autorest\@autorest_python@5.6.4\node_modules\@autorest\python\autorest\jsonrpc\server.py", line 52, in Process
    return plugin.process()
  File "C:\Users\liyw\.autorest\@autorest_python@5.6.4\node_modules\@autorest\python\autorest\init.py", line 54, in process
    self.update_yaml(yaml_data)
  File "C:\Users\liyw\.autorest\@autorest_python@5.6.4\node_modules\@autorest\python\autorest\namer\init.py", line 25, in update_yaml
    NameConverter.convert_yaml_names(yaml_data)
  File "C:\Users\liyw\.autorest\@autorest_python@5.6.4\node_modules\@autorest\python\autorest\namer\name_converter.py", line 25, in convert_yaml_names
    NameConverter._convert_operation_groups(yaml_data['operationGroups'], yaml_data['info']['pascal_case_title'])
  File "C:\Users\liyw\.autorest\@autorest_python@5.6.4\node_modules\@autorest\python\autorest\namer\name_converter.py", line 57, in _convert_operation_groups
    NameConverter._convert_language_default_python_case(parameter, pad_string=PadType.Parameter)
  File "C:\Users\liyw\.autorest\@autorest_python@5.6.4\node_modules\@autorest\python\autorest\namer\name_converter.py", line 182, in _convert_language_default_python_case
    schema_description = schema["language"]["default"]["description"].strip()
KeyError: 'description'
  Error: Plugin namer reported failure.

Using: 
    win10, 
    AutoRest code generation utility [cli version: 3.0.6187; node: v12.19.1]
   Loading AutoRest core      'C:\Users\liyw\.autorest\@autorest_core@3.0.6375\node_modules\@autorest\core\dist' (3.0.6375)
   Loading AutoRest extension '@autorest/python' (latest->5.6.4)
   Loading AutoRest extension '@autorest/modelerfour' (^4.15.456->4.17.1)

Is this a @autorest/python version bug? if yes, how could I let the aotorest use a lower version of @autorest/python? I've tried to downgrade @autorest/python to 5.4.0, however, it's still use 5.6.4.

Thanks a lot.

**Comment by timotheeguerin** [comment]
Hi @Wuliyuanulb is there a swagger spec you could share to try to reproduce the issue?

for pinning a specific version you can add `--use:@autorest/python@5.4..0` or replace with whatever version you want.

**Comment by Wuliyuanulb** [comment]
Hi, @timotheeguerin, sorry I couldn't send you the swagger.json. 
My colleague uses autorest.python version  3.0.56, this version works. However, I couldn't download this version.
Is there a solution for this version?
Thanks a lot.

**Comment by timotheeguerin** [comment]
Hi @Wullyuanulb Without a swagger spec and repro step there isn't much I can do to help here. If you can't share the swagger file. You can try to diagnostic the file yourself by removing elements until you figure out which part cause the issue.
