### ISSUE TITLE
M4: Not able to process media type default at  this moment

### ISSUE THREAD

**Issue by jianyexi** [Azure/autorest#3949]
**Describe the bug**
```
Please provide as much information as you can. This would be: 
- OpenAPI files having the issues
- Autorest command used
npx autorest  https://github.com/Azure/azure-rest-api-specs/blob/5654c7016b4cb7b7d1f56d1174751ce8d64223d7/specification/changeanalysis/resource-manager/readme.md --v3 --output-artifact:code-model-v4 --use:@autorest/modelerfour@4.16.2 --tag=package-2021-04-01 --debug 

```

**Expected behavior**
output good m4 file

**Additional context**
output 
C:\Users\jianyxi\.autorest\@autorest_modelerfour@4.16.2\node_modules\@autorest\modelerfour\dist\main.js - FAILURE  {} Error: Not able to process media type default at 
this moment.
    at ModelerFour.filterMediaTypes (C:\Users\jianyxi\.autorest\@autorest_modelerfour@4.16.2\node_modules\@autorest\src\modeler\modelerfour.ts:1293:21)
    at ModelerFour.processResponses (C:\Users\jianyxi\.autorest\@autorest_modelerfour@4.16.2\node_modules\@autorest\src\modeler\modelerfour.ts:1963:36)
    at ModelerFour.processOperation (C:\Users\jianyxi\.autorest\@autorest_modelerfour@4.16.2\node_modules\@autorest\src\modeler\modelerfour.ts:1593:10)
    at ModelerFour.process (C:\Users\jianyxi\.autorest\@autorest_modelerfour@4.16.2\node_modules\@autorest\src\modeler\modelerfour.ts:2239:14)
    at processRequest (C:\Users\jianyxi\.autorest\@autorest_modelerfour@4.16.2\node_modules\@autorest\src\modeler\plugin-modelerfour.ts:23:31)
    at C:\Users\jianyxi\.autorest\@autorest_modelerfour@4.16.2\node_modules\libs\extension-base\dist\extension-base.js:55:1
PLUGIN FAILURE: Not able to process media type default at this moment., Error: Not able to process media type default at this moment.
    at ModelerFour.filterMediaTypes (C:\Users\jianyxi\.autorest\@autorest_modelerfour@4.16.2\node_modules\@autorest\src\modeler\modelerfour.ts:1293:21)
    at ModelerFour.processResponses (C:\Users\jianyxi\.autorest\@autorest_modelerfour@4.16.2\node_modules\@autorest\src\modeler\modelerfour.ts:1963:36)
    at ModelerFour.processOperation (C:\Users\jianyxi\.autorest\@autorest_modelerfour@4.16.2\node_modules\@autorest\src\modeler\modelerfour.ts:1593:10)
    at ModelerFour.process (C:\Users\jianyxi\.autorest\@autorest_modelerfour@4.16.2\node_modules\@autorest\src\modeler\modelerfour.ts:2239:14)
    at processRequest (C:\Users\jianyxi\.autorest\@autorest_modelerfour@4.16.2\node_modules\@autorest\src\modeler\plugin-modelerfour.ts:23:31)
    at C:\Users\jianyxi\.autorest\@autorest_modelerfour@4.16.2\node_modules\libs\extension-base\dist\extension-base.js:55:1, {}
FATAL: Error: Not able to process media type default at this moment.
C:\Users\jianyxi\.autorest\@autorest_core@3.0.6374\node_modules\@autorest\core\dist\src_lib_autorest-core_ts.js - FAILURE {}
Process() cancelled due to exception : Plugin modelerfour reported failure. / Error: Plugin modelerfour reported failure.
    at C:\Users\jianyxi\.autorest\@autorest_core@3.0.6374\node_modules\@autorest\core\dist\src_lib_autorest-core_ts.js:3745:19
    at async ScheduleNode (C:\Users\jianyxi\.autorest\@autorest_core@3.0.6374\node_modules\@autorest\core\dist\src_lib_autorest-core_ts.js:2543:33)
  Error: Plugin modelerfour reported failure.

**Comment by timotheeguerin** [comment]
The produces in this spec define a media type called `deafult`  https://github.com/Azure/azure-rest-api-specs/blob/5654c7016b4cb7b7d1f56d1174751ce8d64223d7/specification/changeanalysis/resource-manager/Microsoft.ChangeAnalysis/stable/2021-04-01/changeanalysis.json#L21

**Comment by jianyexi** [comment]
> The produces in this spec define a media type called `deafult` https://github.com/Azure/azure-rest-api-specs/blob/5654c7016b4cb7b7d1f56d1174751ce8d64223d7/specification/changeanalysis/resource-manager/Microsoft.ChangeAnalysis/stable/2021-04-01/changeanalysis.json#L21

thanks
