### ISSUE TITLE
Autorest code generation failing with error "Plugin codegen reported failure. / Error: Plugin codegen reported failure."

### ISSUE THREAD

**Issue by Sreevisakh1985** [Azure/autorest#3993]
**Describe the bug**

Hello, 

I am trying to generate python code using the below command

 `autorest --input-file=health.json --python --output-folder=auto_rest_testing/`

Here's my swagger spec. 
```
 {
    "components": {
        "schemas": {
            "HealthState": {
                "description": "An enumeration.",
                "enum": [
                    "Okay",
                    "PartiallyWorking",
                    "NotWorking"
                ],
                "title": "HealthState"
            },
            "HealthStatus": {
                "properties": {
                    "database": {
                        "default": true,
                        "title": "Database",
                        "type": "boolean"
                    },
                    "server": {
                        "title": "Server",
                        "type": "boolean"
                    },
                    "state": {
                        "$ref": "#/components/schemas/HealthState"
                    }
                },
                "required": [
                    "state",
                    "server"
                ],
                "title": "HealthStatus",
                "type": "object"
            }
        }
    },
    "info": {
        "description": "Health Check ",
        "title": "Health Check",
        "version": "0.1.0"
    },
    "openapi": "3.0.2",
    "paths": {
        "/healthcheck": {
            "get": {
                "operationId": "health_get_health",
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/HealthStatus"
                                }
                            }
                        },
                        "description": "Successful Response"
                    }
                },
                "summary": "Get Health",
                "tags": [
                    "health"
                ]
            }
        }
    },
    "tags": [
        {
            "description": "Health check API",
            "name": "health"
        }
    ]
}
```
Here's the autorest version details 
` Type       Extension Name                           Version      Location
 core       @autorest/core                           3.2.1        /Users/smuraleedharan/.autorest/@autorest_core@3.2.1
 extension  @autorest/modelerfour                    4.18.0       /Users/smuraleedharan/.autorest/@autorest_modelerfour@4.18.0
 extension  @autorest/python                         5.6.4        /Users/smuraleedharan/.autorest/@autorest_python@5.6.4`

The code generation failed with the below error
```
AutoRest code generation utility [cli version: 3.1.3; node: v10.16.3, max-memory: 1280 MB]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
Network Enabled: true
Starting @autorest/core from /Users/smuraleedharan/.autorest/@autorest_core@3.2.1
   Loading AutoRest core      '/Users/smuraleedharan/.autorest/@autorest_core@3.2.1/node_modules/@autorest/core/dist' (3.2.1)
VERBOSE [0.68 s]: No configuration found at 'file:///Users/smuraleedharan/Desktop/git_repo/PythonBeginning/'.
VERBOSE [0.69 s]: > Including configuration file 'file:///Users/smuraleedharan/.autorest/@autorest_core@3.2.1/node_modules/@autorest/core/resources/default-configuration.md'
(node:6362) ExperimentalWarning: The fs.promises API is experimental
VERBOSE [0.72 s]: > Including configuration file 'file:///Users/smuraleedharan/.autorest/@autorest_core@3.2.1/node_modules/@autorest/core/resources/inspect.md'
VERBOSE [0.73 s]: > Including configuration file 'file:///Users/smuraleedharan/.autorest/@autorest_core@3.2.1/node_modules/@autorest/core/resources/directives.md'
VERBOSE [0.74 s]: > Including configuration file 'file:///Users/smuraleedharan/.autorest/@autorest_core@3.2.1/node_modules/@autorest/core/resources/pipeline.md'
VERBOSE [0.75 s]: > Including configuration file 'file:///Users/smuraleedharan/.autorest/@autorest_core@3.2.1/node_modules/@autorest/core/resources/loader-openapi.md'
VERBOSE [0.76 s]: > Including configuration file 'file:///Users/smuraleedharan/.autorest/@autorest_core@3.2.1/node_modules/@autorest/core/resources/miscellaneous.md'
VERBOSE [0.77 s]: > Including configuration file 'file:///Users/smuraleedharan/.autorest/@autorest_core@3.2.1/node_modules/@autorest/core/resources/patches.md'
VERBOSE [0.78 s]: > Including configuration file 'file:///Users/smuraleedharan/.autorest/@autorest_core@3.2.1/node_modules/@autorest/core/resources/plugin-powershell.md'
VERBOSE [0.79 s]: > Including configuration file 'file:///Users/smuraleedharan/.autorest/@autorest_core@3.2.1/node_modules/@autorest/core/resources/plugin-azureresourceschema.md'
VERBOSE [0.79 s]: > Including configuration file 'file:///Users/smuraleedharan/.autorest/@autorest_core@3.2.1/node_modules/@autorest/core/resources/plugin-csharp.md'
VERBOSE [0.8 s]: > Including configuration file 'file:///Users/smuraleedharan/.autorest/@autorest_core@3.2.1/node_modules/@autorest/core/resources/plugin-go.md'
VERBOSE [0.81 s]: > Including configuration file 'file:///Users/smuraleedharan/.autorest/@autorest_core@3.2.1/node_modules/@autorest/core/resources/plugin-java.md'
VERBOSE [0.82 s]: > Including configuration file 'file:///Users/smuraleedharan/.autorest/@autorest_core@3.2.1/node_modules/@autorest/core/resources/plugin-nodejs.md'
VERBOSE [0.83 s]: > Including configuration file 'file:///Users/smuraleedharan/.autorest/@autorest_core@3.2.1/node_modules/@autorest/core/resources/plugin-php.md'
VERBOSE [0.83 s]: > Including configuration file 'file:///Users/smuraleedharan/.autorest/@autorest_core@3.2.1/node_modules/@autorest/core/resources/plugin-python.md'
VERBOSE [0.84 s]: > Including configuration file 'file:///Users/smuraleedharan/.autorest/@autorest_core@3.2.1/node_modules/@autorest/core/resources/plugin-ruby.md'
VERBOSE [0.85 s]: > Including configuration file 'file:///Users/smuraleedharan/.autorest/@autorest_core@3.2.1/node_modules/@autorest/core/resources/plugin-typescript.md'
VERBOSE [0.86 s]: > Including configuration file 'file:///Users/smuraleedharan/.autorest/@autorest_core@3.2.1/node_modules/@autorest/core/resources/plugin-validators.md'
VERBOSE [0.88 s]: > Including configuration file 'file:///Users/smuraleedharan/.autorest/@autorest_core@3.2.1/node_modules/@autorest/core/resources/plugin-az.md'
VERBOSE [0.89 s]: > Including configuration file 'file:///Users/smuraleedharan/.autorest/@autorest_core@3.2.1/node_modules/@autorest/core/resources/plugin-terraform.md'
VERBOSE [0.9 s]: > Including configuration file 'file:///Users/smuraleedharan/.autorest/@autorest_core@3.2.1/node_modules/@autorest/core/resources/plugin-azure-functions.md'
VERBOSE [0.91 s]: > Including configuration file 'file:///Users/smuraleedharan/.autorest/@autorest_core@3.2.1/node_modules/@autorest/core/resources/graphs.md'
VERBOSE [0.93 s]: > Including configuration file 'file:///Users/smuraleedharan/.autorest/@autorest_core@3.2.1/node_modules/@autorest/core/resources/help-configuration.md'
INFORMATION: > Loading AutoRest extension '@autorest/python' (latest->5.6.4)
VERBOSE [1.61 s]: > Including extension configuration file 'file:///Users/smuraleedharan/.autorest/@autorest_python@5.6.4/node_modules/@autorest/python/README.md'
VERBOSE [1.61 s]: > Including configuration file 'file:///Users/smuraleedharan/.autorest/@autorest_python@5.6.4/node_modules/@autorest/python/README.md'
INFORMATION: > Loading AutoRest extension '@autorest/modelerfour' (^4.15.456->4.18.0)
VERBOSE [1.68 s]: > Including extension configuration file 'file:///Users/smuraleedharan/.autorest/@autorest_modelerfour@4.18.0/node_modules/@autorest/modelerfour/readme.md'
VERBOSE [1.68 s]: > Including configuration file 'file:///Users/smuraleedharan/.autorest/@autorest_modelerfour@4.18.0/node_modules/@autorest/modelerfour/readme.md'
DEBUG [2.49 s]: swagger-document/loader-swagger - START inputs = 0
DEBUG [2.49 s]: openapi-document/loader-openapi - START inputs = 0
DEBUG [2.49 s]: configuration-emitter - START inputs = 0
DEBUG [2.49 s]: pipeline-emitter - START inputs = 0
DEBUG [2.55 s]: configuration-emitter - END [0.06 s]
DEBUG [2.55 s]: pipeline-emitter - END [0.06 s]
VERBOSE [2.57 s]: Reading OpenAPI 3.0 file file:///Users/smuraleedharan/Desktop/git_repo/PythonBeginning/health.json
DEBUG [2.57 s]: swagger-document/loader-swagger - END [0.08 s]
DEBUG [2.57 s]: swagger-document/individual/transform - SKIPPING
DEBUG [2.57 s]: swagger-document/individual/schema-validator-swagger - SKIPPING
DEBUG [2.57 s]: swagger-document/identity - SKIPPING
DEBUG [2.57 s]: swagger-document/individual/identity - SKIPPING
DEBUG [2.57 s]: openapi-document/openapi-document-converter - SKIPPING
DEBUG [2.58 s]: openapi-document/loader-openapi - END [0.09 s]
DEBUG [2.58 s]: openapi-document/individual/transform - START inputs = 1
DEBUG [2.59 s]: openapi-document/individual/transform - END [0 s]
DEBUG [2.59 s]: openapi-document/individual/schema-validator-openapi - START inputs = 1
DEBUG [2.71 s]: openapi-document/individual/schema-validator-openapi - END [0.12 s]
DEBUG [2.71 s]: openapi-document/individual/identity - START inputs = 1
DEBUG [2.71 s]: openapi-document/individual/identity - END [0 s]
DEBUG [2.71 s]: openapi-document/transform - START inputs = 1
DEBUG [2.72 s]: openapi-document/transform - END [0 s]
DEBUG [2.72 s]: openapi-document/allof-cleaner - START inputs = 1
DEBUG [2.72 s]: openapi-document/allof-cleaner - END [0 s]
DEBUG [2.72 s]: openapi-document/tree-shaker - START inputs = 1
DEBUG [2.72 s]: openapi-document/tree-shaker - END [0 s]
DEBUG [2.72 s]: openapi-document/multi-api-merger - START inputs = 1
DEBUG [2.73 s]: openapi-document/multi-api-merger - END [0 s]
DEBUG [2.73 s]: openapi-document/components-cleaner - START inputs = 1
DEBUG [2.73 s]: openapi-document/components-cleaner - END [0 s]
DEBUG [2.73 s]: openapi-document/component-modifiers - START inputs = 1
DEBUG [2.74 s]: openapi-document/component-modifiers - END [0 s]
DEBUG [2.74 s]: openapi-document/api-version-parameter-handler - START inputs = 1
DEBUG [2.74 s]: openapi-document/api-version-parameter-handler - END [0 s]
DEBUG [2.74 s]: openapi-document/profile-filter - START inputs = 1
DEBUG [2.74 s]: openapi-document/profile-filter - END [0 s]
DEBUG [2.74 s]: openapi-document/model-deduplicator - START inputs = 1
DEBUG [2.74 s]: openapi-document/emitter - START inputs = 1
DEBUG [2.74 s]: openapi-document/model-deduplicator - END [0 s]
DEBUG [2.74 s]: openapi-document/enum-deduplicator - START inputs = 1
DEBUG [2.74 s]: openapi-document/emitter - END [0 s]
DEBUG [2.75 s]: openapi-document/enum-deduplicator - END [0 s]
DEBUG [2.75 s]: openapi-document/subset-reducer - START inputs = 1
DEBUG [2.75 s]: openapi-document/subset-reducer - END [0 s]
DEBUG [2.75 s]: openapi-document/quick-check - START inputs = 1
DEBUG [2.75 s]: openapi-document/multi-api/reset-identity - START inputs = 1
DEBUG [2.75 s]: openapi-document/quick-check - END [0 s]
DEBUG [2.75 s]: openapi-document/multi-api/reset-identity - END [0 s]
DEBUG [2.75 s]: openapi-document/multi-api/identity - START inputs = 1
DEBUG [2.75 s]: openapi-document/multi-api/identity - END [0 s]
DEBUG [2.75 s]: openapi-document/multi-api/emitter - START inputs = 1
DEBUG [2.75 s]: prechecker - START inputs = 1
DEBUG [2.75 s]: openapi-document/multi-api/emitter - END [0 s]

WARNING (PreCheck/CheckDuplicateSchemas): Checking for duplicate schemas, this could take a (long) while.  Run with --verbose for more detail.
DEBUG [2.8 s]: prechecker - END [0.04 s]
DEBUG [2.8 s]: modelerfour - START inputs = 2
VERBOSE [2.83 s]:   ModelerFour/api-version-mode:client
VERBOSE [2.83 s]:   ModelerFour/api-version-parameter:constant
VERBOSE [2.83 s]:   ModelerFour/use-model-namespace:false

WARNING (Modeler/MissingType): The enum schema 'HealthState' with an undefined type and enum values is ambigious. This has been auto-corrected to 'type:string'
DEBUG [2.85 s]: modelerfour - END [0.05 s]
DEBUG [2.85 s]: modelerfour/new-transform - START inputs = 2
DEBUG [2.85 s]: modelerfour/new-transform - END [0 s]
DEBUG [2.85 s]: modelerfour/flattener - START inputs = 2
DEBUG [2.88 s]: modelerfour/flattener - END [0.03 s]
DEBUG [2.88 s]: modelerfour/flattener/new-transform - START inputs = 2
DEBUG [2.88 s]: modelerfour/flattener/new-transform - END [0 s]
DEBUG [2.88 s]: modelerfour/grouper - START inputs = 2
DEBUG [2.92 s]: modelerfour/grouper - END [0.03 s]
DEBUG [2.92 s]: modelerfour/grouper/new-transform - START inputs = 2
DEBUG [2.92 s]: modelerfour/grouper/new-transform - END [0 s]
DEBUG [2.92 s]: modelerfour/pre-namer - START inputs = 2
DEBUG [2.97 s]: modelerfour/pre-namer - END [0.04 s]
DEBUG [2.97 s]: modelerfour/pre-namer/new-transform - START inputs = 2
DEBUG [2.97 s]: modelerfour/pre-namer/new-transform - END [0 s]
DEBUG [2.97 s]: modelerfour/checker - START inputs = 4
DEBUG [2.99 s]: modelerfour/checker - END [0.02 s]
DEBUG [2.99 s]: modelerfour/identity - START inputs = 2
DEBUG [2.99 s]: modelerfour/identity - END [0 s]
DEBUG [3 s]: python - START inputs = 2
DEBUG [3 s]: modelerfour/emitter - START inputs = 2
DEBUG [3 s]: modelerfour/notags/emitter - START inputs = 2
DEBUG [3 s]: python - END [0 s]
DEBUG [3 s]: python/m2r - START inputs = 2
DEBUG [3 s]: modelerfour/emitter - END [0 s]
DEBUG [3 s]: modelerfour/notags/emitter - END [0 s]
DEBUG [3 s]: [main.Process:33] Autorest called process with plugin_name 'm2r' and session_id: 'session_7'
DEBUG [3.13 s]: [main.Process:51] Starting plugin M2R
DEBUG [3.13 s]: [autorest.jsonrpc.stdstream.list_inputs:81] Calling list inputs to Autorest
DEBUG [3.13 s]: [autorest.jsonrpc.stdstream.read_message:27] Received: b'Content-Length: 86'
DEBUG [3.13 s]: [autorest.jsonrpc.stdstream.read_message:36] Trying to read the message
DEBUG [3.13 s]: [autorest.jsonrpc.stdstream.read_message:40] Received a 86 bytes message
DEBUG [3.13 s]: [autorest.process:47] Possible Inputs: ['code-model-v4.yaml', 'code-model-v4-no-tags.yaml']
DEBUG [3.13 s]: [autorest.jsonrpc.stdstream.read_file:74] Asking content for file code-model-v4-no-tags.yaml
DEBUG [3.13 s]: [autorest.jsonrpc.stdstream.read_message:27] Received: b'Content-Length: 4658'
DEBUG [3.13 s]: [autorest.jsonrpc.stdstream.read_message:36] Trying to read the message
DEBUG [3.13 s]: [autorest.jsonrpc.stdstream.read_message:40] Received a 4658 bytes message
DEBUG [3.16 s]: [autorest.jsonrpc.stdstream.write_file:64] Writing a file: code-model-v4-no-tags.yaml
DEBUG [3.16 s]: python/m2r - END [0.16 s]
DEBUG [3.16 s]: python/namer - START inputs = 1
DEBUG [3.17 s]: [main.Process:33] Autorest called process with plugin_name 'namer' and session_id: 'session_8'
DEBUG [3.17 s]: [main.Process:51] Starting plugin Namer
DEBUG [3.17 s]: [autorest.jsonrpc.stdstream.list_inputs:81] Calling list inputs to Autorest
DEBUG [3.17 s]: [autorest.jsonrpc.stdstream.read_message:27] Received: b'Content-Length: 65'
DEBUG [3.17 s]: [autorest.jsonrpc.stdstream.read_message:36] Trying to read the message
DEBUG [3.17 s]: [autorest.jsonrpc.stdstream.read_message:40] Received a 65 bytes message
DEBUG [3.17 s]: [autorest.process:47] Possible Inputs: ['code-model-v4-no-tags.yaml']
DEBUG [3.17 s]: [autorest.jsonrpc.stdstream.read_file:74] Asking content for file code-model-v4-no-tags.yaml
DEBUG [3.17 s]: [autorest.jsonrpc.stdstream.read_message:27] Received: b'Content-Length: 4555'
DEBUG [3.17 s]: [autorest.jsonrpc.stdstream.read_message:36] Trying to read the message
DEBUG [3.17 s]: [autorest.jsonrpc.stdstream.read_message:40] Received a 4555 bytes message
DEBUG [3.2 s]: [autorest.jsonrpc.stdstream.write_file:64] Writing a file: code-model-v4-no-tags.yaml
DEBUG [3.2 s]: python/namer - END [0.04 s]
DEBUG [3.2 s]: python/codegen - START inputs = 1
DEBUG [3.21 s]: [main.Process:33] Autorest called process with plugin_name 'codegen' and session_id: 'session_9'
DEBUG [3.24 s]: [main.Process:51] Starting plugin CodeGenerator
DEBUG [3.24 s]: [autorest.jsonrpc.stdstream.list_inputs:81] Calling list inputs to Autorest
DEBUG [3.24 s]: [autorest.jsonrpc.stdstream.read_message:27] Received: b'Content-Length: 65'
DEBUG [3.24 s]: [autorest.jsonrpc.stdstream.read_message:36] Trying to read the message
DEBUG [3.24 s]: [autorest.jsonrpc.stdstream.read_message:40] Received a 65 bytes message
DEBUG [3.24 s]: [autorest.codegen.process:265] Possible Inputs: ['code-model-v4-no-tags.yaml']
DEBUG [3.24 s]: [autorest.jsonrpc.stdstream.read_file:74] Asking content for file code-model-v4-no-tags.yaml
DEBUG [3.24 s]: [autorest.jsonrpc.stdstream.read_message:27] Received: b'Content-Length: 6415'
DEBUG [3.24 s]: [autorest.jsonrpc.stdstream.read_message:36] Trying to read the message
DEBUG [3.24 s]: [autorest.jsonrpc.stdstream.read_message:40] Received a 6415 bytes message
DEBUG [3.27 s]: [autorest.jsonrpc.stdstream.get_value:87] Calling get value to Autorest: azure-arm
DEBUG [3.27 s]: [autorest.jsonrpc.stdstream.read_message:27] Received: b'Content-Length: 40'
DEBUG [3.27 s]: [autorest.jsonrpc.stdstream.read_message:36] Trying to read the message
DEBUG [3.27 s]: [autorest.jsonrpc.stdstream.read_message:40] Received a 40 bytes message
DEBUG [3.27 s]: [autorest.jsonrpc.stdstream.get_value:87] Calling get value to Autorest: add-credentials
DEBUG [3.27 s]: [autorest.jsonrpc.stdstream.read_message:27] Received: b'Content-Length: 39'
DEBUG [3.27 s]: [autorest.jsonrpc.stdstream.read_message:36] Trying to read the message
DEBUG [3.27 s]: [autorest.jsonrpc.stdstream.read_message:40] Received a 39 bytes message
DEBUG [3.27 s]: [autorest.jsonrpc.stdstream.get_value:87] Calling get value to Autorest: add-credential
DEBUG [3.27 s]: [autorest.jsonrpc.stdstream.read_message:27] Received: b'Content-Length: 39'
DEBUG [3.27 s]: [autorest.jsonrpc.stdstream.read_message:36] Trying to read the message
DEBUG [3.27 s]: [autorest.jsonrpc.stdstream.read_message:40] Received a 39 bytes message
DEBUG [3.27 s]: [autorest.jsonrpc.stdstream.get_value:87] Calling get value to Autorest: credential-default-policy-type
DEBUG [3.28 s]: [autorest.jsonrpc.stdstream.read_message:27] Received: b'Content-Length: 39'
DEBUG [3.28 s]: [autorest.jsonrpc.stdstream.read_message:36] Trying to read the message
DEBUG [3.28 s]: [autorest.jsonrpc.stdstream.read_message:40] Received a 39 bytes message
DEBUG [3.28 s]: [autorest.jsonrpc.stdstream.get_value:87] Calling get value to Autorest: credential-scopes
DEBUG [3.28 s]: [autorest.jsonrpc.stdstream.read_message:27] Received: b'Content-Length: 39'
DEBUG [3.28 s]: [autorest.jsonrpc.stdstream.read_message:36] Trying to read the message
DEBUG [3.28 s]: [autorest.jsonrpc.stdstream.read_message:40] Received a 39 bytes message
DEBUG [3.28 s]: [autorest.jsonrpc.stdstream.get_value:87] Calling get value to Autorest: credential-scopes
DEBUG [3.28 s]: [autorest.jsonrpc.stdstream.read_message:27] Received: b'Content-Length: 39'
DEBUG [3.28 s]: [autorest.jsonrpc.stdstream.read_message:36] Trying to read the message
DEBUG [3.28 s]: [autorest.jsonrpc.stdstream.read_message:40] Received a 39 bytes message
DEBUG [3.28 s]: [autorest.jsonrpc.stdstream.get_value:87] Calling get value to Autorest: credential-key-header-name
DEBUG [3.28 s]: [autorest.jsonrpc.stdstream.read_message:27] Received: b'Content-Length: 39'
DEBUG [3.28 s]: [autorest.jsonrpc.stdstream.read_message:36] Trying to read the message
DEBUG [3.28 s]: [autorest.jsonrpc.stdstream.read_message:40] Received a 39 bytes message
DEBUG [3.28 s]: [autorest.jsonrpc.stdstream.get_value:87] Calling get value to Autorest: header-text
DEBUG [3.28 s]: [autorest.jsonrpc.stdstream.read_message:27] Received: b'Content-Length: 217'
DEBUG [3.28 s]: [autorest.jsonrpc.stdstream.read_message:36] Trying to read the message
DEBUG [3.28 s]: [autorest.jsonrpc.stdstream.read_message:40] Received a 217 bytes message
DEBUG [3.28 s]: [autorest.jsonrpc.stdstream.get_value:87] Calling get value to Autorest: head-as-boolean
DEBUG [3.28 s]: [autorest.jsonrpc.stdstream.read_message:27] Received: b'Content-Length: 39'
DEBUG [3.28 s]: [autorest.jsonrpc.stdstream.read_message:36] Trying to read the message
DEBUG [3.28 s]: [autorest.jsonrpc.stdstream.read_message:40] Received a 39 bytes message
DEBUG [3.28 s]: [autorest.jsonrpc.stdstream.get_value:87] Calling get value to Autorest: keep-version-file
DEBUG [3.28 s]: [autorest.jsonrpc.stdstream.read_message:27] Received: b'Content-Length: 39'
DEBUG [3.28 s]: [autorest.jsonrpc.stdstream.read_message:36] Trying to read the message
DEBUG [3.28 s]: [autorest.jsonrpc.stdstream.read_message:40] Received a 39 bytes message
DEBUG [3.28 s]: [autorest.jsonrpc.stdstream.get_value:87] Calling get value to Autorest: no-async
DEBUG [3.28 s]: [autorest.jsonrpc.stdstream.read_message:27] Received: b'Content-Length: 39'
DEBUG [3.28 s]: [autorest.jsonrpc.stdstream.read_message:36] Trying to read the message
DEBUG [3.28 s]: [autorest.jsonrpc.stdstream.read_message:40] Received a 39 bytes message
DEBUG [3.28 s]: [autorest.jsonrpc.stdstream.get_value:87] Calling get value to Autorest: no-namespace-folders
DEBUG [3.28 s]: [autorest.jsonrpc.stdstream.read_message:27] Received: b'Content-Length: 39'
DEBUG [3.28 s]: [autorest.jsonrpc.stdstream.read_message:36] Trying to read the message
DEBUG [3.28 s]: [autorest.jsonrpc.stdstream.read_message:40] Received a 39 bytes message
DEBUG [3.28 s]: [autorest.jsonrpc.stdstream.get_value:87] Calling get value to Autorest: basic-setup-py
DEBUG [3.28 s]: [autorest.jsonrpc.stdstream.read_message:27] Received: b'Content-Length: 39'
DEBUG [3.28 s]: [autorest.jsonrpc.stdstream.read_message:36] Trying to read the message
DEBUG [3.28 s]: [autorest.jsonrpc.stdstream.read_message:40] Received a 39 bytes message
DEBUG [3.28 s]: [autorest.jsonrpc.stdstream.get_value:87] Calling get value to Autorest: package-name
DEBUG [3.28 s]: [autorest.jsonrpc.stdstream.read_message:27] Received: b'Content-Length: 39'
DEBUG [3.28 s]: [autorest.jsonrpc.stdstream.read_message:36] Trying to read the message
DEBUG [3.28 s]: [autorest.jsonrpc.stdstream.read_message:40] Received a 39 bytes message
DEBUG [3.28 s]: [autorest.jsonrpc.stdstream.get_value:87] Calling get value to Autorest: package-version
DEBUG [3.28 s]: [autorest.jsonrpc.stdstream.read_message:27] Received: b'Content-Length: 39'
DEBUG [3.28 s]: [autorest.jsonrpc.stdstream.read_message:36] Trying to read the message
DEBUG [3.28 s]: [autorest.jsonrpc.stdstream.read_message:40] Received a 39 bytes message
DEBUG [3.28 s]: [autorest.jsonrpc.stdstream.get_value:87] Calling get value to Autorest: client-side-validation
DEBUG [3.28 s]: [autorest.jsonrpc.stdstream.read_message:27] Received: b'Content-Length: 39'
DEBUG [3.28 s]: [autorest.jsonrpc.stdstream.read_message:36] Trying to read the message
DEBUG [3.28 s]: [autorest.jsonrpc.stdstream.read_message:40] Received a 39 bytes message
DEBUG [3.28 s]: [autorest.jsonrpc.stdstream.get_value:87] Calling get value to Autorest: trace
DEBUG [3.28 s]: [autorest.jsonrpc.stdstream.read_message:27] Received: b'Content-Length: 39'
DEBUG [3.28 s]: [autorest.jsonrpc.stdstream.read_message:36] Trying to read the message
DEBUG [3.28 s]: [autorest.jsonrpc.stdstream.read_message:40] Received a 39 bytes message
DEBUG [3.28 s]: [autorest.jsonrpc.stdstream.get_value:87] Calling get value to Autorest: multiapi
DEBUG [3.28 s]: [autorest.jsonrpc.stdstream.read_message:27] Received: b'Content-Length: 39'
DEBUG [3.28 s]: [autorest.jsonrpc.stdstream.read_message:36] Trying to read the message
DEBUG [3.28 s]: [autorest.jsonrpc.stdstream.read_message:40] Received a 39 bytes message
DEBUG [3.28 s]: [autorest.codegen.models.operation_group.from_yaml:82] Parsing health operation group
DEBUG [3.28 s]: [autorest.codegen.models.operation.from_yaml:244] Parsing get_health operation
DEBUG [3.28 s]: [autorest.jsonrpc.stdstream.get_value:87] Calling get value to Autorest: namespace
DEBUG [3.29 s]: [autorest.jsonrpc.stdstream.read_message:27] Received: b'Content-Length: 39'
DEBUG [3.29 s]: [autorest.jsonrpc.stdstream.read_message:36] Trying to read the message
DEBUG [3.29 s]: [autorest.jsonrpc.stdstream.read_message:40] Received a 39 bytes message
DEBUG [3.29 s]: [autorest.codegen._create_code_model:99] Namespace parameter was None
ERROR: [main.Process:54] Python generator raised an exception
Traceback (most recent call last):
  File "/Users/smuraleedharan/.autorest/@autorest_python@5.6.4/node_modules/@autorest/python/autorest/jsonrpc/server.py", line 52, in Process
    return plugin.process()
  File "/Users/smuraleedharan/.autorest/@autorest_python@5.6.4/node_modules/@autorest/python/autorest/codegen/init.py", line 279, in process
    code_model = self._create_code_model(yaml_data=yaml_data, options=options)
  File "/Users/smuraleedharan/.autorest/@autorest_python@5.6.4/node_modules/@autorest/python/autorest/codegen/init.py", line 109, in _create_code_model
    build_schema(yaml_data=schema, exceptions_set=exceptions_set, code_model=code_model)
  File "/Users/smuraleedharan/.autorest/@autorest_python@5.6.4/node_modules/@autorest/python/autorest/codegen/models/init.py", line 81, in build_schema
    schema = EnumSchema.from_yaml(namespace=namespace, yaml_data=yaml_data, **kwargs)
  File "/Users/smuraleedharan/.autorest/@autorest_python@5.6.4/node_modules/@autorest/python/autorest/codegen/models/enum_schema.py", line 151, in from_yaml
    values = EnumSchema._get_enum_values(yaml_data["choices"])
  File "/Users/smuraleedharan/.autorest/@autorest_python@5.6.4/node_modules/@autorest/python/autorest/codegen/models/enum_schema.py", line 130, in _get_enum_values
    values.append(EnumValue.from_yaml(enum))
  File "/Users/smuraleedharan/.autorest/@autorest_python@5.6.4/node_modules/@autorest/python/autorest/codegen/models/enum_schema.py", line 37, in from_yaml
    value=yaml_data["value"],
KeyError: 'value'
/Users/smuraleedharan/.autorest/@autorest_core@3.2.1/node_modules/@autorest/core/dist/src_lib_autorest-core_ts.js - FAILURE {}
Process() cancelled due to exception : Plugin codegen reported failure. / Error: Plugin codegen reported failure.
    at /Users/smuraleedharan/.autorest/@autorest_core@3.2.1/node_modules/@autorest/core/dist/src_lib_autorest-core_ts.js:3060:19
  Error: Plugin codegen reported failure.
[3.29 s] Shutting Down.
[3.29 s] Exiting.`

```
    
When I removed the enum HealthState from the swagger, the generation got successful. Not sure if the issues is caused by the enum.  Should I need to change my pythoncore version ? 

Also I noticed that autorest --version is failing with the following. Not sure if this is related to the above issue. 

` autorest --version
AutoRest code generation utility [cli version: 3.1.3; node: v10.16.3, max-memory: 1280 MB]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
Failure:
Error: Unable to find a valid AutoRest core package '@autorest/core' @ 'true'.
Error: Unable to find a valid AutoRest core package '@autorest/core' @ 'true'.
    at Object.selectVersion (/Users/smuraleedharan/.nvm/versions/node/v10.16.3/lib/node_modules/autorest/dist/src_autorest-as-a-service_ts-src_coloring_ts.js:303:23)` 

Appreciate the help

**Comment by timotheeguerin** [comment]
You are missing `"type": "string"` on the enum which is not a valid openapi definition. Now autorest should automatically default to string when enum is provided as the warning in the logs explain so seems like that part is broken

**Comment by Sreevisakh1985** [comment]
Thanks for the quick response. This spec was generated by fastapi and in my model definition I was just passing enum like below 
`class HealthState( Enum):`

That's the reason the spec didn't have the type. 

Once I updated the type in the declaration , the new spec generated with the type and I am able to generate the code now. 
`class HealthState(str, Enum):` 

Thanks once again for the quick response. Really appreciate it
