### ISSUE TITLE
SyntaxError: Unexpected end of JSON input for java on 3.1.5

### ISSUE THREAD

**Issue by claudiowilson** [Azure/autorest#4098]
I was noticing my autorest command failing to generate code for java. The error was

```
AutoRest code generation utility [cli version: 3.1.5; node: v14.16.1, max-memory: 4096 MB]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
Failure:
SyntaxError: Unexpected end of JSON input
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Yarn.getPackageVersions (/Users/claudiowilson/.npm-packages/lib/node_modules/autorest/dist/src_autorest-as-a-service_ts-src_coloring_ts.js:1754:21)
    at ExtensionManager.getPackageVersions (/Users/claudiowilson/.npm-packages/lib/node_modules/autorest/dist/src_autorest-as-a-service_ts-src_coloring_ts.js:982:26)
    at ExtensionManager.findPackage (/Users/claudiowilson/.npm-packages/lib/node_modules/autorest/dist/src_autorest-as-a-service_ts-src_coloring_ts.js:998:31)
    at ConfigurationLoader.resolveExtension (/Users/claudiowilson/.npm-packages/lib/node_modules/autorest/dist/app.js:4718:30)
    at ConfigurationLoader.load (/Users/claudiowilson/.npm-packages/lib/node_modules/autorest/dist/app.js:4613:43)
    at Object.findCoreVersionUsingConfiguration (/Users/claudiowilson/.npm-packages/lib/node_modules/autorest/dist/app.js:504:24)
    at Object.resolveCoreVersion (/Users/claudiowilson/.npm-packages/lib/node_modules/autorest/dist/app.js:540:28)
    at main (/Users/claudiowilson/.npm-packages/lib/node_modules/autorest/dist/app.js:186:33)
```

I thought this was because of my API definition somehow, but I used the sample openAPI definition [here](https://swagger.io/docs/specification/basic-structure/) and the error still appeared.

Here's the command used `autorest --input-file=sample.yaml --java`, and here's the yaml used.

```
openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing
paths:
  /users:
    get:
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string

```

**Expected behavior**
I expect autorest to be able to generate code for the yaml given for java.

**Additional context**
The command works for other language flags like `--go`, but specifically not for java.

**Comment by timotheeguerin** [comment]
@claudiowilson can you try replacing `--java` with ` --use:@autorest/java@4.0.24` Believe the issue is the fact that autorest.java extension is not published to npm yet and by default doesn't define an exact version so i can't resolve it from the github url.

**Comment by claudiowilson** [comment]
@timotheeguerin that did the trick! thank you!

```
autorest --input-file=sample.yaml --use:@autorest/java@4.0.24                                                                                                                                             
AutoRest code generation utility [cli version: 3.1.5; node: v14.16.1, max-memory: 4096 MB]                                                                                                                  
(C) 2018 Microsoft Corporation.                                                                                                                                                                             
https://aka.ms/autorest                                                                                                                                                                                     
   Loading AutoRest core      '/Users/claudiowilson/.autorest/@autorest_core@3.3.2/node_modules/@autorest/core/dist' (3.3.2)                                                                                
INFORMATION: > Loading AutoRest extension '@autorest/java' (4.0.24->4.0.24)                                                                                                                                 
[4.44 s] Generation Complete
```
