### ISSUE TITLE
Kusto: autorest fails to create PS client

### ISSUE THREAD

**Issue by astauben** [Azure/autorest#4104]
Hi,
I'm trying to generate PS client using 'autorest' and getting the following error:

"
WARNING: AutoRest has not been tested with Node versions greater than v14.

AutoRest code generation utility [cli version: 3.2.0; node: v16.0.0, max-memory: 4096 MB]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
Failure:
SyntaxError: Unexpected token { in JSON at position 95
SyntaxError: Unexpected token { in JSON at position 95
    at JSON.parse (<anonymous>)
    at Yarn.getPackageVersions (C:\Users\astauben\AppData\Roaming\npm\node_modules\autorest\dist\src_autorest-as-a-service_ts-src_coloring_ts.js:1759:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at ExtensionManager.getPackageVersions (C:\Users\astauben\AppData\Roaming\npm\node_modules\autorest\dist\src_autorest-as-a-service_ts-src_coloring_ts.js:982:26)
    at ExtensionManager.findPackage (C:\Users\astauben\AppData\Roaming\npm\node_modules\autorest\dist\src_autorest-as-a-service_ts-src_coloring_ts.js:998:31)
    at ConfigurationLoader.resolveExtension (C:\Users\astauben\AppData\Roaming\npm\node_modules\autorest\dist\app.js:4812:30)
    at ConfigurationLoader.load (C:\Users\astauben\AppData\Roaming\npm\node_modules\autorest\dist\app.js:4707:43)
    at Object.findCoreVersionUsingConfiguration (C:\Users\astauben\AppData\Roaming\npm\node_modules\autorest\dist\app.js:457:24)
    at Object.resolveCoreVersion (C:\Users\astauben\AppData\Roaming\npm\node_modules\autorest\dist\app.js:493:28)
    at main (C:\Users\astauben\AppData\Roaming\npm\node_modules\autorest\dist\app.js:186:33)
"

Could you please help me solve the issue?

Thanks,
Assaf.

**Comment by timotheeguerin** [comment]
that seems to be an issue installing an extension, can you run `autorest --reset` then run your command with `--debug --verbose` and share the output again. Can you also share the config and command line used.

**Comment by astauben** [comment]
AutoRest code generation utility [cli version: 3.2.0; node: v15.11.0, max-memory: 4096 MB]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
> Initial configuration file 'file:///C:/Users/astauben/Desktop/PS/azure-powershell/src/Kusto/readme.md'
> Including configuration file 'file:///C:/Users/astauben/Desktop/PS/azure-powershell/src/Kusto/readme.md'
> Including configuration file 'file:///C:/Users/astauben/Desktop/PS/azure-powershell/src/readme.azure.noprofile.md'
> Including configuration file 'file:///C:/Users/astauben/AppData/Roaming/npm/node_modules/autorest/dist/resources/default-configuration.md'
> Including configuration file 'file:///C:/Users/astauben/AppData/Roaming/npm/node_modules/autorest/dist/resources/inspect.md'
> Including configuration file 'file:///C:/Users/astauben/AppData/Roaming/npm/node_modules/autorest/dist/resources/directives.md'
> Including configuration file 'file:///C:/Users/astauben/AppData/Roaming/npm/node_modules/autorest/dist/resources/pipeline.md'
> Including configuration file 'file:///C:/Users/astauben/AppData/Roaming/npm/node_modules/autorest/dist/resources/loader-openapi.md'
> Including configuration file 'file:///C:/Users/astauben/AppData/Roaming/npm/node_modules/autorest/dist/resources/miscellaneous.md'
> Including configuration file 'file:///C:/Users/astauben/AppData/Roaming/npm/node_modules/autorest/dist/resources/patches.md'
> Including configuration file 'file:///C:/Users/astauben/AppData/Roaming/npm/node_modules/autorest/dist/resources/plugin-powershell.md'
> Including configuration file 'file:///C:/Users/astauben/AppData/Roaming/npm/node_modules/autorest/dist/resources/plugin-azureresourceschema.md'
> Including configuration file 'file:///C:/Users/astauben/AppData/Roaming/npm/node_modules/autorest/dist/resources/plugin-csharp.md'
> Including configuration file 'file:///C:/Users/astauben/AppData/Roaming/npm/node_modules/autorest/dist/resources/plugin-go.md'
> Including configuration file 'file:///C:/Users/astauben/AppData/Roaming/npm/node_modules/autorest/dist/resources/plugin-java.md'
> Including configuration file 'file:///C:/Users/astauben/AppData/Roaming/npm/node_modules/autorest/dist/resources/plugin-nodejs.md'
> Including configuration file 'file:///C:/Users/astauben/AppData/Roaming/npm/node_modules/autorest/dist/resources/plugin-php.md'
> Including configuration file 'file:///C:/Users/astauben/AppData/Roaming/npm/node_modules/autorest/dist/resources/plugin-python.md'
> Including configuration file 'file:///C:/Users/astauben/AppData/Roaming/npm/node_modules/autorest/dist/resources/plugin-ruby.md'
> Including configuration file 'file:///C:/Users/astauben/AppData/Roaming/npm/node_modules/autorest/dist/resources/plugin-typescript.md'
> Including configuration file 'file:///C:/Users/astauben/AppData/Roaming/npm/node_modules/autorest/dist/resources/plugin-validators.md'
> Including configuration file 'file:///C:/Users/astauben/AppData/Roaming/npm/node_modules/autorest/dist/resources/plugin-az.md'
> Including configuration file 'file:///C:/Users/astauben/AppData/Roaming/npm/node_modules/autorest/dist/resources/plugin-terraform.md'
> Including configuration file 'file:///C:/Users/astauben/AppData/Roaming/npm/node_modules/autorest/dist/resources/plugin-azure-functions.md'
> Including configuration file 'file:///C:/Users/astauben/AppData/Roaming/npm/node_modules/autorest/dist/resources/graphs.md'
> Including configuration file 'file:///C:/Users/astauben/AppData/Roaming/npm/node_modules/autorest/dist/resources/help-configuration.md'

## The default version of @autorest/powershell has been bumped from 2.1+ to 3.0+.
 > If you still want to use 2.1+ version, please specify it with --use:@autorest/powershell@2.1.{x}, e.g 2.1.401.

Failed to install extension '@autorest/powershell' (~3.0.0)
Failure:
SyntaxError: Unexpected token { in JSON at position 95
SyntaxError: Unexpected token { in JSON at position 95
    at JSON.parse (<anonymous>)
    at Yarn.getPackageVersions (C:\Users\astauben\AppData\Roaming\npm\node_modules\autorest\dist\src_autorest-as-a-service_ts-src_coloring_ts.js:1759:21)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at ExtensionManager.getPackageVersions (C:\Users\astauben\AppData\Roaming\npm\node_modules\autorest\dist\src_autorest-as-a-service_ts-src_coloring_ts.js:982:26)
    at ExtensionManager.findPackage (C:\Users\astauben\AppData\Roaming\npm\node_modules\autorest\dist\src_autorest-as-a-service_ts-src_coloring_ts.js:998:31)
    at ConfigurationLoader.resolveExtension (C:\Users\astauben\AppData\Roaming\npm\node_modules\autorest\dist\app.js:4812:30)
    at ConfigurationLoader.load (C:\Users\astauben\AppData\Roaming\npm\node_modules\autorest\dist\app.js:4707:43)
    at Object.findCoreVersionUsingConfiguration (C:\Users\astauben\AppData\Roaming\npm\node_modules\autorest\dist\app.js:457:24)
    at Object.resolveCoreVersion (C:\Users\astauben\AppData\Roaming\npm\node_modules\autorest\dist\app.js:493:28)
    at main (C:\Users\astauben\AppData\Roaming\npm\node_modules\autorest\dist\app.js:186:33)


Using PS 7

**Comment by timotheeguerin** [comment]
Hey @astauben  do you happen to be behind a proxy? Seems like it is failing trying to list the remote versions of the powershell package.

Are you able to run the following command  successfully
 ```
yarn --no-node-version-check --no-lockfile info @autorest/powershell version --json
```

**Comment by astauben** [comment]
fixed
