### ISSUE TITLE
RangeError: Maximum call stack size exceeded -- generating C# client

### ISSUE THREAD

**Issue by drmcclelland** [Azure/autorest#4106]
I am trying to generate a C# client for a large-ish (7.6MB 234K lines) OpenAPI spec from a vendor.  Unfortunately it's not public so I cannot attach it here.

Here is my command line:

```
autorest --input-file=verylarge.json --csharp --output-folder=localfolder
```
Here is the error I'm getting
```
AutoRest code generation utility [cli version: 3.2.0; node: v12.18.3, max-memory: 2048 MB]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
NOTE: AutoRest core version selected from configuration: ~3.1.0.
   Loading AutoRest core      'C:\Users\dmcclelland1\.autorest\@autorest_core@3.1.3\node_modules\@autorest\core\dist' (3.1.3)
INFORMATION: > Loading AutoRest extension '@autorest/csharp' (latest->3.0.0-beta.20210428.6)
INFORMATION: > Loading AutoRest extension '@autorest/modelerfour' (4.19.0->4.19.0)
  RangeError: Maximum call stack size exceeded
```

What steps can I take to troubleshoot this?

**Comment by timotheeguerin** [comment]
Hi @drmcclelland could you try running with `--debug --verbose` and see if you get more information? Could you also share the spec you used?

**Comment by drmcclelland** [comment]
I wish I could share the spec, but it was released to us under an NDA   :-(

Here is the additional output given by running with the `--debug --verbose` args:

```
C:\Users\dmcclelland1\.autorest\@autorest_core@3.1.3\node_modules\@autorest\core\dist\src_lib_autorest-core_ts.js - FAILURE {}
Process() cancelled due to exception : Maximum call stack size exceeded / RangeError: Maximum call stack size exceeded
    at mergeYamls (C:\Users\dmcclelland1\.autorest\@autorest_core@3.1.3\node_modules\@autorest\core\dist\src_lib_autorest-core_ts.js:9793:18)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at LoadLiterateSwagger (C:\Users\dmcclelland1\.autorest\@autorest_core@3.1.3\node_modules\@autorest\core\dist\src_lib_autorest-core_ts.js:3142:18)
    at LoadLiterateSwaggers (C:\Users\dmcclelland1\.autorest\@autorest_core@3.1.3\node_modules\@autorest\core\dist\src_lib_autorest-core_ts.js:3172:29)
    at C:\Users\dmcclelland1\.autorest\@autorest_core@3.1.3\node_modules\@autorest\core\dist\src_lib_autorest-core_ts.js:3196:26
    at ScheduleNode (C:\Users\dmcclelland1\.autorest\@autorest_core@3.1.3\node_modules\@autorest\core\dist\src_lib_autorest-core_ts.js:1809:33)
  RangeError: Maximum call stack size exceeded
[7.34 s] Shutting Down.
[7.35 s] Exiting.
```

**Comment by timotheeguerin** [comment]
I think this is an issue that was resolved in a newer version of core. Can you try updating `@autorest/core` with `--version=~3.4.0`

**Comment by drmcclelland** [comment]
Hmmmm....    am I doing something incorrect to update core?

First I ran `autorest --reset`:

```
AutoRest code generation utility [cli version: 3.2.0; node: v12.18.3, max-memory: 2048 MB]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
Clearing 5 autorest temp data folders...


Cleared the AutoRest extension folder.
On the next run, extensions will be reacquired from the repository.
```

Then I ran `autorest --latest`:
```
AutoRest code generation utility [cli version: 3.2.0; node: v12.18.3, max-memory: 2048 MB]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      'C:\Users\dmcclelland1\.autorest\@autorest_core@3.4.0\node_modules\@autorest\core\dist' (3.4.0)
[21.81 s] Generation Complete
```

Finally, I execute the original command again, but it keeps reverting back to version `~3.1.0`:

```
AutoRest code generation utility [cli version: 3.2.0; node: v12.18.3, max-memory: 2048 MB]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
NOTE: AutoRest core version selected from configuration: ~3.1.0.
   Loading AutoRest core      'C:\Users\dmcclelland1\.autorest\@autorest_core@3.1.3\node_modules\@autorest\core\dist' (3.1.3)
INFORMATION: > Loading AutoRest extension '@autorest/csharp' (latest->3.0.0-beta.20210430.1)
INFORMATION: > Loading AutoRest extension '@autorest/modelerfour' (4.19.0->4.19.0)
  RangeError: Maximum call stack size exceeded
```

**Comment by timotheeguerin** [comment]
Where you running just `autorest --latest` or with the arguments of the original command as well?

**Comment by drmcclelland** [comment]
I ran all 3 commands separately:  

```
autorest --reset
autorest --latest
autorest --input-file=verylarge.json --csharp --output-folder=localfolder
```

I also tried these 2 variations of the original command (the output does indicate that it uses version 3.4.0):

```
autorest --input-file=verylarge.json --csharp --output-folder=localfolder --latest
autorest --input-file=verylarge.json --csharp --output-folder=localfolder --version=3.4.0
```

However, I now get a different error (for v3.4.0):

```
AutoRest code generation utility [cli version: 3.2.0; node: v12.18.3, max-memory: 2048 MB]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      'C:\Users\dmcclelland1\.autorest\@autorest_core@3.4.0\node_modules\@autorest\core\dist' (3.4.0)
INFORMATION: > Loading AutoRest extension '@autorest/csharp' (latest->3.0.0-beta.20210430.1)
INFORMATION: > Loading AutoRest extension '@autorest/modelerfour' (4.19.0->4.19.0)

<--- Last few GCs --->

[22108:000001D734F6ECE0]   105959 ms: Mark-sweep 2013.9 (2083.4) -> 2012.1 (2090.4) MB, 2504.3 / 0.0 ms  (average mu = 0.099, current mu = 0.003) allocation failure GC in old space requested
[22108:000001D734F6ECE0]   108216 ms: Mark-sweep 2013.3 (2090.4) -> 2012.8 (2091.9) MB, 2254.9 / 0.0 ms  (average mu = 0.053, current mu = 0.001) allocation failure GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 00007FF7582AB3BD]
Security context: 0x01ec278408d1 <JSObject>
    1: /* anonymous */(aka /* anonymous */) [000002BDE530F8E9] [C:\Users\dmcclelland1\.autorest\@autorest_core@3.4.0\node_modules\@autorest\core\dist\src_lib_autorest-core_ts.js:~11350] [pc=000000657081AC1A](this=0x029a049404b1 <undefined>,0x00f12f17e149 <Object map = 0000026D33D87F59>)
    2: map [000001EC27858EC9](this=0x02bde530f921 <JSArray[352551]>,0x...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF757695EBF napi_wrap+114095
 2: 00007FF757640B46 v8::base::CPU::has_sse+66998
 3: 00007FF757641946 v8::base::CPU::has_sse+70582
 4: 00007FF757E56E4E v8::Isolate::ReportExternalAllocationLimitReached+94
 5: 00007FF757E3EF21 v8::SharedArrayBuffer::Externalize+833
 6: 00007FF757D0B18C v8::internal::Heap::EphemeronKeyWriteBarrierFromCode+1436
 7: 00007FF757D163C0 v8::internal::Heap::ProtectUnprotectedMemoryChunks+1312
 8: 00007FF757D12EE4 v8::internal::Heap::PageFlagsAreConsistent+3204
 9: 00007FF757D086E3 v8::internal::Heap::CollectGarbage+1283
10: 00007FF757D06D54 v8::internal::Heap::AddRetainedMap+2452
11: 00007FF757D2809D v8::internal::Factory::NewFillerObject+61
12: 00007FF757A8E06F v8::internal::interpreter::JumpTableTargetOffsets::iterator::operator=+1295
13: 00007FF7582AB3BD v8::internal::SetupIsolateDelegate::SetupHeap+546637
14: 000000657081AC1A
```

**Comment by drmcclelland** [comment]
Here is the same error msg (as previous) but with the additional `--verbose --debug` flags:
```
DEBUG [41.76 s]: openapi-document/loader-openapi - END [12.18 s]
DEBUG [41.76 s]: openapi-document/individual/transform - SKIPPING
DEBUG [41.76 s]: openapi-document/individual/schema-validator-openapi - SKIPPING
DEBUG [42.18 s]: openapi-document/individual/identity - SKIPPING
DEBUG [49.29 s]: swagger-document/loader-swagger - END [19.71 s]
DEBUG [49.3 s]: swagger-document/individual/transform - START inputs = 1

<--- Last few GCs --->

[23032:000001B00BEF9200]   100159 ms: Mark-sweep 2018.5 (2077.5) -> 1995.1 (2068.5) MB, 1170.5 / 0.1 ms  (average mu = 0.239, current mu = 0.219) allocation failure scavenge might not succeed
[23032:000001B00BEF9200]   102102 ms: Mark-sweep 2010.0 (2068.9) -> 1997.7 (2070.8) MB, 1872.4 / 0.0 ms  (average mu = 0.137, current mu = 0.036) allocation failure scavenge might not succeed


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 00007FF7582AB3BD]
Security context: 0x004f450808d1 <JSObject>
    1: set [000000202E306229] [C:\Users\dmcclelland1\.autorest\@autorest_core@3.4.0\node_modules\@autorest\core\dist\src_lib_autorest-core_ts.js:~14361] [pc=0000037BEFBE3096](this=0x0002982e4a59 <Object map = 0000004C92B1F429>,0x00202e306181 <Object map = 0000005763A00439>,0x01679f9e7631 <String[3]: 200>,0x00202e306409 <JSProxy>)
    2: InternalFrame [pc: ...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF757695EBF napi_wrap+114095
 2: 00007FF757640B46 v8::base::CPU::has_sse+66998
 3: 00007FF757641946 v8::base::CPU::has_sse+70582
 4: 00007FF757E56E4E v8::Isolate::ReportExternalAllocationLimitReached+94
 5: 00007FF757E3EF21 v8::SharedArrayBuffer::Externalize+833
 6: 00007FF757D0B18C v8::internal::Heap::EphemeronKeyWriteBarrierFromCode+1436
 7: 00007FF757D163C0 v8::internal::Heap::ProtectUnprotectedMemoryChunks+1312
 8: 00007FF757D12EE4 v8::internal::Heap::PageFlagsAreConsistent+3204
 9: 00007FF757D086E3 v8::internal::Heap::CollectGarbage+1283
10: 00007FF757D06D54 v8::internal::Heap::AddRetainedMap+2452
11: 00007FF757D281DB v8::internal::Factory::NewFixedArrayWithFiller+107
12: 00007FF757D28161 v8::internal::Factory::NewFixedArray+65
13: 00007FF757BF436F v8::internal::FeedbackNexus::ic_state+59487
14: 00007FF757C06985 v8::Object::GetIsolate+14677
15: 00007FF757BED51D v8::internal::FeedbackNexus::ic_state+31245
16: 00007FF757BA9A37 v8::internal::JSObject::AddDataElement+1015
17: 00007FF757B6762F v8::internal::PrototypeUsers::Add+2015
18: 00007FF757B8289D v8::internal::Object::SetProperty+237
19: 00007FF757A7B2BF v8::internal::Runtime::SetObjectProperty+303
20: 00007FF757A7A685 v8::internal::Runtime::GetObjectProperty+17909
21: 00007FF7582AB3BD v8::internal::SetupIsolateDelegate::SetupHeap+546637
22: 0000037BEFBE3096
```

**Comment by timotheeguerin** [comment]
hhm interesting, without the a spec to reproduce its going to be hard to figure out if this is just running out of memory due to the size of the specs(which was the orignal  max stack problem)  or there is a memory leak happening.

One thing you can try is to increase the max memory for node. Setting the following environment variable
```
NODE_OPTIONS= --max-old-space-size=8192
```

**Comment by drmcclelland** [comment]
OK that seems to have helped immensely, thanks!  It ran for over an hour before it died again with this error:

```
DEBUG [4386.4 s]: modelerfour/pre-namer - START inputs = 2
C:\Users\dmcclelland1\.autorest\@autorest_modelerfour@4.19.0\node_modules\@autorest\modelerfour\dist\main.js - FAILURE  {} Error: Name is empty!
    at Object.setName (C:\Users\dmcclelland1\.autorest\@autorest_modelerfour@4.19.0\node_modules\@autorest\src\prenamer\naming-utils.ts:54:11)
    at PreNamer.processChoiceNames (C:\Users\dmcclelland1\.autorest\@autorest_modelerfour@4.19.0\node_modules\@autorest\src\prenamer\prenamer.ts:310:9)
    at PreNamer.process (C:\Users\dmcclelland1\.autorest\@autorest_modelerfour@4.19.0\node_modules\@autorest\src\prenamer\prenamer.ts:123:10)
    at processRequest (C:\Users\dmcclelland1\.autorest\@autorest_modelerfour@4.19.0\node_modules\@autorest\src\prenamer\plugin-prenamer.ts:22:27)
    at C:\Users\dmcclelland1\.autorest\@autorest_modelerfour@4.19.0\node_modules\libs\extension-base\dist\extension-base.js:55:1
PLUGIN FAILURE: Name is empty!, Error: Name is empty!
    at Object.setName (C:\Users\dmcclelland1\.autorest\@autorest_modelerfour@4.19.0\node_modules\@autorest\src\prenamer\naming-utils.ts:54:11)
    at PreNamer.processChoiceNames (C:\Users\dmcclelland1\.autorest\@autorest_modelerfour@4.19.0\node_modules\@autorest\src\prenamer\prenamer.ts:310:9)
    at PreNamer.process (C:\Users\dmcclelland1\.autorest\@autorest_modelerfour@4.19.0\node_modules\@autorest\src\prenamer\prenamer.ts:123:10)
    at processRequest (C:\Users\dmcclelland1\.autorest\@autorest_modelerfour@4.19.0\node_modules\@autorest\src\prenamer\plugin-prenamer.ts:22:27)
    at C:\Users\dmcclelland1\.autorest\@autorest_modelerfour@4.19.0\node_modules\libs\extension-base\dist\extension-base.js:55:1, {}
FATAL: Error: Name is empty!
C:\Users\dmcclelland1\.autorest\@autorest_core@3.4.0\node_modules\@autorest\core\dist\src_lib_autorest-core_ts.js - FAILURE {}
Process() cancelled due to exception : Plugin pre-namer reported failure. / Error: Plugin pre-namer reported failure.
    at C:\Users\dmcclelland1\.autorest\@autorest_core@3.4.0\node_modules\@autorest\core\dist\src_lib_autorest-core_ts.js:3097:19
    at ScheduleNode (C:\Users\dmcclelland1\.autorest\@autorest_core@3.4.0\node_modules\@autorest\core\dist\src_lib_autorest-core_ts.js:1656:33)
  Error: Plugin pre-namer reported failure.
[4390.37 s] Shutting Down.
[4390.39 s] Exiting.
```

I'm guessing there may be some error in the JSON that it doesn't like?

**Comment by timotheeguerin** [comment]
Yeah that error looks like there is something named with an empty string or blank string. Usually this is an enum with an empty value. I believe this can be resolved by giving the explict name to the enum empty value using `x-ms-enum`

**Comment by drmcclelland** [comment]
I will keep looking through it, but since the original error is resolved I'll close this for now - thanks for your help @timotheeguerin
