### ISSUE TITLE
TypeError: jsonPath.nodes is not a function

### ISSUE THREAD

**Issue by nickweeds2** [Azure/autorest#4109]
**Describe the bug**

I ran the command:

```
autorest --input-file=edgeRouter.json --input-file=operation.json --model-validator=true
```

This gave the following output:

```
AutoRest code generation utility [cli version: 3.2.0; node: v14.16.1, max-memory: 4096 MB]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
NOTE: AutoRest core version selected from configuration: ~2.0.4413.
   Loading AutoRest core      'C:\Users\nickweeds\.autorest\@microsoft.azure_autorest-core@2.0.4419\node_modules\@microsoft.azure\autorest-core\dist' (2.0.4419)
   Loading AutoRest extension 'oav' (~0.4.20->0.4.70)
TypeError: jsonPath.nodes is not a function
    at openApiValidationExample (C:\Users\nickweeds\.autorest\oav@0.4.70\node_modules\oav\dist\lib\autorestPlugin\extension.js:75:40)
    at async analyzeSwagger (C:\Users\nickweeds\.autorest\oav@0.4.70\node_modules\oav\dist\lib\autorestPlugin\extension.js:34:38)
    at async C:\Users\nickweeds\.autorest\oav@0.4.70\node_modules\oav\dist\lib\autorestPlugin\extension.js:48:70
    at async Promise.all (index 0)
    at async C:\Users\nickweeds\.autorest\oav@0.4.70\node_modules\oav\dist\lib\autorestPlugin\extension.js:49:5
    at async C:\Users\nickweeds\.autorest\oav@0.4.70\node_modules\@microsoft.azure\autorest-extension-base\dist\lib\extension-base.js:39:17
FATAL: TypeError: jsonPath.nodes is not a function
FATAL: swagger-document/model-validator - FAILED
FATAL: Error: Plugin model-validator reported failure.
Process() cancelled due to exception : Plugin model-validator reported failure.
  Error: Plugin model-validator reported failure.
```

**Expected behavior**

I expected autorest to perform model validation and output any results.
In this case it appears to me that validation has failed but autorest has crashed trying to output the results.

**Additional context**

I am in the process of writing a new Resource Provider API so the OpenAPI source files are at an early stage of development.

I have run "autorest --reset" and "autorest --latest" but still get the same result.

**Comment by timotheeguerin** [comment]
seems to be an issue with the oav extension, please open the issue there https://github.com/Azure/oav
