### ISSUE TITLE
Downloading plugins not working using custom nexus repository

### ISSUE THREAD

**Issue by pure-zero** [Azure/autorest#4111]
**Describe the bug**
Running autorest on the latest node docker container, I am getting the following error.

autorest --input-file=https://petstore.swagger.io/v2/swagger.json --output-folder=myfolder --typescript --verbose
---
> Including configuration file 'file:///usr/local/lib/node_modules/autorest/dist/resources/help-configuration.md'
Failed to install extension '@autorest/typescript' (latest)
Failure:
Error: Unable to resolve package '@autorest/typescript@latest'.
Error: Unable to resolve package '@autorest/typescript@latest'.
    at fetchPackageMetadata (/usr/local/lib/node_modules/autorest/dist/src_autorest-as-a-service_ts-src_coloring_ts.js:920:15)
    at runNextTicks (node:internal/process/task_queues:58:5)
    at processImmediate (node:internal/timers:436:9)
    at ExtensionManager.findPackage (/usr/local/lib/node_modules/autorest/dist/src_autorest-as-a-service_ts-src_coloring_ts.js:1004:24)
    at ExtensionManager.getInstalledExtension (/usr/local/lib/node_modules/autorest/dist/src_autorest-as-a-service_ts-src_coloring_ts.js:1036:25)
    at ConfigurationLoader.resolveExtension (/usr/local/lib/node_modules/autorest/dist/app.js:4805:40)
    at ConfigurationLoader.load (/usr/local/lib/node_modules/autorest/dist/app.js:4707:43)
    at Object.findCoreVersionUsingConfiguration (/usr/local/lib/node_modules/autorest/dist/app.js:457:24)
    at Object.resolveCoreVersion (/usr/local/lib/node_modules/autorest/dist/app.js:493:28)
    at main (/usr/local/lib/node_modules/autorest/dist/app.js:186:33)

I have set my registry using both yarn and npm configs. I can also run npm install @autorest/typescript@latest

**Expected behavior**
I would expect this to use your npm registry just as you would when you install the package

Thanks for your help, I am quite new to this package so if I am doing anything wrong in the initial command let me know.

**Comment by timotheeguerin** [comment]
Hi @pure-zero, I am a little confused by what you mean here by using custom repository.
Are you saying that you want the package to be available via this custom registry and it works fine when doing `npm install`? Or you are saying that autorest tries to use your custom registry when it shouldn't?

If this is the 1st issue can you try setting `autorest_registry` environment variable to be the registry url you wish?

**Comment by pure-zero** [comment]
This is exactly what I wanted thanks a lot!

I had a lot of trouble finding any info on this, but that could have just been my method of searching.

**Comment by pure-zero** [comment]
Closing as issue was my own

**Comment by omazany** [comment]
Hello, we had similar issue when we need to use our corporate nexus repository. It would be great if this autorest_registry environment variable could be documented.
