### ISSUE TITLE
[typescipt] TypeError when emitting client when definition file contains `servers`

### ISSUE THREAD

**Issue by craignicol** [Azure/autorest#4114]
With the following YAML file
```
openapi: 3.0.1
info:
  title: Data
  description: Services for general data
  version: 1.0.0
paths:
  /:
    get:
      operationId: Home
      summary: Get Home Page
      responses:
        '200':
          description: Home page
servers:
  - description: Azure
    url: https://dev.azure.com
  - description: Microsoft
    url: https://www.microsoft.com
```

and the following command

```
autorest --input-file=data.yaml --v3 --debug --verbose --clear-output-folder --output-folder=data --typescript
```

I get the following error

```
An error was encountered while handling a request: TypeError: Cannot read property 'type' of undefined
    at transformChoice (/home/craignicol/.autorest/@autorest_typescript@6.0.0-dev.20201105.2/node_modules/@autorest/typescript/dist/src/transforms/transforms.js:44:23)
    at Array.map (<anonymous>)
    at transformChoices (/home/craignicol/.autorest/@autorest_typescript@6.0.0-dev.20201105.2/node_modules/@autorest/typescript/dist/src/transforms/transforms.js:24:20)
    at Object.transformCodeModel (/home/craignicol/.autorest/@autorest_typescript@6.0.0-dev.20201105.2/node_modules/@autorest/typescript/dist/src/transforms/transforms.js:73:9)
    at async Object.generateTypeScriptLibrary (/home/craignicol/.autorest/@autorest_typescript@6.0.0-dev.20201105.2/node_modules/@autorest/typescript/dist/src/typescriptGenerator.js:46:27)
    at async processRequest (/home/craignicol/.autorest/@autorest_typescript@6.0.0-dev.20201105.2/node_modules/@autorest/typescript/dist/src/main.js:12:9)
    at async /home/craignicol/.autorest/@autorest_typescript@6.0.0-dev.20201105.2/node_modules/@azure-tools/autorest-extension-base/dist/extension-base.js:43:17
```

In this case, the `choice` variable that is being dereferenced does not have a `choiceType` property:

```
ChoiceSchema {
  choices: [
    ChoiceValue { value: 'https://dev.azure.com', language: [Object] },
    ChoiceValue {
      value: 'https://www.microsoft.com',
      language: [Object]
    }
  ],
  type: 'choice',
  language: Languages {
    default: { name: 'HostOptions', description: 'choices for server host' }
  },
  protocol: Protocols {}
}
```

**Expected behavior**
A typescript client is successfully generated. (for comparison, the C# emitter does work with this file)

**Additional context**
```
AutoRest code generation utility [cli version: 3.1.2; node: v12.18.2, max-memory: 2048 MB]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
Network Enabled: true

There is a new version of AutoRest available (3.2.0).
 > You can install the newer version with with npm install -g autorest@latest

Starting @autorest/core from /home/craignicol/.autorest/@autorest_core@3.0.6375
```

[OpenAPI Spec : servers](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.2.md#serverObject)

**Comment by timotheeguerin** [comment]
Hi @craignicol can you try updating to the latest version of @autorest/core (adding `--version=latest` )  I am not able to reproduce 
![image](https://user-images.githubusercontent.com/1031227/117473897-4b710380-af0f-11eb-8ae5-3d7454eaba91.png)

**Comment by craignicol** [comment]
@timotheeguerin apologies for the delay in getting back to this. I can confirm that I no longer get this error in the latest version.
