### ISSUE TITLE
Failed to generate typescript client

### ISSUE THREAD

**Issue by mohamadLy** [Azure/autorest#4232]
I am seeing an issue while generating the typescript client. This started 2 days ago it use to work fine. Autorest core version did not changed see below version. But maybe the typescript version did change since it is bundle with autorest client. I don't remember which version of typescript was being used before.

Current version

Issue log
```
AutoRest code generation utility [cli version: 3.3.2; node: v14.15.5]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
NOTE: AutoRest core version selected from configuration: 3.0.6339.
   Loading AutoRest core      'C:\Users\me\.autorest\@autorest_core@3.0.6339\node_modules\@autorest\core\dist' (3.0.6339)
   Installing AutoRest extension '@autorest/typescript' (6.0.0-dev.20201105.2)
   Installed AutoRest extension '@autorest/typescript' (6.0.0-dev.20201105.2->6.0.0-dev.20201105.2)
   Installing AutoRest extension '@autorest/modelerfour' (4.15.421)
   Installed AutoRest extension '@autorest/modelerfour' (4.15.421->4.15.421)
C:\Users\me\.autorest\@autorest_typescript@6.0.0-dev.20201105.2\node_modules\@azure-tools\codemodel\dist\model\yaml-schema.js:38
exports.codeModelSchema = js_yaml_1.Schema.create(js_yaml_1.DEFAULT_SAFE_SCHEMA, [
                                           ^

TypeError: js_yaml_1.Schema.create is not a function
    at Object.<anonymous> (C:\Users\me\.autorest\@autorest_typescript@6.0.0-dev.20201105.2\node_modules\@azure-tools\codemodel\dist\model\yaml-schema.js:38:44)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\me\.autorest\@autorest_typescript@6.0.0-dev.20201105.2\node_modules\@azure-tools\codemodel\dist\exports.js:42:14)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
Process() cancelled due to failure
Deleting generated swagger folder with swager.json files...
```

autorest version
```
AutoRest code generation utility [cli version: 3.3.2; node: v14.15.5]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest


Showing All Installed Extensions

 Type       Extension Name                           Version      Location
 core       @autorest/core                           3.0.6339     C:\Users\me\.autorest\@autorest_core@3.0.6339
 extension  @autorest/csharp                         3.0.0-beta.20210720.1 C:\Users\me\.autorest\@autorest_csharp@3.0.0-beta.20210720.1
 extension  @autorest/modelerfour                    4.15.421     C:\Users\me\.autorest\@autorest_modelerfour@4.15.421
 extension  @autorest/modelerfour                    4.19.3       C:\Users\me\.autorest\@autorest_modelerfour@4.19.3
 extension  @autorest/typescript                     6.0.0-beta.8 C:\Users\me\.autorest\@autorest_typescript@6.0.0-beta.8
 extension  @autorest/typescript                     6.0.0-dev.20201105.2 C:\Users\me\.autorest\@autorest_typescript@6.0.0-dev.20201105.2
 extension  @microsoft.azure/autorest.csharp         2.3.91       C:\Users\me\.autorest\@microsoft.azure_autorest.csharp@2.3.91
 extension  @microsoft.azure/autorest.modeler        2.3.55       C:\Users\me\.autorest\@microsoft.azure_autorest.modeler@2.3.55
```

I don't see the issue if upgrade to autorest core 3.5.0 version

**Comment by sarangan12** [comment]
@mohamadLy This is a great question. But, Only the autorest core team could answer this question. So, I am transfering this issue to core repo. 

@timotheeguerin FYI...

**Comment by timotheeguerin** [comment]
Not fully sure but my guess is: 
- that version of autorest core would default to using this old version of @autorest/typescript(which was in dev/alpha at the time)
- that dev version of typescript didn't pin a npm dependency that got updated recently and introduced a breaking change(or a version conflict).

Solutions to prevent that in the future if for @autorest/typescript to bundle all dependency in it like @autorest/core(or @autorest/modelerfour) does it so it takes those dependency issues out of the equation.
