### ISSUE TITLE
FATAL: Internal error in AutoRest.CSharp

### ISSUE THREAD

**Issue by AlexanderSher** [Azure/autorest#4263]
@thisisdevanshu commented on [Fri Jul 30 2021](https://github.com/Azure/autorest.csharp/issues/1442)

Ran into the below error while generating .NET SDK 

```
PS C:\sdk> autorest C:\git_repos\azure-rest-api-specs-pr\specification\{resource}\resource-manager\readme.md --csharp --version=3.5.1 --verbose
AutoRest code generation utility [cli version: 3.3.2; node: v12.18.4]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
.
.
FATAL: YamlDotNet.Core.YamlException: (Line: 2540, Col: 37, Idx: 90547) - (Line: 2540, Col: 37, Idx: 90547): Exception during deserialization
 ---> System.InvalidCastException: Object must implement IConvertible.
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at YamlDotNet.Serialization.Utilities.TypeConverter.ChangeType(Object value, Type destinationType, CultureInfo culture)
   at YamlDotNet.Serialization.NodeDeserializers.CollectionNodeDeserializer.DeserializeHelper(Type tItem, IParser parser, Func`3 nestedObjectDeserializer, IList result, Boolean canUpdate)
   at YamlDotNet.Serialization.NodeDeserializers.CollectionNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
.
.
.
 at AutoRest.CSharp.Input.CodeModelSerialization.DeserializeCodeModel(String yaml) in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Input\CodeModelSerialization.cs:line 52
   at AutoRest.CSharp.AutoRest.Plugins.CSharpGen.<>cDisplayClass2_0.<<Execute>b0>d.MoveNext() in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\Common\AutoRest\Plugins\CSharpGen.cs:line 80
--- End of stack trace from previous location where exception was thrown ---
   at AutoRest.CSharp.AutoRest.Plugins.CSharpGen.ExecuteAsync(Task`1 codeModelTask, Configuration configuration) in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\Common\AutoRest\Plugins\CSharpGen.cs:line 42
   at AutoRest.CSharp.AutoRest.Plugins.CSharpGen.Execute(IPluginCommunication autoRest) in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\Common\AutoRest\Plugins\CSharpGen.cs:line 96
```

---

@thisisdevanshu commented on [Wed Aug 04 2021](https://github.com/Azure/autorest.csharp/issues/1442#issuecomment-893025989)

PS C:\sdk> autorest C:\git_repos\azure-rest-api-specs-pr\specification\orbital\resource-manager\readme.md --csharp --v3 --verbose
https://github.com/Azure/azure-rest-api-specs-pr/pull/4294
```
FATAL: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at AutoRest.Modeler.SwaggerModeler.Build(ServiceDefinition serviceDefinition) in /opt/vsts/work/1/s/src/SwaggerModeler.cs:line 142
   at AutoRest.Modeler.Program.<ProcessInternal>d__2.MoveNext() in /opt/vsts/work/1/s/src/Program.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NewPlugin.<Process>d__15.MoveNext()
FATAL: csharp/imodeler1 - FAILED
FATAL: Error: Plugin imodeler1 reported failure.
```

---

@markcowl commented on [Wed Aug 04 2021](https://github.com/Azure/autorest.csharp/issues/1442#issuecomment-893026148)

swagger spec for this is here: https://github.com/MicrosoftJim/azure-rest-api-specs-pr-1/blob/dev-orbital-Microsoft.Orbital-2020-09-01-preview/specification/orbital/resource-manager/readme.md

**Comment by timotheeguerin** [comment]
Hey, A bit confused here by which is the error? There is 2 completely different errors both being in Autorest CSharp extension. 
Seems like the 1st one might be an issue due to a malformed yaml? Do you have more info on how to repro(The links don't exists anymore, the PR was merged.)?

**Comment by AlexanderSher** [comment]
Hey, here is the config: https://github.com/Azure/azure-rest-api-specs-pr/tree/dev-orbital-Microsoft.Orbital-2020-09-01-preview/specification/orbital/resource-manager

**Comment by timotheeguerin** [comment]
I am seeing yet a different error for this: 
```
Error: Enum types of 'object' and format 'undefined' are not supported. Correct your input (OrbitalGatewaysProperties-provisioningState)
```

This one seems to be related to having enums defined with `allOf` but without a type: "string`. Can you repro the 1st error sent here?

**Comment by AlexanderSher** [comment]
No, I have the same error as you do.

**Comment by thisisdevanshu** [comment]
Yes, that was the initial error. But once I fix all the enum ref to be of "type": "string" I run into the  "FATAL: YamlDotNet.Core.YamlException:"
