### ISSUE TITLE
[Azure.Anaytics.Synapse.Artifacts] Deserialization exception from CodeModel.yaml

### ISSUE THREAD

**Issue by AlexanderSher** [Azure/autorest#4264]
@annelo-msft commented on [Thu Aug 05 2021](https://github.com/Azure/autorest.csharp/issues/1454)

I am trying to generate code for the `Azure.Anaytics.Synapse.Artifacts` from an updated `autorest.md` file pointing to the service team's new preview swagger:
- `autorest.md`: https://github.com/Azure/azure-sdk-for-net/pull/23132/commits/511946efb4789de741e128f927b724651f40c10c#diff-c5d644299c0fe037d2d3ba972e0bf0b9631dbc07b1f8818fd88bdcc5fc8b3d0bR13

(i.e. [this API Spec](https://github.com/Azure/azure-rest-api-specs/blob/c981b81aa26ad4d0d156e034e6782853b4e747a1/specification/synapse/data-plane/readme.md) with the tag `package-artifacts-2021-06-01-preview`)

I am getting the following exception:

YamlDotNet.Core.YamlException: '(Line: 51548, Col: 11, Idx: 3358409) - (Line: 51548, Col: 11, Idx: 3358409): Exception during deserialization'

YamlDotNet.Core.YamlException
  HResult=0x80131500
  Message=(Line: 51548, Col: 11, Idx: 3358409) - (Line: 51548, Col: 11, Idx: 3358409): Exception during deserialization
  Source=YamlDotNet
  StackTrace:
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.<>c__DisplayClass3_0.<DeserializeValue>b__0(IParser r, Type t)
   at YamlDotNet.Serialization.NodeDeserializers.ObjectNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.<>c__DisplayClass3_0.<DeserializeValue>b__0(IParser r, Type t)
   at YamlDotNet.Serialization.NodeDeserializers.ObjectNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.<>c__DisplayClass3_0.<DeserializeValue>b__0(IParser r, Type t)
   at YamlDotNet.Serialization.NodeDeserializers.CollectionNodeDeserializer.DeserializeHelper(Type tItem, IParser parser, Func`3 nestedObjectDeserializer, IList result, Boolean canUpdate)
   at YamlDotNet.Serialization.NodeDeserializers.CollectionNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.<>c__DisplayClass3_0.<DeserializeValue>b__0(IParser r, Type t)
   at YamlDotNet.Serialization.NodeDeserializers.ObjectNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.<>c__DisplayClass3_0.<DeserializeValue>b__0(IParser r, Type t)
   at YamlDotNet.Serialization.NodeDeserializers.ObjectNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(IParser parser, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at YamlDotNet.Serialization.Deserializer.Deserialize(IParser parser, Type type)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](IParser parser)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](TextReader input)
   at YamlDotNet.Serialization.Deserializer.Deserialize[T](String input)
   at AutoRest.CSharp.Input.CodeModelSerialization.DeserializeCodeModel(String yaml) in C:\src\autorest.csharp\src\AutoRest.CSharp\Common\Input\CodeModelSerialization.cs:line 52

  This exception was originally thrown at this call stack:
    System.Convert.ChangeType(object, System.Type, System.IFormatProvider)
    YamlDotNet.Serialization.Utilities.TypeConverter.ChangeType(object, System.Type, System.Globalization.CultureInfo)
    YamlDotNet.Serialization.Utilities.TypeConverter.ChangeType(object, System.Type)
    YamlDotNet.Serialization.NodeDeserializers.CollectionNodeDeserializer.DeserializeHelper(System.Type, YamlDotNet.Core.IParser, System.Func<YamlDotNet.Core.IParser, System.Type, object>, System.Collections.IList, bool)
    YamlDotNet.Serialization.NodeDeserializers.CollectionNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(YamlDotNet.Core.IParser, System.Type, System.Func<YamlDotNet.Core.IParser, System.Type, object>, out object)
    YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(YamlDotNet.Core.IParser, System.Type, YamlDotNet.Serialization.Utilities.SerializerState, YamlDotNet.Serialization.IValueDeserializer)

Inner Exception 1:
InvalidCastException: Object must implement IConvertible.

Files:
[CodeModelAndConfiguration.zip](https://github.com/Azure/autorest.csharp/files/6941072/CodeModelAndConfiguration.zip)

**Comment by AlexanderSher** [comment]
Looks like the issue is caused by incorrect code model.

Exception happens when YamlDotNet tries to convert `StringSchema` object into `ComplexSchema` object. The object that it tries to convert:
```
    - !StringSchema &ref_657
      type: string
      apiVersions:
        - !ApiVersion 
          version: 2021-06-01-preview
      extensions:
        x-csharp-usage: converter
      language: !Languages 
        default:
          name: DatasetCompression
          description: The compression method used on a dataset.
      protocol: !Protocols {}
```

The place where it is used that requests conversion:
```
    - !ObjectSchema 
      type: object
      apiVersions:
        - !ApiVersion 
          version: 2021-06-01-preview
      parents: !Relations 
        all:
          - *ref_657
        immediate:
          - *ref_657
      extensions:
        x-csharp-usage: converter
        x-ms-discriminator-value: BZip2
```

Exception is raised for the `all`.

**Comment by AlexanderSher** [comment]
From the swagger, it seems that `DatasetCompression` should not be a `StringSchema`: https://github.com/Azure/azure-rest-api-specs/blob/0a68678e554b9e69695fb28853993035244f93c5/specification/synapse/data-plane/Microsoft.Synapse/stable/2020-12-01/entityTypes/Dataset.json#L399

**Comment by timotheeguerin** [comment]
hey @AlexanderSher do you know which version of core and autorest.csharp are used here? I am not seeing the same error.

I get another error in the csharp extension using the latest core and @autorest/csharp
```
Exception: Constant type mismatch
   at AutoRest.CSharp.Output.Models.Shared.Constant..ctor(Object value, CSharpType type) in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Output\Models\Shared\Constant.cs:line 44
   at AutoRest.CSharp.Output.Builders.BuilderHelpers.ParseConstant(Object value, CSharpType type) in D:\a\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Output\Builders\BuilderHelpers.cs:line 54
```

**Comment by annelo-msft** [comment]
@timotheeguerin, are you able to repro the issue with these autorest.md, CodeModel.yaml, and Configuration.json files?  

[autorest.md](https://github.com/Azure/autorest/files/7146833/autorest.md)
[Generated.zip](https://github.com/Azure/autorest/files/7146843/Generated.zip)

**Comment by annelo-msft** [comment]
@lmazuel FYI

**Comment by timotheeguerin** [comment]
Ok, I repro now with this config, will take a look

**Comment by timotheeguerin** [comment]
So this seems to be due to this directive:
```yaml
directive:
  from: swagger-document
  where: $.definitions.DatasetCompression
  transform: $.type = "string"
```
which change the type of DatasetCompression to string and I guess some other schema have allOf reference to it which cause issue as it can't be extending a string.

Now I a not sure why modelerfour doesn't complain before about that, will look into it.

**Comment by timotheeguerin** [comment]
Yeah I can easily repro with this simple spec with an allOf that is a `string`

```yaml
openapi: 3.0.1
info:
  title: test
  version: 0.0.1
  description: ""
paths:
  /test:
    post:
      operationId: some_api
      parameters: []
      responses:
        default:
          description: Test
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/Foo
components:
  schemas:
    Foo:
      description: Foo
      type: object
      allOf:
        - $ref: "#/components/schemas/Bar"
      properties:
        projectId:
          type: string
    Bar:
      type: string

```

Will see what validation I can add here.

For your use case though why did you change the type? Is this necessary?

**Comment by annelo-msft** [comment]
> For your use case though why did you change the type? Is this necessary?

We had a request to treat this field as a string since it is used as a discriminator, and a discriminator must be a string.

**Comment by timotheeguerin** [comment]
@annelo-msft is this resolved? Latest version show a validation error.

**Comment by lmazuel** [comment]
CC @AlexanderSher please confirm if this is still a problem

**Comment by AlexanderSher** [comment]
Not reproduced with 2021-06-01 spec
