### ISSUE TITLE
Fatal | Error: Not able to process media type ErrorResponse at this moment.

### ISSUE THREAD

**Issue by shaduk** [Azure/autorest#4414]
**Before filling a bug**

- [X] have you checked the [faq](https://github.com/Azure/autorest/tree/main/docs/faq.md) for known issues.
- [X] have you checked existing issues

**Describe the bug**

I am encountering the below error while trying to process a openapi 3.0.1 swagger spec

```
warning | Deprecated | seal-single-value-enum-by-default is a temporary flag that WILL be removed in the future. Please change the spec to add x-ms-enum.modelAsString=false for enums with this issue.
warning | Deprecated | seal-single-value-enum-by-default is a temporary flag that WILL be removed in the future. Please change the spec to add x-ms-enum.modelAsString=false for enums with this issue.
warning | Deprecated | seal-single-value-enum-by-default is a temporary flag that WILL be removed in the future. Please change the spec to add x-ms-enum.modelAsString=false for enums with this issue.
fatal   | Error: Not able to process media type ErrorResponse at this moment.
fatal   | Process() cancelled due to exception : Plugin modelerfour reported failure. / Error: Plugin modelerfour reported failure.
    at C:\Users\vipnai\.autorest\@autorestcore@3.7.5\node_modules\@autorest\core\dist\src_lib_autorest-corets.js:2779:19
    at ScheduleNode (C:\Users\vipnai\.autorest\@autorestcore@3.7.5\node_modules\@autorest\core\dist\src_lib_autorest-corets.js:1317:33)
error   |   Error: Plugin modelerfour reported failure.
debug   | [10.95 s] Shutting Down.
debug   | [10.95 s] Exiting.
```

I am currently using autorest 3.7.5

![image](https://user-images.githubusercontent.com/4323839/152818992-caf227b2-f387-4df6-8b44-c993bb63907c.png)

OpenApi 3.0.1 swagger spec:

```
"delete": {
        "tags": [
          "DataStore"
        ],
        "summary": "Delete a Datastore.",
        "description": "Delete a Datastore with a specific name.",
        "operationId": "DataStores_Delete",
        "parameters": [
          {
            "$ref": "#/components/parameters/subscriptionIdParameter"
          },
          {
            "$ref": "#/components/parameters/resourceGroupNameParameter"
          },
          {
            "$ref": "#/components/parameters/workspaceNameParameter"
          },
          {
            "name": "name",
            "in": "path",
            "description": "The Datastore name.",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "The Datastore is deleted successfully.",
            "content": {
              "application/json": { }
            }
          },
          "204": {
            "description": "The Datastore did not exist.",
            "content": {
              "application/json": { }
            }
          },
          "default": {
            "description": "Error response describing why the operation failed.",
            "content": {
              "ErrorResponse": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                }
              }
            }
          }
```

**Comment by shaduk** [comment]
I am using Swashbuckle auto generator (https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-6.0&tabs=visual-studio) to publish the json. Not sure how it would generate a wrong contract.

**Comment by timotheeguerin** [comment]
The keys under `content` must be a media type or mediaType range https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#response-object

This seems like an issue with Swashbuckle 

You can use autorest directive to fix the swagger in the meantime.
https://github.com/Azure/autorest/blob/main/docs/generate/directives.md#structure-and-terminology
