### ISSUE TITLE
autorest 3.5.1 does not run in apple arm

### ISSUE THREAD

**Issue by chenrui333** [Azure/autorest#4450]
**Before filling a bug**

- [x] have you checked the [faq](https://github.com/Azure/autorest/tree/main/docs/faq.md) for known issues.
- [x] have you checked existing issues

**Describe the bug**

Failed to run autorest in apple M1.

```
$ /opt/homebrew/Cellar/autorest/3.5.1_1/bin/autorest --input-file=petstore.yaml --nodejs --output-folder=petstore
SourceMapConsumer.initialize is a no-op when running in node.js
AutoRest code generation utility [cli version: 3.5.1; node: v16.14.0]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
info    | AutoRest core version selected from configuration: ~2.0.4413.
installing core... [========================================] 100% | 2/2
   Loading AutoRest core      '/Users/rui/.autorest/@microsoft.azureautorest-core@2.0.4421/nodemodules/@microsoft.azure/autorest-core/dist' (2.0.4421)
   Installing AutoRest extension '@microsoft.azure/autorest.nodejs' (~2.1.25)
Failed to install or start extension '@microsoft.azure/autorest.nodejs' (~2.1.25)
  Error: Package '@microsoft.azure/autorest.nodejs' - '2.1.128' failed to install:
  Failed to install package 'https://registry.npmjs.org/@microsoft.azure/autorest.nodejs/-/autorest.nodejs-2.1.128.tgz' -- Error: Process Failed.Error: Failed to install package 'https://registry.npmjs.org/@microsoft.azure/autorest.nodejs/-/autorest.nodejs-2.1.128.tgz' -- Error: Process Failed.
    at install (/node_modules/@microsoft.azure/extension/dist/main.js:303:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExtensionManager.installPackage (/node_modules/@microsoft.azure/extension/dist/main.js:472:13)
    at async Configuration.CreateView (/Users/rui/.autorest/@microsoft.azureautorest-core@2.0.4421/nodemodules/@microsoft.azure/autorest-core/dist/lib/configuration.js:685:51)
    at async AutoRest.RegenerateView (/Users/rui/.autorest/@microsoft.azureautorest-core@2.0.4421/nodemodules/@microsoft.azure/autorest-core/dist/lib/autorest-core.js:55:29)
    at async currentMain (/Users/rui/.autorest/@microsoft.azureautorest-core@2.0.4421/nodemodules/@microsoft.azure/autorest-core/dist/app.js:303:20)
    at async mainImpl (/Users/rui/.autorest/@microsoft.azureautorest-core@2.0.4421/nodemodules/@microsoft.azure/autorest-core/dist/app.js:506:20)
    at async main (/Users/rui/.autorest/@microsoft.azureautorest-core@2.0.4421/nodemodules/@microsoft.azure/autorest-core/dist/app.js:530:20)
```

**Expected behavior**

Should passed the test

**Additional context**
relates to https://github.com/Homebrew/homebrew-core/pull/96527

**Comment by timotheeguerin** [comment]
Hi @chenrui333 does running `npm install `@microsoft.azure/autorest.nodejs` works?

**Comment by chenrui333** [comment]
it does not work

```
$ npm install @microsoft.azure/autorest.nodejs
npm ERR! code 1
npm ERR! path /Users/rui/Downloads/node_modules/dotnet-2.0.0
npm ERR! command failed
npm ERR! command sh -c node -e "/*PostInstall: Installs platform-specific .NET framework */try{require('./dist/app.js')}catch(e){}"
npm ERR! Unable to install/use dotnet framework.
```

**Comment by timotheeguerin** [comment]
This is the error. The nodejs generator is an old v2 generator. If you want to target javascript use `--typescript` flag for the latest generator.

**Comment by chenrui333** [comment]
got you, let me give that a try.
