### ISSUE TITLE
rush update fails

### ISSUE THREAD

**Issue by mikekistler** [Azure/autorest#4494]
**Before filling a bug**

- [x] have you checked the [faq](https://github.com/Azure/autorest/tree/main/docs/faq.md) for known issues.
- [x] have you checked existing issues

**Describe the bug**

I'm following the instructions in docs/internal/development.md to set up for development in autorest.

I did a fresh install of rush:
```
npm install -g @microsoft/rush
```

Then I ran `rush update` but this fails:
```
node_modules/.pnpm/tree-sitter@0.19.0/node_modules/tree-sitter: Running install script, failed in 5.5s
.../node_modules/tree-sitter install$ prebuild-install || node-gyp rebuild
│ prebuild-install WARN install No prebuilt binaries found (target=16.14.2 runtime=node arch=arm64 libc= platform=darwin)
│ gyp info it worked if it ends with ok
│ gyp info using node-gyp@7.1.2
│ gyp info using node@16.14.2 | darwin | arm64
│ gyp info find Python using Python version 3.9.10 found at "/opt/homebrew/opt/python@3.9/bin/python3.9"
│ (node:92282) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
│ (Use `node --trace-deprecation ...` to show where the warning was created)
│ gyp info spawn /opt/homebrew/opt/python@3.9/bin/python3.9
│ gyp info spawn args [
│ gyp info spawn args   '/Users/mikekistler/.rush/node-v16.14.2/pnpm-5.16.0/node_modules/pnpm/dist/node_modules/node-gyp/gyp/gyp_main.py',
│ gyp info spawn args   'binding.gyp',
│ gyp info spawn args   '-f',
│ gyp info spawn args   'make',
│ gyp info spawn args   '-I',
│ gyp info spawn args   '/Users/mikekistler/Projects/Azure/autorest/common/temp/node_modules/.pnpm/tree-sitter@0.19.0/node_modules/tree-sitter/build/config.gypi',
│ gyp info spawn args   '-I',
│ gyp info spawn args   '/Users/mikekistler/.rush/node-v16.14.2/pnpm-5.16.0/node_modules/pnpm/dist/node_modules/node-gyp/addon.gypi',
│ gyp info spawn args   '-I',
│ gyp info spawn args   '/Users/mikekistler/Library/Caches/node-gyp/16.14.2/include/node/common.gypi',
│ gyp info spawn args   '-Dlibrary=shared_library',
│ gyp info spawn args   '-Dvisibility=default',
│ gyp info spawn args   '-Dnode_root_dir=/Users/mikekistler/Library/Caches/node-gyp/16.14.2',
│ gyp info spawn args   '-Dnode_gyp_dir=/Users/mikekistler/.rush/node-v16.14.2/pnpm-5.16.0/node_modules/pnpm/dist/node_modules/node-gyp',
│ gyp info spawn args   '-Dnode_lib_file=/Users/mikekistler/Library/Caches/node-gyp/16.14.2/<(target_arch)/node.lib',
│ gyp info spawn args   '-Dmodule_root_dir=/Users/mikekistler/Projects/Azure/autorest/common/temp/node_modules/.pnpm/tree-sitter@0.19.0/node_modules/tree-sitter',
│ gyp info spawn args   '-Dnode_engine=v8',
│ gyp info spawn args   '--depth=.',
│ gyp info spawn args   '--no-parallel',
│ gyp info spawn args   '--generator-output',
│ gyp info spawn args   'build',
│ gyp info spawn args   '-Goutput_dir=.'
│ gyp info spawn args ]
│ gyp info spawn make
│ gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
│   CC(target) Release/obj.target/tree_sitter/vendor/tree-sitter/lib/src/lib.o
│   LIBTOOL-STATIC Release/tree_sitter.a
│   CXX(target) Release/obj.target/tree_sitter_runtime_binding/src/binding.o
│ In file included from ../src/binding.cc:1:
│ In file included from /Users/mikekistler/Library/Caches/node-gyp/16.14.2/include/node/node.h:63:
│ In file included from /Users/mikekistler/Library/Caches/node-gyp/16.14.2/include/node/v8.h:30:
│ /Users/mikekistler/Library/Caches/node-gyp/16.14.2/include/node/v8-internal.h:492:38: error: no template named 'remove_cv_t' in namespace 'std'; did you mean 'remove_cv'?
│             !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
│                                 ~~~~~^~~~~~~~~~~
│                                      remove_cv
│ /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/type_traits:710:50: note: 'remove_cv' declared here
│ template <class _Tp> struct _LIBCPP_TEMPLATE_VIS remove_cv
│                                                  ^
│ 1 error generated.
│ make: *** [Release/obj.target/tree_sitter_runtime_binding/src/binding.o] Error 1
│ gyp ERR! build error 
│ gyp ERR! stack Error: `make` failed with exit code: 2
│ gyp ERR! stack     at ChildProcess.onExit (/Users/mikekistler/.rush/node-v16.14.2/pnpm-5.16.0/node_modules/pnpm/dist/node_modules/node-gyp/lib/build.js:194:23)
│ gyp ERR! stack     at ChildProcess.emit (node:events:526:28)
│ gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
│ gyp ERR! System Darwin 20.6.0
│ gyp ERR! command "/opt/homebrew/Cellar/node@16/16.14.2/bin/node" "/Users/mikekistler/.rush/node-v16.14.2/pnpm-5.16.0/node_modules/pnpm/dist/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
│ gyp ERR! cwd /Users/mikekistler/Projects/Azure/autorest/common/temp/node_modules/.pnpm/tree-sitter@0.19.0/node_modules/tree-sitter
│ gyp ERR! node -v v16.14.2
│ gyp ERR! node-gyp -v v7.1.2
│ gyp ERR! not ok 
└─ Failed in 5.5s
node_modules/.pnpm/jsonpath@1.0.0/node_modules/jsonpath: Running postinstall script, done in 81ms
 ERROR  Command failed with exit code 1.

The command failed:
 /Users/mikekistler/Projects/Azure/autorest/common/temp/pnpm-local/node_modules/.bin/pnpm install --store /Users/mikekistler/Projects/Azure/autorest/common/temp/pnpm-store --no-prefer-frozen-lockfile
ERROR: Error: The command failed with exit code 1
```

**Expected behavior**

`rush update` works.

**Comment by timotheeguerin** [comment]
Do you have python installed and if so which version? Feel like it’s trying to build this native dependency when it finds python

**Comment by timotheeguerin** [comment]
Ok I have been able to repro. This seems to be an issue with node 16 and building native dependencies. Version 0.20.0 of tree-sitter should have fixed it. 
Can you try going into `packages/tools/compare/package.json` and updating the version of "tree-sitter` to `0.20.0`

**Comment by mikekistler** [comment]
That fixes it!

**Comment by DeagleGross** [comment]
@timotheeguerin @mikekistler  I believe it will be **quite helpful** to add `install python` step to the documentation, if it is needed for running autorest locally.

Also `rush update` is not working for me (cloned last main on 04\05\2022)
```
PS C:\Code\autorest> rush update    

Rush Multi-Project Build Tool 5.38.0 - https://rushjs.io
Node.js version is 16.14.2 (LTS)

Starting "rush update"

Validating package manager shrinkwrap file.

Trying to acquire lock for pnpm-5.16.0
Acquired lock for pnpm-5.16.0
Found pnpm version 5.16.0 in C:\Users\dmkorolev\.rush\node-v16.14.2\pnpm-5.16.0

Symlinking "C:\Code\autorest\common\temp\pnpm-local"
  --> "C:\Users\dmkorolev\.rush\node-v16.14.2\pnpm-5.16.0"
Copying C:\Code\autorest\common\config\rush\.npmrc --> C:\Code\autorest\common\temp\.npmrc
Updating C:\Code\autorest\common\temp\pnpmfile.js

Updating temp projects in C:\Code\autorest\common\temp\projects
Finished creating temporary modules (0.13 seconds)
Deleting files from C:\Code\autorest\common\temp\node_modules

Running "pnpm install" in C:\Code\autorest\common\temp

Using hooks from: C:\Code\autorest\common\temp\pnpmfile.js
readPackage hook is declared. Manifests of dependencies might get overridden
 WARN  @rush-temp/autorest > jest > @jest/core > @jest/reporters > jest-resolve: jest-pnp-resolver@1.2.2 requires a peer of jest-resolve@* but version 28.0.0-alpha.7 was installed.
 WARN  @rush-temp/autorest: ts-jest@27.1.3 requires a peer of @types/jest@^27.0.0 but version 26.0.24 was installed.
 WARN  @rush-temp/autorest: ts-jest@27.1.3 requires a peer of jest@^27.0.0 but version 28.0.0-alpha.7 was installed.
Packages: +1133
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: C:\Code\autorest\common\temp\pnpm-store\v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 1132, reused 1132, downloaded 0, added 1133, done
 WARN  Failed to find "/fsevents/2.3.2" in lockfile during hoisting. Next aliases will not be hoisted: fsevents
node_modules/.pnpm/tree-sitter-python@0.19.0/node_modules/tree-sitter-python: Running install script, failed in 5.3s
.../node_modules/tree-sitter-python install$ node-gyp rebuild
│ C:\Code\autorest\common\temp\node_modules\.pnpm\tree-sitter-python@0.19.0\node_modules\tree-sitter-python>if not defined npm_config_node_gyp (node "C:\Users\dmkorolev\.rush\node-v16.14.2\pnpm-5.16.0\node_modu
│ gyp info it worked if it ends with ok
│ gyp info using node-gyp@7.1.2
│ gyp info using node@16.14.2 | win32 | x64
│ gyp info find Python using Python version 3.10.4 found at "C:\Users\dmkorolev\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe"
│ gyp http GET https://nodejs.org/download/release/v16.14.2/node-v16.14.2-headers.tar.gz
│ gyp http 200 https://nodejs.org/download/release/v16.14.2/node-v16.14.2-headers.tar.gz
│ gyp http GET https://nodejs.org/download/release/v16.14.2/SHASUMS256.txt
│ gyp http GET https://nodejs.org/download/release/v16.14.2/win-x86/node.lib
│ gyp http GET https://nodejs.org/download/release/v16.14.2/win-x64/node.lib
│ gyp http GET https://nodejs.org/download/release/v16.14.2/win-arm64/node.lib
│ gyp http 200 https://nodejs.org/download/release/v16.14.2/SHASUMS256.txt
│ gyp http 404 https://nodejs.org/download/release/v16.14.2/win-arm64/node.lib
│ gyp http 200 https://nodejs.org/download/release/v16.14.2/win-x86/node.lib
│ gyp http 200 https://nodejs.org/download/release/v16.14.2/win-x64/node.lib
│ gyp ERR! find VS
│ gyp ERR! find VS msvs_version not set from command line or npm config
│ gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
│ gyp ERR! find VS unknown version "undefined" found at "C:\Program Files\Visual Studio\2022"
│ gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
│ gyp ERR! find VS looking for Visual Studio 2015
│ gyp ERR! find VS - not found
│ gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
│ gyp ERR! find VS
│ gyp ERR! find VS **************************************************************
│ gyp ERR! find VS You need to install the latest version of Visual Studio
│ gyp ERR! find VS including the "Desktop development with C++" workload.
│ gyp ERR! find VS For more information consult the documentation at:
│ gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
│ gyp ERR! find VS **************************************************************
│ gyp ERR! find VS
│ gyp ERR! configure error
│ gyp ERR! stack Error: Could not find any Visual Studio installation to use
│ gyp ERR! stack     at VisualStudioFinder.fail (C:\Users\dmkorolev\.rush\node-v16.14.2\pnpm-5.16.0\node_modules\pnpm\dist\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
│ gyp ERR! stack     at C:\Users\dmkorolev\.rush\node-v16.14.2\pnpm-5.16.0\node_modules\pnpm\dist\node_modules\node-gyp\lib\find-visualstudio.js:74:16
│ gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Users\dmkorolev\.rush\node-v16.14.2\pnpm-5.16.0\node_modules\pnpm\dist\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
│ gyp ERR! stack     at C:\Users\dmkorolev\.rush\node-v16.14.2\pnpm-5.16.0\node_modules\pnpm\dist\node_modules\node-gyp\lib\find-visualstudio.js:70:14
│ gyp ERR! stack     at C:\Users\dmkorolev\.rush\node-v16.14.2\pnpm-5.16.0\node_modules\pnpm\dist\node_modules\node-gyp\lib\find-visualstudio.js:372:16
│ gyp ERR! stack     at C:\Users\dmkorolev\.rush\node-v16.14.2\pnpm-5.16.0\node_modules\pnpm\dist\node_modules\node-gyp\lib\util.js:54:7
│ gyp ERR! stack     at C:\Users\dmkorolev\.rush\node-v16.14.2\pnpm-5.16.0\node_modules\pnpm\dist\node_modules\node-gyp\lib\util.js:33:16
│ gyp ERR! stack     at ChildProcess.exithandler (node:child_process:406:5)
│ gyp ERR! stack     at ChildProcess.emit (node:events:526:28)
│ gyp ERR! stack     at maybeClose (node:internal/child_process:1092:16)
│ gyp ERR! System Windows_NT 10.0.22000
│ gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\dmkorolev\\.rush\\node-v16.14.2\\pnpm-5.16.0\\node_modules\\pnpm\\dist\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
│ gyp ERR! cwd C:\Code\autorest\common\temp\node_modules\.pnpm\tree-sitter-python@0.19.0\node_modules\tree-sitter-python
│ gyp ERR! node -v v16.14.2
│ gyp ERR! node-gyp -v v7.1.2
│ gyp ERR! not ok
└─ Failed in 5.3s
node_modules/.pnpm/tree-sitter-typescript@0.19.0/node_modules/tree-sitter-typescript: Running install script...
node_modules/.pnpm/yarn@1.22.17/node_modules/yarn: Running preinstall script, done in 54ms
node_modules/.pnpm/tree-sitter@0.20.0/node_modules/tree-sitter: Running install script...
node_modules/.pnpm/jsonpath@1.0.0/node_modules/jsonpath: Running postinstall script, done in 157ms
 ERROR  Command failed with exit code 1.

The command failed:
 C:\Code\autorest\common\temp\pnpm-local\node_modules\.bin\pnpm install --store C:\Code\autorest\common\temp\pnpm-store --no-prefer-frozen-lockfile
ERROR: Error: The command failed with exit code 1

Trying again (attempt #2)...

Deleting the "node_modules" folder
Deleting the "pnpm-store" folder

ERROR: Error: Error: EPERM: operation not permitted, symlink 'C:\Code\autorest\common\temp\node_modules\.pnpm\@jridgewell\trace-mapping@0.3.4\node_modules\@jridgewell\trace-mapping\' ->
'C:\Code\autorest\common\temp\rush-recycler\node_modules_1649161826229\.pnpm\@ampproject\remapping@2.1.2\node_modules\@jridgewell\trace-mapping'
Often this is caused by a file lock from a process like the virus scanner.
PS C:\Code\autorest> 
```

**Comment by timotheeguerin** [comment]
Hey @DeagleGross when you say trying to run autorest locally, are you trying to run autorest or contribute to it?

For the issue you have the version of visual studio shouldn't matter, if you installed nodejs from the website it should install the native build tools as well. But it does looks like we are missing some information for building the native dependencies. I'll update the docs
