### ISSUE TITLE
Failed to generate the Golang SDK

### ISSUE THREAD

**Issue by qinqingxu** [Azure/autorest#4547]
I try to run these commands:

> **autorest readme.md  --csharp --azure-arm --tag=package-2022-05-10-privatepreview --output-folder=csharp_sdk/
> autorest readme.md  --python --azure-arm --tag=package-2022-05-10-privatepreview --output-folder=python_sdk/**

They are all succeeded.

But, when I try to run this command:

> **autorest readme.md  --go --azure-arm --tag=package-2022-05-10-privatepreview --output-folder=go_sdk/**

It show the error like:

```
AutoRest code generation utility [cli version: 3.6.1; node: v16.13.0]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
info    | AutoRest core version selected from configuration: ~2.0.4413.
   Loading AutoRest core      'C:\Users\qinqiangxu\.autorest\@microsoft.azureautorest-core@2.0.4421\nodemodules\@microsoft.azure\autorest-core\dist' (2.0.4421)
   Installing AutoRest extension '@microsoft.azure/autorest.go' (~2.1.47)
Failed to install or start extension '@microsoft.azure/autorest.go' (~2.1.47)
  Error: Package '@microsoft.azure/autorest.go' - '2.1.187' failed to install:
  Failed to install package 'https://registry.npmjs.org/@microsoft.azure/autorest.go/-/autorest.go-2.1.187.tgz' -- Error: Process Failed.Error: Failed to install package 'https://registry.npmjs.org/@microsoft.azure/autorest.go/-/autorest.go-2.1.187.tgz' -- Error: Process Failed.
    at install (/node_modules/@microsoft.azure/extension/dist/main.js:303:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExtensionManager.installPackage (/node_modules/@microsoft.azure/extension/dist/main.js:472:13)
    at async Configuration.CreateView (C:\Users\qinqiangxu\.autorest\@microsoft.azureautorest-core@2.0.4421\nodemodules\@microsoft.azure\autorest-core\dist\lib\configuration.js:685:51)
    at async AutoRest.RegenerateView (C:\Users\qinqiangxu\.autorest\@microsoft.azureautorest-core@2.0.4421\nodemodules\@microsoft.azure\autorest-core\dist\lib\autorest-core.js:55:29)
    at async currentMain (C:\Users\qinqiangxu\.autorest\@microsoft.azureautorest-core@2.0.4421\nodemodules\@microsoft.azure\autorest-core\dist\app.js:303:20)
    at async mainImpl (C:\Users\qinqiangxu\.autorest\@microsoft.azureautorest-core@2.0.4421\nodemodules\@microsoft.azure\autorest-core\dist\app.js:506:20)
    at async main (C:\Users\qinqiangxu\.autorest\@microsoft.azureautorest-core@2.0.4421\nodemodules\@microsoft.azure\autorest-core\dist\app.js:530:20)

```

**Comment by qinqingxu** [comment]
@timotheeguerin could you please help on this question?

**Comment by timotheeguerin** [comment]
Are you able to install that package with npm install

**Comment by qinqingxu** [comment]
Yes, I install the autorest via npm install

**Comment by timotheeguerin** [comment]
no i mean autorest install the extension as an npm package. If the extension cannot be installed via npm then there is an issue with your environment or the package itself.
In this case try `npm install @microsoft.azure/autorest.go` somewhere fresh.

Also  I think the @autorest/go package should be used, probably something we the go team needs to update to be the default

**Comment by qinqingxu** [comment]
Even I try to install the Microsoft.azure/autorest.go, it still not work.
```

PS C:\XQQ\Code\mcatspec\specification\appcomplianceautomation\resource-manager> autorest readme.md  --go --azure-arm --tag=package-2022-05-10-privatepreview --output-folder=go_sdk/
AutoRest code generation utility [cli version: 3.6.1; node: v16.13.0]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
info    | AutoRest core version selected from configuration: ~2.0.4413.
   Loading AutoRest core      'C:\Users\qinqiangxu\.autorest\@microsoft.azureautorest-core@2.0.4421\nodemodules\@microsoft.azure\autorest-core\dist' (2.0.4421)
   Installing AutoRest extension '@microsoft.azure/autorest.go' (~2.1.47)
Failed to install or start extension '@microsoft.azure/autorest.go' (~2.1.47)
  Error: Package '@microsoft.azure/autorest.go' - '2.1.187' failed to install:
  Failed to install package 'https://registry.npmjs.org/@microsoft.azure/autorest.go/-/autorest.go-2.1.187.tgz' -- Error: Process Failed.Error: Failed to install package 'https://registry.npmjs.org/@microsoft.azure/autorest.go/-/autorest.go-2.1.187.tgz' -- Error: Process Failed.
    at install (/node_modules/@microsoft.azure/extension/dist/main.js:303:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExtensionManager.installPackage (/node_modules/@microsoft.azure/extension/dist/main.js:472:13)
    at async Configuration.CreateView (C:\Users\qinqiangxu\.autorest\@microsoft.azureautorest-core@2.0.4421\nodemodules\@microsoft.azure\autorest-core\dist\lib\configuration.js:685:51)
    at async AutoRest.RegenerateView (C:\Users\qinqiangxu\.autorest\@microsoft.azureautorest-core@2.0.4421\nodemodules\@microsoft.azure\autorest-core\dist\lib\autorest-core.js:55:29)
    at async currentMain (C:\Users\qinqiangxu\.autorest\@microsoft.azureautorest-core@2.0.4421\nodemodules\@microsoft.azure\autorest-core\dist\app.js:303:20)
    at async mainImpl (C:\Users\qinqiangxu\.autorest\@microsoft.azureautorest-core@2.0.4421\nodemodules\@microsoft.azure\autorest-core\dist\app.js:506:20)
    at async main (C:\Users\qinqiangxu\.autorest\@microsoft.azureautorest-core@2.0.4421\nodemodules\@microsoft.azure\autorest-core\dist\app.js:530:20)
```

**Comment by timotheeguerin** [comment]
this is not npm log this is still autorest...

**Comment by qinqingxu** [comment]
Yes, regarding to your recommendation, I have been execute the npm, and it is succeeded:

```
C:\Users\qinqiangxu>npm install @microsoft.azure/autorest.go -g

changed 2 packages in 2s
```


But after I execute the above command, and the autorest still failure as you see.

**Comment by timotheeguerin** [comment]
yeah so that would not solve the issue but the goal was to see if it was the problem. One issue autorest v2 installation apart from having terrible logging and no info is that it would have an issue you have a package.json file in a parent directory to where it is installed. In your case `C:\Users\qinqiangxu\.autorest` can you check there isn't a package.json in any of those and delete it if there is.

**Comment by qinqingxu** [comment]
![image](https://user-images.githubusercontent.com/93512957/171567253-d7f0c451-b071-4acd-80d3-e939939ba9f8.png)

Actually there is no package.json file under this folder.

But I found there are two autorest core folders:
![image](https://user-images.githubusercontent.com/93512957/171567404-42bd4a43-c4dc-4746-91a1-88e7a7493a32.png)


So, maybe I need to remove one of them?

**Comment by timotheeguerin** [comment]
Did you check the parent directories too?

**Comment by qinqingxu** [comment]
Yes I have checked the parent directories, and remove the package.json files, and do the autorest --reset again.  And it is still not work.

![image](https://user-images.githubusercontent.com/93512957/172100057-b64fb9f8-ae24-4f8e-b9f4-38f336415821.png)
