### ISSUE TITLE
m1 mac, nvm 12 lts, unable to install @microsoft.azure/autorest.go

### ISSUE THREAD

**Issue by maceip** [Azure/autorest#4586]
```bash
$autorest --verbose --debug --input-file=fb.json --go --output-folder=here
AutoRest code generation utility [cli version: 3.6.1; node: v12.22.12]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
info    | AutoRest core version selected from configuration: ~2.0.4413.
debug   | [0.60 s] Network Enabled: true
debug   | [0.65 s] No @autorest/core (or @microsoft.azure/autorest-core) is installed.
debug   | [0.65 s] ~2.0.4413 was not satisfied directly by a previous installation.
installing core... [========================================] 100% | 2/2
debug   | [5.12 s] Starting @autorest/core from /Users/rpm/.autorest/@microsoft.azureautorest-core@2.0.4421/nodemodules/@microsoft.azure/autorest-core
   Loading AutoRest core      '/Users/rpm/.autorest/@microsoft.azureautorest-core@2.0.4421/nodemodules/@microsoft.azure/autorest-core/dist' (2.0.4421)
No configuration found at 'file:///Users/rpm/'.
   Installing AutoRest extension '@microsoft.azure/autorest.go' (~2.1.47)
VERBOSE: Installing @microsoft.azure/autorest.go, 2.1.188
VERBOSE: Error: Failed to install package 'https://registry.npmjs.org/@microsoft.azure/autorest.go/-/autorest.go-2.1.188.tgz' -- Error: Process Failed.
VERBOSE: Error: Failed to install package 'https://registry.npmjs.org/@microsoft.azure/autorest.go/-/autorest.go-2.1.188.tgz' -- Error: Process Failed.
    at install (/node_modules/@microsoft.azure/extension/dist/main.js:303:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ExtensionManager.installPackage (/node_modules/@microsoft.azure/extension/dist/main.js:472:13)
    at async Configuration.CreateView (/Users/rpm/.autorest/@microsoft.azureautorest-core@2.0.4421/nodemodules/@microsoft.azure/autorest-core/dist/lib/configuration.js:685:51)
    at async AutoRest.RegenerateView (/Users/rpm/.autorest/@microsoft.azureautorest-core@2.0.4421/nodemodules/@microsoft.azure/autorest-core/dist/lib/autorest-core.js:55:29)
    at async currentMain (/Users/rpm/.autorest/@microsoft.azureautorest-core@2.0.4421/nodemodules/@microsoft.azure/autorest-core/dist/app.js:303:20)
    at async mainImpl (/Users/rpm/.autorest/@microsoft.azureautorest-core@2.0.4421/nodemodules/@microsoft.azure/autorest-core/dist/app.js:506:20)
    at async main (/Users/rpm/.autorest/@microsoft.azureautorest-core@2.0.4421/nodemodules/@microsoft.azure/autorest-core/dist/app.js:530:20)
VERBOSE: Cleaning up failed installation: /Users/rpm/.autorest/@microsoft.azure_autorest.go@2.1.188
Failed to install or start extension '@microsoft.azure/autorest.go' (~2.1.47)
  Error: Package '@microsoft.azure/autorest.go' - '2.1.188' failed to install:
  Failed to install package 'https://registry.npmjs.org/@microsoft.azure/autorest.go/-/autorest.go-2.1.188.tgz' -- Error: Process Failed.Error: Failed to install package 'https://registry.npmjs.org/@microsoft.azure/autorest.go/-/autorest.go-2.1.188.tgz' -- Error: Process Failed.
    at install (/node_modules/@microsoft.azure/extension/dist/main.js:303:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ExtensionManager.installPackage (/node_modules/@microsoft.azure/extension/dist/main.js:472:13)
    at async Configuration.CreateView (/Users/rpm/.autorest/@microsoft.azureautorest-core@2.0.4421/nodemodules/@microsoft.azure/autorest-core/dist/lib/configuration.js:685:51)
    at async AutoRest.RegenerateView (/Users/rpm/.autorest/@microsoft.azureautorest-core@2.0.4421/nodemodules/@microsoft.azure/autorest-core/dist/lib/autorest-core.js:55:29)
    at async currentMain (/Users/rpm/.autorest/@microsoft.azureautorest-core@2.0.4421/nodemodules/@microsoft.azure/autorest-core/dist/app.js:303:20)
    at async mainImpl (/Users/rpm/.autorest/@microsoft.azureautorest-core@2.0.4421/nodemodules/@microsoft.azure/autorest-core/dist/app.js:506:20)
    at async main (/Users/rpm/.autorest/@microsoft.azureautorest-core@2.0.4421/nodemodules/@microsoft.azure/autorest-core/dist/app.js:530:20)
```

**Comment by timotheeguerin** [comment]
Hey @maceip  can you try using `--use=@autorest/go` instead of `--go`. This will use the newer go generator.

If you really want to use the legacy one, can you make sure running `npm install @microsoft.azure/autorest.go` in a random folder on your system works fine. Unfortunately autorest v2 doesn't pass the npm installation errors through the logs correctly.
