### ISSUE TITLE
 Error: Package '@autorest/az' - '1.8.0' failed to install

### ISSUE THREAD

**Issue by vtahiliani** [Azure/autorest#4606]
Unable to install autorest az folder with following configurations: 
Command used:  `autorest --az --clear-output-folder=true --azure-cli-extension-folder=cli --multiapi readme.md`

### Tried to `autorest --reset` as well using Node 12.20 as mention here: https://github.com/Azure/autorest.az#take-logz-extension-as-a-dry-run
Any help on this issue is appreciated. 

### ---------------------------- Logs:----------------------------------------------------------------------------------------------
```
SourceMapConsumer.initialize is a no-op when running in node.js
**AutoRest code generation utility [cli version: 3.5.1; node: v16.16.0]**
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest

There is a new version of AutoRest available (3.6.2).
 > You can install the newer version with with npm install -g autorest@latest

installing core... [========================================] 100% | 2/2
info    |    Loading AutoRest core      'C:\Users\xyz\.autorest\@autorestcore@3.9.1\nodemodules\@autorest\core\dist' (3.9.1)
info    |    Installing AutoRest extension '@autorest/az' (latest -> 1.8.0)
installing... [========================================] 100% | 2295/2295
error   |   Error: Package '@autorest/az' - '1.8.0' failed to install:
  Failed to install package 'https://registry.npmjs.org/@autorest/az/-/az-1.8.0.tgz' -- Error: Process Failed.

Installation logs:

  | warning: package.json: No license field
  | info: No lockfile found.
  | info:  Step: Resolving packages
  | warning: https://registry.npmjs.org/ > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
  | warning: https://registry.npmjs.org/ > request-promise-native@1.0.8: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
  | warning: https://registry.npmjs.org/ > jszip-sync > core-js@2.3.0: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
  | warning: https://registry.npmjs.org/ > @azure-tools/codemodel@4.13.325: Warning: This package has been renamed to '@autorest/codemodel', please use '@autorest/codemodel' instead.
  | warning: https://registry.npmjs.org/ > request > har-validator@5.1.5: this library is no longer supported
  | warning: https://registry.npmjs.org/ > request > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
  | warning: https://registry.npmjs.org/ > @azure-tools/extension > npm > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
  | warning: https://registry.npmjs.org/ > @azure-tools/extension > npm > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
  | warning: https://registry.npmjs.org/ > oav > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
  | warning: https://registry.npmjs.org/ > @azure-tools/extension > npm > libcipm@4.0.8: This module is no longer used. Please see @npmcli/arborist if you would like to build and reify package trees programmatically.
  | warning: https://registry.npmjs.org/ > @azure-tools/codemodel > @azure-tools/autorest-extension-base@3.1.267: Warning: This package has been renamed to '@autorest/extension-base', please use '@autorest/extension-base' instead.
  | warning: https://registry.npmjs.org/ > @azure-tools/extension > npm > node-gyp > request@2.88.2: request has been deprecated, see
 https://github.com/request/request/issues/3142
  | warning: https://registry.npmjs.org/ > @azure-tools/extension > npm > read-package-tree@5.3.1: The functionality that this package provided is now in @npmcli/arborist
  | warning: https://registry.npmjs.org/ > oav > @azure/arm-resources@4.2.2: Please note, versions of this package with version numbers 4.2.2 and below have been deprecated as of 31-March-2022. We strongly encourage you to upgrade to version 5.0.0 or above to continue receiving updates. Refer to our deprecation policy: https://azure.github.io/azure-sdk/policies_support.html for more details.
  | warning: https://registry.npmjs.org/ > oav > ms-rest > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
  | warning: https://registry.npmjs.org/ > oav > ms-rest > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
  | warning: https://registry.npmjs.org/ > oav > swagger-parser > z-schema > core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
  | warning: https://registry.npmjs.org/ > @azure-tools/extension > npm > libnpm > libnpmconfig@1.2.1: This module is not used anymore. npm config is parsed by npm itself and by @npmcli/config
  | warning: https://registry.npmjs.org/ > oav > newman > postman-request > har-validator@5.1.5: this library is no longer supported
  | warning: https://registry.npmjs.org/ > oav > newman > postman-request > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
  | warning: https://registry.npmjs.org/ > oav > newman > serialised-error > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
  | warning: https://registry.npmjs.org/ > node-yaml > promise-fs > @octetstream/eslint-config > babel-eslint@9.0.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
  | warning: https://registry.npmjs.org/ > oav > yasway > istanbul@0.4.5: This module is no longer maintained, try this instead:
  |            npm i nyc
  |          Visit https://istanbul.js.org/integrations for other alternatives.
  | warning: https://registry.npmjs.org/ > oav > yuml2svg > jsdom > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
  | warning: https://registry.npmjs.org/ > oav > yuml2svg > jsdom > request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
  | warning: https://registry.npmjs.org/ > oav > yuml2svg > viz.js@2.1.2: no longer supported
  | warning: https://registry.npmjs.org/ > oav > json-refs > path-loader > superagent@7.1.6: Please downgrade to v7.1.5 if you need IE/ActiveXObject support OR upgrade to v8.0.0 as we no longer support IE and published an incorrect patch version (see https://github.com/visionmedia/superagent/issues/1731)
  | warning: https://registry.npmjs.org/ > oav > yuml2svg > jsdom > left-pad@1.3.0: use String.prototype.padStart()
  | warning: https://registry.npmjs.org/ > cpy-cli > cpy > globby > fast-glob > micromatch > snapdragon > source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
  | warning: https://registry.npmjs.org/ > cpy-cli > cpy > globby > fast-glob > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
  | warning: https://registry.npmjs.org/ > cpy-cli > cpy > globby > fast-glob > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
  | warning: https://registry.npmjs.org/ > cpy-cli > cpy > globby > fast-glob > micromatch > snapdragon > source-map-resolve > source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
  | info:  Step: Fetching packages
  | info:  Step: Linking dependencies
  | warning: "https://registry.npmjs.org/ > eslint-plugin-prettier@3.4.1" has unmet peer dependency "eslint@>=5.0.0".
  | warning: "https://registry.npmjs.org/ > eslint-config-prettier@7.2.0" has unmet peer dependency "eslint@>=7.0.0".
  | warning: "https://registry.npmjs.org/ > node-yaml > promise-fs > @octetstream/eslint-config@3.0.0" has unmet peer dependency "eslint@^5.4.0".
  | warning: "https://registry.npmjs.org/ > node-yaml > promise-fs > @octetstream/eslint-config > eslint-config-airbnb-base@13.2.0" has unmet peer dependency "eslint@^4.19.1 || ^5.3.0".
  | warning: "https://registry.npmjs.org/ > node-yaml > promise-fs > @octetstream/eslint-config > eslint-plugin-import@2.26.0" has unmet peer dependency "eslint@^2 || ^3 || ^4 || ^5 || ^6 || ^7.2.0 || ^8".
  | warning: "https://registry.npmjs.org/ > oav > @azure/openapi-markdown > @ts-common/commonmark-to-markdown > @ts-common/iterator@1.1.2" has incorrect peer dependency "tslib@^2.3.1".
  | info:  Step: Building fresh packages
  | error: C:\Users\xyz\.autorest\@autorestaz@1.8.0\nodemodules\@autorest\az: Command failed.
  |        Exit code: 1
  |        Command: mkdirp dist && cpy src/python/* dist/ --parents && tsc dist/src/python/setup.ts && node dist/src/python/setup.js dist/src/python/install.py
  |        Arguments:
  |        Directory: C:\Users\xyz\.autorest\@autorestaz@1.8.0\nodemodules\@autorest\az
  |        Output:
  |        Traceback (most recent call last):
  |          File "C:\Users\xyz\.autorest\@autorestaz@1.8.0\nodemodules\@autorest\az\dist\src\python\install.py", line 72, in <module>
  |            main()
  |          File "C:\Users\xyz\.autorest\@autorestaz@1.8.0\nodemodules\@autorest\az\dist\src\python\install.py", line 44, in main
  |            envbuilder.create(venvpath)
  |          File "C:\Users\xyz\AppData\Local\Programs\Python\Python310\Lib\venv\_init_.py", line 75, in create
  |            self.setuppip(context)
  |          File "C:\Users\xyz\AppData\Local\Programs\Python\Python310\Lib\venv\_init__.py", line 313, in _setuppip
  |            subprocess.check_output(cmd, stderr=subprocess.STDOUT)
  |          File "C:\Users\xyz\AppData\Local\Programs\Python\Python310\Lib\subprocess.py", line 420, in check_output
  |            return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  |          File "C:\Users\xyz\AppData\Local\Programs\Python\Python310\Lib\subprocess.py", line 524, in run
  |            raise CalledProcessError(retcode, process.args,
  |        subprocess.CalledProcessError: Command '['C:\\Users\\xyz\\.autorest\\@autorestaz@1.8.0\\nodemodules\\@autorest\\az\\venv\\Scripts\\python.exe', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.
  | info: Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

With core version : 3.0.6370

```
> AutoRest code generation utility [cli version: 3.5.1; node: v16.16.0]
> (C) 2018 Microsoft Corporation.
> https://aka.ms/autorest
> info    | AutoRest core version selected from configuration: 3.0.6370.
> 
> There is a new version of AutoRest available (3.6.2).
>  > You can install the newer version with with npm install -g autorest@latest
> 
> installing core... [========================================] 100% | 2/2
>    Loading AutoRest core      'C:\Users\xyz\.autorest\@autorestcore@3.0.6370\nodemodules\@autorest\core\dist' (3.0.6370)
>    Installing AutoRest extension '@autorest/az' (latest)
> Failed to install or start extension '@autorest/az' (latest)
>   Error: Package '@autorest/az' - '1.8.0' failed to install:
>   Failed to install package 'https://registry.npmjs.org/@autorest/az/-/az-1.8.0.tgz' -- Error: Process Failed.Error: Failed to install package 'https://registry.npmjs.org/@autorest/az/-/az-1.8.0.tgz' -- Error: Process Failed.
>     at install (/node_modules/@azure-tools/extension/dist/main.js:367:15)
>     at runMicrotasks (<anonymous>)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at async ExtensionManager.installPackage (/node_modules/@azure-tools/extension/dist/main.js:571:13)
>     at async resolveExtensions (C:\Users\xyz\.autorest\@autorestcore@3.0.6370\nodemodules\@autorest\core\dist\lib\configuration\configuration-loader.js:330:55)
>     at async ConfigurationLoader.CreateView (C:\Users\xyz\.autorest\@autorestcore@3.0.6370\nodemodules\@autorest\core\dist\lib\configuration\configuration-loader.js:371:9)
>     at async AutoRest.RegenerateView (C:\Users\xyz\.autorest\@autorestcore@3.0.6370\nodemodules\@autorest\core\dist\lib\autorest-core.js:86:30)
>     at async currentMain (C:\Users\xyz\.autorest\@autorestcore@3.0.6370\nodemodules\@autorest\core\dist\app.js:313:20)
>     at async mainImpl (C:\Users\xyz\.autorest\@autorestcore@3.0.6370\nodemodules\@autorest\core\dist\app.js:517:20)
>     at async main (C:\Users\xyz\.autorest\@autorestcore@3.0.6370\nodemodules\@autorest\core\dist\app.js:544:20)
```

**Comment by timotheeguerin** [comment]
Are you able to run `npm install @autorest/az` in a fresh folder somewhesre on your system?

**Comment by vtahiliani** [comment]
PS C:\Users\xyz> npm install @autorest/az
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@autorest/python/-/python-5.4.0.tgz/@autorest%2faz
npm ERR! 404
npm ERR! 404  '@autorest/az@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xyz\AppData\Roaming\npm-cache\_logs\2022-08-09T05_27_05_378Z-debug.log

It fails in the registry. Not able to proceed

**Comment by timotheeguerin** [comment]
Please see this about az tooling https://github.com/Azure/autorest.az/issues/898
