### ISSUE TITLE
Failed to install or start extension '@autorest/python' (5.4.0)

### ISSUE THREAD

**Issue by vtahiliani** [Azure/autorest#4608]
Facing issue with autorest to generate az cli extension using reference: https://github.com/Azure/autorest.az#take-logz-extension-as-a-dry-run
I have following configuration:
<html>
<body>

AutoRest Core | AutoRest CLI | Node.js
-- | -- | --
3.0.6370 | 3.5.1 | 12.20

</body>
</html>
Any workaround/fix for this issue, blocking issue not processing further. 

```
Installing AutoRest extension '@autorest/python' (5.4.0)
Failed to install or start extension '@autorest/python' (5.4.0)
  Error: Package '@autorest/python' - '5.4.0' failed to install:
  Failed to install package '[https://registry.npmjs.org/@autorest/python/-/python-5.4.0.tgz'](https://registry.npmjs.org/@autorest/python/-/python-5.4.0.tgz%27) -- Error: Process Failed.Error: Failed to install package '[https://registry.npmjs.org/@autorest/python/-/python-5.4.0.tgz'](https://registry.npmjs.org/@autorest/python/-/python-5.4.0.tgz%27) -- Error: Process Failed.
    at install (/node_modules/@azure-tools/extension/dist/main.js:367:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ExtensionManager.installPackage (/node_modules/@azure-tools/extension/dist/main.js:571:13)
    at async resolveExtensions (C:\Users\xyz\.autorest\@autorestcore@3.0.6370\nodemodules\@autorest\core\dist\lib\configuration\configuration-loader.js:330:55)
    at async ConfigurationLoader.CreateView (C:\Users\xyz\.autorest\@autorestcore@3.0.6370\nodemodules\@autorest\core\dist\lib\configuration\configuration-loader.js:371:9)
    at async AutoRest.RegenerateView (C:\Users\xyz\.autorest\@autorestcore@3.0.6370\nodemodules\@autorest\core\dist\lib\autorest-core.js:86:30)
    at async currentMain (C:\Users\xyz\.autorest\@autorestcore@3.0.6370\nodemodules\@autorest\core\dist\app.js:313:20)
    at async mainImpl (C:\Users\xyz\.autorest\@autorestcore@3.0.6370\nodemodules\@autorest\core\dist\app.js:517:20)
    at async main (C:\Users\xyz\.autorest\@autorestcore@3.0.6370\nodemodules\@autorest\core\dist\app.js:544:20)
```

**Comment by timotheeguerin** [comment]
please use a newer version, there is an issue with a dependency of dependency that wasn't pinned in this version.

**Comment by vtahiliani** [comment]
Can you share version to be used to get unblock in generating az cli from autorest.

**Comment by vtahiliani** [comment]
Hi,

Can you share version to be used to get unblock in generating az cli from autorest.

BR,
Vinita

**Comment by timotheeguerin** [comment]
Please see this for using AZ https://github.com/Azure/autorest.az/issues/898
