### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'has')

### ISSUE THREAD

**Issue by JonasJes** [Azure/autorest#4629]
**Describe the bug**

When running autorest on one of our swagger 2.0 files we get a fatal error `TypeError: Cannot read properties of undefined (reading 'has')`

This looks to it is related to this line when visitedComponents[t] is undefined.
https://github.com/Azure/autorest/blob/main/packages/extensions/core/src/lib/plugins/components-cleaner.ts#L257

Unfortunately I cannot share the swagger file, but we are looking into it to find what could cause this issue.
But when we running it through https://validator.swagger.io/ it is valid
And it also works fine in SwaggerUI

**Expected behavior**
That crawlObject in components-cleaner.ts can:
- Handle if something i undefinded
   or
- Returns at clear error message if it considers the swaggerfile is invalid, to enable easier debugging

**Additional context**
Command
```
autorest --typescript --input-file=https://*** --output-folder=./src/autorest-generated/cms.interface.ts --hide-client=true --debug --verbose --generate-metadata=false 
```

Full response
```
AutoRest code generation utility [cli version: 3.6.2; node: v18.7.0]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
info    | AutoRest core version selected from configuration: ^3.7.0.
debug   | [1.06 s] Network Enabled: true
debug   | [1.38 s] The most recent installed version is 3.9.2
debug   | [1.38 s] Starting @autorest/core from C:\Users\***\.autorest\@autorestcore@3.9.2\nodemodules\@autorest\core
Debugger listening on ws://127.0.0.1:50099/066b907d-a244-43a6-873f-5bb67c6b5d65
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
info    |    Loading AutoRest core      'C:\Users\***\.autorest\@autorestcore@3.9.2\nodemodules\@autorest\core\dist' (3.9.2)
verbose | [2.78 s] No configuration found at '***'.
verbose | [2.79 s]    Including configuration file 'file:///C:/Users/***/.autorest/@autorestcore@3.9.2/nodemodules/@autorest/core/dist/resources/default-configuration.md'
verbose | [2.84 s]    Including configuration file 'file:///C:/Users/***/.autorest/@autorestcore@3.9.2/nodemodules/@autorest/core/dist/resources/inspect.md'
verbose | [2.85 s]    Including configuration file 'file:///C:/Users/***/.autorest/@autorestcore@3.9.2/nodemodules/@autorest/core/dist/resources/directives.md'
verbose | [2.88 s]    Including configuration file 'file:///C:/Users/***/.autorest/@autorestcore@3.9.2/nodemodules/@autorest/core/dist/resources/pipeline.md'
verbose | [2.91 s]    Including configuration file 'file:///C:/Users/***/.autorest/@autorestcore@3.9.2/nodemodules/@autorest/core/dist/resources/loader-openapi.md'
verbose | [2.94 s]    Including configuration file 'file:///C:/Users/***/.autorest/@autorestcore@3.9.2/nodemodules/@autorest/core/dist/resources/miscellaneous.md'
verbose | [2.98 s]    Including configuration file 'file:///C:/Users/***/.autorest/@autorestcore@3.9.2/nodemodules/@autorest/core/dist/resources/plugin-powershell.md'
verbose | [3.08 s]    Including configuration file 'file:///C:/Users/***/.autorest/@autorestcore@3.9.2/nodemodules/@autorest/core/dist/resources/plugin-azureresourceschema.md'
verbose | [3.11 s]    Including configuration file 'file:///C:/Users/***/.autorest/@autorestcore@3.9.2/nodemodules/@autorest/core/dist/resources/plugin-csharp.md'
verbose | [3.16 s]    Including configuration file 'file:///C:/Users/***/.autorest/@autorestcore@3.9.2/nodemodules/@autorest/core/dist/resources/plugin-go.md'
verbose | [3.19 s]    Including configuration file 'file:///C:/Users/***/.autorest/@autorestcore@3.9.2/nodemodules/@autorest/core/dist/resources/plugin-java.md'
verbose | [3.23 s]    Including configuration file 'file:///C:/Users/***/.autorest/@autorestcore@3.9.2/nodemodules/@autorest/core/dist/resources/plugin-nodejs.md'
verbose | [3.27 s]    Including configuration file 'file:///C:/Users/***/.autorest/@autorestcore@3.9.2/nodemodules/@autorest/core/dist/resources/plugin-php.md'
verbose | [3.36 s]    Including configuration file 'file:///C:/Users/***/.autorest/@autorestcore@3.9.2/nodemodules/@autorest/core/dist/resources/plugin-python.md'
verbose | [3.42 s]    Including configuration file 'file:///C:/Users/***/.autorest/@autorestcore@3.9.2/nodemodules/@autorest/core/dist/resources/plugin-ruby.md'
verbose | [3.49 s]    Including configuration file 'file:///C:/Users/***/.autorest/@autorestcore@3.9.2/nodemodules/@autorest/core/dist/resources/plugin-typescript.md'
verbose | [3.56 s]    Including configuration file 'file:///C:/Users/***/.autorest/@autorestcore@3.9.2/nodemodules/@autorest/core/dist/resources/plugin-validators.md'
verbose | [3.63 s]    Including configuration file 'file:///C:/Users/***/.autorest/@autorestcore@3.9.2/nodemodules/@autorest/core/dist/resources/plugin-az.md'
verbose | [3.74 s]    Including configuration file 'file:///C:/Users/***/.autorest/@autorestcore@3.9.2/nodemodules/@autorest/core/dist/resources/plugin-terraform.md'
verbose | [3.81 s]    Including configuration file 'file:///C:/Users/***/.autorest/@autorestcore@3.9.2/nodemodules/@autorest/core/dist/resources/plugin-azure-functions.md'
verbose | [3.89 s]    Including configuration file 'file:///C:/Users/***/.autorest/@autorestcore@3.9.2/nodemodules/@autorest/core/dist/resources/graphs.md'
verbose | [3.95 s]    Including configuration file 'file:///C:/Users/***/.autorest/@autorestcore@3.9.2/nodemodules/@autorest/core/dist/resources/help-configuration.md'
info    |    Loading AutoRest extension '@autorest/typescript' (latest->6.0.0-rc.1)
verbose | [5.93 s]    Including extension configuration file 'file:///C:/Users/***/.autorest/@autoresttypescript@6.0.0-rc.1/nodemodules/@autorest/typescript/README.md'
verbose | [5.93 s]    Including configuration file 'file:///C:/Users/***/.autorest/@autoresttypescript@6.0.0-rc.1/nodemodules/@autorest/typescript/README.md'
info    |    Loading AutoRest extension '@autorest/modelerfour' (4.23.5->4.23.5)
verbose | [6.25 s]    Including extension configuration file 'file:///C:/Users/***/.autorest/@autorestmodelerfour@4.23.5/nodemodules/@autorest/modelerfour/readme.md'
verbose | [6.25 s]    Including configuration file 'file:///C:/Users/***/.autorest/@autorestmodelerfour@4.23.5/nodemodules/@autorest/modelerfour/readme.md'
debug   | [8.30 s] swagger-document/loader-swagger - START inputs = 0
debug   | [8.30 s] openapi-document/loader-openapi - START inputs = 0
debug   | [8.30 s] pipeline-emitter - START inputs = 0
debug   | [8.30 s] configuration-emitter - START inputs = 0
debug   | [8.30 s] pipeline-emitter - END [0.05 s][75 MB]
debug   | [8.30 s] configuration-emitter - END [0.05 s][75 MB]
verbose | [14.27 s] Reading OpenAPI 2.0 file https://***
debug   | [14.30 s] openapi-document/loader-openapi - END [6.02 s][67 MB]
debug   | [14.30 s] swagger-document/loader-swagger - END [6.06 s][60 MB]
debug   | [14.30 s] openapi-document/individual/transform - SKIPPING
debug   | [14.30 s] openapi-document/individual/schema-validator-openapi - SKIPPING
debug   | [14.30 s] openapi-document/individual/full-ref-resolver - SKIPPING
debug   | [14.30 s] openapi-document/individual/identity - SKIPPING
debug   | [14.30 s] swagger-document/individual/transform - START inputs = 1
debug   | [14.31 s] swagger-document/individual/transform - END [0 s][60 MB]
debug   | [14.31 s] swagger-document/individual/schema-validator-swagger - START inputs = 1
debug   | [14.73 s] swagger-document/individual/schema-validator-swagger - END [0.41 s][78 MB]
debug   | [14.73 s] swagger-document/individual/full-ref-resolver - START inputs = 1
debug   | [14.77 s] swagger-document/individual/full-ref-resolver - END [0.04 s][72 MB]
debug   | [14.77 s] swagger-document/identity - START inputs = 1
debug   | [14.77 s] swagger-document/individual/identity - START inputs = 1
debug   | [14.77 s] swagger-document/identity - END [0 s][72 MB]
debug   | [14.77 s] swagger-document/individual/identity - END [0 s][72 MB]
debug   | [14.79 s] openapi-document/openapi-document-converter - START inputs = 1
debug   | [15.07 s] openapi-document/openapi-document-converter - END [0.29 s][80 MB]
debug   | [15.07 s] openapi-document/transform - START inputs = 1
debug   | [15.09 s] openapi-document/transform - END [0.01 s][85 MB]
debug   | [15.09 s] openapi-document/semantic-validator - START inputs = 1
debug   | [15.12 s] openapi-document/semantic-validator - END [0.03 s][73 MB]
debug   | [15.12 s] openapi-document/allof-cleaner - START inputs = 1
debug   | [15.16 s] openapi-document/allof-cleaner - END [0.03 s][78 MB]
debug   | [15.17 s] openapi-document/tree-shaker - START inputs = 1
debug   | [15.58 s] openapi-document/tree-shaker - END [0.41 s][88 MB]
debug   | [15.58 s] openapi-document/multi-api-merger - START inputs = 1
debug   | [16.06 s] openapi-document/multi-api-merger - END [0.47 s][99 MB]
debug   | [16.06 s] openapi-document/components-cleaner - START inputs = 1
fatal   | Process() cancelled due to exception : Cannot read properties of undefined (reading 'has') / TypeError: Cannot read properties of undefined (reading 'has')
    at UnsuedComponentFinder.crawlObject (C:\Users\***\.autorest\@autorestcore@3.9.2\node_modules\@autorest\core\dist\src_lib_autorest-corets.js:2349:48)
    at UnsuedComponentFinder.crawlObject (C:\Users\***\.autorest\@autorestcore@3.9.2\node_modules\@autorest\core\dist\src_lib_autorest-corets.js:2360:22)
    at UnsuedComponentFinder.crawlObject (C:\Users\***\.autorest\@autorestcore@3.9.2\node_modules\@autorest\core\dist\src_lib_autorest-corets.js:2360:22)
    at UnsuedComponentFinder.crawlObject (C:\Users\***\.autorest\@autorestcore@3.9.2\node_modules\@autorest\core\dist\src_lib_autorest-corets.js:2360:22)
    at UnsuedComponentFinder.crawlObject (C:\Users\***\.autorest\@autorestcore@3.9.2\node_modules\@autorest\core\dist\src_lib_autorest-corets.js:2360:22)
    at UnsuedComponentFinder.crawlObject (C:\Users\***\.autorest\@autorestcore@3.9.2\node_modules\@autorest\core\dist\src_lib_autorest-corets.js:2360:22)
    at UnsuedComponentFinder.crawlObject (C:\Users\***\.autorest\@autorestcore@3.9.2\node_modules\@autorest\core\dist\src_lib_autorest-corets.js:2360:22)
    at UnsuedComponentFinder.findComponentsToKeepInPaths (C:\Users\***\.autorest\@autorestcore@3.9.2\node_modules\@autorest\core\dist\src_lib_autorest-corets.js:2276:18)
    at UnsuedComponentFinder.find (C:\Users\***\.autorest\@autorestcore@3.9.2\node_modules\@autorest\core\dist\src_lib_autorest-corets.js:2269:14)
    at ComponentsCleaner.init (C:\Users\***\.autorest\@autorestcore@3.9.2\node_modules\@autorest\core\dist\src_lib_autorest-corets.js:2192:40)
    at ComponentsCleaner.runProcess (C:\Users\***\.autorest\@autorestcore@3.9.2\node_modules\@autorest\core\dist\src_lib_autorest-corets.js:16329:13)
    at ComponentsCleaner.getOutput (C:\Users\***\.autorest\@autorestcore@3.9.2\node_modules\@autorest\core\dist\src_lib_autorest-corets.js:16259:9)
    at clean (C:\Users\***\.autorest\@autorestcore@3.9.2\node_modules\@autorest\core\dist\src_lib_autorest-corets.js:2370:24)
    at ScheduleNode (C:\Users\***\.autorest\@autorestcore@3.9.2\node_modules\@autorest\core\dist\src_lib_autorest-corets.js:1351:29)
error   |   TypeError: Cannot read properties of undefined (reading 'has')
error   | Autorest completed with an error. If you think the error message is unclear, or is a bug, please declare an issues at https://github.com/Azure/autorest/issues with the error message you are seeing.
debug   | [16.17 s] Shutting Down.
debug   | [16.18 s] Exiting.
```

**Comment by JonasJes** [comment]
A possible "sinner" for this could be this

```
"Exception": {
      "type": "object",
      "properties": {
        "Message": {
          "type": "string"
        },
        "InnerException": {
          "$ref": "#/definitions/Exception"
        },
        "StackTrace": {
          "type": "string"
        },
        "Source": {
          "type": "string"
        }
      }
    },
```

As the `InnerException` is a type of itself

**Comment by timotheeguerin** [comment]
hey @JanasJes, recursive reference like that should work. 

The error seems like it is visiting a component that doesn't belong to one of those categories.
```
 schemas: new Set<string>(),
    responses: new Set<string>(),
    parameters: new Set<string>(),
    examples: new Set<string>(),
    requestBodies: new Set<string>(),
    headers: new Set<string>(),
    securitySchemes: new Set<string>(),
    links: new Set<string>(),
    callbacks: new Set<string>(),
```

Auotrest first convert swagger 2.0 into openapi3. Seems like something unexpected got into the `components` field.

Without the spec, it is definitely hard to know what could be happening. Any chance you could try to delete part of the spec and try to make a shareable repro?

**Comment by JonasJes** [comment]
Hi @timotheeguerin, we got it working.
We had some new endpoint returning Asp.Net Modelstates.
We usually convert those to `IDictionary<string, string>`, but this was not done in this case.

So the responses had
```
          "400": {
            "x-nullable": false,
            "description": "\nor\n",
            "schema": {},
            "x-expectedSchemas": [
              {
                "description": "",
                "schema": {
                  "type": "string"
                }
              },
              {
                "description": "",
                "schema": {
                  "$ref": "#/definitions/ModelStateDictionary"
                }
              }
            ]
          },
```

The def was
```

    "ModelStateDictionary": {
      "type": "object",
      "required": [
        "MaxAllowedErrors",
        "HasReachedMaxErrors",
        "ErrorCount",
        "Count",
        "Keys",
        "Values",
        "IsValid",
        "ValidationState"
      ],
      "properties": {
        "Root": {
          "$ref": "#/definitions/ModelStateEntry"
        },
        "MaxAllowedErrors": {
          "type": "integer",
          "format": "int32"
        },
        "HasReachedMaxErrors": {
          "type": "boolean"
        },
        "ErrorCount": {
          "type": "integer",
          "format": "int32"
        },
        "Count": {
          "type": "integer",
          "format": "int32"
        },
        "Keys": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "Values": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/ModelStateEntry"
          }
        },
        "IsValid": {
          "type": "boolean"
        },
        "ValidationState": {
          "$ref": "#/definitions/ModelValidationState"
        },
        "Item": {
          "$ref": "#/definitions/ModelStateEntry"
        }
      }
    },
    "ModelStateEntry": {
      "type": "object",
      "x-abstract": true,
      "required": [
        "validationState"
      ],
      "properties": {
        "rawValue": {},
        "attemptedValue": {
          "type": "string"
        },
        "errors": {
          "$ref": "#/definitions/ModelErrorCollection"
        },
        "validationState": {
          "$ref": "#/definitions/ModelValidationState"
        }
      }
    },
    "ModelErrorCollection": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/ModelError"
      }
    },
    "ModelError": {
      "type": "object",
      "properties": {
        "exception": {
          "$ref": "#/definitions/Exception"
        },
        "errorMessage": {
          "type": "string"
        }
      }
    },
    "Exception": {
      "type": "object",
      "properties": {
        "Message": {
          "type": "string"
        },
        "InnerException": {
          "$ref": "#/definitions/Exception"
        },
        "StackTrace": {
          "type": "string"
        },
        "Source": {
          "type": "string"
        }
      }
    },
    "ModelValidationState": {
      "type": "string",
      "description": "",
      "x-enumNames": [
        "Unvalidated",
        "Invalid",
        "Valid",
        "Skipped"
      ],
      "enum": [
        "unvalidated",
        "invalid",
        "valid",
        "skipped"
      ]
    },
 ```

**Comment by drake127** [comment]
Hello, if it helps, for me the "undefined" type was "definitions".

**Comment by drake127** [comment]
Dug bit deeper.

The following breaks the autorest tool with that error:
```
            "x-schema": {
              "$ref": "#/definitions/AzureBenefit"
            },
```
In addition, the following code doesn't seem to be working properly - evaluates definition as an object:
```
      "x-ms-enum": {
        "name": "AzureBenefit",
        "modelAsString": true
      }
```

Both can be found in Marketplace Catalog:
https://github.com/Azure/azure-rest-api-specs/blob/main/specification/marketplacecatalog/data-plane/Search/preview/2022-08-17-preview/search.json

**Comment by duncancarroll** [comment]
@timotheeguerin I am also running into this issue, the problem is that autorest doesn't provide the line number it's failing on, and the error is obscure so so there is no way to debug / resolve.

Would be great if it could output some additional debug info, perhaps which field is being parsed, so at least there is a clue =)
