### ISSUE TITLE
[Question] How can I avoid getting the error 'collision detected inserting into object'

### ISSUE THREAD

**Issue by nickfloyd** [Azure/autorest#4711]
Before asking the question:

- [x] have you checked the [faq](https://github.com/Azure/autorest/tree/main/docs/faq.md), the documentation in the [docs folder](https://github.com/Azure/autorest/tree/main/docs) and couldn't find the information there
- [x] have you checked existing issues for a similar question?

------

Hey Friends,

I am trying to generate a go client using an OpenAPI v3 document (attached) and a defined config (attached).  The generation fails with the error below.  I am pretty sure I know why the error is happening, and I was wondering if there was a way to work around it either without changing the OpenAPI definition or changing the definitions but without introducing breaking changes. 

This is the [repo](https://github.com/octokit/source-generator) where we are working with autorest generation.

------

### The reason I believe the error below is happening

1 There is a `page-build` schema/object containing a property named `status`

2 There is also a `page-build-status` schema/object

I've only briefly looked at the generator source (and am continuing to look at it) but here are my assumptions:

When the generator runs, it takes `page-build.status`, and I assume it makes a prop name (for mapping) (something like `PageBuildStatus`) and inserts it into an in-memory schema map.

The generator then takes the object `page-build-status` and tries to insert it into the schema prop map as `PageBuildStatus`, which causes the collision.

It looks like there are extensions for overriding the naming  using [x-ms-client-name](https://github.com/Azure/autorest/blob/main/docs/extensions/readme.md#x-ms-client-name). I've tried that specific extension it on both the `page-build` `status` property and the `page-build-status` object in yaml with no success.  My gut tells me that I am probably missing something obvious - I'd appreciate any guidance to help me find out if there  **Is there a better way to do this?**

------

### The command that I am using

```
time autorest autorest-config.yaml --go --debug --verbose
```

------

### The error that I get when running generation

```
fatal   | Process() cancelled due to exception : Collision detected inserting into object: page-build-status / Error: Collision detected inserting into object: page-build-status
    at Object.set (/Users/nickfloyd/.autorest/@autorestcore@3.9.4/node_modules/@autorest/core/dist/src_lib_autorest-corets.js:15706:23)
    at OAI3Shaker.newObject (/Users/nickfloyd/.autorest/@autorestcore@3.9.4/node_modules/@autorest/core/dist/src_lib_autorest-corets.js:16286:24)
    at OAI3Shaker.dereference (/Users/nickfloyd/.autorest/@autorestcore@3.9.4/node_modules/@autorest/core/dist/src_lib_autorest-corets.js:7215:30)
    at OAI3Shaker.dereferenceItems (/Users/nickfloyd/.autorest/@autorestcore@3.9.4/node_modules/@autorest/core/dist/src_lib_autorest-corets.js:7113:18)
    at OAI3Shaker.visitComponents (/Users/nickfloyd/.autorest/@autorestcore@3.9.4/node_modules/@autorest/core/dist/src_lib_autorest-corets.js:7120:26)
    at OAI3Shaker.process (/Users/nickfloyd/.autorest/@autorestcore@3.9.4/node_modules/@autorest/core/dist/src_lib_autorest-corets.js:6810:26)
    at OAI3Shaker.runProcess (/Users/nickfloyd/.autorest/@autorestcore@3.9.4/node_modules/@autorest/core/dist/src_lib_autorest-corets.js:16337:28)
    at OAI3Shaker.getOutput (/Users/nickfloyd/.autorest/@autorestcore@3.9.4/node_modules/@autorest/core/dist/src_lib_autorest-corets.js:16257:9)
    at shakeTree (/Users/nickfloyd/.autorest/@autorestcore@3.9.4/node_modules/@autorest/core/dist/src_lib_autorest-corets.js:7260:24)
    at ScheduleNode (/Users/nickfloyd/.autorest/@autorestcore@3.9.4/node_modules/@autorest/core/dist/src_lib_autorest-corets.js:1351:29)
error   |   Error: Collision detected inserting into object: page-build-status
error   | Autorest completed with an error. If you think the error message is unclear, or is a bug, please declare an issues at https://github.com/Azure/autorest/issues with the error message you are seeing.
```

[api.github.com.zip](https://github.com/Azure/autorest/files/10701355/api.github.com.zip)

**Comment by timotheeguerin** [comment]
Seems like this issue is caused by the collision in the examples section(with `page-build-status` and `page-build.status`. Not sure why it is checking that however. Workaround for now would be to just remove one of those examples

**Comment by nickfloyd** [comment]
Hey, @timotheeguerin. Thank you for the follow-up. ❤️.  We ended up bridging the gap with a pre-processor that corrects the issue, then generation.  We're looking to use overlays and versioning to phase out the odd schema format in future iterations as well so that we can eventually remove the pre-processor.
