### ISSUE TITLE
java.lang.NoClassDefFoundError: com/azure/autorest/customization/models/Range

### ISSUE THREAD

**Issue by samvaity** [Azure/autorest#4984]
No class definition found for Range

info    | AutoRest core version selected from configuration: ^3.7.0.
info    |    Loading AutoRest core      'C:\Users\savaity\.autorest\@autorestcore@3.10.2\nodemodules\@autorest\core\dist' (3.10.2)
info    |    Loading AutoRest extension '@autorest/java' (4.1.26->4.1.26)
info    |    Loading AutoRest extension '@autorest/modelerfour' (4.27.0->4.27.0)

java.lang.NoClassDefFoundError: com/azure/autorest/customization/models/Range
        at PersonalizerCustomization.lambda$useBinaryDataForRankApis$2(PersonalizerCustomization.java:64)
        at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4390)
        at PersonalizerCustomization.useBinaryDataForRankApis(PersonalizerCustomization.java:56)

**Comment by weidongxu-microsoft** [comment]
@samvaity

Is it this https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/personalizer/azure-ai-personalizer/swagger/src/main/java/PersonalizerCustomization.java
