### ISSUE TITLE
[tsp-client convert] Fails on compute/resource-manager with "unresolvable duplicated ChoiceSchemas"

### ISSUE THREAD

**Issue by mikeharder** [Azure/autorest#5013]
## Repro Steps
1. `gh repo clone azure/azure-rest-api-specs`
2. `git checkout 564142ed8d60f75a58b4ed987c2fc970c898c4da`
3. `npm ci`
4. `npx tsp-client convert --swagger-readme specification/compute/resource-manager/readme.md --arm`

```
0.12.1
Converting swagger to typespec...
AutoRest code generation utility [cli version: 3.7.1; node: v20.16.0]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
info    | AutoRest core version selected from configuration: ^3.7.0.
info    |    Loading AutoRest core      '/home/mharder/.autorest/@autorestcore@3.10.2/nodemodules/@autorest/core/dist' (3.10.2)
warning | DeprecatedConfig | Using directive.0.suppress which is deprecated and will be removed in the future.
```

5. Wait several minutes

```
warning | PreNamer/DeduplicateName | Deduplicating schema name: 'PurchasePlan' -> 'PurchasePlanAutoGenerated'
fatal   | Internal error in AutoRest.CSharp
   Please file an issue at https://github.com/Azure/autorest.csharp/issues/new.
   Attach the written 'Configuration.json' and 'CodeModel.yaml' or the original swagger so we can reproduce your error.

Exception: We have unresolvable duplicated ChoiceSchemas. These are: [PremiumLRS, Premium_ZRS, PremiumV2_LRS, Standard_LRS, StandardSSD_LRS, StandardSSD_ZRS, UltraSSD_LRS], [Premium_LRS, Standard_LRS, StandardZRS]
   at AutoRest.CSharp.Mgmt.Decorator.Transformer.DuplicateSchemaResolver.CollapseChoices(IEnumerable`1 schemas) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Mgmt\Decorator\Transformer\DuplicateSchemaResolver.cs:line 152
   at AutoRest.CSharp.Mgmt.Decorator.Transformer.DuplicateSchemaResolver.CollapseMultipleSchemas(HashSet`1 schemas) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Mgmt\Decorator\Transformer\DuplicateSchemaResolver.cs:line 45
   at AutoRest.CSharp.Mgmt.Decorator.Transformer.DuplicateSchemaResolver.ResolveDuplicates() in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Mgmt\Decorator\Transformer\DuplicateSchemaResolver.cs:line 33
   at AutoRest.CSharp.Mgmt.Decorator.CodeModelTransformer.Transform() in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Mgmt\Decorator\CodeModelTransformer.cs:line 32
   at AutoRest.CSharp.Mgmt.AutoRest.MgmtOutputLibrary..ctor() in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Mgmt\AutoRest\MgmtOutputLibrary.cs:line 102
   at AutoRest.CSharp.Output.Models.Types.BuildContext`1.EnsureLibrary() in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Output\Models\Types\BuildContextOfT.cs:line 31
   at AutoRest.CSharp.Output.Models.Types.BuildContext`1.getLibrary() in D:\a\work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Output\Models\Types\BuildContextOfT.cs:line 20
   at AutoRest.CSharp.AutoRest.Plugins.MgmtTarget.ExecuteAsync(GeneratedCodeWorkspace project, CodeModel codeModel, SourceInputModel sourceInputModel) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Mgmt\AutoRest\MgmtTarget.cs:line 125
   at AutoRest.CSharp.AutoRest.Plugins.CSharpGen.ExecuteAsync(CodeModel codeModel) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\AutoRest\Plugins\CSharpGen.cs:line 43
   at AutoRest.CSharp.AutoRest.Plugins.CSharpGen.Execute(IPluginCommunication autoRest) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\AutoRest\Plugins\CSharpGen.cs:line 98
fatal   | Process() cancelled due to failure
error   |   Error: Plugin csharpgen reported failure.
error   | Autorest completed with an error. If you think the error message is unclear, or is a bug, please declare an issues at https://github.com/Azure/autorest/issues with the error message you are seeing.
```

**Comment by pshao25** [comment]
I already replied to customer that is because he is not using the correct readme.

**Comment by mikeharder** [comment]
Teams discussion: 

https://teams.microsoft.com/l/message/19:906c1efbbec54dc8949ac736633e6bdf@thread.skype/1725404571050?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1725404571050&teamName=Azure%20SDK&channelName=TypeSpec%20Discussion&createdTime=1725404571050
