### ISSUE TITLE
Plugin 'full-ref-resolver' completed with some error

### ISSUE THREAD

**Issue by mikeharder** [Azure/autorest#5044]
```
$ gh repo clone azure/azure-rest-api-specs
$ git checkout d18a495685ccec837b72891b4deea017f62e8190

$ npx autorest --v3 --spectral --azure-validator --semantic-validator=false \
  --model-validator=false --openapi-type=arm --openapi-subtype=arm \
  --use=@microsoft.azure/openapi-validator@2.2.3 --tag=package-2021-05-metrics \
  specification/monitor/resource-manager/readme.md

fatal   | Plugin 'full-ref-resolver' completed with some error.
error   |   Error: Plugin 'full-ref-resolver' completed with some error.
error   | stack: Error: Plugin 'full-ref-resolver' completed with some error.
    at /home/mharder/.autorest/@autorestcore@3.10.3/node_modules/@autorest/core/dist/src_lib_autorest-corets.js:2898:19
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ScheduleNode (/home/mharder/.autorest/@autorestcore@3.10.3/node_modules/@autorest/core/dist/src_lib_autorest-corets.js:1351:29)
```

**Comment by mikeharder** [comment]
Root cause was these delete transforms in `readme.md`:


```
``` yaml $(tag) == 'package-2021-05-metrics'
input-file:
  - Microsoft.Insights/preview/2017-12-01-preview/metricNamespaces_API.json
  - Microsoft.Insights/stable/2018-03-01/metricAlert_API.json
  - Microsoft.Insights/stable/2019-03-01/metricBaselines_API.json
  - Microsoft.Insights/stable/2021-05-01/metricDefinitions_API.json
  - Microsoft.Insights/stable/2021-05-01/metrics_API.json
  - Microsoft.Insights/stable/2021-05-01/operations_API.json
directive:
  - from: metricBaselines_API.json
    where: $.parameters
    transform: delete $["MetricNamespaceParameter"]
    reason: Description doesn't match, the definition will be "inherit" from metrics_API.json
  - from: metricBaselines_API.json
    where: $.parameters
    transform: delete $["MetricNamesParameter"]
    reason: Description doesn't match, the definition will be "inherit" from metrics_API.json
```

https://github.com/Azure/azure-rest-api-specs/blob/c49a2294eb759d4abf571e3b44351574d8e5cd4c/specification/monitor/resource-manager/readme.md?plain=1#L670-L687

Which caused these error messages, prior to the exception:

```
error   | InvalidRef | Ref '#/parameters/MetricNamesParameter' is not referencing a valid location. paths,/{resourceUri}/providers/Microsoft.Insights/metricBaselines,get,parameters,1
    - file:///home/mharder/specs/specification/monitor/resource-manager/Microsoft.Insights/stable/2019-03-01/metricBaselines_API.json:59:11
error   | InvalidRef | Ref '#/parameters/MetricNamespaceParameter' is not referencing a valid location. paths,/{resourceUri}/providers/Microsoft.Insights/metricBaselines,get,parameters,2
    - file:///home/mharder/specs/specification/monitor/resource-manager/Microsoft.Insights/stable/2019-03-01/metricBaselines_API.json:62:11
```

The spec was fixed here:

https://github.com/Azure/azure-rest-api-specs/pull/30787/files#diff-264accec1b0fe201eedacac26baaf709a64bed776778f36992c08265ac4b6165L644-L652
