### ISSUE TITLE
Node.js sample results in "RangeError: Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by mcoimbrac** [Azure/autorest#919]
Hi all.

I've run into an Exception using the node.js sample provided on the 0.15.0 release, which I think is a bug.

It happens on a recursive loop function, using setImmediate, process.nextTick or a setTimeout wrapper.

The following scripts are simple ways of replicating my problem. This script:
```
var petStoreApi = require('./petStoreSampleApi.js');
var msRest = require('ms-rest');
var credentials = new msRest.TokenCredentials("special-key");
var petStoreClient = new petStoreApi(credentials);

var petId = 1;

function loop( i, callback ) {
    if( i < 10000 ) {
        petStoreClient.getPetById(petId, function(err, result, httpReq, response) {
            console.log(i, new Date());
            process.nextTick( function() {
                loop( i+1, resume ); 
            });
        });
    } else {
        callback();
    }
}

console.log('start at ', new Date());
loop( 0, function() {
    console.log('end at ', new Date());
});
```
results in:
```
marcelo@local:~/opt/autorest$ node getPetById-github-issue-code-used.js 
start at  Tue Apr 05 2016 14:26:33 GMT-0300 (BRT)
0 Tue Apr 05 2016 14:26:34 GMT-0300 (BRT)
1 Tue Apr 05 2016 14:26:34 GMT-0300 (BRT)
(...)
4951 Tue Apr 05 2016 15:02:21 GMT-0300 (BRT)
4952 Tue Apr 05 2016 15:02:22 GMT-0300 (BRT)
url.js:426
  if (search && search.charAt(0) !== '?') search = '?' + search;
                                                       ^
RangeError: Maximum call stack size exceeded
    at String.replace (native)
    at Url.format (url.js:428:23)
    at Url.parse (url.js:365:20)
    at Object.urlParse [as parse] (url.js:104:5)
    at Request.init (/opt/autorest/node_modules/ms-rest/node_modules/request/request.js:250:20)
    at new Request (/opt/autorest/node_modules/ms-rest/node_modules/request/request.js:141:8)
    at request (/opt/autorest/node_modules/ms-rest/node_modules/request/index.js:55:10)
    at /opt/autorest/node_modules/ms-rest/node_modules/request/index.js:101:12
    at /opt/autorest/node_modules/ms-rest/node_modules/request/index.js:101:12
    at /opt/autorest/node_modules/ms-rest/node_modules/request/index.js:101:12
```

However when I use only `request` it works pretty well. Here is the working sample:
```
var request = require('request');

var simpleRequestPetById = function(petId, callback) {
    if (!callback) {
        throw new Error('callback cannot be null.');
    }

    var reqUrl = 'http://petstore.swagger.io/v2/pet/' + petId;
    var reqOptions = {
        method: 'GET',
        uri: reqUrl,
        headers: {
            Authorization: 'Bearer special-key'
        }
    };
    request(reqOptions, function(error, response, body) {
        if (error) {
            callback(error);
        } else {
            if (body) {
                callback(null, response, body);
            } else {
                callback(null, response);
            }
        }
    });
}

var petId = 1;

function loop( i, callback ) {
    if( i < 10000 ) {
        simpleRequestPetById(petId, function(err, result) {
            console.log(i, new Date());
            process.nextTick( function() {
                loop( i+1, callback ); 
            });
        });
    } else {
        callback();
    }
}

console.log('start at ', new Date());
loop( 0, function() {
    console.log('end at ', new Date());
});
```
results in:
```
marcelo@local:~/opt/autorest$ node getPetById-github-issue-working-code.js 
start at  Tue Apr 05 2016 14:52:38 GMT-0300 (BRT)
0 Tue Apr 05 2016 14:52:39 GMT-0300 (BRT)
1 Tue Apr 05 2016 14:52:39 GMT-0300 (BRT)
2 Tue Apr 05 2016 14:52:39 GMT-0300 (BRT)
3 Tue Apr 05 2016 14:52:40 GMT-0300 (BRT)
(...)
9998 Tue Apr 05 2016 15:25:00 GMT-0300 (BRT)
9999 Tue Apr 05 2016 15:25:01 GMT-0300 (BRT)
end at  Tue Apr 05 2016 15:25:01 GMT-0300 (BRT)
```

**Comment by amarzavery** [comment]
@mcoimbrac Thanks for reporting this issue. I was able to reproduce as well. Modified the script a little to log the memory usage of the process

```
6131 Tue Apr 05 2016 18:38:37 GMT-0700 (Pacific Daylight Time)
{ rss: 86585344, heapTotal: 69338448, heapUsed: 30511808 }
{ id: 1,
  name: 'Tomcat',
  photoUrls: [],
  tags: [],
  status: 'available' }
6132 Tue Apr 05 2016 18:38:38 GMT-0700 (Pacific Daylight Time)
{ rss: 86585344, heapTotal: 69338448, heapUsed: 33456504 }
{ id: 1,
  name: 'Tomcat',
  photoUrls: [],
  tags: [],
  status: 'available' }
6133 Tue Apr 05 2016 18:38:38 GMT-0700 (Pacific Daylight Time)
{ rss: 86609920, heapTotal: 69338448, heapUsed: 36090920 }
{ id: 1,
  name: 'Tomcat',
  photoUrls: [],
  tags: [],
  status: 'available' }
6134 Tue Apr 05 2016 18:38:38 GMT-0700 (Pacific Daylight Time)
{ rss: 86630400, heapTotal: 69338448, heapUsed: 38432888 }
{ id: 1,
  name: 'Tomcat',
  photoUrls: [],
  tags: [],
  status: 'available' }
6135 Tue Apr 05 2016 18:38:38 GMT-0700 (Pacific Daylight Time)
{ rss: 86650880, heapTotal: 69338448, heapUsed: 40516656 }
```
heapTotal value correlated to the value (69.3MB) in task manager.


V/S running your script which was using the request module directly
```
{"id":1,"name":"Tomcat","photoUrls":[],"tags":[],"status":"available"}
{ rss: 54120448, heapTotal: 37339984, heapUsed: 22205960 }
9995 Tue Apr 05 2016 18:40:18 GMT-0700 (Pacific Daylight Time)
{"id":1,"name":"Tomcat","photoUrls":[],"tags":[],"status":"available"}
{ rss: 54120448, heapTotal: 37339984, heapUsed: 22258856 }
9996 Tue Apr 05 2016 18:40:18 GMT-0700 (Pacific Daylight Time)
{"id":1,"name":"Tomcat","photoUrls":[],"tags":[],"status":"available"}
{ rss: 54124544, heapTotal: 37339984, heapUsed: 22312552 }
9997 Tue Apr 05 2016 18:40:18 GMT-0700 (Pacific Daylight Time)
{"id":1,"name":"Tomcat","photoUrls":[],"tags":[],"status":"available"}
{ rss: 54128640, heapTotal: 37339984, heapUsed: 22365824 }
9998 Tue Apr 05 2016 18:40:18 GMT-0700 (Pacific Daylight Time)
{"id":1,"name":"Tomcat","photoUrls":[],"tags":[],"status":"available"}
{ rss: 54128640, heapTotal: 37339984, heapUsed: 22419600 }
9999 Tue Apr 05 2016 18:40:19 GMT-0700 (Pacific Daylight Time)
end at  Tue Apr 05 2016 18:40:19 GMT-0700 (Pacific Daylight Time)
```
heap total close to 37.3MB..

Will have to dig further to find out the root cause.

**Comment by mcoimbrac** [comment]
hey @amarzavery just wanted to know how things are going with this bug and if I can be of any assistance to you. thanks for the effort. :)

**Comment by amarzavery** [comment]
@mcoimbrac - Currently we generate two versions Generic and Azure specific.

I assume petstore client is generated using generic version. It will not accept credentials as one of the arguments to the client constructor, unless it was specified to generate a client with credentials to `Autorest.exe -AddCredentials`.

The generic version signature looks like this https://github.com/Azure/autorest/blob/master/Samples/petstore/NodeJS/swaggerPetstore.js#L34.

It accepts baseuri and options.

If credentials is supplied as the first argument, the request library throws an error "InvalidUri" and the stack grows. 

I just want to confirm that when you were testing the generated client, the request was actually made, meaning that the autorest generated client was able to successfully get the pet from petstore server, correct ?

**Comment by mcoimbrac** [comment]
Hi @amarzavery!

As far as I can tell, the request was made and the autorest client was able to successfully get the pet data from the petstore serve.

I tested the new autorest version (0.16.0). And since you've pointed the credentials as a possible source of problems, I took the liberty to take it out of equation and make things simpler.

I created a public repository with the source code used to test (https://github.com/mcoimbrac/autorest-sample), in case you want to take a look at what we used.

The code is pretty much the same, just added more logs and removed credentials.

```
var petStoreApi = require('./swaggerPetstore.js');
var msRest = require('ms-rest');
// var credentials = new msRest.TokenCredentials("special-key");
var petStoreClient = new petStoreApi();

var petId = 1;

function loop( i, resume ) {
    if( i < 10000 ) {
        petStoreClient.getPetById(petId, function(err, result, httpReq, response) {
            if (err) console.log(err);
            if (result) console.log(result);

            console.log(i, new Date());
            process.nextTick( function() {
                loop( i+1, resume ); 
            });
        });
    } else {
        resume();
    }
}

console.log('start at ', new Date());
loop( 0, function() {
    console.log('end at ', new Date());
});
```

And it also resulted in:

```
marcelo@local:/opt/autorest$ node getPetById-github-issue-code-used-no-credentials.js 
start at  Mon May 23 2016 16:36:22 GMT-0300 (BRT)
{ id: 1, name: 'Tom', photoUrls: [ 'http://test' ], tags: [] }
0 Mon May 23 2016 16:36:22 GMT-0300 (BRT)
{ id: 1, name: 'Tom', photoUrls: [ 'http://test' ], tags: [] }
(...)
{ id: 1, name: 'Tom', photoUrls: [ 'http://test' ], tags: [] }
6231 Mon May 23 2016 17:27:57 GMT-0300 (BRT)
{ id: 1, name: 'Tom', photoUrls: [ 'http://test' ], tags: [] }
6232 Mon May 23 2016 17:27:57 GMT-0300 (BRT)
url.js:413
  pathname = pathname.replace(/[?#]/g, function(match) {
                      ^

RangeError: Maximum call stack size exceeded
    at String.replace (native)
    at Url.format (url.js:413:23)
    at Url.parse (url.js:344:20)
    at Object.urlParse [as parse] (url.js:84:5)
    at Request.init (/opt/autorest/node_modules/ms-rest/node_modules/request/request.js:250:20)
    at new Request (/opt/autorest/node_modules/ms-rest/node_modules/request/request.js:141:8)
    at request (/opt/autorest/node_modules/ms-rest/node_modules/request/index.js:55:10)
    at /opt/autorest/node_modules/ms-rest/node_modules/request/index.js:101:12
    at /opt/autorest/node_modules/ms-rest/node_modules/request/index.js:101:12
    at /opt/autorest/node_modules/ms-rest/node_modules/request/index.js:101:12
```

**Comment by sedouard** [comment]
hey I'm @amarzavery hitting this issue as well with a worker task that runs on every `process.nextTick`. Using `ms-rest-azure` `1.12.0` (which uses `ms-rest`).

**Comment by sedouard** [comment]
Hey @amarzavery this issue is *really* hurting us a lot.

I've solved the issue and opened a PR.

https://github.com/Azure/autorest/pull/1342
